* authentic
美 [ɔ'θɛntɪk] 英 [ɔː'θentɪk]
adj.真的,真诚的;高仿的;可信的
authority--权威---权威的话往往是真的,是可信的。
词源： authentic 真实的 → 来自author.
真实的(38%)，真正的(34%)，可信的(15%)，可靠的(13%)
柯林斯词典★★☆☆☆   
adj.真的；真正的；真实的；真诚的
An authentic person, object, or emotion is genuine.
  [usu ADJ n]
authenticity
There are factors, however, that have cast doubt on the statue's authenticity.
然而，有些因素让人对该雕塑的真伪产生了怀疑。
authentically
Consumers are increasingly interested in the authentically exotic tastes...
消费者对于真正的异国风味越来越情有独钟。
The enamel gives new brass an authentically tarnished finish.
用瓷釉作末道漆使新的黄铜器看似自然地失去了光泽。
adj.（仿制品）能够以假乱真的，逼真的
If you describe something as authentic, you mean that it is such a good imitation that it is almost the same as or as good as the original.
  [usu ADJ n] [approval]
authentically
The team decided to try and replicate the missing curtains as authentically as possible.
小组决定尽可能照原样重新制作丢失的幕帘。
adj.(信息或记述）准确的，可靠的，可信的
An authentic piece of information or account of something is reliable and accurate.
  [usu ADJ n]
authentically
The book authentically and intimately describes the small details of her daily life.
本书翔实地记述了她日常生活中的小细节。
authenticity
The film's authenticity of detail has impressed critics.
电影在细节上的真实性给影评人士留下了深刻的印象。
* 同义词辨析
real, authentic, genuine, true, actual, factual
这组词都有“真的，真实的，实在的”的意思，其区别是：
[[real]]: 普通用词，含义较广，有时可与actual和genuine换用。指一切真实的或 表面看不出虚假的事物。
[[authentic]]: 常可与genuine换用，指与事实完全相符，强调准确可靠。
[[genuine]]: 普通常用词，指真正的，货真价实的，强调非人为或非虚假的。
[[true]]: 指同实际情况或标准完全一致。口语中多用。
[[actual]]: 指事物的实际存在，并非出自主观臆造。
[[factual]]: 与actual同义，但更测重根据事实，不扩大或缩小，不渲染。
同根词派生
词根：authentic
* adv.
* authentically 真正地，确实地；可靠地
* n.
* authentication 证明；鉴定；证实
* authenticity 真实性，确实性；可靠性
* vt.
* authenticate 鉴定；证明…是真实的