* COCA：12763 发音 附注 例句Unit20   恋练有词-1575   Collins
* CET6 考研 TOEFL IELTS GRE   
diffuse
美 [dɪ'fjus] 英 [dɪ'fjuːz]
v.舒缓(尤指不良情绪);(使)扩散 adj.散布的,分散的;难以理解的
词源：
diffuse 漫射
→ dis-,分开，散开，-fus,流，涌，词源同fusion,confuse.即光线向不同方向流出，漫射开。
释义：弥漫(61%)，扩散(24%)，传播(10%)，冗长的(3%)，散开(1%)，四散的(1%)
* 词性：动词(53%), 形容词(47%)
柯林斯词典★☆☆☆☆   
The verb is pronounced /dɪ'fjuːz/. The adjective is pronounced /dɪ'fjuːs/. 动词读作 /dɪ'fjuːz/。形容词读作/dɪ'fjuːs/。
** v.(使）（知识、消息等)传播；（使）散布；（使）普及
If something such as knowledge or information is diffused, or if it diffuses somewhere, it is made known over a wide area or to a lot of people.
  [be V-ed] [V n] [V prep] [WRITTEN 笔语]
diffusion
...the development and diffusion of ideas.
思想的发展和传播
- verb.宣泄，舒缓(尤指不良情绪)
To diffuse a feeling, especially an undesirable one, means to cause it to weaken and lose its power to affect people.
  [V n]
verb.使(光)漫射；使发散
If something diffuses light, it causes the light to spread weakly in different directions.
  [V n]
v.（使）扩散；（使）弥漫；（使）渗透
To diffuse or be diffused through something means to move and spread through it.
  [V prep] [V n prep] [Also V]
diffusion
There are data on the rates of diffusion of molecules.
有关于分子扩散速度的数据。
adj.散布的；分散的；弥漫的
Something that is diffuse is not directed towards one place or concentrated in one place but spread out over a large area.
  [WRITTEN 笔语]
adj.含糊不清的；难以理解的
If you describe something as diffuse, you mean that it is vague and difficult to understand or explain.
* 同义词辨析
** scatter, diffuse, spread, disperse
** 这组词都有“使分散、使散开”的意思，其区别是：
** [[scatter]]: 普通用词，指用暴力等手段使人或物向四处散开，或把物随意撒开。
** [[diffuse]]: 指光线、声音或气味等在空中传送或散布，强调覆盖面积与物质分布相对密度之间的关系。
** [[spread]]: 指一直延伸、蔓延，侧重遍及。
** disperse: 多指把一群人或物等彻底驱散。
** diffuse, dilute, disperse, dissolve
** diffuse: 使扩散（气体或热量等的扩散或弥漫）
** dilute: 稀释，减少事物的强度，浓度，纯度
** [[disperse]]: 扩散，消散
** dissolve: 溶解，固体溶解于水中
* 同根词派生
词根：diffuse
** adj.
*** diffused 散布的，扩散的；普及的
*** diffusive 普及的；散布性的；冗长的
** adv.
*** diffusely 广泛地；扩散地
** n.
*** diffusion 扩散，传播；[光] 漫射
*** diffuser [机] 扩散器；散布者
*** diffuseness 扩散；漫无边际
*** diffusor 扩散器；散布者；扩散体
** v.
*** diffused 散布，传播（diffuse的过去分词）；使分散