* Efforts to ^^rein in^^ climate change will ^^upend^^ the geopolitics of energy
* Oil fuelled the 20th century—its cars, its wars, its economy and its geopolitics. Now the world is in the midst of an energy shock that is speeding up the shift to a new order. As covid-19 ^^struck^^ the global economy earlier this year, demand for oil ^^dropped by^^ more than a fifth and prices ^^collapsed^^. Since then there has been a ^^jittery^^ recovery, but a return to the old world is unlikely. Fossil-fuel producers are being forced to confront their ^^vulnerabilities^^. ExxonMobil has been ejected from the Dow Jones Industrial Average, having been a member since 1928.  Petrostates such as Saudi Arabia need an oil price of $70-80 a barrel to balance their budgets. Today it is ^^scraping^^ along at just $40.
* There have been oil slumps before, but this one is different. As the public, governments and investors wake up to climate change, the clean-energy industry is gaining ^^momentum^^. Capital markets have shifted: clean-power stocks are up by 45% this year. With interest rates near zero, politicians are ^^backing^^ green- infrastructure plans. America’s Democratic presidential contender, Joe Biden, wants to spend $2trn ^^decarbonising^^ America’s economy. The European Union has ^^earmarked^^ 30% of its $880bn covid-19 recovery plan for climate measures, and its president, Ursula von der Leyen, used her state-of-the-union address this week to confirm that she wants the eu to cut greenhouse-gas emissions by 55% over 1990 levels in the next decade.
* The 21st-century energy system promises to be better than the oil age—better for human health, more politically stable and less economically ^^volatile^^. The shift involves big risks. If disorderly, it could ^^add to^^ political and economic instability in petrostates and concentrate control of the green-supply chain in China. Even more dangerous, it could happen too slowly.
* Today fossil fuels are the ultimate source of 85% of energy. But this system is dirty. Energy accounts for two-thirds of greenhouse-gas emissions; the pollution from burning fossil fuels kills over 4m people a year, mostly in the emerging world’s mega-cities. Oil has also created political instability. For decades petrostates such as Venezuela and Saudi Arabia, with little ^^incentive^^ to develop their economies, have been ^^mired^^ in the politics of handouts and ^^cronyism^^. In an effort to ensure secure supplies, the world’s big powers have ^^vied^^ to influence these states, not least in the Middle East, where America has roughly 60,000 troops. Fossil fuels cause economic volatility, too. Oil markets are ^^buffeted^^ by an ^^erratic^^ ^^cartel^^. Concentration of the world’s oil reserves makes supply vulnerable to geopolitical shocks. Little wonder that the price has ^^swung^^ by over 30% in a sixth-month period 62 times since 1970.
* A picture of the new energy system is emerging. With bold a tion, renewable electricity such as solar and wind power could rise from 5% of supply today to 25% in 2035, and nearly 50% by 2050. Oil and coal use will drop, although cleaner natural gas will remain central. This architecture will ultimately bring huge benefits. Most important, decarbonising energy will avoid the chaos of unchecked climate change, including devastating droughts, famine, floods and mass dislocation. Once mature, it should be more politically stable, too, because supply will be ^^diversified^^, geographically and technologically. Petrostates will have to attempt to reform themselves and, as their governments start to depend on taxing their own citizens, some will become more representative. Consuming countries, which once ^^sought^^ energy security by ^^meddling^^ in the politics of the oil producers, will instead look to sensible regulation of their own power industry. The 21st-century system should also be less economically volatile. Electricity prices will be determined not by a few bigactors but by competition and gradual efficiency gains.
* Yet even as a better energy system emerges, the threat of a poorly managed transition ^^looms^^. Two risks stand out. ^^Autocratic^^ China could temporarily gain ^^clout^^ over the global power sys tem because of its dominance in making key components and developing new technologies. Today Chinese firms produce 72% of the world’s solar modules, 69% of its lithium-on batteries and 45% of its wind turbines. They also control much of the refining of minerals ^^critical^^ to clean energy, such as ^^cobalt^^ and lithium. Instead of a petrostate, the People’s Republic may become an “electrostate”. In the past six months it has announced invest ments in electric-car infrastructure and transmission, tested a nuclear plant in Pakistan and considered ^^stockpiling^^ cobalt.
* China’s ^^leverage^^ depends on how fast other economies move (see briefing). Europe is home to giant developers of wind and solar farms—Orsted, Enel and Iberdrola are building such projects around the world. European firms are leading the race to cut their own emissions, too. America’s ^^trajectory^^ has been affected by the rise of ^^shale^^ oil and gas, which has made it the world’s largest oil producer, and by Republican resistance to decarbonisation measures. If America were to act on climate change—with, say, a carbon tax and new infra structure—its capital markets, national energy laboratories anduniversities would make it a ^^formidable^^ green power.
* The other big risk is the transition of petrostates, which account for 8% of world gdp and nearly 900m citizens. As oil demand ^^dwindles^^, they will face a ^^vicious^^ fight for market share which will be won by the countries with the cheapest and cleanest ^^crude^^. Even as they ^^grapple^^ with the growing urgency of economic and political reform, the public resources to pay for it may dwindle. This year Saudi Arabia’s government revenue fell by 49% in the second quarter. A ^^perilous^^ few decades lie ahead. Faced with these dangers, the temptation will be to ease the adjustment, by taking the transition more slowly. However, that would bring about a different, even more destabilising set of cli- mate-related consequences. Instead, as our special report in this issue explains, the investments being contemplated fall drastically short of what is needed to keep temperatures within 2°C of pre-industrial levels, let alone the 1.5°C required to limit the environmental, economic and political ^^turmoil^^ of climate change. For example, annual investment in wind and solar capacity needs to be about $750bn, triple recent levels. And if the shift to-wards fossil-fuel-free renewable energy accelerates, as it must, it will cause even more geopolitical turbulence. The move to a new energy order is vital, but it will be ^^messy^^.
* Summary
** rein in ![*](((625bcd2c-7e4b-4a3e-b903-d06152dd6284)))
** up-end ![*](((625bcd2c-7e4b-4a3e-b903-d06152dd6284)))
** struck ![*](((625bcd32-aa8e-4d35-b419-23fb5ad237a6)))
** jittery ![*](((625bcd32-aa8e-4d35-b419-23fb5ad237a6)))
** vulnerabilities ![*](((625bcd32-aa8e-4d35-b419-23fb5ad237a6)))
** scraping ![*](((625bcd32-aa8e-4d35-b419-23fb5ad237a6)))
** backing ![*](((625bcd60-e4ed-4aac-b121-13497d9b1a0f)))
** decarbonising ![*](((625bcd60-e4ed-4aac-b121-13497d9b1a0f)))
** earmarked ![*](((625bcd60-e4ed-4aac-b121-13497d9b1a0f)))
** volatile ![*](((625bcd68-cc72-4eaf-be60-ee81a6b914c0)))
** add to ![*](((625bcd68-cc72-4eaf-be60-ee81a6b914c0)))
** mired ![*](((625bcd70-e8ff-40d7-97f9-6e78afd7985e)))
** cronyism ![*](((625bcd70-e8ff-40d7-97f9-6e78afd7985e)))
** vied ![*](((625bcd70-e8ff-40d7-97f9-6e78afd7985e)))
** buffeted ![*](((625bcd70-e8ff-40d7-97f9-6e78afd7985e)))
** erratic ![*](((625bcd70-e8ff-40d7-97f9-6e78afd7985e)))
** cartel ![*](((625bcd70-e8ff-40d7-97f9-6e78afd7985e)))
** swung ![*](((625bcd70-e8ff-40d7-97f9-6e78afd7985e)))
** diversified ![*](((625bcd87-4a8e-4735-9372-0af20c846861)))
** sought ![*](((625bcd87-4a8e-4735-9372-0af20c846861)))
** meddling ![*](((625bcd87-4a8e-4735-9372-0af20c846861)))
** looms ![*](((625bd197-67f8-417c-aae5-cf2003d436e1)))
** Autocratic ![*](((625bd197-67f8-417c-aae5-cf2003d436e1)))
** clout ![*](((625bd197-67f8-417c-aae5-cf2003d436e1)))
** critical ![*](((625bd197-67f8-417c-aae5-cf2003d436e1)))
** cobalt ![*](((625bd197-67f8-417c-aae5-cf2003d436e1)))
** stockpiling ![*](((625bd197-67f8-417c-aae5-cf2003d436e1)))
** leverage ![*](((625bd2e7-2702-42d1-9cf2-65802030577f)))
** trajectory ![*](((625bd2e7-2702-42d1-9cf2-65802030577f)))
** shale ![*](((625bd2e7-2702-42d1-9cf2-65802030577f)))
** formidable ![*](((625bd2e7-2702-42d1-9cf2-65802030577f)))
** dwindles ![*](((625bd39d-40e3-404e-815d-a3636b709049)))
** vicious ![*](((625bd39d-40e3-404e-815d-a3636b709049)))
** crude ![*](((625bd39d-40e3-404e-815d-a3636b709049)))
** grapple ![*](((625bd39d-40e3-404e-815d-a3636b709049)))
** perilous ![*](((625bd39d-40e3-404e-815d-a3636b709049)))
** turmoil ![*](((625bd39d-40e3-404e-815d-a3636b709049)))
** messy ![*](((625bd39d-40e3-404e-815d-a3636b709049)))