#+deck:内科学::呼吸系统::教材::支气管扩张症

* 支气管扩张症/概述 #card
:PROPERTIES:
:id: 62495157-8878-4939-bafc-31a1e27d0a91
:collapsed: true
:END:
** 支气管扩张症（bronchiectasis，或支气管扩张）最早在1819年由发明听诊器的Laennec首先描述，主要指^^急、慢性呼吸道感染和支气管阻塞后，反复发生支气管化脓性炎症^^，致使支气管壁^^结构破坏，管壁增厚^^，引起^^支气管异常和持久性扩张^^的一类异质性疾病的总称，可以是原发或继发，主要分为^^囊性纤维化导致的支气管扩张症和非囊性纤维化导致^^的支气管扩张症。
* 支气管扩张症/病因和发病机制 #card
:PROPERTIES:
:id: 624951ac-1d2b-4e0f-8781-d2d23d1b5688
:collapsed: true
:END:
** 本病可以分为先天性和继发性。
** ^^先天性支气管扩张症少见^^，有些病例无明显病因，
** 但^^弥漫性支气管扩张常发生于有遗传、免疫或解剖缺陷的病人^^，如^^囊性纤维化、纤毛运动障碍和严重的α·抗膜蛋白酶缺乏病人^^。低免疫球蛋白血症、免疫缺陷和罕见的气道结构异常也可引起弥漫性支气管扩张，^^如巨大气管－支气管症（Mounier-Kuhn综合征）、支气管软骨发育不全（Williams-Campbell综合征）^^等。此外，其他气道疾病，如^^变态反应性支气管肺曲菌病（allergic bronchopulmonary aspergillosis, ABPA）也是诱发支气管扩张症的原因之一^^（表2δ－1）。
** 局灶性支气管扩张可源于未进行治疗的^^肺炎或气道阻塞，例如异物或肿瘤^^、^^外源性压迫或肺叶切除后解剖移位。^^
** ((624959ec-b42b-4e97-814d-4bc8635c6168))
* 支气管扩张症/临床表现 #card
:PROPERTIES:
:id: 6249521e-df04-4902-a655-47bf491a7e59
:collapsed: true
:END:
** 主要症状为^^持续或反复的咳嗽、咳痰或咳脓痰^^。痰液为黏液性、黏液脓性或脓性，可呈黄绿色，收集后分层：
*** ^^上层为泡沫，中间为浑浊黏液，下层为脓性成分，最下层为坏死组织^^。
** ^^无明显诱因者常隐匿起病^^，无症状或症状轻微。呼吸困难和喘息常提示有广泛的支气管扩张或有潜在的慢阻肺。随着感染加重，可出现痰量增多和发热，可仅为支气管感染加重，也可为病变累及周围肺实质出现肺炎所致。
** 当支气管扩张^^伴急性感染时，病人可表现为咳嗽、咳脓痰和伴随肺炎^^。50%～70%的病例可发生咯血，大出血常为^^小动脉被侵蚀或增生的血管被破坏所致^^。
** 部分病人以^^反复咯血为唯一症状，称为“干性支气管扩张”^^。
** 气道内有较多^^分泌物时，体检可闻及湿啰音和干啰音^^。病变严重尤其是伴有慢性缺氧、^^肺源性心脏病和右心衰竭的病人可出现杵状指及右心衰竭体征。^^
* 支气管扩张症/实验室和其他辅助检查
:PROPERTIES:
:collapsed: true
:END:
** 支气管扩张症/实验室和其他辅助检查/影像学检查 #card
:PROPERTIES:
:id: 6249546b-28c8-40e6-9e64-3dc4ca5c0ab6
:END:
*** 胸部X线检查:
**** ^^囊状支气管扩张的气道表现为显著的囊腔,腔内可存在气液平面^^
**** 囊腔内无气液平面时，很难与^^大疱性肺气肿或严重肺间质病变的蜂窝肺^^鉴别。
**** 支气管扩张的其他表现为^^气道壁增厚，主要由支气管周围炎症所致^^。
**** 由于受累肺实质通气不足、萎陷，扩张的气道往往聚拢，^^纵切面可显示为“双轨征”，横切面显示“环形阴影^^”。这是由于^^扩张的气道内充满分泌物，管腔显像较透亮区致密，产生不透明的管道或分支的管状结构^^。但是这一检查对判断有无支气管扩张缺乏特异性，病变轻时影像学检查可正常。
*** 胸部高分辨CT扫描（HRCT) :
**** HRCT^^可在横断面上清楚地显示扩张的支气管^^（图2δ－2），且兼具无创、易重复、易接受的特点，现已成为支气管扩张的主要诊断方法。支气管扩张症在HRCT上的主要表现^^为支气管呈柱状及囊状改变，气道壁增厚（支气管内径＜80%外径）^^、^^黏液阻塞、树芽征及马赛克征^^。当CT扫描层面与支气管平行时，扩张的支气管呈“双轨征”或“串珠”状改变；当扫描层面与支气管垂直时，扩张的支气管与伴行的肺动脉形成“印戒征”；
**** 当多个囊状扩张的支气管彼此相邻时，则表现为“蜂窝”状改变。
** 支气管扩张症/实验室和其他辅助检查/实验室检查 #card
:PROPERTIES:
:id: 62495541-e686-4ee2-a2de-8308ee83342a
:END:
*** (1）血常规及炎症标志物：当细菌感染导致支气管扩张症急性加重时，血常规白细胞计数、中性粒细胞分类及C反应蛋白可升高。
*** (2）血清免疫球蛋白：合并免疫功能缺陷者可出现血清免疫球蛋白(IgG、lgA,lgM）缺乏。
*** (3）血气分析：可判断病人是否合并低氧血症和（或）高碳酸血症。
*** (4）微生物学检查：应留取合格的痰标本送检涂片染色以及痰细菌培养，痰培养和药敏试验结果可指导抗菌药物的选择，痰液中找到抗酸杆菌时需要进一步分型是结核杆菌还是非结核分枝杆菌。
*** (5）其他：必要时可检测类风湿因子、抗核抗体、抗中性粒细胞胞浆抗体。怀疑ABPA的病人可选择性进行血清lgE测定、烟曲霉皮试、曲霉沉淀素检查。如病人自幼起病，合并慢性鼻窦炎或中耳炎，或合并右位心，需怀疑PCD可能，可行鼻呼出气一氧化氮测定筛查，疑诊者需进一步取纤毛上皮行电镜检查，必要时行基因检测
** 支气管扩张症/实验室和其他辅助检查/其他检查 #card
:PROPERTIES:
:id: 624955bd-3c81-4164-b162-f9f0c9f9d594
:END:
*** 纤维支气管镜检查：当支气管扩张呈^^局灶性^^且位于^^段支气管以上^^时，可^^发现弹坑样改变^^，可通过纤维支气管镜采样用于病原学诊断及病理诊断。纤支镜检查还可明确出血、扩张或阻塞的部位。还可经纤支镜进行局部灌洗，采取灌洗液标本进行涂片、细菌学和细胞学检查，协助诊断和指导治疗。
*** 肺功能测定：可证实由弥漫性支气管扩张或相关阻塞性肺病导致的^^气流受限以及指导临床使用支气管舒张剂。^^
* 支气管扩张症/诊断 #card
:PROPERTIES:
:id: 6249560c-a83e-488b-9cf7-3782856c2276
:END:
** 诊断
*** 根据^^反复咳脓痰、咯血病史^^和既往有^^诱发支气管扩张的呼吸道感染病史^^，^^HRCT显示支气管扩张的异常影像学改变^^，^^即可明确诊断为支气管扩张^^。
*** 诊断支气管扩张症的病人还应进一步^^仔细询问既往病史、评估上呼吸道症状、根据病情完善相关检查以明确病因诊断。^^
* 支气管扩张症/评估 #card
:PROPERTIES:
:id: 624956ed-9929-403f-b08f-9dea695763cb
:END:
** 评估病人初次诊断后的评估包括：
*** 痰液检查，包括痰涂片（包括真菌和抗酸染色），痰培养加药敏试验。
*** 肺部CT随访，尤其是肺内出现空洞，无法解释的咯血或痰中带血，治疗反应不佳，反复急性加重等。
*** 肺功能用于评估疾^^病进展程度和指导药物治疗。^^
*** 血气分析判断是否存在低氧血症和（或）C02滞留。以及实验室检查评估病人的炎症反应，免疫状态，是否合并其他病原体感染等。
* 支气管扩张/鉴别诊断 #card
:PROPERTIES:
:id: 62495674-c436-40fd-b9ca-bb5c5f8d8a87
:END:
** 需鉴别的疾病主要为慢性支气管炎、肺脓肿、肺结核、先天性肺囊肿、支气管肺癌和弥漫性泛细支气管炎等。仔细研究^^病史和临床表现，参考影像学、纤维支气管镜和支气管造影的特征^^常可作出明确的鉴别诊断。下述要点对鉴别性诊断有一定参考意义：
** 1.慢性支气管炎多发生在^^中年以上病^^人，在气候多变的冬、春季节咳嗽、咳痰明显，^^多咳白色黏液痰^^，感染急性发作时可出现脓性痰，但^^无反复咯血史^^。昕诊双肺可闻及^^散在干、湿唠音^^。
** 2.肺脓肿: 起病急，有^^高热、咳嗽、大量脓臭痰^^。X线检查可见局部浓密炎症阴影，内^^有空腔液平^^。
** 3.肺结核 :常有^^低热、盗汗、乏力、消瘦^^等结核毒性症状，干、湿啰音多局限于上肺，X线胸片和痰结核菌检查可作出诊断。
** 4.先天性肺囊肿
*** X线检查可见多个边界纤细的^^圆形或椭圆形阴影，壁较薄，周围组织无炎症浸润^^。胸部CT和支气管造影可协助珍断。
** 5.弥漫性泛细支气管炎 有慢性咳嗽、咳痰、活动时呼吸困难及慢性鼻窦炎。胸片和胸部CT显示^^弥漫分布的小结节影。大环内醋类抗生素治疗有效^^。
** 6.支气管肺癌多见于40岁以上病人，可伴有^^咳嗽、咳痰、胸痛，痰中带血。大咯血少见^^。影像学、痰细胞学、支气管镜检查等有助于确诊。
* 支气管扩张/治疗概括 #card
:PROPERTIES:
:id: 6249571d-c0c1-4b1b-be09-ff8139100df9
:END:
** 治疗基础病
** 控制感染
** 改善气流受限
** 清除气道分泌物
** 免疫调节剂
** 咯血的治疗
** 外科治疗
** 预防
* 支气管扩张/治疗/治疗基础病 #card
:PROPERTIES:
:id: 6249577a-abaa-494b-86ed-db70cbef451a
:collapsed: true
:END:
** 对活动性肺结核伴支气管扩张应积极抗结核治疗，低免疫球蛋白血症可用免疫球蛋白替代治疗
* 支气管扩张/治疗/控制感染 #card
:PROPERTIES:
:id: 624958c0-2d1c-41be-a101-918aaf8ae149
:collapsed: true
:END:
** 支气管扩张症病人出现^^痰量增多及其脓性成分增加等急性感染征象时，需应用抗感染药物^^。
** 急性加重期开始抗菌药物治疗前应常规送痰培养，根据^^痰培养和药敏结果指导抗生素应用^^，但在^^等待培养结果时即应开始经验性抗菌药物治疗^^。
** ^^无铜绿假单胞菌感染高危因素的病人应立即经验性使用对流感嗜血杆菌有活性的抗菌药物^^，如氨节西林／筒’巴坦，阿莫西林／克拉维酸，^^第二代头孢菌素，第三代头孢菌素^^（头抱曲松纳、头抱唾肪），莫西沙星、左氧氟沙星。
** 对于^^存在铜绿假单胞菌感染高危因素的病人^^［如存在以下4条中的2条：①近期住院；②每年4次以上或近3个月以内应用抗生素；③重度气流阻塞（FEV1<30%预计值）；④最近2周每日口服泼尼松＜lOmg］，可选择具有抗假单胞菌活性的β内酰胺类抗生素（^^头孢他啶,头孢吡亏,哌拉西林／他唑巴坦、头抱哌R酣／舒巴坦^^），^^碳青霉烯类^^（如亚服培南、美罗培南），^^氨基糖苷类^^，^^喹诺酮类（环丙沙星或左氧氟沙星)^^，可单独应用或联合应用。
** 对于慢性咳脓痰病人，还可考虑使用^^疗程更长的抗生素，如口服阿莫西林或吸人氨基糖苷类药物^^，或间断并规则使用单一抗生素以及轮换使用抗生素以加强对下呼吸道病原体的清除。^^合并ABPA时，除一般需要糖皮质激素（泼尼松0.5～lmg/kg）外，还需要抗真菌药物（如伊曲康嗖）联合治疗^^，疗程较长。
** 支气管扩张症病人^^出现肺内空洞，尤其是内壁光滑的空洞，合并或没有合并树芽征，要考虑到不典型分枝杆菌感染的可能^^，可采用痰抗酸染色，痰培养及痰的微生物分子检测进行诊断。^^本病也容易合并结核，^^病人可以有肺内空洞或肺内结节，渗出合并增殖性改变等，可合并低热，夜间盗汗，需要在随访过程中密切注意上述相关的临床表现。支气管扩张症病人^^容易合并曲霉菌的定植和感染，表现为管腔内有曲霉球，或出现慢性纤维空洞样改变，或急’性、亚急性侵袭性感染。曲霉菌的侵袭性感染治疗一般选择伏立康唑^^
* 支气管扩张/治疗/改善气流受限 #card
:PROPERTIES:
:id: 624958c6-c714-4d06-bade-2b6f86cefe09
:collapsed: true
:END:
** 建议支气管扩张症病人^^常规随访肺功能的变化^^，尤其是已经有阻塞性通气功能障碍的病人。
** 长效支气管舒张剂（长效β2受体激动剂，长效抗胆碱能药物，吸人糖皮质激素／长效β2受体激动剂）可改善气流受限并帮助清除分泌物，对伴有^^气道高反应及可逆性气流受限^^的病人常有一定疗效。但由于^^缺乏循证医学的依据，在支气管舒张剂的选择上，目前并无常规推荐的指征。^^
* 支气管扩张/治疗/清除气道分泌物 #card
:PROPERTIES:
:id: 624958d8-6528-4a32-8217-55c456a2180d
:collapsed: true
:END:
** 包括物理排痰和化痰药物。
** 物理排痰包括
*** ^^体位引流，一般头低臀部抬高，可配合震动拍击背部协助痰液引流^^。
*** 气道内^^雾化吸人生理盐水^^，短时间内吸人高渗生理盐水，或吸入黏液松解剂如乙酰半脱氨酸等，可有助于痰液的稀释和排出。
*** 其他如胸壁震荡，正压通气，主动呼吸训练等合理使用也可以起到排痰作用。
** 药物包括黏液溶解剂，痰液促排剂，抗氧化剂等^^。N－乙酰半脱氨酸具有较强的化痰和抗氧化作用。^^切忌在^^非囊性纤维化支气管扩张病人使用重组脱氧核糖核酸酶。^^
* 支气管扩张/治疗/免疫调节剂 #card
:PROPERTIES:
:id: 624958d8-c719-41b6-b1da-2905f4c7cc88
:collapsed: true
:END:
** 用一些促进^^呼吸道免疫增强^^的药物如^^细菌细胞壁裂解产物^^可以减少支气管扩张症病人的急性发作。部分支气管扩张症病人长期使用^^十四环或十五环大环内酯类抗生素可以减少急性发作和改善病人的症状^^，但需要注意长期口服抗生素带来的其他副作用，包括心血管、听力、肝功能的损害及出现细菌耐药等。
* 支气管扩张/治疗/咯血的治疗 #card
:PROPERTIES:
:id: 624958d9-5761-4199-8fbb-1b1e8d58b612
:collapsed: true
:END:
** 对反复咯血的病人，如果咯血量少，可以对症治疗或口服^^卡巴克洛（安咯血）、云南白药^^。若出血量中等，可静脉给予^^垂体后叶素或[[酚妥拉明]]^^；若出血量大，经内科治疗无效，可考虑^^介入栓塞治疗或手术治疗^^。^^使用垂体后叶素需要注意低钠血症的产生^^。
* 支气管扩张/治疗/外科治疗 #card
:PROPERTIES:
:id: 624958dd-2564-43cb-a8f9-778e1950bbc2
:collapsed: true
:END:
** 如支气管扩张为^^局限性，经充分内科治疗仍顽固反复发作者^^，可考虑外科手术^^切除病变肺组织^^。如大出血来自增生的支气管动脉，经休息和抗生素等保守治疗不能缓解仍反复大咯血时，病变局限者可考虑外科手术，否则采用支气管动脉栓塞术治疗。^^对于那些尽管采取了所有治疗仍致残的病例，合适者可考虑肺移植。^^
*
*