* 呼吸系统
** 慢性支气管炎 $\textcolor{yellow}{不在大纲}$
:PROPERTIES:
:collapsed: true
:END:
*** [#A] 2. 1994N63A 慢性支气管炎早期肺功能改变为
- [ ] A.VC减少
- [x] B.一秒率减少
- [ ] C.残气量增加
- [ ] D.闭合气量减少
- [ ] E.肺总量增加

#+BEGIN_QUOTE
一秒率是关于流速的量，VC肺活量、RV残气量、TLC肺总量都是有关容量的量，而老慢支是典型的阻塞性通气功能障碍，也就是说老慢支是流速减慢的障碍，所以老慢支时有关流速的量就早早发生了变化(减小)，有关容量的量发生变化(增加)就晚一些。
       闭合容量指肺下部的小气道开始闭合后，继续呼出的气体量，老慢支发展到后期到肺气肿甚至COPD时，早期小气道就病变，所以小气道闭合的早，所以闭合容积增加。
         现在老慢支、肺气肿已经不再大纲了，只考COPD。❤️COPD早期变化：闭合容积增加，静态肺顺应性↑、动态肺顺应性↓。
静态肺顺应性只取决于肺的弹性
动态肺顺应性取决于气道阻力和肺的弹性
#+END_QUOTE
** [[肺气肿]]
:PROPERTIES:
:collapsed: true
:END:
*** 7. 1995N66A 关于阻塞性肺气肿，哪一项描述是正确的
- [ ] A.经积极治疗可以痊愈
- [x] B.其病理改变是不可逆的
- [ ] C.仅限于肺泡弹性减退与膨胀
- [ ] D.α₁-抗胰蛋白酶增加易发生肺气肿
- [ ] E.肺功能改变主要是肺活量减少

#+BEGIN_QUOTE
阻塞性肺气肿主要是由于气道阻塞导致肺部终末细支气管远端气腔出现异常持久的扩张，并伴有肺泡壁和细支气管的破坏，病变并非仅限于肺泡弹性减退与膨胀（P22）（C错），肺组织的变化多呈进行性发展，不可逆（P22）（B对）。积极治疗可以减慢或者阻止肺组织的进一步破坏，但已损坏的肺组织无法恢复，疾病无法痊愈（A错）。蛋白酶增多或抗蛋白酶不足可导致组织结构破坏，产生肺气肿，α₁-抗胰蛋白酶增加不会发生肺气肿（D错）。阻塞性肺气肿的肺功能改变主要是流速降低、残气量增加，限制性通气障碍的肺功能改变主要是肺活量减少（E错）。
#+END_QUOTE
*** 8. 1996N61A 目前认为关于肺气肿发生的机理，下列哪项不正确
- [x] A.弹性酶活性受抑制
{{embed ((6214a5f1-4a22-45d2-b5e7-2398d57591c5))}} 
- [ ] B.α₁-抗胰蛋白酶缺乏
- [ ] C.血清α₁-抗胰蛋白酶活力低下
- [ ] D.中性粒细胞和巨噬细胞释放蛋白分解酶增多
- [ ] E.肺泡壁毛细血管受压，肺组织营养障碍
[[混淆]]:肺泡壁的小动脉
*** [#A] 9. 2004N142X 下列哪些因素与肺气肿的发病机制有关
- [x] A.肺部慢性炎症，损害肺组织和肺泡壁
- [x] B.支气管慢性炎症，使管腔狭窄，形成不完全阻塞
- [ ] C.肺小动脉受压，血液供应减少，肺组织营养障碍
[[Comments]] :应该是肺毛细血管受压血液供应减少肺组织营养障碍
- [ ] D.慢性炎症破坏肺泡间质，使其失去支架作用，促使肺泡膨胀
[[Comments]]:肺气肿不伴有肺间质的纤维化其破坏的不是肺间质而是肺泡壁并使其异常持久的扩张
*** [#A] 13. 1999N57A 慢性支气管炎并发肺气肿早期病理生理改变，下列哪项错误
- [ ] A.病变局限于细小气道
- [x] B.[[最大通气量]]降低
- [ ] C.闭合容积增大
- [ ] D.动态肺顺应性降低
- [ ] E.静态肺顺应性增加 
#+BEGIN_QUOTE
慢支合并肺气肿呼吸功能检查早期可无异常表现，病变局限于细小气道（A对），若有小气道阻塞时，最大呼气流量-容积曲线显示流量明显减低（该指标比第一秒用力呼气量更敏感）闭合容量可增加（C对）、动态肺顺应性降低（D对）；然后随着病情发展，肺组织弹性日益减退，肺泡持续扩大，回缩障碍，则残气量及残气量占肺总量的百分比增加，可有最大通气量降低，可见最大通气量降低为晚期表现，并非早期病理生理改变（B错，为本题正确答案）。顺应性是指弹性体在外力作用下发生形变的难易程度。它包括静态顺应性和动态顺应性两者，前者反映了肺组织的弹性，肺气肿时，肺组织的弹性阻力降低，在外力作用下更容易发生形变，故静态顺应性应当增加（E对）；动态顺应性反应的是肺呼吸运动的容易程度，慢性支气管炎并发肺气肿时肺呼吸运动困难，故动态顺应性下降。
#+END_QUOTE 
#+BEGIN_QUOTE
闭合容积说的从下级小气道关闭开始后继续呼出的气量，你体会COPD的患者或者小气道病变的人的呼气性呼吸困难是因为小气道提前关闭了，既然提前关闭，那么此时就开始计算闭合容积，提前计算了那么肯定会增加吧。（不要想着小气道病变了还怎么继续往外呼气，要知道早期并不是所有的小气道都病变了，还有正常的，但是因为病变的小气道存在使计算闭合容积提前。体会起来就像肾糖阈一样，一颗老鼠屎坏了一锅粥。）
#+END_QUOTE
*** 15. 1997N67A 慢性支气管炎并发肺气肿时，最早出现的病理生理改变是
- [x] A.时间肺活量降低
- [ ] B.生理无效腔气量增大
- [ ] C.通气/血流比例失调
- [ ] D.残气占肺总量百分比增加
- [ ] E.低氧血症 
#+BEGIN_QUOTE
^^慢性支气管炎并发肺气肿主要导致肺的通气功能障碍，早期病变累及小气道，表现为小气道炎症、小气道纤维组织形成、小气道黏液栓等，使小气道阻力明显升高，肺功能检查以流速降低为主要改变，时间肺活量降低^^(A对）。以后病情发展，肺组织弹性日益减退，肺泡持续扩大，回缩障碍，则残气量及残气量占肺总量的百分比增加（D错）。肺气肿加重导致肺泡周围肺毛细血管受挤压大量减少，肺泡间血流减少，此时肺泡虽有通气，但肺泡壁无血流灌流，导致无效腔样气量增大（B错）；也有部分肺区虽有血流灌流，但通气不良，导致功能性分流增加，从而产生通气血流比例失调（C错）。发展到最后会引起缺氧和二氧化碳潴留，发生不同程度的低氧血症（E错）和高碳酸血症。
#+END_QUOTE
[[Comments]]:为什么COPD的最早病理生理改变是小气道的缩窄?因为其由慢支为基础发展为肺气肿再发展为COPD,气腔的扩张依赖于小气道狭窄
** COPD
*** [#A] 17. 2016N142B COPD患者出现低氧血症最主要的机制是
- [x] A.肺泡通气量下降
{{embed ((6214b57b-8de5-4955-8492-e699bf67dd28))}} 
- [ ] B.弥散障碍
- [ ] C.通气/血流比例失调
- [ ] D.肺内分流

#+BEGIN_QUOTE
慢阻肺的特征性病理生理变化是持续气流受限导致肺通气功能障碍，肺泡通气量下降（A对）。其为COPD患者出现低氧血症最主要的机制，随着病情发展，会出现通气/血流比例失调（肺内分流为其类型之一）和弥散障碍（BCD错）。弥散障碍为间质性肺疾病患者出现低氧血症的主要机制。
#+END_QUOTE
*** [#A] 18. 1999N56A 阻塞性肺气肿支气管炎型的临床表现，下列哪项是正确的
- [x] A.发病年龄较轻 
#+BEGIN_QUOTE
老书有，COPD分红喘(气肿型)与紫肿(支气管型)两型，前者以老年人，消瘦，肺气肿为主要特征。后者以年轻人，胖子，支气管炎，咳嗽重喘息轻为主要特征。后者缺氧较前者严重，故发紫绀。肺心病，故水肿。
#+END_QUOTE 
- [ ] B.多无紫绀
- [ ] C.喘息明显，多呈持续性
[[Comments]] :咳嗽重喘息轻
- [ ] D.X线胸片呈肺纹理减少 
#+BEGIN_QUOTE
肺气肿无明显纤维化  这个是个很重要的考点
#+END_QUOTE 
- [ ] E.静息时PaO₂轻度降低
[[Comments]]:支气管型比气肿型的缺氧严重
*** 19. 2010N58A 下列疾病中，叩诊检查可发现Kronig峡增宽的是
- [ ] A.肺炎
- [x] B.肺气肿 
#+BEGIN_QUOTE
[[Kronig峡]]是指肺尖的宽度，正常值为4～6cm。当肺内含气量增大时，Kronig峡增宽，反之变狭窄。肺气肿（B对）、COPD患者肺内含气量增大，故Kronig峡增宽。肺结核（C错）出现肺尖浸润时，可使Kronig峡变狭窄；[[肺炎]]、[[胸腔积液]]均不会使Kronig峡增宽（AD错）。
#+END_QUOTE 
- [ ] C.肺结核
- [ ] D.胸腔积液
*** 20. 1989N13A 对阻塞性肺气肿的诊断，最有价值的是
- [ ] A.PaO₂＜正常
- [ ] B.潮气量低于正常
- [ ] C.肺活量降低
- [x] D.残气量/肺总量＞40% 
#+BEGIN_QUOTE
阻塞性肺气肿的病理变化为肺部[[终末细支气管远端气腔]]出现异常持久的扩张，伴有肺泡壁和细支气管的破坏（P22），肺组织弹性日益减退，肺泡持续扩大，回缩障碍，则残气量及残气量占肺总量的百分比增加，所以临床上把^^残气量/肺总量>40%（D对）作为诊断肺气肿最有价值的指标^^。潮气量低于正常（B错）及肺活量降低（C错）也可见于[[支扩]]、[[支气管哮喘]]等多种疾病，对诊断阻塞性肺气肿的特异性不高，故其不是诊断阻塞性肺气肿最有价值的指标。PaO₂<正常（A错）、PaCO₂>正常（E错）可见于COPD、支气管哮喘及肺心病等多种疾病，对诊断阻塞性肺气肿的特异性不高，故其不是诊断阻塞性肺气肿最有价值的指标。
#+END_QUOTE 
- [ ] E.PaCO₂＞正常
*** [#A] 23. 1997N128C 慢性阻塞性肺气肿
- [ ] A.弥散障碍
{{embed ((6214b57f-7f29-4bd6-b422-b4efcf78d729))}}
- [ ] B.第一秒用力呼气率减低
- [x] C.两者均有
- [ ] D.两者均无
*** 29. 2006N61A 用于鉴别COPD和支气管哮喘的试验是
- [ ] A.过敏原试验
- [ ] B.支气管激发试验
- [ ] C.低氧激发试验
- [ ] D.运动试验
- [x] E.支气管舒张试验 
#+BEGIN_QUOTE
{{embed ((6215fa75-c10a-4403-875d-39ed203cee34))}} 
#+END_QUOTE
[[Comments]]:为什么支气管舒张试验的标准是增加12%因为,正常人是83%而诊断 [[COPD]]为70%
*** 30. 1992N138X 吸氧浓度至40%，可纠正以下哪种情况引起的低氧血症
- [ ] A.房间隔缺损引起的肺动脉高压 
#+BEGIN_QUOTE
严重肺气肿（B对）、慢性肺心病急性加重期（C对）都存在肺通气下降的情况，肺通气下降导致动脉血氧分压下降，提高氧浓度可使患者低氧血症有所纠正或好转。房间隔缺损（P272）（A错）后，由于左房压力高于右房，血液由左向右分流，肺血流量增加，持续肺血流量增加引起肺淤血，导致肺动脉高压，右心系统的压力随之持续增高甚至超过左心系统，此时逆转为右向左的分流，分流的静脉血不经过肺循环直接进入体循环而引起低氧血症，故吸氧浓度至40%不能纠正低氧血症。ARDS（P130）（D错）可因休克、创伤等诱因使肺毛细血管内皮、肺泡细胞损伤，致使肺微血管血栓形成，肺泡表面活性物质减少，肺泡不张，致使通气与血流比例失调，肺内分流增加，导致严重的低氧血症，而提高吸氧浓度并不能改善通气与血流比例和肺内分流，故吸氧浓度至40%不能纠正低氧血症。
#+END_QUOTE 
- [x] B.严重的肺气肿
- [x] C.慢性肺心病急性加重期
- [ ] D.ARDS
*** [#A] 31. 2000N152X 关于肺源性心脏病呼吸衰竭的氧疗，下列哪些正确
- [x] A.提高肺泡内PaO₂，增加O₂弥散能力
- [x] B.提高动脉血氧饱和度，增加可利用氧
- [ ] C.增加肺泡通气量，促进CO₂排出 
#+BEGIN_QUOTE
氧疗的原则是在保证氧分压迅速提高到60mmHg或脉搏容积血氧饱和度达到90%以上的前提下，尽量降低吸氧浓度。氧疗可提高肺泡内氧分压，加大肺泡和毛细血管之间的氧分压差，增加O₂的弥散能力（A对），从而提高动脉血氧饱和度，增加可利用氧，提高患者的活动耐力和延长生存时间。（B对）。由于缺氧会导致肺血管收缩，肺动脉压力增高，故氧疗还可通过降低肺循环阻力和肺动脉压，降低后负荷，增加心肌收缩力（D对）。氧疗只能提高氧分压及血氧饱和度，但不能增加肺泡通气量及促进CO₂的排出（C错）。
#+END_QUOTE 
#+BEGIN_QUOTE
氧疗:病人主动吸氧，通气量由自身的肺功能决定。
机械通气:病人被动吸氧，通气量可增加可调节。
#+END_QUOTE 
- [x] D.降低肺循环阻力和肺动脉压，增强心肌收缩力
*** [#B] 32. 2013N96A 男性，60岁。反复咳喘40余年，活动后气短10余年，间断双下肢水肿5年，加重1天入院，吸烟史40年。查体：嗜睡，口唇发绀，颈静脉怒张，桶状胸，双肺可闻及干湿啰音，心率110次/分，心率整，肝肋下3.0cm，双下肢水肿。血气分析示pH7.26，PaO₂45mmHg，PaCO₂75mmHg。下列治疗措施错误的是
- [ ] A.积极控制感染
- [ ] B.应用无创呼吸机改善通气
- [x] C.应用5%碳酸氢钠纠正酸中毒 
#+BEGIN_QUOTE
患者老年男性，长期吸烟史，反复咳喘40余年，桶状胸，故有COPD的基础疾病。现该患者双下肢水肿，颈静脉怒张，肝肋下3.0cm，应考虑存在右心衰；嗜睡，口唇发绀，血气分析示pH7.26，PaO₂45mmHg，PaCO₂75mmHg，存在Ⅱ型呼吸衰竭（PaO₂<60mmHg，PaCO₂>50mmHg），合并呼吸性酸中毒。该患者现处于COPD急性加重期。急性加重期的治疗措施主要为积极控制感染（A对）、应用无创呼吸机改善通气（B对）、应用支气管舒张剂（D对）。该患者存在酸中毒是通气障碍所致，所以应该改善肺部通气来治疗酸中毒（C错，为本题正确答案），补碱一般应用于重症代谢性酸中毒且不易控制量，容易导致碱中毒，使氧解离曲线左移，减少血红蛋白氧的释放，加重组织缺氧。
#+END_QUOTE 
- [ ] D.应用支气管舒张剂