#+title: 内科学/消化系统/功能性肠胃病/教材/肠易激综合征
#+deck:  内科学::消化系统::功能性肠胃病::教材::肠易激综合征

* 肠易激综合征/定义 #card
:PROPERTIES:
:id: 6252bfc9-d934-4586-9f21-8cbe173d0546
:END:
** 肠易激综合征(irritable bowel syndrome, IBS) <span class="untestedHL">是一种以腹痛伴排便习惯改变为特征而无器质性病变的常见功能性肠病</span>。在欧美国家成人患病率为10%~20%,我国为10%左右。 <span class="tested">病人以中青年居多,男女比例约1:2,有家族聚集倾向。</span>
* 肠易激综合征/病因和发病机制 #card
:PROPERTIES:
:id: 6252c064-1841-4890-9bb8-3a7d32f10933
:END:
** 是多因素共同作用的结果,病理生理机制涉及:
** ①胃肠动力学异常: <span class="untestedHL"> <span class="untestedHL">结肠电生理研究显示IBS以便秘、腹痛为主者3次/分的慢波频率明显增加</span>。腹泻型IBS高幅收缩波明显增加。对各种生理性和非生理性刺激(如进食、肠腔扩张、肠内容物以及某些胃肠激素)的动力学反应过强,并呈反复发作过程。</span>
** ②内脏高敏感性: <span class="untestedHL">直肠气囊充气试验表明,IBS病人充气疼痛阔值明显低于对照组</span>。大量研究发现,IBS病人对胃肠道充盈扩张、肠平滑肌收缩等生理现象敏感性增强,易产生腹胀腹痛。胃肠动力学异常和内脏高敏感性可能是IBS的核心发病机制。
** ③ <span class="untestedHL">中枢神经系统对肠道刺激的感知异常和脑-肠轴调节异常:</span>IBS病人存在中枢神经系统的感觉异常和调节异常,IBS可以被认为是对脑-肠系统的超敏反应,包括对肠神经系统和中枢神经系统。其中,5-HT、胆囊收缩素、生长抑素、胃动素等胃肠激素可能在胃肠道动力和感觉调节中发挥作用。
** ④肠道感染:越来越多的临床研究表明, <span class="untestedHL">IBS可能是急慢性感染性胃肠道炎症后的结果之一,其发病与感染的严重性及应用抗生素时间均有一定相关性。</span>
** ⑤肠道微生态失衡: <span class="untestedHL">IBS-D病人乳酸菌、脱硫弧菌和双歧杆菌数量明显减少</span>,而IBS-C病人韦荣球菌数目增加。但是肠道微生态参与IBS发病的具体机制仍待进一步研究。
** <span class="tested">6精神心理障碍:大量调查表明,IBS病人焦虑、抑郁积分显著高于正常人,应激事件发生频率亦高于正常人,对应激反应更敏感和强烈。</span>
* 肠易激综合征/临床表现 #card
:PROPERTIES:
:id: 6252c0de-dac9-4e4a-94a5-edacac2a0297
:END:
** 起病隐匿, <span class="tested">症状反复发作或慢性迁延</span>,病程可长达数年至数十年,但全身健康状况却不受影响。精神、饮食等因素常诱使症状复发或加重。最主要的临床表现是腹痛、排便习惯和粪便性状的改变。
** 腹痛:  <span class="tested">几乎所有IBS病人都有不同程度的腹痛,部位不定,以下腹和左下腹多见,排便或排气后缓解。极少有睡眠中痛醒者。</span>
腹泻:  <span class="tested">腹泻型IBS常排便较急,粪便呈糊状或稀水样,一般每日3~5次左右,少数严重发作期可达10余次,可带有黏液,但无脓血。</span>部分病人腹泻与便秘交替发生。
** 便秘:  <span class="untestedHL">便秘型IBS常有排便困难,类便干结、量少,呈羊粪状或细杆状,表面可附黏液</span>。
** 其他: <span class="untestedHL"> 常伴腹胀、排便不净感,部分病人同时有消化不良症状和失眠、焦虑、抑郁、头晕、头痛等精神症状。</span>
** 体征: 一般无明显体征,可在相应部位有轻压痛,部分病人可触及 <span class="untestedHL">腊肠样肠管</span>,直肠指检可感到肛门痉挛、张力较高,可有触痛。
* 诊断与鉴别诊断
** 肠易激综合征/诊断 #card
:PROPERTIES:
:id: 6252c305-b574-47d9-a46d-88b1aa8e09b8
:END:
*** <span class="tested">在缺乏可解释症状的形态学改变和生化异常基础上,反复发作的腹痛,近3个月内发作至少每周1次,伴下面2项或者2项以上症状:</span>
**** <span class="tested">①与排便相关;</span>
**** <span class="tested">②症状发生伴随排便次数改变;</span>
**** <span class="tested">③症状发生伴随粪便性状(外观)改变。诊断前症状出现至少6个月,近3个月符合以上诊断。</span>
*** <span class="tested">以下症状不是诊断所必备,但属常见症状,这些症状越多越支持IBS的诊断:</span>
**** <span class="tested">①排便频率异常(每,天排便>3次或每周<3次);</span>
**** <span class="tested">②粪便性状异常(块状/硬便或稀水样便);</span>
**** <span class="tested">③粪便排出过程异常(费力、急迫感、排便不尽感);</span>
**** <span class="tested">④黏液便;</span>
**** <span class="tested">⑤胃肠胀气或腹部膨胀感。</span>
*** 西方国家便秘型多见,我国则以腹泻型为主。
** 肠易激综合征/鉴别诊断 #card
:PROPERTIES:
:id: 6252c31b-91cc-4d3e-a6ac-b5965f3e892a
:END:
*** 在详细询问病史基础上, <span class="untestedHL">应分别与引起腹痛和腹泻/便秘的疾病进行鉴别,要注意与乳糖不耐受症及药物不良反应引起的便秘鉴别。</span>对于存在警报症状的病人不宜轻易诊断IBS,这些警报症状包括体重下降、持续性腹泻、夜间腹泻、粪便中带血、顽固性腹胀、贫血、低热等,特别是50岁以上出现新发
症状者要高度警惕器质性疾病。
* 肠易激综合征/治疗 #card
:PROPERTIES:
:id: 6252c3eb-4b11-4939-a474-671d0d1dd3fe
:END:
** 旨在改善病人症状,提高生活质量、消除顾虑。
(一)一般治疗
*** <span class="untestedHL">了解促发因素,并设法予以去除</span>;
*** 指导病人建立良好的生活习惯及饮食结构 <span class="untestedHL">,避免诱发症状的食物</span>。
*** 告知病人IBS的性质, <span class="untestedHL">解除病人顾虑</span>。对伴有失眠、焦虑者可适当给予镇静药。
** (二)对症治疗
*** 1.腹痛
**** (1)解痉药: <span class="tested">匹维澳铵为选择性作用于胃肠道平滑肌的钙拮抗药,能够缓解平滑肌痉挛,还可以降低内脏高敏感性,对腹痛亦有一定疗效</span>,且不良反应少,用法为每次50mg,3次/日。 <span class="untestedHL">阿托品、莨菪碱类、颠茄合剂等抗胆碱药物可作为缓解腹痛的短期对症治疗,不适于长期用药。</span>
**** (2)调节内脏感觉的药物: <span class="untestedHL">5-HT₃选择性括抗剂阿洛司琼、雷莫司琼可以改善病人腹痛症状,减少大便次数</span>。 <span class="untestedHL">5-HT₄受体激动剂普卡必利可减轻病人腹痛、腹胀症状,使排便通畅。</span>
*** 2.腹泻
**** <span class="untestedHL">腹泻病人可根据病情适当选用止泻药。洛哌丁胺或地芬诺酯止泻效果好,适用于腹泻症状较重者,但不宜长期使用。轻症者宜使用吸附止泻药如蒙脱石散、药用炭等。</span>
*** 3.便秘
**** (1)泻药:对以便秘为主的病人,宜使用作用温和的轻泻剂,常用的渗透性轻泻剂如聚乙二醇、乳果糖或山梨醇,容积性泻药如甲基纤维素等也可选用。
**** (2)促动力药:此类药物如莫沙必利、依托比利等,能够促进小肠和结肠蟠动。马来酸曲美布汀是消化道双向调节剂,对各种类型的IBS症状都有较好的效果。
*** 4. <span class="untestedHL">抗抑郁药 </span>详见本章第一节。
*** 5.肠道微生态制剂  <span class="untestedHL">如双歧杆菌、乳酸杆菌、酪酸菌等制剂,</span>可纠正肠道菌群失调,对腹泻、腹胀有一定疗效。
** (三)心理和行为疗法
症状严重而顽固,经一般治疗和药物治疗无效者应考虑予以心理行为治疗,包括心理治疗、认知疗法、催眠疗法和生物反馈疗法等,