* 呼吸系统
** 慢性支气管炎 $\textcolor{yellow}{不在大纲}$
:PROPERTIES:
:collapsed: true
:END:
*** [#A] 2. 1994N63A 慢性支气管炎早期肺功能改变为
- [ ] A.VC减少
- [x] B.一秒率减少
- [ ] C.残气量增加
- [ ] D.闭合气量减少
- [ ] E.肺总量增加

#+BEGIN_QUOTE
一秒率是关于流速的量，VC肺活量、RV残气量、TLC肺总量都是有关容量的量，而老慢支是典型的阻塞性通气功能障碍，也就是说老慢支是流速减慢的障碍，所以老慢支时有关流速的量就早早发生了变化(减小)，有关容量的量发生变化(增加)就晚一些。
       闭合容量指肺下部的小气道开始闭合后，继续呼出的气体量，老慢支发展到后期到肺气肿甚至COPD时，早期小气道就病变，所以小气道闭合的早，所以闭合容积增加。
         现在老慢支、肺气肿已经不再大纲了，只考COPD。❤️COPD早期变化：闭合容积增加，静态肺顺应性↑、动态肺顺应性↓。
静态肺顺应性只取决于肺的弹性
动态肺顺应性取决于气道阻力和肺的弹性
#+END_QUOTE
** [[肺气肿]]
:PROPERTIES:
:collapsed: true
:END:
*** 7. 1995N66A 关于阻塞性肺气肿，哪一项描述是正确的
- [ ] A.经积极治疗可以痊愈
- [x] B.其病理改变是不可逆的
- [ ] C.仅限于肺泡弹性减退与膨胀
- [ ] D.α₁-抗胰蛋白酶增加易发生肺气肿
- [ ] E.肺功能改变主要是肺活量减少

#+BEGIN_QUOTE
阻塞性肺气肿主要是由于气道阻塞导致肺部终末细支气管远端气腔出现异常持久的扩张，并伴有肺泡壁和细支气管的破坏，病变并非仅限于肺泡弹性减退与膨胀（P22）（C错），肺组织的变化多呈进行性发展，不可逆（P22）（B对）。积极治疗可以减慢或者阻止肺组织的进一步破坏，但已损坏的肺组织无法恢复，疾病无法痊愈（A错）。蛋白酶增多或抗蛋白酶不足可导致组织结构破坏，产生肺气肿，α₁-抗胰蛋白酶增加不会发生肺气肿（D错）。阻塞性肺气肿的肺功能改变主要是流速降低、残气量增加，限制性通气障碍的肺功能改变主要是肺活量减少（E错）。
#+END_QUOTE
*** 8. 1996N61A 目前认为关于肺气肿发生的机理，下列哪项不正确
- [x] A.弹性酶活性受抑制
{{embed ((6214a5f1-4a22-45d2-b5e7-2398d57591c5))}} 
- [ ] B.α₁-抗胰蛋白酶缺乏
- [ ] C.血清α₁-抗胰蛋白酶活力低下
- [ ] D.中性粒细胞和巨噬细胞释放蛋白分解酶增多
- [ ] E.肺泡壁毛细血管受压，肺组织营养障碍
[[混淆]]:肺泡壁的小动脉
*** [#A] 9. 2004N142X 下列哪些因素与肺气肿的发病机制有关
- [x] A.肺部慢性炎症，损害肺组织和肺泡壁
- [x] B.支气管慢性炎症，使管腔狭窄，形成不完全阻塞
- [ ] C.肺小动脉受压，血液供应减少，肺组织营养障碍
[[Comments]] :应该是肺毛细血管受压血液供应减少肺组织营养障碍
- [ ] D.慢性炎症破坏肺泡间质，使其失去支架作用，促使肺泡膨胀
[[Comments]]:肺气肿不伴有肺间质的纤维化其破坏的不是肺间质而是肺泡壁并使其异常持久的扩张
*** [#A] 13. 1999N57A 慢性支气管炎并发肺气肿早期病理生理改变，下列哪项错误
- [ ] A.病变局限于细小气道
- [x] B.[[最大通气量]]降低
- [ ] C.闭合容积增大
- [ ] D.动态肺顺应性降低
- [ ] E.静态肺顺应性增加 
#+BEGIN_QUOTE
慢支合并肺气肿呼吸功能检查早期可无异常表现，病变局限于细小气道（A对），若有小气道阻塞时，最大呼气流量-容积曲线显示流量明显减低（该指标比第一秒用力呼气量更敏感）闭合容量可增加（C对）、动态肺顺应性降低（D对）；然后随着病情发展，肺组织弹性日益减退，肺泡持续扩大，回缩障碍，则残气量及残气量占肺总量的百分比增加，可有最大通气量降低，可见最大通气量降低为晚期表现，并非早期病理生理改变（B错，为本题正确答案）。顺应性是指弹性体在外力作用下发生形变的难易程度。它包括静态顺应性和动态顺应性两者，前者反映了肺组织的弹性，肺气肿时，肺组织的弹性阻力降低，在外力作用下更容易发生形变，故静态顺应性应当增加（E对）；动态顺应性反应的是肺呼吸运动的容易程度，慢性支气管炎并发肺气肿时肺呼吸运动困难，故动态顺应性下降。
#+END_QUOTE 
#+BEGIN_QUOTE
闭合容积说的从下级小气道关闭开始后继续呼出的气量，你体会COPD的患者或者小气道病变的人的呼气性呼吸困难是因为小气道提前关闭了，既然提前关闭，那么此时就开始计算闭合容积，提前计算了那么肯定会增加吧。（不要想着小气道病变了还怎么继续往外呼气，要知道早期并不是所有的小气道都病变了，还有正常的，但是因为病变的小气道存在使计算闭合容积提前。体会起来就像肾糖阈一样，一颗老鼠屎坏了一锅粥。）
#+END_QUOTE
*** 15. 1997N67A 慢性支气管炎并发肺气肿时，最早出现的病理生理改变是
- [x] A.时间肺活量降低
- [ ] B.生理无效腔气量增大
- [ ] C.通气/血流比例失调
- [ ] D.残气占肺总量百分比增加
- [ ] E.低氧血症 
#+BEGIN_QUOTE
^^慢性支气管炎并发肺气肿主要导致肺的通气功能障碍，早期病变累及小气道，表现为小气道炎症、小气道纤维组织形成、小气道黏液栓等，使小气道阻力明显升高，肺功能检查以流速降低为主要改变，时间肺活量降低^^(A对）。以后病情发展，肺组织弹性日益减退，肺泡持续扩大，回缩障碍，则残气量及残气量占肺总量的百分比增加（D错）。肺气肿加重导致肺泡周围肺毛细血管受挤压大量减少，肺泡间血流减少，此时肺泡虽有通气，但肺泡壁无血流灌流，导致无效腔样气量增大（B错）；也有部分肺区虽有血流灌流，但通气不良，导致功能性分流增加，从而产生通气血流比例失调（C错）。发展到最后会引起缺氧和二氧化碳潴留，发生不同程度的低氧血症（E错）和高碳酸血症。
#+END_QUOTE
[[Comments]]:为什么COPD的最早病理生理改变是小气道的缩窄?因为其由慢支为基础发展为肺气肿再发展为COPD,气腔的扩张依赖于小气道狭窄
** COPD
:PROPERTIES:
:collapsed: true
:END:
*** [#A] 17. 2016N142B COPD患者出现低氧血症最主要的机制是
- [x] A.肺泡通气量下降
{{embed ((6214b57b-8de5-4955-8492-e699bf67dd28))}} 
- [ ] B.弥散障碍
- [ ] C.通气/血流比例失调
- [ ] D.肺内分流

#+BEGIN_QUOTE
慢阻肺的特征性病理生理变化是持续气流受限导致肺通气功能障碍，肺泡通气量下降（A对）。其为COPD患者出现低氧血症最主要的机制，随着病情发展，会出现通气/血流比例失调（肺内分流为其类型之一）和弥散障碍（BCD错）。弥散障碍为间质性肺疾病患者出现低氧血症的主要机制。
#+END_QUOTE
*** [#A] 18. 1999N56A 阻塞性肺气肿支气管炎型的临床表现，下列哪项是正确的
- [x] A.发病年龄较轻 
#+BEGIN_QUOTE
老书有，COPD分红喘(气肿型)与紫肿(支气管型)两型，前者以老年人，消瘦，肺气肿为主要特征。后者以年轻人，胖子，支气管炎，咳嗽重喘息轻为主要特征。后者缺氧较前者严重，故发紫绀。肺心病，故水肿。
#+END_QUOTE 
- [ ] B.多无紫绀
- [ ] C.喘息明显，多呈持续性
[[Comments]] :咳嗽重喘息轻
- [ ] D.X线胸片呈肺纹理减少 
#+BEGIN_QUOTE
肺气肿无明显纤维化  这个是个很重要的考点
#+END_QUOTE 
- [ ] E.静息时PaO₂轻度降低
[[Comments]]:支气管型比气肿型的缺氧严重
*** 19. 2010N58A 下列疾病中，叩诊检查可发现Kronig峡增宽的是
- [ ] A.肺炎
- [x] B.肺气肿 
#+BEGIN_QUOTE
[[Kronig峡]]是指肺尖的宽度，正常值为4～6cm。当肺内含气量增大时，Kronig峡增宽，反之变狭窄。肺气肿（B对）、COPD患者肺内含气量增大，故Kronig峡增宽。肺结核（C错）出现肺尖浸润时，可使Kronig峡变狭窄；[[肺炎]]、[[胸腔积液]]均不会使Kronig峡增宽（AD错）。
#+END_QUOTE 
- [ ] C.肺结核
- [ ] D.胸腔积液
*** 20. 1989N13A 对阻塞性肺气肿的诊断，最有价值的是
- [ ] A.PaO₂＜正常
- [ ] B.潮气量低于正常
- [ ] C.肺活量降低
- [x] D.残气量/肺总量＞40% 
#+BEGIN_QUOTE
阻塞性肺气肿的病理变化为肺部[[终末细支气管远端气腔]]出现异常持久的扩张，伴有肺泡壁和细支气管的破坏（P22），肺组织弹性日益减退，肺泡持续扩大，回缩障碍，则残气量及残气量占肺总量的百分比增加，所以临床上把^^残气量/肺总量>40%（D对）作为诊断肺气肿最有价值的指标^^。潮气量低于正常（B错）及肺活量降低（C错）也可见于[[支扩]]、[[支气管哮喘]]等多种疾病，对诊断阻塞性肺气肿的特异性不高，故其不是诊断阻塞性肺气肿最有价值的指标。PaO₂<正常（A错）、PaCO₂>正常（E错）可见于COPD、支气管哮喘及肺心病等多种疾病，对诊断阻塞性肺气肿的特异性不高，故其不是诊断阻塞性肺气肿最有价值的指标。
#+END_QUOTE 
- [ ] E.PaCO₂＞正常
*** [#A] 23. 1997N128C 慢性阻塞性肺气肿
- [ ] A.弥散障碍
{{embed ((6214b57f-7f29-4bd6-b422-b4efcf78d729))}}
- [ ] B.第一秒用力呼气率减低
- [x] C.两者均有
- [ ] D.两者均无
*** 29. 2006N61A 用于鉴别COPD和支气管哮喘的试验是
- [ ] A.过敏原试验
- [ ] B.支气管激发试验
- [ ] C.低氧激发试验
- [ ] D.运动试验
- [x] E.支气管舒张试验 
#+BEGIN_QUOTE
{{embed ((6215fa75-c10a-4403-875d-39ed203cee34))}} 
#+END_QUOTE
[[Comments]]:为什么支气管舒张试验的标准是增加12%因为,正常人是83%而诊断 [[COPD]]为70%
*** 30. 1992N138X 吸氧浓度至40%，可纠正以下哪种情况引起的低氧血症
- [ ] A.房间隔缺损引起的肺动脉高压 
#+BEGIN_QUOTE
严重肺气肿（B对）、慢性肺心病急性加重期（C对）都存在肺通气下降的情况，肺通气下降导致动脉血氧分压下降，提高氧浓度可使患者低氧血症有所纠正或好转。房间隔缺损（P272）（A错）后，由于左房压力高于右房，血液由左向右分流，肺血流量增加，持续肺血流量增加引起肺淤血，导致肺动脉高压，右心系统的压力随之持续增高甚至超过左心系统，此时逆转为右向左的分流，分流的静脉血不经过肺循环直接进入体循环而引起低氧血症，故吸氧浓度至40%不能纠正低氧血症。ARDS（P130）（D错）可因休克、创伤等诱因使肺毛细血管内皮、肺泡细胞损伤，致使肺微血管血栓形成，肺泡表面活性物质减少，肺泡不张，致使通气与血流比例失调，肺内分流增加，导致严重的低氧血症，而提高吸氧浓度并不能改善通气与血流比例和肺内分流，故吸氧浓度至40%不能纠正低氧血症。
#+END_QUOTE 
- [x] B.严重的肺气肿
- [x] C.慢性肺心病急性加重期
- [ ] D.ARDS
*** [#A] 31. 2000N152X 关于肺源性心脏病呼吸衰竭的氧疗，下列哪些正确
- [x] A.提高肺泡内PaO₂，增加O₂弥散能力
- [x] B.提高动脉血氧饱和度，增加可利用氧
- [ ] C.增加肺泡通气量，促进CO₂排出 
#+BEGIN_QUOTE
氧疗的原则是在保证氧分压迅速提高到60mmHg或脉搏容积血氧饱和度达到90%以上的前提下，尽量降低吸氧浓度。氧疗可提高肺泡内氧分压，加大肺泡和毛细血管之间的氧分压差，增加O₂的弥散能力（A对），从而提高动脉血氧饱和度，增加可利用氧，提高患者的活动耐力和延长生存时间。（B对）。由于缺氧会导致肺血管收缩，肺动脉压力增高，故氧疗还可通过降低肺循环阻力和肺动脉压，降低后负荷，增加心肌收缩力（D对）。氧疗只能提高氧分压及血氧饱和度，但不能增加肺泡通气量及促进CO₂的排出（C错）。
#+END_QUOTE 
#+BEGIN_QUOTE
氧疗:病人主动吸氧，通气量由自身的肺功能决定。
机械通气:病人被动吸氧，通气量可增加可调节。
#+END_QUOTE 
- [x] D.降低肺循环阻力和肺动脉压，增强心肌收缩力
*** [#B] 32. 2013N96A 男性，60岁。反复咳喘40余年，活动后气短10余年，间断双下肢水肿5年，加重1天入院，吸烟史40年。查体：嗜睡，口唇发绀，颈静脉怒张，桶状胸，双肺可闻及干湿啰音，心率110次/分，心率整，肝肋下3.0cm，双下肢水肿。血气分析示pH7.26，PaO₂45mmHg，PaCO₂75mmHg。下列治疗措施错误的是
- [ ] A.积极控制感染
- [ ] B.应用无创呼吸机改善通气
- [x] C.应用5%碳酸氢钠纠正酸中毒 
#+BEGIN_QUOTE
患者老年男性，长期吸烟史，反复咳喘40余年，桶状胸，故有COPD的基础疾病。现该患者双下肢水肿，颈静脉怒张，肝肋下3.0cm，应考虑存在右心衰；嗜睡，口唇发绀，血气分析示pH7.26，PaO₂45mmHg，PaCO₂75mmHg，存在Ⅱ型呼吸衰竭（PaO₂<60mmHg，PaCO₂>50mmHg），合并呼吸性酸中毒。该患者现处于COPD急性加重期。急性加重期的治疗措施主要为积极控制感染（A对）、应用无创呼吸机改善通气（B对）、应用支气管舒张剂（D对）。该患者存在酸中毒是通气障碍所致，所以应该改善肺部通气来治疗酸中毒（C错，为本题正确答案），补碱一般应用于重症代谢性酸中毒且不易控制量，容易导致碱中毒，使氧解离曲线左移，减少血红蛋白氧的释放，加重组织缺氧。
#+END_QUOTE 
- [ ] D.应用支气管舒张剂
** [[支气管哮喘
*** [#A] 3. 1994N65A 支气管哮喘的发病与下列哪种物质无关 
- [ ] A.环化一磷酸腺苷（cAMP）
- [ ] B.环化一磷酸鸟苷（cGMP） 
#+BEGIN_QUOTE
哮喘发作与cAMP/cGMP比值有关（AB对），比值增大时，支气管扩张，比值减小时，支气管痉挛，发生哮喘。慢反应物质（SRS-A）（D对）是发生速发型过敏反应时，肺组织释放的化学介质，可使气管和支气管平滑肌收缩，引发哮喘。[[前列环素]]（PGI₂）（E对）与血栓烷A₂（TXA₂）之间的失衡参与了哮喘的发病。腺苷脱氨酶ADA（C错，为本题正确答案）主要用于肝脏疾病、结核、SLE等疾病的诊断，与哮喘发病无关，故应排除。
#+END_QUOTE 
- [x] C.腺苷脱氨酶（ADA
{{embed ((621605c0-6e2b-4dbb-8925-4c5bd1ee3e87))}}
- [ ] D.慢反应物质（SRS-A）
- [ ] E.[[前列环素]]
[[Comments]]:这个选项我忘了什么是[[前列环素]]
*** [#B] 4. 2015N58A 下列疾病中，可出现抑制性呼吸现象的病因是
- [x] A.急性胸膜炎 
#+BEGIN_QUOTE
九版诊断学P128）&“抑制性呼吸 此为胸部发生剧烈疼痛所致的吸气相突然中断，呼吸运动短暂地突然受到抑制，患者表情痛苦，呼吸较正常浅而快。常见于急性胸膜炎（A对）、胸膜恶性肿瘤、肋骨骨折及胸部严重外伤等”。
#+END_QUOTE 
- [ ] B.[[糖尿病酮症]]
[[Comments]] :表现为[[深大呼吸]],怎么记既然是酮症酸中毒代谢性酸中毒就需要通过呼吸代偿,只能加深加大呼吸以排除更多CO₂
- [ ] C.充血性心力衰竭
[[Comments]] :表现为[[潮式呼吸]]怎么记,充血→红色→月圆→潮汐
- [ ] D.支气管哮喘
[[Anchor]]:[[充血性心力衰竭]]的定义
*** [#B] 5. 1993N151X 支气管哮喘的患者出现下面哪些情况提示病情严重有合并症发生
- [ ] A.PaCO₂=4.6KPa（35mmHg），PaO₂=8.7KPa（65mmHg）
- [x] B.[[奇脉]] 
#+BEGIN_QUOTE
来看这儿 讲几个主要区别点吧
轻度 没特殊 散在哮鸣音 血气分析正常
中度 开始有三凹征和奇脉 满肺哮鸣音
重度 端坐呼吸 心率＞120 呼吸＞30 PaCO2＞45 PaO2＜60
危重 有肺性脑病(嗜睡意识模糊) [[胸腹矛盾运动]] 沉默肺 奇脉可以消失
#+END_QUOTE
- [ ] C.两肺哮鸣音
- [x] D.呼吸困难加重，而哮鸣音减轻或消失 {{embed ((6216192a-19aa-4c5c-9adb-88683869b1a1))}}
*** [#B] 7. 2001N54A 关于支气管哮喘发作的临床表现，下列哪项不正确
- [ ] A.强迫端坐位
- [ ] B.出现严重呼气性呼吸困难
- [x] C.呼吸动度增大、呈吸气位 
#+BEGIN_QUOTE

1、[[吸气位]]：吸入空气之后由于呼气困难导致难以快速呼出，胸廓呈吸气后的饱满扩装张状态


3、重症哮喘有三凹征。重症哮喘→气道痉挛→呼气困难→呼气延长 
但是缺氧导致呼吸频率加快→吸气缩短→吸气肌过度用力以获得足够的潮气量→三凹征

4、呼气性呼气困难→气体积在肺出不去→气多了语音共振就会减弱 
大叶性肺炎→实变→语音震颤增强
   震颤减弱:口诀，气水堵厚弱！！！

5、呼吸活动度是呼吸时胸廓的活动度。气体只进不出，胸廓内气体越来越多，所以活动度越来越小
呼吸动度变小，呈吸气位，可有三凹征
6、强迫端坐体位。此时膈肌下降 肺通气功能增加 
#+END_QUOTE 
- [ ] D.语音震颤减弱
- [ ] E.大汗淋漓伴紫绀
*** [#B] 13. 1997N127C 支气管哮喘
- [ ] A.弥散障碍
- [x] B.第一秒用力呼气率减低
[[Comments]] :哮喘是只有通气功能障碍而COPD因为是晚期疾病伴有肺气肿的病理所以既有通气功能障碍又有换气功能障碍
- [ ] C.两者均有
- [ ] D.两者均无
*** [#B] 16. 2018N43A 支气管哮喘有别于心源性哮喘的临床表现是
- [ ] A.咳嗽、咳痰
- [ ] B.多于夜间发作
- [x] C.呼气性呼吸困难，可自行缓解 
#+BEGIN_QUOTE
支气管哮喘由多种刺激因素刺激炎症细胞引起，多见于青少年有过敏史者。心源性哮喘系由左心衰竭引起的呼吸困难（夜间阵发性呼吸困难），多见于器质性心脏病患者（为避免混淆，目前已经不再使用“心源性哮喘”一词）。^^[[支气管哮喘]]与[[心源性哮喘]]都可出现咳嗽（A错）、常于夜间发作（B错）及双肺哮鸣音（D错）等临床表现，但支气管哮喘病人咳嗽不咳痰^^，心源性哮喘病人则常咳粉红色泡沫痰。支气管哮喘发作时典型症状为伴有哮鸣音的呼气性呼吸困难，可经平喘药物治疗后缓解或自行缓解，心源性哮喘（夜间阵发性呼吸困难）系患者入睡后突然因憋气而惊醒，被迫取坐位，重者可有哮鸣音，多于端坐休息后缓解，故支气管哮喘有别于心源性哮喘的临床表现是^^呼气性呼吸困难，可自行缓解^^（C对）。二者临床表现相似，测定血浆BNP水平对鉴别心源性和支气管性哮喘有较大的参考价值。
#+END_QUOTE 
- [ ] D.双肺可闻及哮鸣音
*** [#B] 18. 2008N64A 患者，男，45岁。吸烟20年，有喘息、咳嗽症状，普通胸片未发现明显异常，支气管舒张试验阳性。最可能的诊断是
:PROPERTIES:
:id: 62173f74-dead-4404-aeb9-3ee6d54d4aa7
:END:
- [ ] A.心源性哮喘
- [x] B.支气管哮喘
{{embed ((62161751-935c-4a8e-a811-229d228b3369))}}
- [ ] C.嗜酸细胞性肺炎
- [ ] D.COPD
*** [#A] 19. 1988N9A 支气管[[哮喘持续状态]]很重要的治疗方法是
- [ ] A.应用抗生素
- [ ] B.应用祛痰药物
- [x] C.补液纠正失水 
#+BEGIN_QUOTE
大家可能有误区，支气管持续状态是指在一定相对长的时间经正确治疗后哮喘不能有效(缓解)，而不是指哮喘的长期治疗，此时常规药物已经用了，比如ABDE，又因为患者因快速呼吸啊，血压下降啊等等容易缺水，所以应当注重补水。比如2011年63
题说的就是哮喘持续状态。
#+END_QUOTE 
[[Comments]] :一补:补液,二纠:酸中毒,电解质紊乱,三碱:补碱,抗胆碱,茶碱.氧疗+两素:糖皮质激素+抗生素
- [ ] D.应用支气管扩张药物
- [ ] E.应用肾上腺皮质激素
*** [#A] 21. 1992N115C 抗胆碱类药物
:PROPERTIES:
:id: 621741eb-34e0-4964-b130-48fc086e199b
:END:
- [x] A.抑制肥大细胞释放介质 
#+BEGIN_QUOTE
乙酰胆碱兴奋M胆碱受体，可增加[[鸟苷酸环化酶]]活性，促进三磷酸鸟苷（GTP）转化为[[环磷酸鸟苷]]（cGMP），可增加生物活性物质释放，使支气管收缩，发生哮喘。使用抗胆碱类药物，可抑制乙酰胆碱，使生物活性物质释放减少（A对）。抗胆碱药分为短效抗胆碱药（SAMA）和长效抗胆碱药（LAMA），SAMA主要用于哮喘急性发作的治疗，LAMA主要用于哮喘合并慢阻肺以及慢阻肺患者的长期治疗，不用于哮喘发作的预防（B错）。
#+END_QUOTE 
- [ ] B.预防哮喘发作
- [ ] C.两者皆有
- [ ] D.两者皆无
*** [#B] 22. 1992N116C [[色苷酸二钠]]
- [ ] A.抑制[[肥大细胞]]释放介质
- [ ] B.预防哮喘发作
- [x] C.两者皆有 
#+BEGIN_QUOTE
色苷酸钠具有稳定肥大细胞膜作用，可以抑制肥大细胞释放介质（A对）。此药为预防哮喘发作的药物（八版药理学P297）（B对）。本题AB均对，正确答案为C。
#+END_QUOTE 
- [ ] D.两者皆无
*** [#A] 23. 1994N62A 氨茶碱治疗支气管哮喘的作用机理是
- [ ] A.阻断迷走神经
- [x] B.抑制[[磷酸二酯酶]] {{embed ((62172739-cd53-4a71-abc8-3e0bc90c040c))}}
- [ ] C.激活腺苷酸环化酶
- [ ] D.保护肥大细胞溶酶体膜
- [ ] E.使封闭抗体增加
*** [#A] 25. 1995N134C β₂受体兴奋剂
:PROPERTIES:
:id: 6217438a-e397-4e40-9bb2-75cfe38565ca
:END:
- [ ] A.抗炎作用
- [ ] B.抑制肥大细胞释放介质
- [x] C.两者均有 
#+BEGIN_QUOTE
β₂受体激动剂治疗哮喘主要是两方面的机制：①激动气道平滑肌的β₂肾上腺素受体，舒张气道平滑肌，使支气管扩张；②激动肥大细胞等细胞膜表面的β₂肾上腺素受体，减少肥大细胞和嗜碱粒细胞脱颗粒和介质的释放，从而起到舒张支气管、缓解哮喘症状的作用（二版八年制内科学P57）。所以β₂受体激动剂具有抗炎作用和抑制肥大细胞释放介质的作用。本题AB均对，正确答案为C。
#+END_QUOTE 
- [ ] D.两者均无
*** [#A] 26. 1997N66A 冠心病患者伴发支气管哮喘时应慎用哪种药物
- [ ] A.氨茶碱
- [ ] B.肾上腺皮质激素
- [ ] C.酮替芬
- [x] D.肾上腺素 
#+BEGIN_QUOTE
冠状动脉的[[窃血现象]]  “窃血现象”是当冠状动脉一个分支发生狭窄，为满足机体生命活动需要，其远端的阻力血管发生代偿性扩张（动用储备，自动调节）以保证正常血流量。此时，若给予强扩血管药物或运动负荷增加等，这种刺激将使其它正常的冠状动脉分支扩张，血流量增加，而发生粥样硬化的冠状动脉分支，其狭窄远端的阻力血管早已最大扩张，因此，缺血区的血流量不再增加，这样，非缺血区的血管阻力低于缺血区，血液将从缺血区通过侧支循环流入非缺血区，狭窄远端心肌的血流仿佛被正常区所“窃去”，故称“窃血现象”。
#+END_QUOTE 
#+BEGIN_QUOTE
支气管哮喘禁用吗啡，抑制呼吸。

心源性哮喘禁用肾上腺素，增加心肌耗氧。
无法鉴别是先用氨茶碱。
陈年老梗，大家记清。
#+END_QUOTE 
- [ ] E.色苷酸钠
*** [#A] 27. 1998N57A 关于用肾上腺糖皮质激素治疗迟发性哮喘的机制，下列哪项不正确
:PROPERTIES:
:id: 62173777-1a6e-48de-a4b4-d0e599bded0d
:END:
- [ ] A.抑制磷酸脂酶A₂
- [ ] B.抑制前列腺素、血小板活化因子合成
- [ ] C.抑制组织胺脱羧酶，减少组织胺形成
- [x] D.抑制小血管收缩，减少渗出和炎症细胞浸润 
#+BEGIN_QUOTE
糖皮质激素是治疗哮喘最有效的药物。其主要作用机制为：①抑制炎症细胞的迁移和活化。②抑制细胞因子（如血小板活化因子）（B对）的生成。③抑制炎症介质的生成和释放：抑制磷脂酶A₂，从而影响花生四烯酸、前列腺素的生成（AB对）；抑制组织胺脱羧酶，减少组织胺形成（C对）。④^^促使小血管收缩，减少渗出和炎症细胞的浸润（^^D错，为本题正确答案）（八版药理学P335）；^^⑤糖皮质激素可以增强平滑肌细胞β₂受体的反应性，但不能增加β受体数量（E错），本题答案应为DE，但参考答案为D。^^
#+END_QUOTE 
- [x] E.增加β受体数量
*** [#A] 28. 1999N58A 常用控制支气管哮喘急性发作药物的作用，下列哪项不正确
:PROPERTIES:
:id: 6217465d-4916-4d2d-b31d-439e1916c1c8
:END:
- [ ] A.β₂受体兴奋剂可提高细胞内cAMP的浓度
- [ ] B.茶碱主要是通过抑制磷酸二酯酶、减少cAMP的水解起作用
- [ ] C.抗胆碱能类药可减少cGMP的浓度
- [x] D.色苷酸二钠可稳定肥大细胞膜
- [x] E.酮替芬可抑制组胺和慢反应物质释放

#+BEGIN_QUOTE
支气管哮喘是由于支气管平滑肌过度收缩引起的，而支气管平滑肌受多种生物活性物质影响，所以当支气管哮喘发作时，可通过影响这些物质来缓解患者症状。缓解哮喘急性发作的药物有：短效β₂受体激动剂、短效吸入型抗胆碱能药物、短效茶碱、全身用糖皮质激素^^。β₂肾上腺素受体激动剂主要通过激动呼吸道的β₂受体，激活[[腺苷酸环化酶]]，使细胞内的cAMP含量增加（A对^^），游离钙离子减少，从而松弛支气管平滑肌，是控制哮喘急性发作的首选药物（七版内科学P75）；^^茶碱可抑制磷酸二酯酶，减少cAMP的水解（B对^^），提高支气管平滑肌细胞内的cAMP浓度，拮抗腺苷受体，增强呼吸肌的力量以及增强气道纤毛清除功能等，从而起到舒张支气管和气道抗炎作用；抗胆碱药可选择性得阻断M受体，抑制细胞内cGMP的转化，减少cGMP的浓度，使生物活性物质释放减少，从而松弛支气管平滑肌（C对）；^^[[色苷酸钠]]可以稳定肥大细胞膜，抑制肥大细胞释放介质，但属于控制性药物（D错^^）；[[酮替芬]]可抑制组胺和慢反应物质释放，主要用于防治轻、中度哮喘（八版药理学P297），亦属于控制性药物（E错）。本题DE错，为正确答案，但参考答案为B。
#+END_QUOTE
*** [#A] 29. 2005N60A β₂-受体兴奋剂在应用两周后，常引起β₂-受体下调，使支气管舒张作用减弱。下列哪种药物可促进β₂-受体功能的恢复
- [ ] A.氨茶碱
- [x] B.酮替酚 
#+BEGIN_QUOTE
目前，研究已证实[[酮替芬可]]逆转长期应用β2-受体兴奋剂引起的β2-受体下调，增加气道内β2-受体的密度，增强β2-受体兴奋剂的疗效（B对）。氨茶碱（A错）等茶碱类药物可以通过抑制磷酸二酯酶来舒张支气管；溴化己胺醇（C错）为β2-受体激动剂；白三烯受体拮抗剂（D错）通过对气道平滑肌和其他细胞表面白三烯受体的拮抗，抑制肥大细胞和嗜酸性粒细胞的致喘和致炎作用，并可产生轻度支气管舒张；异丙托品（E错）等抗胆碱类药物，可抑制乙酰胆碱，舒张支气管平滑肌；但均无促进β2-受体功能恢复的作用。
#+END_QUOTE 

#+BEGIN_QUOTE
使受体下调恢复：酮替芬
不产生受体下调：福莫特罗
#+END_QUOTE 
- [ ] C.溴化己胺醇
- [ ] D.白三烯受体拮抗剂
- [ ] E.异丙托品
*** [#A] 30. 2005N61A 中度持续发作的支气管哮喘患者应用糖皮质激素的原则是
:PROPERTIES:
:id: 621747e6-fbfe-468f-9f7d-2723219d0a41
:END:
- [ ] A.长期口服5～10mg强的松
- [ ] B.长期吸入二丙酸倍氯米松＜400μg/d
- [x] C.长期吸入二丙酸倍氯米松200～1000μg/d 
#+BEGIN_QUOTE
糖皮质激素，是目前控制哮喘最有效的药物。激素通过作用于气道炎症形成过程中的诸多环节，有效抑制气道炎症，可以分为吸入、口服和静脉用药。吸入型糖皮质激素局部作用强而全身副作用较小，^^所以目前临床上已将其作为长期治疗哮喘的首选方案^^，常用的药物有倍氯米松（BDP）、布地奈德、氟替卡松、环索奈德、莫米松等。根据哮喘病情，吸入剂量（BDP或等效量其他皮质激素）在轻度持续者一般200～500μg/d（B错），^^中度持续者^^一般500～1000μg/d，重度持续者一般＞1000μg/d（不宜超过2000μg/d）。长期口服5～10mg泼尼松（A错）多用于吸入激素无效或需要短期加强治疗的患者，但长期口服会有明显的副作用，故并不提倡。一次性大剂量激素冲击治疗（E错）多用于治疗免疫性疾病，而支气管哮喘患者应用激素治疗时，多采用小剂量。综上，中度持续发作的支气管哮喘患者的治疗为：在短期应用短效支气管舒张剂的基础上，长期吸入二丙酸倍氯米松500～l000μg/d（C对），因为长期使用支气管扩张剂，容易造成支气管平滑肌对其敏感性下降，治疗效果降低（D错）。
#+END_QUOTE 
- [ ] D.间断吸入激素加长期应用支气管扩张剂
- [ ] E.一次性大剂量激素冲击治疗
*** [#A] 37. 2011N63A 患者，男，30岁。哮喘发作已2天，自服氨茶碱、吸入丙酸倍氯松气雾剂无效而来诊，体检：患者神志恍惚，紫绀，有奇脉，两肺满布哮鸣音，HR120次/分，对该患者的紧急处理方法是
- [ ] A.静脉推注氨茶碱并检测血药浓度
- [ ] B.静脉注射地塞米松和β₂受体激动剂
- [x] C.大量补液、气管插管和机械通气 {{embed ((62172898-a3b3-47a6-b175-a45291f60d19))}}
- [ ] D.静脉滴注抗生素和支气管舒张剂
*** [#A] 40. 2016N65A 支气管哮喘急性发作首选治疗方法是
:PROPERTIES:
:id: 621749de-911f-4a36-8855-0812502b137c
:END:
- [ ] A.静脉注射氨茶碱
- [ ] B.雾化吸入异丙托溴胺
- [x] C.雾化吸入沙丁胺醇 {{embed ((621724cd-ae73-4e42-9955-4a553a1204e2))}}
- [ ] D.静脉使用糖皮质激素
*** [#A] 41. 2012N96A 男性，35岁。支气管哮喘30年，再发咳嗽伴喘息3天，吸入沙丁胺醇症状稍改善，1天来喘息加重。查体：R32次/分，端坐呼吸，大汗，语不成句，口唇发绀，双肺呼吸音低，可闻及散在哮鸣音，未闻及湿啰音，心率126次/分，有奇脉。应首选的辅助检查是
- [ ] A.胸部X线
- [ ] B.肺功能
- [x] C.动脉血气分析 
#+BEGIN_QUOTE
该患者查体R32次/分，端坐呼吸，大汗，语不成句，口唇发绀，双肺呼吸音低，可闻及散在哮鸣音，未闻及湿啰音，心率126次/分，有奇脉，诊断为支气管哮喘重度急性发作期。支气管哮喘是气道的一种慢性变态反应性炎症性疾病，这种慢性炎症导致可逆性气流受限。肺功能检查中1秒率（FEV₁/FVC%）<70%或FEV₁低于正常预计值的80%是判断气流受限的最重要指标，所以支气管哮喘诊断一般首选肺功能检查。但该患者处于支气管哮喘重度急性发作期，无法配合完成肺功能检查（B错），所以应首选的辅助检查为动脉血气分析，以判断酸碱、离子平衡和PaO₂、PaCO₂状态来帮助确定疾病的严重程度（C对）。胸部X线和心电图一般不作为首选（AD错）。
#+END_QUOTE 
- [ ] D.心电图
*
*