#+title: 外科学/外科学总论/疼痛/教材/疼痛治疗
#+deck: 外科学::外科学总论::疼痛::教材::疼痛治疗

* 疼痛/定义
** <span class="tested">疼痛(pain)是人类大脑对机体组织损伤或可能导致组织损伤的刺激所产生的一种不愉快的主观感觉。</span>丧失意识(如昏迷)的病人对组织损伤或者伤害性刺激的反应称为伤害感受(nociception)。人体对疼痛的感受在个体间和(或)不同状态下存在差异。不论是疼痛还是伤害感受均可能诱发机体产生代谢、内分泌、呼吸、循环、应激、神经、精神等功能或状态的改变。疼痛已成为影响人类健康的重要医学问题。
* 疼痛的临床分类 
:PROPERTIES:
:id: 624d9d46-8040-4d44-a34c-c771786aff51
:END:
** 1.按疼痛程度分类  <span class="untestedHL">①轻微疼痛;②中度疼痛;③剧烈疼痛。</span>
** 2.按起病缓急分类  <span class="untestedHL">①急性疼痛(acute pain)</span>:如发生于创伤、手术、急性炎症、急性脏器缺血,如心肌梗死等,急性脏器梗阻、牵胀,如肠梗阻、胆道梗阻、输尿管梗阻等。② <span class="untestedHL">慢性疼痛(chronic pain)</span>:慢性疼痛是一种疾病,如慢性腰腿痛、癌症痛等。神经病理性疼痛(neuropathic pain)是指发生于周围神经和中枢神经任何部位的神经病变和损害所致的疼痛,如带状疱疹后神经痛、糖尿病性神经病变、残端痛、幻肢痛等。
** 3.按疼痛部位分类 ① <span class="untestedHL">浅表痛</span>:位于体表或黏膜,以角膜和牙髓最敏感。性质多为锐痛,比较局限,定位明确。主要由A8有髓神经纤维传导。 <span class="untestedHL">②深部痛:</span>内脏、关节、韧带、骨膜等部位的疼痛。一般为钝痛,不局限,病人常常难以明确指出疼痛部位。主要由C类无髓神经纤维传导。内脏痛是深部痛的一种,可能伴有牵涉痛。
* 癌痛治疗/WHO推荐的三阶段疗法 
:PROPERTIES:
:id: 624d9e48-7974-40f2-a452-9aaf6a38e887
:END:
** 基本原则:① <span class="untestedHL">根据疼痛程度选择镇痛药物</span>;② <span class="untestedHL">口服给药,一般以口服药为主</span>;③ <span class="untestedHL">按时服药,根据药理特性有规律地按时用药</span>;④ <span class="untestedHL">个体化用药,应根据具体病人和疗效用药。</span>
** 第一阶梯, <span class="untestedHL">轻度疼痛时,选用非阿片类镇痛药,如阿司匹林</span>;也可选用胃肠道反应较轻的布洛芬和对乙酰氨基酚等。
** 第二阶梯,在轻、中度疼痛时,单用 <span class="untestedHL">非阿片类镇痛药不能控制疼痛,应加用弱阿片类药以提高镇痛效果,代表药物为可待因。</span>
** 第三阶梯, <span class="untestedHL">选用强阿片类药,如吗啡。应根据疼痛的强度(如中、重度癌痛者)而不是根据癌症的预后或生命的时限选择用药。常用缓释或控释剂型。</span>
** 在癌痛治疗中,常采取联合用药, <span class="untestedHL">即加用一些辅助药以减少主药的用量和副作用。常用辅助药物包括:①弱安定药,如地西泮和艾司唑仑等;②强安定药,如氯丙嗉和氣赈啶醇等;③抗抑郁药,如阿米替林。</span>
* 癌痛治疗/术后镇痛 
:PROPERTIES:
:id: 624d9f5c-3482-401b-8a88-9ee0420a88f9
:END:
** 镇痛药物
*** <span class="untestedHL">术后镇痛最常用的药物有阿片类药,如吗啡和芬太尼等非阿片类药,如曲马多等</span>;硬膜外镇痛时局麻药常选用罗派卡因或布比卡因,如浓度低于0.2%则对运动神经的阻滞很弱,比较安全。
*** <span class="untestedHL">解热镇痛药效果差,故少用</span>
** 镇痛方法
*** 以硬膜外镇痛和病人自控镇痛法为好
*** (一)硬膜外镇痛 通 <span class="untestedHL">过留置的硬膜外导管包括硬膜外单次和持续给药。常选用吗啡,吗啡可透过硬膜外间隙进入蛛网膜下隙,作用于脊髓后角的阿片受体。</span>成人常用剂量为2~3mg/次,用生理盐水稀释至10ml注入,注药后约30分钟起效;持续6~24小时,平均为12小时。疼痛再度出现时,可重复给药。
不良反应: <span class="untestedHL">常有恶心、呕吐、皮肤瘙痒、尿猪留和呼吸抑制</span>。药液中加入氣喉利多2.5mg,既可增强镇痛,又可减少恶心呕吐的发生。由于注射吗啡可产生延迟性呼吸抑制,故应密切观察,最好控制次剂量在2~3mg,对老年危重病人更应警惕。
*** (二)病人自控镇痛( patient controlled analgesia, PCA) 即在 <span class="untestedHL">病人感到疼痛时,可自行按压PCA装置的给药键,按设定的剂量注入镇痛药,从而达到止痛效果。</span>它弥补了传统镇痛方法存在的镇痛不足和忽视病人个体差异,以及难以维持血药浓度稳定等问题。PCA装置包括:注药泵;自动控制装置,一般用微电脑控制;输注管道和防止反流的单向活瓣等
*