#+title: 外科学/普通外科/胰腺疾病/教材/胰腺炎

* 急性胰腺炎/病因
** <table style="border-collapse:collapse;border-spacing:0" class="tg"><thead><tr><th style="border-color:inherit;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;font-weight:normal;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:middle;word-break:normal">胆道疾病</th><th style="border-color:inherit;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;font-weight:normal;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:middle;word-break:normal">我国最常见病因(占50%),结石阻塞胆总管末端,共同通道受阻所致,称胆源性胰腺炎</th></tr></thead><tbody><tr><td style="border-color:inherit;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:middle;word-break:normal">过量饮酒</td><td style="border-color:inherit;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:middle;word-break:normal">国外最常见的病因(约占60%)</td></tr><tr><td style="border-color:inherit;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:middle;word-break:normal">暴饮暴食</td><td style="border-color:inherit;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:middle;word-break:normal">最常见诱 因。因此急性胰腺炎也称为"节日病"</td></tr><tr><td style="border-color:inherit;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:middle;word-break:normal">代谢性疾病</td><td style="border-color:inherit;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:middle;word-break:normal">高脂血症性胰腺炎(占7%)、高钙血症(甲状旁腺功能亢进所致)</td></tr><tr><td style="border-color:inherit;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:middle;word-break:normal">十二指肠液反流</td><td style="border-color:inherit;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:middle;word-break:normal">当十二指肠内压力增高,十二指肠液可向胰管内反流,导致急性胰腺炎</td></tr><tr><td style="border-color:inherit;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:middle;word-break:normal">医源性因素</td><td style="border-color:inherit;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:middle;word-break:normal">ERCP可导致约2%-10%病人发生胰腺炎,胰管空肠吻合☐狭窄可导致残余胰腺炎</td></tr><tr><td style="border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:middle;word-break:normal">肿瘤</td><td style="border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:middle;word-break:normal">胰腺导管内乳头状黏液肿瘤、胰腺癌可导致胰管梗阻,从而发生急性胰腺炎</td></tr><tr><td style="border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:middle;word-break:normal">某些药物</td><td style="border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:middle;word-break:normal">5-氨基水杨酸.硫唑嘌呤.6-巯嘌呤、阿糖胞苷、呋塞米、噻嗪类利尿剂、雌激素、甲硝唑、 丙戊酸、对乙酰氨基酚、糖皮质激素、磺胺类等可引起急性胰腺炎</td></tr><tr><td style="border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:middle;word-break:normal">创伤</td><td style="border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:middle;word-break:normal">上腹部钝器伤(腹部方向盘伤)、穿通伤、手术创伤(尤其胆胰手术)均可导致胰腺炎</td></tr><tr><td style="border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:middle;word-break:normal">血液循环障碍</td><td style="border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:middle;word-break:normal">低血压、心肺旁路,动脉栓塞,血管炎,均可造成胰腺血液循环障碍而发生急性胰腺炎</td></tr><tr><td style="border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:middle;word-break:normal">其他</td><td style="border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:middle;word-break:normal">感染、妊娠、内分泌、遗传.自身免疫性疾病</td></tr><tr><td style="border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:middle;word-break:normal">病因不明</td><td style="border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:middle;word-break:normal">少数病因不明者,称为特发性急性胰腺炎</td></tr><tr><td style="border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;overflow:hidden;padding:10px 5px;text-align:left;vertical-align:middle;word-break:normal" colspan="2">注意:①急性胰腺炎最常见的病因,在我国为胆石症;在西方国家为过量饮酒。 ②急性胰腺炎最常见的诱因为暴饮暴食。应注意"病因"和"诱因"的区别。 面</td></tr></tbody></table>
** 3.病理
基本病理改变是胰腺呈不同程度的水肿、充血、出血和坏死。
*** （1）急性水肿性腹腺炎 病变较轻，多局限于胰腺体尾部。胰腺肿胀变硬，充血，被膜紧张，胰周可有积液。腹腔内的脂肪组织，特别是大网膜可见散在粟粒状或斑块状黄白色皂化斑（脂肪酸钙）。腹水淡黄色。镜下见间质充血、水肿，并有炎性细胞浸润，有时可发生局限性脂肪坏死。
*** （2）急性出血坏死性腺腺炎 病变以胰腺实质出血、坏死为特征。胰腺肿胀，呈暗紫色，坏死灶呈灰黑色。腹腔内可见皂化班和脂肪坏死灶，腹膜后可出现广泛组织坏死。腹腔内有暗红色血性液体或血性混浊渗液。镜下可见脂肪坏死和腺泡破坏，间质小血管壁也有坏死，呈现片状出血，炎细胞浸润。
** 4.临床表现
*** （1）腹痛是本病的主要症状，常于饱餐后和饮酒后突然发作，为左上腹剧痛，呈持续性，向左肩及左腰背部放射。胆源性胰腺炎的腹痛始发于右上腹，逐渐向左侧转移。
*** （2）腹胀 腹胀与腹痛同时存在。腹膜后炎症越严重，腹胀越明显。腹腔积液时可加重腹胀，病人排便、排气停止。腹腔内压增高可导致腹腔间隔室综合征。
*** （3）恶心、呕吐 早期即可出现，呕吐剧烈且频繁，呕吐物为胃十二指肠液，偶可呈咖啡色。呕吐后腹痛不缓解为急性胰腺炎的特点，
*** （4）腹膜炎体征
**** ①急性水肿性膜腺炎压痛多局限于上腹部，常无明显肌紧张。
**** ②急性出血坏死性胰腺炎腹部压痛明显，并伴肌紧张和反跳痛。腹腔渗液量大者移动性浊音为阳性。肠鸣音减弱或消失。
*** （5）发热 轻症急性胰腺炎可不发热或有轻度发热。重症急性胰腺炎可有持续发热。
*** （6）黄疸若胆道结石嵌顿或肿大胰头压迫胆总管可出现黄疸。
*** （7）休克 重症急性胰腺炎可有休克。早期为低血容量所致，后期继发感染使休克原因复杂化。
*** （8）体征 少数重症病人胰腺的出血可经腹膜后途径渗人皮下，在腰部、季肋部和下腹部皮肤出现大片青紫色療斑，称为Grey-Tumer证；若出现在脐周，称为Cullen征
（9）其他 胃肠出血时，可有呕血和便血。血钙降低时，可有手足抽搐。
** 并发症
*** （1）局部并发症包括急性胰周液体积聚、胰腺假性囊肿、急性坏死物积聚、包裹性坏死、胸腔积液、胃流出道梗阻、消化道痿、腹腔或消化道出血、脾静脉或门静脉血栓形成等。
（2）全身并发症 包括SIRS、脓毒症、多器官功能障碍综合征（MODS）、腹腔间隔室综合征等。
*** 注意：胰液经坏死破损的胰管溢出，在胰腺周围积聚，被纤维组织包裹形成假性囊肿。多在病程4周出现，多位于腹体尾部。初期为液体积聚，无明显囊壁，此后由肉芽或纤维组织构成的囊壁缺乏上皮，故称假性囊肿。最内无细菌生长，但含有胰酶。假性囊肿大小10~5000ml。囊肿大时，可压迫邻近组织引起相应症状，如明显腹胀、肠道梗阻等。一般<5cm的假性囊肿，6周内约有50%可自行吸收。