#+deck:外科学::外科学总论::无菌术::教材::手术人员和病人手术区域的准备

* 手术人员的术前准备 
:PROPERTIES:
:id: 624a553c-33e7-4ea5-a779-18faf027394d
:END:
** 一般准备
*** 手术人员进入手术室后，先要换穿手术室准备的清洁鞋和衣裤，戴好帽子和口罩。帽子要^^盖住全部头发^^，口罩要盖住鼻孔。剪短指甲，并去除甲缘下的积垢^^。手或臂部有破损或有化服性感染时·，不能参加于术^^
** 外科手消毒
*** 人体皮肤表面存在着微生物群落，一部分存在于皮肤皱榴和毛孔等深部，称为^^常居菌^^落，主要包括凝固酶阴性葡萄球菌、棒状杆菌类、丙酸菌属、不动杆菌等，不易被摩擦等方式清除；另一部分为皮肤表面的^^暂居菌^^，多是来自环境，松散附着于皮肤表面。手臂消毒法^^能清除皮肤表面几乎所有暂居菌，和少部分常居细菌^^。在手术过程中，^^深藏的常居菌可能逐渐移到皮肤表面。所以在手臂消毒后，还要戴上消毒橡胶手套和穿无菌手术衣，^^以防止这些细菌污染伤口。
*** 手臂的消毒包括^^清洁和消毒两个步骤^^：先用皂液或洗手液，^^按“六步洗手法”彻底清洗^^手臂，去除表面各种污渍，^^然后用消毒剂作皮肤消毒^^。目前常用的于消毒剂有乙醇、异丙醇、氯己定、腆附等。消毒方法有刷洗法、冲洗法和免冲洗法。外科手消毒最常用的刷洗法，按一定顺序刷洗手臂3分钟，可达到外科手消毒标准。传统的手臂消毒法有肥皂水刷洗、乙醇浸泡法，需要15分钟才能完成，现在已很少使用。新型于消毒剂的出现使消毒过程逐渐简化
** 穿无菌手术衣和戴手套的方法
* 病人手术区的准备 
:PROPERTIES:
:id: 624a5651-9731-4cd4-9871-71f57338ab79
:END:
** 病人皮肤表面也存在着暂居菌和常居菌。这些细菌进入切开的组织可能会导致感染.^^病人手术区准备^^的目的是^^清除手术切口处及其周围皮肤上的暂局菌并抑制常局菌的移^^位,最大程度减少手术部位相关感染
** <span class="tested">手术区域附近皮肤如果毛发浓密，可能影响显露和操作时，应于术前去除。</span>手术前一日，健康状况允许的病人应沐浴。如皮肤上有较多^^油脂或胶布粘贴的残迹，可用汽油或松节油拭去。^^
** 除局部麻醉外，^^手术前皮肤消毒应在麻醉后进行^^，传统的皮肤消毒法是用2.5%～3%腆酊涂擦手术区，待其干燥后以^^70%酒精涂擦两遍^^，脱去腆町。近年来，含活性腆或活性氯的专用皮肤消毒剂陆续问世并广泛用于临床，新型消毒剂对皮肤剌激性小，可长时间留在皮肤表面，消毒抑菌作用持久。
** 消毒规范：
*** ① <span class="tested">涂擦消毒剂时，应由于术区中心部向四周涂擦。如为感染部位手术，或为肛门区手术，则应从手术区外周涂向感染处或会阴虹门处。</span>已经接触污染部位的药液纱布，不应再返擦清洁处；
*** ② <span class="tested">手术区皮肤消毒范围要包括手术切口周围15cm的区域。</span>如切口有延长的可能，应相应扩大皮肤消毒范围。不同手术部位的皮肤消毒范围可参见配套教材《外科实习医师手册》相关章节的图示说明
** 手术区消毒后，需铺设无菌布单，^^目的是^^除显露手术切口所必需的最小皮肤区以外，^^遮盖非手术区，尽量减少手术中的污染，^^为于术操作提供充分的无菌平面。除手术切开部位外，手^^术切口周围必须覆盖四层或四层以上无菌巾^^。铺巾原则是： <span class="tested">先铺相对不洁区（如下腹部、会阴部），最后铺靠近操作者的一侧</span>，并用布巾钳将交角夹住，以防移动。 <span class="untestedHL">无菌巾铺设完成，不可随便移动，如果位置不准确，只能由于术区向外移，不能由外向内移动。</span>铺巾具体操作步骤详见配套教材《外科实习医师手册》。
*