#+title: 外科学/外科学总论/重症监测治疗与复苏/常见器官的功能衰竭的治疗原则
#+deck: 外科学::外科学总论::重症监测治疗与复苏::教材::常见器官的功能衰竭的治疗

* 急性肝衰竭
** 急性肝衰竭的治疗/病因治疗 #card
:PROPERTIES:
:id: 624d8b6d-8b89-4dfa-b803-a55203be52af
:END:
*** (1)化学物质中毒:在可疑由 <span class="untestedHL">药物肝毒性所致AHF时,停用必需药物以外的所有药物</span>。对于已知对乙酰氨基酚过量或在就诊4小时内疑似对乙酰氨基酚过量病人,在开始给N-乙酰半胱氨酸治疗前先给活性炭; <span class="untestedHL">对于摄入大量对乙酰氨基酚,血清药物水平或转氨酶水平升高,提示即将发生或已发生肝损伤的所有病人,迅速开始给予N-乙酰半胱氨酸治疗</span>;在已知或疑似 <span class="untestedHL">蘑菇中毒的ALF病人,考虑给予青霉素G和N-乙酰半胱氨酸治疗。</span>
*** (2)病毒性肝炎: <span class="untestedHL">应考虑用核苷酸类似物治疗乙型肝炎相关的AHF和预防肝移植后乙型肝炎复发。</span>与AHF相关的甲型(和丁型)肝炎必须用支持治疗。对于已知或怀疑由疱疹病毒或水痘带状疱疹导致AHF的病人,应使用阿昔洛韦治疗。
*** (3)其他: <span class="untestedHL">对于妊娠期急性脂肪肝或HELLP综合征(溶血,肝酶水平升高,血小板计数低),建议迅速终止妊娠。</span>
** 急性肝衰竭的治疗/一般治疗 #card
:PROPERTIES:
:id: 624d8bb4-9f51-42db-9686-dd216283ebd2
:END:
*** ①营养支持, <span class="untestedHL">首选肠内营养,</span>可鼻饲含有酪氨酸、牛磺酸和w-3脂肪酸的营养剂。 <span class="untestedHL">肠外营养支持治疗时,可用葡萄糖和支链氨基酸,脂肪乳剂可选用中链/长链脂肪乳剂,并给予足量的维生素。</span>
*** <span class="untestedHL">②补充血清白蛋白</span>。
*** ③口服 <span class="untestedHL">乳果糖</span>,以排软便2~3次/日为度。 <span class="untestedHL">口服肠道抗菌药</span>,以减少肠内菌群,如新霉素和甲硝唑。
*** ④静脉点滴醋谷胺(乙酰谷酰胺)、 <span class="untestedHL">谷氨酸(钾或钠)或门冬氨酸等,以降低血気</span>。
*** ⑤静滴y-氨酪酸、左旋多巴,改善中枢神经递质,可能有利于恢复大脑功能。
*** <span class="untestedHL">6纠正酸碱失衡和电解质素乱。</span>
** 急性肝衰竭的治疗/防治多器官功能障碍 #card
:PROPERTIES:
:id: 624d8bb9-e9f3-4e3f-8e66-f97adb870756
:END:
*** <span class="untestedHL">给予H₂受体阻滞剂或质子泵抑制剂(或硫糖铝作为二线药物)预防与应激相关的胃肠道出血;</span>
*** <span class="untestedHL">避免使用肾损害药物以预防肾损伤;</span>
*** <span class="untestedHL">预防和治疗ARDS。</span>
** 急性肝衰竭的治疗/预防感染 #card
:PROPERTIES:
:id: 624d8bca-68d4-4dc6-ad89-21b102879455
:END:
*** 应全身使用广谱抗生素必要时用抗真菌药物。
** 急性肝衰竭的治疗/肝性脑病的治疗 #card
:PROPERTIES:
:id: 624d8bd4-de93-42e7-b947-484596af20fc
:END:
*** <span class="untestedHL">①脱水:建议用甘露醇(0.5~1.0g/kg)为一线治疗药物;</span>
*** <span class="untestedHL">②低温:将核心体温降至34~35℃为宜;</span>
*** <span class="untestedHL">③自身免疫性肝炎引起的肝性脑病可考虑使用激素。</span>
** 急性肝衰竭的治疗/人工肝支持 #card
:PROPERTIES:
:id: 624d8bdb-72ae-4574-a476-c0bfcc00569e
:END:
*** 6.人工肝支持  <span class="untestedHL">可通过灌流、吸附和透析作用,清除肝衰竭病人血中有害物质。尤其是等待肝移植的病人,可用人工肝暂时支持肝的功能,为施行肝移植术作准备</span>。
** 急性肝衰竭的治疗/肝移植 #card
:PROPERTIES:
:id: 624d8be4-8c69-4301-85d9-2f37a5f37c91
:END:
*** 7.肝移植 肝移植是治疗AHF最有效的治疗手段,适用于经积极内科和人工肝治疗疗效欠佳者。
**
*
*