#+title: 外科学/外科学总论/外科微创技术/教材

* 内镜技术在外科临床中的应用
** 内镜技术在消化外科中的应用 
:PROPERTIES:
:id: 62510864-f430-440a-ae0f-31b30a9fae23
:END:
*** 胃镜
**** 随着内镜技术的完善，食管、胃息肉及早期癌症的诊断率已明显提高。 <span class="untestedHL">胃镜下可使用 高频电刀对病变进行切除,也可采用内镜下黏膜切除术(endoscopic mucosal resection, EMR)、内镜黏膜 下剥离术(endoscopic submucosal dissection, ESD)对此类疾病进行治疗。</span>近年来内镜下扩张及支架置人技术发展迅速,为肿瘤引起的食管狭窄、术后吻合口狭窄等疾病的治疗提供了一种微创、有效的治疗手段。另外 <span class="untestedHL">,胃镜下采用套扎、栓塞及硬化等技术也可有效治疗食管胃底静脉曲张。</span>
*** 十二指肠镜
**** 2.十二指肠镜  <span class="untestedHL">经十二指肠镜的逆行胰胆管造影术及内镜下十二指肠乳头括约肌切开术</span>(endo-scopic sphincterotomy, EST)近年来快速发展,现已成为胰胆系统直接造影及处理胆管结石的主要方法(图16-1)。
*** 小肠镜
*** 大肠镜
*** 胆道镜
*** 胶囊内镜
*** 超声内镜
*** 共聚焦激光显微镜
** 内镜技术在泌尿外科中的应用 
:PROPERTIES:
:id: 62510864-2e5e-4a44-847e-aa445c1ddba4
:END:
*** (二)内镜技术在泌尿外科中的应用 泌尿外科是内镜技术应用最为广泛的临床科室之一,
**** <span class="untestedHL">约90%以上的泌尿外科手术均可通过内镜来完成。经皮肾镜、输尿管镜、膀胱镜或腹腔镜,可采用气压弹道、液电、超声波、激光等方法碎石,清除绝大多数肾、输尿管或膀胱结石。</span>
**** 自20世纪70年代以来, <span class="untestedHL">经尿道前列腺电切术已经成为治疗良性前列腺增生症的标准术式。</span>
**** <span class="untestedHL">此外,内镜技术在泌尿系肿瘤的治疗中占有重要地位。膀胱癌根据其不同分期,可以选择不同的内镜治疗,如浅表性膀胱癌可经尿道作膀胱肿瘤电切术。</span>
* 内镜技术在胸外科中的应用 
:PROPERTIES:
:id: 62510864-d113-4e91-9084-7a0883ee94ae
:END:
** 支气管镜在胸外科主要用于支气管病变的诊断和切除止血或支气管狭窄球囊扩张等
* 内镜技术在骨科中的应用 
:PROPERTIES:
:id: 62510864-3a00-4021-b33a-dde5be0f3906
:END:
** <span class="untestedHL">关节镜是一种观察滑膜、软骨、半月板以及韧带等关节内部结构的内镜</span>，主要用于关节内疾病的诊疗。此外，还可采用脊柱内镜行侧路或后路的脊柱微创手术，具有组织损伤小、出血少、脊柱稳定性能破坏小、术后疼痛轻、住院时间短等优点。
* 内镜技术在神经外科中的应用 
:PROPERTIES:
:id: 62510864-a449-4d8d-b026-9de97abafee7
:END:
** <span class="untestedHL">神经内镜自20世纪60年代开始应用于神经外科疾病的诊疗,现已用于脑积水、颅内囊肿、颅内血肿、脑室及室旁肿瘤、垂体腺瘤、颅咽管瘤等神经外科疾病的治</span>疗。
* 腹腔镜外科手术适应症
** 早年,腔镜主要用于腹腔探查,对疾病进行诊断。近20年来,腹腔镜手术在临床上广泛地应用于外科疾病的治疗。主要适应证包括
*** <span class="untestedHL">炎性疾病(如胆囊炎、阑尾炎)</span>
*** <span class="untestedHL">先天性发育异常(如小儿巨结肠)、</span>
*** <span class="untestedHL">外伤及良性肿瘤等。</span>
* 腹腔镜外科常用手术
** 常用的手术包括腹腔镜胆囊切除术、结肠切除术(良性肿瘤)、阑尾切除术、 <span class="untestedHL">食管反流手术(Nissen手术)</span>、小肠切除术、疝修补术、甲状腺手术、胃部分(楔形)切除术、脾切除术、胰腺尾部切除术、淋巴清扫术、肝楔形切除术(良性肿瘤)等。 <span class="untestedHL">现在腹腔镜下恶性肿瘤切除所占比例逐年增加,结直肠癌根治性切除术、胃癌根治术等越来越普及。</span>而胰十二指肠切除术(Whipple手术)、解剖性半肝切除术、供肝切取术、供肾切取术、血管动脉瘤切除或转流术等,近几年发展迅速,很多医院已经开展。
* 腹腔镜手术的并发症
** <span class="untestedHL">腹腔镜手术的创伤微小并不等于它的手术危险也是微小的</span>,腹腔镜手术除了可能发生与传统开腹手术同样的并发症以外,还可发生腹腔镜技术所导致的特有并发症。
** (一) CO2气腹相关的并发症与不良反应 腹腔镜手术一般用CO₂气体来建立气腹。气腹的建立必将对心肺功能产生一定程度的影响,如隔肌上抬、肺顺应性降低、有效通气减少、心排血量减少、下肢静脉淤血和内脏血流减少等,并由此产生一系列并发症, <span class="untestedHL">包括皮下气肿、气胸、心包积气、气体栓塞、高碳酸血症与酸中毒、心律不齐、下肢静脉淤血和血栓形成、腹腔内缺血、体温下降等。</span>
** (二)与腹腔镜手术相关的并发症
1. <span class="untestedHL">血管损伤</span> 术中血管损伤可发生于各种腹腔镜手术中,暴力穿刺是损伤后腹膜大血管的主要原因,其他则发生在手术操作过程中。根据损伤血管的部位,大致可分为以下三类:①腹膜后大血管,包括腹主动脉、下腔静脉、豁动静脉、门静脉等大血管,虽然这类损伤发生率较低,但死亡率很高;②腹壁、肠系膜和网膜血管等;③手术区血管,如在行LC(胆囊切除术)时损伤肝蒂血管,包括肝动脉、门静脉和胆囊动脉及其分支等。
2. <span class="untestedHL">内脏损伤</span> 腹腔镜术中内脏损伤并不少见,常因术中未能得到发现,术后发生腹膜炎等严重并发症而又未能及时确诊,造成严重后果。根据损伤脏器的不同可分为两类:①空腔脏器损伤:包括肝外胆管、小肠、结肠、胃、输尿管和膀胱等;②实质性脏器损伤:包括肝、脾、膈肌、肾、子宫等。
3. <span class="untestedHL">腹壁并发症</span> 腹腔镜手术的腹壁并发症主要是与截孔有关,有截孔出血与腹壁血肿,截孔感染、腹壁坏死性筋膜炎和截孔疝等。
* 腹腔镜胆囊切除术
** <span class="untestedHL">是目前腹腔镜技术在外科手术中应用最广泛、最具代表性的手术。</span>
LC 的手术指征与开腹手术相同，其手术操作步骤大致为∶① <span class="untestedHL">建立气腹 13mmHg</span>，置入腹腔镜探查腹腔。② <span class="untestedHL">用抓钳将胆囊底部向头部牵拉</span>，另一抓钳将胆囊颈向右下方牵拉，使胆囊管有张力并与胆总管呈垂直角度，以显露 Calot 三角。③ <span class="untestedHL">仔细解剖出胆囊管与囊动脉.分别夹闭两端并剪断</span>。④ <span class="untestedHL">顺行或逆行将胆囊从胆囊床上剥离下来。⑤将胆囊装人标本袋取出</span>。