#+title: 外科学/普通外科/胆道疾病/教材/解剖生理概要

* 胆道系统的应用解剖
:PROPERTIES:
:collapsed: true
:END:
** 胆道分为肝内胆管和肝外胆道。
*** （一）肝内胆管起自毛细胆管，汇集成小叶间胆管、肝段胆管、肝叶胆管及肝内部分的左右肝管。肝内胆管，肝动脉和门静脉各级分支的分布和走行大体一致，三者同为一结缔组织鞘（Glisson鞘）所包绕。通常，左肝管由左内叶和左外叶胆管汇合而成，右肝管由右前叶和右后叶胆管汇合而成。
左、右肝管为一级支，左内叶、左外叶、右前叶、右后叶胆管为二级支，各肝段胆管为三级支。
*** （二）肝外胆道 肝外胆道由左肝管和右肝管、肝总管、胆囊、胆囊管以及胆总管组成。
**** 1，左、右肝管和肝总管 左肝管细长，长约2.5~4cm；右肝管短粗，长约1~3cm。左、右肝管出肝后，在肝门部汇合形成肝总管。左、右肝管，门静脉左、右支，肝动脉左、右支，淋巴管及神经等出人肝门的结构称为肝蒂，走行于肝十二指肠韧带内。肝门处，一般左、右肝管及肝总管在前偏右，肝动脉左、右支及主干居中偏左，门静脉左、右支及主干在两者后方；左、右肝管的汇合点位置最高，门静脉左、右支的分叉点稍低；肝固有动脉左、右支的分叉点最低（图40-1）肝总管直径通常为0.4~0.6cm，长约3cm，最长可达7cm，其下端与胆囊管汇合形成胆总管。有时肝总管前方有肝固有动脉发出的肝右动脉或胆囊动脉越过，6%~10%的人有副肝管，1.4%的人可无肝总管，胆道手术时应注意解剖变异
**** 2.胆总管 肝总管与胆囊管汇合形成胆总管长约4~8cm，直径0.6~0.8cm。胆总管分为四段：
***** ①十二指肠上段：长约1.4cm，经肝十二指肠韧带右缘下行，是临床上胆总管探查、引流的常用部位。
***** ②十二指肠后段：长约2cm，行经十二指肠第一段后方，其后方为下腔静脉，左侧有门静脉和胃十二指肠动脉。
***** ③胰腺段：长约1~2cm，在胰头后方的胆管沟内或胰腺实质内下行。因其与胰头部关系密切，胰头肿块常压迫或侵及此处造成梗阻性黄疸。
***** ④十二指肠壁内段：长约1cm，行至十二指肠降部中段，斜行进人肠管后内侧壁。
***** 胆总管与主胰管在肠壁内汇合，膨大呈壶状，亦称Vater壶腹。壶腹周围有Oddi括约肌包绕，末端通常开口于十二指肠乳头。胆总管和主肤管的汇合常发生解剖变异：胆总管与主胰管汇合后形成一个管道开口于十二指肠（约占70%）；胆总管与主胰管没有汇合形成一个管道，而是在十二指肠有一个共同的开口（约占20%）；胆总管与主膜管分别开口于十二指肠（约占10%）（图40-2）。Oddi括约肌主要包括胆管括约肌、胰管括约肌和壶腹括约肌，它具有控制和调节胆总管和胰管的开放，以及防止十二指肠内容物反流的作用。
**** 3.胆囊为腹膜间位器官，呈梨形，游离的一侧被脏腹膜覆盖，另一侧位于肝脏面胆囊窝内，借结缔组织与肝相连。胆囊长5~8cm，宽3~5cm，容积30~60ml；分为底、体、颈三部。底部为盲端，是胆囊穿孔的好发部位；底部向左后上方延伸为体部，体部向前上弯曲变窄形成胆囊颈，三者间无明显界线。胆囊颈上部呈囊状扩大，称Hartmann袋，胆囊结石常滞留于此处。
**** 4.胆囊管 由胆囊颈延伸而成，长1~5cm，直径0.2~0.4cm。胆囊管内壁黏膜形成螺旋状皱璧，称Heister瓣，对于防止胆结石进入胆总管有重要作用。胆囊管可能存在多种解剖变异（图40-3），其中胆囊管过长且低位汇入胆总管是发生Mirizzi综合征的解剖基础。胆囊管、肝总管、肝下缘所构成的三角区称为胆囊三角（Calot三角）。胆囊动脉、肝右动脉、副右肝管常在此区穿过，胆道手术时应特别注意避免损伤。胆囊淋巴结位于胆囊管与肝总管相汇处夹角的上方，可作为手术寻找胆囊动脉和胆管的解剖标志。
*** （三）胆道的血管、淋巴和神经 胆道有丰富的血液供应，主要来自胃十二指肠动脉、肝总动脉和肝右动脉，这些动脉的分支在胆管壁周围相互吻合成丛状。胆囊、胆囊管、胆总管上部由胆囊动脉供血；胆总管下部的血供来自胰十二指肠动脉及十二指肠后动脉的分支。胆囊静脉和肝外胆道静脉直接汇人门静脉。胆囊的淋巴引流人胆囊淋巴结和肝淋巴结，并与肝内的淋巴管有吻合。肝外胆管的淋巴引流人肝总管和胆总管后方的淋巴结。
胆道系统分布着丰富的神经纤维，主要来自腹腔丛发出的迷走神经和交感神经。术中过度牵拉胆囊致迷走神经受激惹，可诱发胆心反射，产生胆心综合征，甚至发生心搏骤停，需高度重视。
*** （四）胆道的结构 肝内胆管起源于毛细胆管。毛细胆管是相邻肝细胞膜局部凹陷形成的微细小管，在肝板内连接成网状管道，逐渐由中央向外周汇集，于小叶边缘处形成若干由单层立方上皮构成的短小闺管。闺管出肝小叶后，汇人小叶间胆管，再进一步汇合成肝段、肝叶胆管，肝管管径逐渐增大，于肝门处汇合形成左、右肝管。胆管壁由单层立方上皮渐变成单层柱状上皮。
**** 肝外胆管黏膜层由单层柱状上皮构成，含杯状细胞和其他含黏液的细胞；肌层含平滑肌和弹力纤维层，受刺激时肌纤维可疫李性收缩引起绞痛；浆膜层由结缔组织组成，含神经纤维和血管分支。胆囊
**** 黏膜层由高柱状细胞组成，具吸收作用；底部含小管泡状腺体，可分泌黏液。胆囊内的众多黏膜皱璧，能增加浓缩胆汁的能力。肌层内层呈纵行，外层呈环行，夹以弹力纤维。外膜层由结缔组织及肝包膜延续而来的浆膜形成
* 胆道系统的生理功能
** 胆道系统具有分泌、贮存、浓缩与输送胆汁的功能。
:PROPERTIES:
:collapsed: true
:END:
*** （一）胆汁的生成、分泌和代谢
**** 1.胆汁的分泌和功能 成人每日分泌胆汁约800~1200ml，胆汁主要由肝细胞分泌，约占胆汁分泌量的3/4，胆管细胞分泌的黏液约占1/4。胆汁中97%是水，其他成分主要有胆汁酸与胆汁酸盐（胆，盐）、胆固醇、磷脂、胆红素、脂肪酸和无机盐等。胆固醇在肝内代谢后合成的胆汁酸称为初级胆汁酸，即胆酸和鹅脱氧胆酸。初级胆汁酸在小肠内被细菌降解而成为次级胆汁酸，即脱氧胆酸和石胆酸。阳酸、脱氧胆酸、鹅脱氧胆酸和石胆酸称为游离型胆汁酸；游离型胆汁酸与甘氨酸或牛磺酸结合后形成以钠盐或钾盐形式存在的结合型胆汁酸，即胆汁酸盐。
胆汁呈中性或弱碱性，其主要生理功能是；
***** ①乳化脂肪；胆盐随胆汁进人肠道后与食物中的脂肪结合形成能溶于水的脂肪微粒而被肠黏膜吸收，刺激胰脂肪酶的分泌并使之激活，水解脂类，促使脂肪、胆固醇和脂溶性维生素的吸收；
***** ②清除毒素及代谢产物：胆汁参与胆固醇和胆红素的代谢及清除；
③抑制肠内致病菌生长繁殖和内毒素形成；
***** ④刺激肠蠕动；
***** ⑤中和胃酸。
**** 2.胆汁分泌的调节 胆汁分泌受神经及体液因素的调节。迷走神经兴奋，胆汁分泌增加，交感神经兴奋，胆汁分泌减少。促胰液素、胃泌素、胆囊收缩素（cholecystokinin，CCK）等可促进胆汁分泌，其中促胰液素的作用最强；生长抑素则抑制胆汁分泌。胃酸、脂肪和蛋白质的分解产物由胃进入十二指肠后，刺激十二指肠黏膜分泌促胰液素和CCK，两者均可引起胆囊平滑肌收缩和Oddi括约肌松弛。
**** 3.胆汁的代谢 胆固醇不溶于水而溶于胆汁，胆汁中的胆盐和磷脂形成的微胶粒将胆固醇包裹于其中，使其溶解，当胆盐与磷脂的比例为（2~3）：1时，胆固醇的溶解度最大。在胆汁中还有一种磷脂和胆固醇按同等比例组成的球泡，其中无胆盐。球泡溶解胆固醇的能力比微胶粒大10~20倍，可溶解胆汁内70%~80%的胆固醇，当胆汁中胆盐的浓度较高时，胆固醇主要以微胶粒的形式存在。随着胆固醇浓度增加，微胶粒饱和，球泡的数量增加。球泡中胆固醇过饱和时，胆固醇从球泡中析出结晶，形成胆固醇结石。胆盐由胆固醇在肝内合成后随胆汁分泌至胆囊内储存并浓缩。进食时，胆盐随胆汁排至肠道，其中95%的胆盐被肠道（主要在回肠）吸收人肝，称为肠肝循环；5%随粪便和尿液排出体外。因此，肝每天只需产生少量的胆盐（0.2~0.6g/d）即可保持胆盐池的稳定。胆盐的肠肝循环被破坏时，胆汁中胆盐减少、胆固醇增加，胆固醇易于析出形成结石。
非结合胆红素在肝内与葡萄糖醛酸结合，形成可溶性结合胆红素并随胆汁排入肠道，经回肠下段及结肠内细菌作用转变为胆素原，小部分被肠道吸收，形成胆色素的肠肝循环。如胆色素在肝内未与葡萄糖醛酸相结合，或当胆道感染时，大肠埃希菌所产生的B-葡萄糖醛酸酶将结合性胆红素水解成为非结合性胆红素，易聚结析出与钙结合形成胆红素钙，促发胆色素结石形成。
*** （二）胆管的生理功能
**** 胆管主要生理功能是输送胆汁至胆囊和十二指肠，由胆囊和Oddi括约肌协调完成。空腹时，Oddi括约肌收缩，胆管内的压力升高，胆汁流向压力较低的胆囊并在胆囊内浓缩和储存。进餐后，迷走神经兴奋，食物中的脂肪、蛋白质和胃酸促进十二指肠释放CCK，致使胆囊收缩、Oddi括约肌松弛，胆汁排入十二指肠。另外，胆管分泌的黏液参与胆汁的形成。
*** （三）胆囊的生理功能
**** 1.浓缩储存胆汁 胆囊容积仅为30~60ml，但24小时内能接纳约500ml胆汁。胆囊黏膜吸收水和电解质的功能很强，可将胆汁浓缩5~10倍而储存于胆囊内。
**** 2，排出胆汁 胆汁的分泌是持续的，而胆汁的排放则随进食而断续进行，这一过程可通过胆囊平滑肌收缩和Oddi括约肌松弛来实现，受神经系统和体液因素（胃肠道激素、代谢产物、药物等）的调节。每次排胆时相长短与食物的种类和量有关。CCK是餐后胆囊收缩的主要生理性刺激因子。餐后40分钟，胆囊排空50%~70%内容物；餐后60~90分钟，CCK浓度下降，胆汁重新贮存至胆囊并进一步浓缩。
**** 3.分泌功能 胆囊黏膜每天分泌约20ml黏液性物质，主要是黏蛋白，有润滑和保护胆囊黏膜的作用。胆囊管梗阻时，胆汁中胆红素被吸收，胆囊黏膜分泌黏液增加，胆囊内积存的液体呈无色透明，称"白胆汁”。
** 胆道系统的检查
:PROPERTIES:
:collapsed: true
:END:
*** 3，胆道系统常用的检查方法
*** （1）超声检查 ①诊断胆道疾病的首选方法，对胆囊结石、肝内胆管结石诊断准确率高达90%以上，对肝外胆管结石诊断准确率约80%；2超声对急慢性胆囊炎、胆囊及胆管肿瘤、先天性胆道畸形等胆道疾病也有较高的诊断准确率；③有些检查和治疗可在超声引导下进行，如胆囊穿刺置管术、经皮肝胆管穿刺造影、引流和取石等；④手术中超声检查在胆道疾病的诊断和治疗中也可发挥重要作用。
*** （2）X线检查 单纯腹部平片对胆道疾病的诊断价值有限。
*** （3）PTC和PTCD 经皮肝穿刺胆管造影（PTC）和经皮肝穿刺胆管引流（PTCD）为有创检查，可显示肝内外胆管病变部位、范围和程度，有助于黄疸的诊断和鉴别。常见并发症有胆汁漏、出血、胆道感染。
另外，可通过PTCD进行术前减黄或置放胆管内支架用作治疗。
*** （4）内镜逆行康胆管造影术（ERCP）①可直接观察十二指肠和乳头部病变，并取材活检；②ERCP可显示胆管和胰管病变；3ERCP并发症包括急性胰腺炎、出血、穿孔、胆道感染。
*** （5）术中及术后胆管造影 可了解有无胆道系统解剖变异、残留结石、胆管狭窄和通畅情况，帮助确定手术方式。对肝内、外胆管置管引流者，拔管前应常规经导管或T管行胆管造影。
*** （6）核素扫描 可用于黄疸的鉴别诊断及术后胆漏的识别。
*** （7）胆道镜 包括术中或术后胆道镜，可观察胆道有无狭窄、肿瘤、结石，并可经胆道镜进行治疗。
*** （8）磁共振胆胰管成像（MRCP）能直观地显示胆管分支形态，对胆道狭窄、胆管损伤、肝内外胆管结石、胆道系统变异、胆道梗阻的定位均有重要价值。