#+title: 外科学/普通外科/颈部疾病/教材/甲状旁腺功能亢进的外科治疗
#+deck: 外科学::普通外科::颈部疾病::教材::甲状旁腺功能亢进的外科治疗

* 甲状旁腺的解剖及生理概要/
** 甲状旁腺的解剖及生理概要/解剖 
:PROPERTIES:
:id: 62512fe6-f816-42d5-bedf-df7c3df95494
:END:
*** 甲状旁腺紧密附于 <span class="untestedHL">甲状腺左右甲状腺叶背面,数目不定,一般为4枚,每侧上下各1个</span>(图22-5)。呈卵圆形或扁平形,外观呈黄、红或棕红色,平均重量每枚35~40mg。上甲状旁腺相对固定,多数位于以喉返神经与甲状腺下动脉交叉上方1cm处为中心、直径2cm的一个圆形区域内(约占80%)。下甲状旁腺有60%位于甲状腺下、后、侧方,其余可位于甲状腺前面,或与胸腺紧密联系,或位于纵隔。
** 甲状旁腺的解剖及生理概要/生理概要 
:PROPERTIES:
:id: 62513038-67a1-460d-8d7f-54bdb2d0bb54
:END:
*** 甲状旁腺分泌甲状旁腺素(parathyroid hormone,PTH),其主要靶器官为骨和肾。PTH的生理功能是调节体内钙的代谢并维持钙和磷的平衡, <span class="untestedHL">它促进破骨细胞的作用,使骨钙(磷酸钙)溶解释放人血,致血钙和血磷浓度升高</span>。当其血中浓度超过肾阔时,便经尿排出,导致高尿钙和高尿磷。 <span class="untestedHL">PTH同时能抑制肾小管对磷的回收,使尿磷增加、血磷降低。因此当发生甲状旁腺功能亢进时,可出现高血钙、高尿钙和低血磷</span>。 <span class="tested">PTH不受垂体控制,而与血钙离子浓度之间存在反馈关系,血钙过低可刺激PTH释放;反之,血钙过高则抑制PTH释放。</span>
* 甲状旁腺/病理 
:PROPERTIES:
:id: 62512f95-f6c8-4d47-afab-a325fb5a977e
:END:
** 【病理】原发性甲状旁腺功能亢进包括腺瘤、增生及腺癌。 <span class="tested">甲状旁腺腺瘤(parathyroid adenoma) 中单发腺瘤约占80%,多发性约1% ~5%;甲状旁腺增生(parathyroid hyperplasia)约占12%,4枚腺体均受累;腺癌仅占1%~2%。</span>
* 甲状旁腺/临床表现 
:PROPERTIES:
:id: 62513117-30f3-4623-8ed0-07bb2a7a0998
:END:
** 【临床表现】原发性甲状旁腺功能亢进 <span class="untestedHL">包括无症状型及症状型两类</span>。
** <span class="untestedHL">无症状型病例可仅有骨质疏松等非特异性症状</span>,常在普查时因血钙增高而被确诊。我国目前 <span class="untestedHL">以症状型原发性甲状旁腺功能亢进多见</span>。按其症状可分为三型:
*** Ⅰ型: <span class="untestedHL">最为多见,以骨病为主,也称骨型。病人可诉骨痛,易于发生骨折。骨膜下骨质吸收是本病特点,最常见于中指烧侧或锁骨外1/3处。</span>
Ⅱ型: <span class="untestedHL">以肾结石为主,故称肾型</span>。在尿路结石病病人中,约有3%是甲状旁腺腺瘤, <span class="untestedHL">病人在长期高血钙后,逐渐发生氮质血症。</span>
Ⅲ型:为兼有上述两型的特点, <span class="untestedHL">表现有骨骼改变及尿路结石。</span>
其他症状可有 <span class="untestedHL">消化性溃疡、腹痛、神经精神症状、虚弱及关节痛。</span>
* 甲状旁腺/诊断/
** 甲状旁腺/诊断/实验室检查 
:PROPERTIES:
:id: 6251325d-cbc3-47d8-9066-883d9cb01928
:END:
*** (1)血钙测定:是 <span class="untestedHL">发现甲状旁腺功能亢进的首要指标,正常人的血钙值一般为2.1~2.5mmol/L,甲状旁腺功能亢进可>3.0mmol/L。</span>
*** (2)血磷测定 <span class="untestedHL">:血磷的诊断价值较血钙小,血磷值<0.65~0.97mmol/L。</span>
*** (3) PTH 测定: <span class="untestedHL">PTH 测定值升高是诊断甲状旁腺功能充进最可靠的直接证据</span>,可高达正常值的数倍。
*** (4)尿中环腺苷酸(cAMP)的测定: <span class="untestedHL">原发性甲状旁腺功能亢进时,尿中环腺昔酸(cAMP)排出量明,显增高,可反映甲状旁腺的活性,有助于诊断甲状旁腺功能亢进。</span>
** 甲状旁腺/诊断/定位检查 
:PROPERTIES:
:id: 62513289-adeb-4614-984f-19073133a678
:END:
*** (1)超声检查:是常用的检查方法。正常甲状旁腺呈圆形或卵圆形,直径2~4mm,腺体回声较低。前 <span class="untestedHL">方为甲状腺,侧方为颈总动脉。</span>
*** (2)核素显像目前普遍采用”"Tc-MIBI双时相法,效果满意,定位准确率可达90%以上。对于异位甲状旁腺的定位尤为有用
* 甲状旁腺/治疗 
:PROPERTIES:
:id: 625132fc-edef-4b78-a3b9-5faff992775a
:END:
** 【治疗】主要采用手术治疗,手术方式可选择常规或腔镜。术中超声可帮助定位,术中冰冻切片检查、病灶切除后血钙和甲状旁腺激素降低有助于定性诊断。
1.甲状旁腺腺瘤  <span class="untestedHL">原则是切除腺瘤,对早期病例效果良好。</span>病程长并有肾功能损害的病例,切除腺瘤后可终止甲状旁腺功能亢进的继续损害,但对已有肾功能损害,若属严重者,疗效较差。
** 2.甲状旁腺增生 有两种手术方法,一是作 <span class="untestedHL">甲状旁腺次全切除,即切除3枚腺体,保留1/2枚腺体</span>。另 <span class="untestedHL">一种方法是切除所有4枚甲状旁腺,同时作甲状旁腺自体移植,并冻存部分腺体,以备必要时应用。</span>
** 3.甲状旁腺癌  <span class="untestedHL">应作整块切除,</span>且应包括一定范围的周围正常组织。
手术并发症及术后处理:并发症很少,偶尔可发生胰腺炎,原因尚不清楚。探查广泛,且操作不慎时可损伤喉返神经。术后24~48小时内血清钙会明显下降,病人会感到面部、口周或肢端发麻,严重者可发生手足抽搞。静脉注射10%葡萄糖酸钙溶液,剂量视低血钙症状而定。一般在术后3~4天后恢复正常。 <span class="untestedHL">术后出现血清钙下降,往往表示手术成功,病变腺体已经切除。</span>
*
*