#+title: 外科学/胸部外科/肺疾病/教材/肺肿瘤
#+deck:外科学::胸部外科::肺疾病::教材::肺肿瘤

* 肺癌定义 #card
:PROPERTIES:
:id: 62523f48-e1fb-4a42-8934-7876d09a9e40
:collapsed: true
:END:
** 肺癌(lungcancer)又称原发性支气管肺癌。 <span class="untestedHL">指的是源于支气管黏膜上皮或肺泡上皮的恶性肿瘤</span>。近年来,全世界肺癌的发病率明显增高,在工业发达国家和我国大城市中,肺癌的发病率已居男性肿瘤发病的首位。20世纪末,肺癌已成为恶性肿瘤死因中的首位。 <span class="tested">肺癌的发病年龄大多在40岁以上,男性居多,但女性肺癌的发病率近年明显增加。</span>
* 肺癌/病因 #card
:PROPERTIES:
:id: 62523fc6-7045-43e2-90fa-f967738fd6ce
:collapsed: true
:END:
** 【病因】肺癌的病因至今不完全明确,肺癌危险因素包括吸烟、大气污染、烹任油烟、职业接触(包括碑、镉、铭、锦、石棉、煤炼焦过程、氧、电离辐射等)、饮食因素、遗传易感性、基因变异等。长期大量吸烟是肺癌的最重要风险因素,吸烟量越大、开始年龄越早、吸烟年限越长则患肺癌的危险性越高。
* 肺癌/病理/梗概 #card
:PROPERTIES:
:id: 62524003-9e2c-45b4-8b0f-5c8797ab3e09
:collapsed: true
:END:
** 【病理】肺癌起源于支气管黏膜上皮或肺泡上皮。肺癌的分布, <span class="untestedHL">右肺多于左肺,上叶多于下叶</span>。传统上把起源肺 <span class="untestedHL">段支气管开口以近,位置靠近肺门的肺癌称为中心型肺癌;起源于肺段支气管开口以远,位于肺周围部分的肺癌称为周围型肺癌。</span>
肺癌通常分为小细胞肺癌和非小细胞肺癌两大类。由于小细胞肺癌在生物学行为、治疗、预后等方面与其他类型差别巨大,因此将小细胞肺癌以外的肺癌统称为非小细胞肺癌(non-small cell lungcancer, NSCLC)。目前肺癌病理学分类采用的是2015年世界卫生组织(WHO)修订的病理分型标准,其中较为常见的肺癌病理类型有以下几种:
** 鳞状细胞癌
** 腺癌
** 小细胞癌
**
* 肺癌/病理/
:PROPERTIES:
:collapsed: true
:END:
** 肺癌/病理/鳞状细胞癌 #card
:PROPERTIES:
:id: a7e8fab7-2c2f-4dcb-af30-04546efce05d
:END:
*** 1.鳞状细胞癌  <span class="tested">与吸烟关系密切,男性占多数。大多起源于较大的支气管,常为中心型肺癌</span>。鳞癌的分化程度不一,生长速度较缓慢,病程较长,肿块较大时可以发生中心坏死,形成厚壁空洞。 <span class="untestedHL">通常先经淋巴转移,血行转移发生相对较晚。</span>
** 肺癌/病理/腺癌 #card
:PROPERTIES:
:id: 36119b1d-7eca-47e2-960a-bf9e38f8a5ac
:END:
*** <span class="tested">2.腺癌 近年来发病率上升明显,已超越鳞癌成为最常见的肺癌。</span>发病年龄普遍低于鳞癌和小细胞肺癌, <span class="untestedHL">多为周围型</span>,一般生长较慢,但有时在早期即发生血行转移,淋巴转移相对较晚。
** 肺癌/病理/小细胞癌 #card
:PROPERTIES:
:id: ccb8cc96-ae86-438c-bff5-a1d33379512c
:END:
*** <span class="tested">3.小细胞癌 与吸烟关系密切。老年男性、中心型多见。</span>小细胞癌为神经内分泌起源,恶性程度高,生长快,很早可出现淋巴和血行转移。其对放射和化学治疗虽较敏感,但可迅速耐药,预后差。部分肺癌病例可同时存在不同类型的癌肿组织,如腺癌和鳞癌混合,非小细胞癌与小细胞癌并存等。
* 肺癌/扩展及转移 #card
:PROPERTIES:
:id: 9931c794-d858-4b4d-941c-0415b1d32e52
:collapsed: true
:END:
** 1.直接扩散 <span class="untestedHL"> 癌肿沿支气管壁并向支气管腔内生长,造成支气管腔部分或全部阻塞;</span>癌肿可穿越肺叶间裂侵人相邻的肺叶;肺癌可突破脏层胸膜,造成胸膜腔种植转移;癌肿可直接侵犯胸壁、纵隔内其他组织和器官。
** 2.淋巴转移  <span class="untestedHL">淋巴转移是常见的扩散途径,小细胞癌和鳞癌较多见</span>。癌细胞经支气管和肺血管周围的淋巴管道,先侵入邻近的肺段或肺叶支气管周围的淋巴结,然后到达肺门或隆突下淋巴结,或经气管旁淋巴结,最后累及锁骨上前斜角肌淋巴结和颈部淋巴结。纵隔和锁骨上以及颈部淋巴结转移一般发生在原发灶同侧,但也可以在对侧,即交叉转移。肺癌也可以在肺内、肺门淋巴结无转移情况下发生纵隔淋巴结转移,为跳跃转移。
** 3.血行转移 小 <span class="untestedHL">细胞癌和腺癌的血行转移,较鳞癌常见</span>。肺癌最常见的远处转移部位是 <span class="untestedHL">肺、骨、脑、肝、肾上腺。</span>
* 肺癌/临床表现/
:PROPERTIES:
:collapsed: true
:END:
** 【临床表现】肺癌的临床表现与癌肿的部位、大小、是否压迫侵犯邻近器官以及有无转移等情况
密切相关。
** 肺癌/临床表现/早期肺癌特别是周围型肺癌 #card
:PROPERTIES:
:id: 625243e5-58b4-49cf-94bf-eb4709fdf898
:END:
*** <span class="untestedHL">往往无任何症状大多在行胸片或胸部CT检查时发现</span>。随着肿瘤的进展,出现不同的症状。 <span class="untestedHL">临床常见症状包括:咳嗽、血疾、胸痛、发热、气促。其中最常见的症状为咳嗽,癌肿在较大的支气管内长大后,常出现刺激性咳嗽</span>。当癌肿继续长大阻塞支气管,继发肺部感染,疾量增多,伴有旅性疾液。血痰常见于中心型肺癌,通常为痰中带血点、血丝或断续地少量略血;大量略血则很少见。
肺癌的症状没有特异性,凡超过两周经治不愈的呼吸道症状,尤其是血痰、干咳,或原有的呼吸道症状发生改变,要警惕肺癌的可能性。
** 肺癌/临床表现/局部晚期肺癌 #card
:PROPERTIES:
:id: 625242bd-c8d2-43a1-86f3-6f8507217f47
:END:
*** 压迫或侵犯邻近器官时可产生下列症状和体征
*** ①压迫或侵犯隔神经,引起同侧膈肌麻痹;
*** ②压迫或侵犯喉返神经,引起声带麻痹,声音嘶哑;
*** ③压迫上腔静脉,引起上腔静脉梗阻综合征,表现为面部、颈部、上肢和上胸部静脉怒张,皮下组织水肿;
*** ④胸膜腔种植,可引起胸膜腔积液,常为血性积液,导致气促;癌肿侵犯胸膜及胸壁,还可引起持续性剧烈胸痛;
*** ⑤癌肿侵入纵隔,压迫食管,可引起吞咽困难;
*** 6肺上沟瘤,亦称Pancoast瘤(Pancoast tumor),侵入纵隔和压迫位于胸廓入口的器官或组织,如第1肋骨、锁骨下动脉和静脉、臂丛神经、颈交感神经等,产生剧烈胸肩痛、上肢静脉怒张、水肿、臂痛和上肢运动障碍,也可引起同侧上眼脸下垂、瞳孔缩小、眼球内陷、面部无汗等颈交感神经综合征(Horner综合征)。
** 肺癌/临床表现/远处转移的临床表现 #card
:PROPERTIES:
:id: 625242c7-e3f7-4ac8-b23f-07bec09249a8
:END:
*** 按侵入的器官不同产生不同症状,脑转移可引起头痛、恶心或其他的神经系统症状和体征;骨转移可引起骨痛、血液碱性磷酸酶或血钙升高;肝转移可导致肝大、碱性磷酸酶、谷草转氨酶、乳酸脱氢酶或胆红素升高等;皮下转移时可在皮下触及结节。
** 肺癌/临床表现/副瘤综合征 #card
:PROPERTIES:
:id: 625242ca-dff4-4ac9-b7d1-321b1cc8c1ab
:END:
*** 少数肺癌病例,由于肿瘤产生内分泌物质,临床上呈现非转移性的全身症状, <span class="untestedHL">如骨关节病综合征(杵状指、骨关节痛、骨膜增生等)、Cushing综合征、Lambert-Eaton综合征、男性乳腺增大、多发性肌肉神经痛等</span>。这些症状在切除肺癌后有可能会消失。
* 肺癌/诊段/梗概
:PROPERTIES:
:collapsed: true
:END:
** 肺癌/诊段/影像学检查方法 #card
:PROPERTIES:
:id: 625245a3-ebb7-4ec0-a94e-f72ff733a5ea
:END:
*** 胸部正侧位片
**** (1)胸部正侧位片:是临床常用的检查手段,可发现较典型的肺内病灶。 <span class="untestedHL">中心型肺癌早期X线胸片可无异常征象</span>。当癌肿阻塞支气管,受累的肺段或肺叶出现肺炎征象。支气管管腔被癌肿完全阻塞,可产生相应的肺叶或一侧全肺不张。 <span class="untestedHL">癌肿转移到肺门及纵隔淋巴结可出现肺门阴影或纵隔阴影增宽,不张的上叶肺与肺门肿块联合可形成“反S征”影像</span>。纵隔转移淋巴结压迫隔神经时,可见隔肌抬高,透视可见隔肌反常运动。气管隆突下肿大的转移淋巴结,可使气管分叉角度增大。晚期病例还可看到胸膜腔积液或肋骨破坏。
*** CT
**** (2) CT:胸部CT图像避免了病变与正常组织互相重叠,可发现一般X线检查隐藏区的病变(如肺尖、脊柱旁、心脏后、纵隔等处)。因其薄层扫描,密度分辨率很高,可以显示直径更小,密度更低的病变。CT不但可以显示病灶的局部影像特征,还可以评估肿瘤范围、肿瘤与邻近器官关系、淋巴结转移状况,为制定肺癌的治疗方案提供重要依据。 <span class="untestedHL">低剂量胸部CT是目前肺癌筛查最有效的手段,可以发现肺内的早期病变。</span>通过早发现、早诊断、早治疗,从而降低肺癌病人的死亡率。
 <span class="untestedHL">肺癌常见的CT征象有:分叶征、毛刺征、空泡征、空气支气管像、肿瘤滋养动脉、血管切迹和集束,征、胸膜凹陷或牵拉征、偏心空洞等征象。</span>部分早期肺腺癌在CT中可表现为磨玻璃样病灶(ground-glass opacity,GGO)。中心型肺癌CT表现为肺门肿块,还可表现支气管内占位、管腔狭窄、阻塞、管壁增厚,同时伴有肺门增大,及阻塞性肺炎或肺不张等改变。
*** PET
**** (3) PET:是利用正常细胞和肿瘤细胞对放射性核素标记的脱氧葡萄糖的摄取不同而显像,恶性肿瘤的糖代谢高于正常细胞,表现为局部放射性浓聚。 <span class="untestedHL">PET检查可用于肺结节的鉴别诊断、肺癌分期、转移灶检测、疗效评价、肿瘤复发转移监测等。</span>近年来发展的PET-CT,结合了PET与CT的优点,弥补了PET对病灶精确定位的困难,提高了诊断的效能及准确性。
*** MRI
**** (4) MRI:并非肺癌诊断的常用检查手段, <span class="untestedHL">但对肺上沟瘤(Pancoast肺癌)</span>需显示胸壁侵犯及锁骨下血管和臂丛神经受累情况,MRI可提供更准确的诊断信息。此外对硬过敏不能行增强CT扫描的病例可考虑行MRI检查。
*** 超声
**** (5)超声:对于 <span class="untestedHL">肺癌分期具有重要意义</span>,除腹部超声(主要是肝和肾上腺)外,对胸腔积液定位、锁骨上区淋巴结等也是重要的辅助检查手段。
*** 骨扫描
**** (6)骨扫描:采用*c标记的二腾酸盐进行骨代谢显像是 <span class="untestedHL">肺癌骨转移筛查的重要手段。</span>
** 肺癌/诊段/有助于明确病理的检查方法 #card
:PROPERTIES:
:id: 625245b0-a065-4b71-a8c4-f8dd5a47e2d1
:END:
*** 痰细胞学检查
**** 肺癌脱落的癌细胞可随痰液咳出， <span class="untestedHL">痰细胞学检查找到癌细胞，可以明确诊断</span>。 <span class="untestedHL">中央型肺癌,特别是伴有血痰的病例,疾中找到癌细胞的机会较高</span>。临床可疑肺癌者,应连续送检痰液3次或3次以上做细胞学检查。
*** 支气管镜检查
**** (2)支气管镜检查:临床怀疑的肺癌病例应常规进行支气管镜检查,其主要目的是:①观察气管和支气管中的病变, <span class="untestedHL">并取得病理证据(包括在直视下钳取、刷检、肺泡灌洗);</span>②病灶准确定位,对制定手术切除范围、方式有重要意义;③发现可能同时存在的气管内原发癌。近年新出现的自发荧光电子支气管镜技术能进一步提高对肉眼未能观察到的原位癌或隐性肺癌的诊断。
*** 支气管内超声引导针吸活检术
**** (3)支气管内超声引导针吸活检术(endobronchial ultrasound-guided transbronchial needleaspiration, EBUS-TBNA) :通过气管镜,在超声引导下, <span class="untestedHL">对纵隔或肺门淋巴结进行细针穿刺针吸活检</span>,用于肺癌病理获取和淋巴结分期。与纵隔镜检查相比,它具有更加微创的优势。
*** 纵隔镜检查
**** (4)纵隔镜检查:全麻下经颈部或胸骨旁局部切口,直视下对气管周围、隆突下区域淋巴结做组织活检, <span class="untestedHL">明确有无(纵隔)淋巴结转移</span>。纵隔镜取材量大,诊断准确率高,如临床需要,应积极采用。
*** 经胸壁针吸细胞学或组织学检查
**** (5)经胸壁针吸细胞学或组织学检查(transthoracic needle aspiration,TTNA) :对于肺部的病变,尤其是靠近周边的肿块,常规的痰细胞学或支气管镜等检查难以确诊的病例,可考虑行TTNA。 <span class="untestedHL">这项检查在CT或B超引导下进行经胸壁穿刺针吸活检</span>,有引起气胸、出血的可能,少数可能会引起针道种植转移,故通常只用于无手术指征的肺癌病人病理取材,以协助指导放、化疗方案的制订。
***
*** 胸水检查
*** 转移病灶活检
*** 胸腔镜检查
*** #+BEGIN_QUOTE
注意∶①中央型肺癌早期即可有刺激性喊嗽、痰中带血。由于肿块压迫，可使远端支气管阻塞致肺不张。
②确诊中央型肺癌首选纤维支气管镜+活组织检查，确诊周围型肺癌首选经胸壁穿刺活检。
③纤支镜用于中央型肺癌的检查，胸腔镜用于周围型肺癌的检查，纵隔镜用于纵隔肿瘤的检查。
#+END_QUOTE
**
**
* 肺癌/治疗/梗概 #card
:PROPERTIES:
:id: 62524aa6-308c-4401-b559-876cadc19780
:END:
** 【治疗】肺癌的治疗方法主要有外科手术治疗、放射治疗、化学药物治疗、靶向治疗、免疫治疗等。小细胞肺癌和非小细胞肺癌在治疗原则有很大的不同。 <span class="untestedHL">小细胞肺癌远处转移早,除早期(T,.,N, M。)的病人适于手术治疗外,其他应以非手术治疗为主。而非小细胞肺癌则依据确诊时的TNM分期治疗(表26-2)。</span>
** ((62524b3b-f741-4b96-9d1c-a3bfb7c6129a))
** 手术治疗
** 放射治疗
** 化学治疗
** 靶向治疗
** 免疫治疗
**
* 肺癌/治疗/
** 肺癌/治疗/手术治疗 #card
:PROPERTIES:
:id: e5e6c564-cba4-47e3-a92a-f9bd1cd3f34a
:END:
*** 1.手术治疗  <span class="untestedHL">早期肺癌外科手术治疗通常能达到治愈效果</span>。 <span class="untestedHL">手术治疗的适应证是Ⅰ、Ⅱ期和部分经过选择的ⅢA期(如T,N, M)的非小细胞肺癌。</span>已明确纵隔淋巴结转移(N2)的病人,手术可考,虑在(新辅助)化疗/放化疗后进行。 <span class="untestedHL">ⅢB、IV期肺癌,除个别情况外,手术不应列为主要的治疗手段。</span>除考虑肿瘤因素外,病人心肺等重要器官需有足够的功能储备以耐受手术。
肺癌手术方式首选解剖性肺叶切除和淋巴结清扫。但由于肿瘤或病人耐受性因素,又有扩大切除和局部切除。扩大切除,指需切除范围不仅局限于一个肺叶的术式,如双肺叶切除、支气管袖状肺叶切除术、肺动脉袖状肺叶切除术、一侧肺切除(全肺切除)、心包内处理肺血管和(或)合并部分左心房切除的全肺切除等。扩大切除的风险远高于标准肺叶切除,因此手术适应证的筛选宜谨慎。局部切除术,指切除范围小于一个肺叶的术式,包括肺段切除术和模形切除术。其优点是手术风险低,但与标准的肺叶切除相比局部复发率增加,主要用于非常早期的肺癌和耐受不良的老年病人。
目前常用的手术方法包括传统的开胸直视手术(经后外侧切口,胸部小切口等切口人胸)和胸腔镜手术(VATS)。VTAS仅用1~3个1~3cm长切口,替代传统开胸直视手术的20~30cm切口,创伤小,恢复快,且效果好,已成为我国肺癌外科治疗的主要手术方法。
** 肺癌/治疗/放射治疗 #card
:PROPERTIES:
:id: be6a28fe-a660-4b5a-8a1c-48ee3b2e48ef
:END:
*** 2.放射治疗 是肺癌局部治疗手段之一。对有纵隔淋巴结转移的肺癌,全剂量放射治疗联合化疗是主要的治疗模式;对有远处转移的肺癌,放射治疗一般用于对症治疗,是姑息治疗方法。一些早期肺癌病人,因高龄或心肺等重要器官不能耐受手术者,放射治疗也可作为一种局部治疗手段。手术后放射治疗用于处理术后的切缘残留或局部晚期的病例。 <span class="untestedHL">在各种类型的肺癌中,小细胞癌对放射疗法敏感性较高,鳞癌次之,>腺癌>细支气管肺泡癌。</span>
** 肺癌/治疗/化学治疗 #card
:PROPERTIES:
:id: 61c2d921-bc1f-416f-aee5-7af654bc2245
:END:
*** 3.化学治疗 肺癌的化学治疗分为新辅助化疗(术前化疗)、辅助化疗(术后化疗)和系统性化,疗。 <span class="untestedHL">肺癌的标准化疗方案是包含铂类药(顺铂或卡铂)的两药联合方案</span>。方案的选择取决于病理类型和病人情况。身体耐受差也可选择单药化疗。辅助化疗疗程一般是4个周期。
** 肺癌/治疗/靶向治疗 #card
:PROPERTIES:
:id: ef04cb49-13da-44d7-990e-8e2d3f52817c
:END:
*** 4.靶向治疗 针对肿瘤特有的和依赖的驱动基因异常进行的治疗称为靶向治疗。它具有针对性强、对该肿瘤具有较好的疗效,且副作用轻。 <span class="untestedHL">目前,在肺癌领域的得到应用的靶点主要有表皮生长因子受体(EGFR)、血管内皮生长因子(VEGF)和间变淋巴瘤激酶(ALK)等</span>。包括中国在内的 <span class="untestedHL">东亚肺腺癌病人群中,特别是女性、非吸烟者,EGFR基因突变比例超过50%,是最重要的治疗靶点。</span>
携带驱动基因异常的晚期肺癌病人接受靶向治疗的有效率和疾病控制时间远高于传统化疗,部分病人可长期生存。新一代靶向药物也在不断研发,覆盖更多的驱动基因,克服旧有药物的耐药,使病人获得更长的生存。
** 肺癌/治疗/免疫治疗 #card
:PROPERTIES:
:id: 81d84f3a-8d0c-4252-9073-a9f6ffb63657
:END:
*** 5.免疫治疗 主要针对抑制T细胞的程序性细胞死亡分子1(PD-1)及其受体(PD-L1)通路的单克隆抗体药物,可以纠正被肺癌细胞表达的PD-L1分子抑制的免疫反应,从而特异性杀伤肿瘤。 <span class="untestedHL">可使少数晚期病人可获得远期生存。</span>
**
*