#+title: 外科学/普通外科/肝疾病/教材/继发性肝癌,肝海绵状瘤,肝囊肿

* 本病又称继发性肝肿瘤（secondary tumor of the liver），包括转移性肝癌（metastatic cancer of the liv-
er）和转移性肝肉瘤（metastatic sarcoma of the liver）。原发肿瘤主要（57%）为结、直肠癌，胃癌，胰腺癌和胃、肠平滑肌肉瘤等；肺癌、乳腺癌、肾癌、宫颈癌、卵巢癌、前列腺癌和头颈部肿瘤等也可发生肝转移。
** 【分类】
*** 根据原发肿瘤与转移性肝肿瘤发生的时间关系，将转移性肝肿瘤分为3类：
*** ①早发类，病人先有转移性肝肿瘤的临床表现，或转移性肝肿瘤先被发现，之后才找到原发肿瘤；
*** ②同步类，同时发现原发肿瘤和转移性肝肿瘤；
*** ③迟发类，发现原发肿瘤或原发肿瘤手术切除数月至数年后才发生肝转移。
** 【临床表现及诊断】
*** 转移性肝肿瘤较小时，一般无症状，常在影像学检查时被发现。随着转移瘤增大，可出现上腹或肝区不适或隐痛；病情加重时，可出现乏力、发热、体重下降等；晚期病人可出现贫血、黄疸、腹水等。体检发现肝大，有时可触及坚硬的癌结节。超声、CT、MRI和PET等影像学检查有重要诊断价值。肿瘤标志物：AFP升高者较少；CEA、CA19-9、CA125等对消化系统、肺、卵巢等器官癌肿的肝转移具有诊断价值。
** 【治疗】
*** 对于单发的转移性肝肿瘤，最有效的治疗方法是肝切除。多发的转移性肝肿瘤是否行肝切除，存在争论。文献中有报告一次手术切除肝5个转移肿瘤，取得了较好的效果。手术原则：完全切除肿瘤（切缘距肿瘤>1cm），最大限度保留健康肝组织。
如为同步类，且原发癌和转移癌均可切除，可行同期手术切除，但术前要认真评估病人耐受手术的能力。对不适应手术切除的肝转移癌或术中发现不能手术切除者，根据病人全身及原发肿瘤情况，选用区域灌注化疗、微波固化、射频消融、冷冻及放射等局部治疗，部分病人治疗后转移癌缩小，肿瘤数目减少，可延长生存时间。
** 【预后】
*** 病人预后与原发癌的性质、发生肝转移的时间、原发和转移癌发现时的严重程度，肿瘤对药物治疗的敏感度，以及个体因素等有关。总体上，转移性肝癌手术切除后5年生存率为25%~46%
* 肝海绵状血管瘤（cavernous hemangioma of liver）
** 常见于中年女性，多为单发，也可多发；左、右肝的发生率大致相等。肿瘤生长缓慢，病程长达数年以上。瘤体较小时无任何临床症状，增大后主要表现为肝大或压迫胃、十二指肠等邻近器官，引起上腹部不适、腹胀、暖气、腹痛等症状。
** 体格检查：腹部肿块与肝相连，表现光滑，质地柔软，有囊性感及不同程度的压缩感，有时可呈分叶状。根据临床表现，超声、CT、MRI或肝动脉造影等检查，不难诊断。
** 手术切除是治疗肝海绵状血管瘤的最有效的方法。但小的、无症状的肝海绵状血管瘤不需治疗，可每隔6~12个月作超声检查，以动态观察其变化。如病人临床症状明显且影响正常生活和工作，或肿瘤直径>10cm，特别是位于肝缘，有发生外伤性破裂危险者，可行手术切除。通常沿肿瘤包膜外分离，完整地切除肿瘤，尽量不损伤正常的肝组织；如有必要，也可以做肝部分切除或解剖性肝切除术。
病变广泛分布在左右半肝而不能切除者，可行肝动脉结扎术。我国手术切除的最大一例肝海绵状血管瘤的体积为63cmx48.5cmx40cm，重达18kg。肝海绵状血管瘤最危险的并发症是肿瘤破裂引起的大出血，但极少发生。
** 其他良性肿瘤，如肝腺瘤、血管内皮瘤、胆管囊腺瘤、脂肪瘤、神经纤维瘤等，均少见。有效的治疗，方法是手术切除
* 肝囊肿
** 肝囊肿（cyst of liver）是较常见的肝良性疾病，分为寄生虫性（如肝棘球蚴病）和非寄生虫性肝囊肿；后者又可分为先天性、创伤性、炎症性和肿瘤性囊肿。临床多见的是先天性肝囊肿，它又可分为单发性和多发性两种。
*** 单发性肝囊肿以20~50岁年龄组多见，男女发生率之比为1：4；囊肿发生于肝右叶居多；囊肿小者直径仅数毫米，大者含液量>500ml，甚至可占据整个肝叶。
*** 多发性肝囊肿以40~60岁女性多见，囊肿大小不等，可分布于全肝，或局限于一段或一叶。震壁内层上皮细胞可因肝囊肿大小而不同，呈现为柱状、立方形、扁平状或缺如，外层为胶原样组织；
*** 囊液澄清透明，多不含胆汁。
** 先天性肝囊肿生长缓慢，小的囊肿常无任何症状，多系超声、CT等影像学检查或其他腹部手术中发现，囊肿增大到一定程度，则可因压迫邻近脏器而出现食后饱胀、恶心、呕吐、右上腹隐痛不适等症状。体格检查可能触及右上腹肿块和肝大，肿块与肝相连，表面光滑，带囊性感，无明显压痛而可随呼吸上下移动。
** 除上述临床表现外，超声检查是诊断肝囊肿的首选方法。
** CT，MRI检查可明确囊肿的大小、部位、形态和数目。
** 大的肝囊肿可因其所在部位不同，X线检查可显示隔肌拾高或胃肠受压移位等征象。多发性肝囊肿病人还应检查肾、肺、胰以及其他脏器有无囊肿（多囊病）或先天性畸形，并注意与先天性肝内胆管扩张症（Caroli's disease）相鉴别。
** 一般而言，无症状的肝囊肿病人，不需特殊处理。巨大而又出现症状者，可予以适当治疗。常用的方法是囊肿“开窗术”或“去顶术”，多在腹腔镜下完成该手术。即经腹腔镜切除部分囊壁，吸净囊液后使囊腔向腹腔开放。需行剖腹囊肿切除术或肝切除术的先天性肝囊肿病例现已极少。
对并发感染、囊内出血者，可在“开窗术”后放置引流，待引流液清亮、正常后拔除引流管。对囊液含有胆汁者，应寻找胆管漏口予以缝合，置管。必要时可行肝切除术。
多发性肝囊肿一般仅限于处理其中可能引起症状的大囊肿，可行囊肿“开窗术”，以缓解症状。对病变局限于肝的一段或一叶，且伴有症状，或开窗术效果不佳者，也可行病变肝段或肝叶切除术。