#+deck:外科学::外科学总论::输血::教材::输血的适应证和注意事项

* 适应症
** 输血的适应症/梗概 #card
:PROPERTIES:
:id: 624c4074-0a8b-4b35-93de-cddc60d18c2f
:END:
*** 大量失血
*** 贫血或低蛋白血症
*** 重症感染
*** 凝血异常
** 输血的适应症/大量失血 #card
:PROPERTIES:
:id: 624c40e7-e963-4cb9-821f-f6d64a4d5909
:END:
*** 大量失血 主要是补充血容量，用于治疗因手术、严重创伤或其他各种原因所致的低血容量 休克。补充的血量、血制品种类应根据失血量、速度和病人的临床表现确定。
*** 凡一次失血量低于总血 容量 10%(500ml)者， <span class="untestedHL">可通过机体自身代偿而无需输血。</span>
*** 当失血量达总血容量的 10%~20%( 500~1000ml)时，应根据有无血容量不足的临床症状及其严重程度，同时参照血红蛋白和血细胞比容(hematocrit, HCT) 的变化选择治疗方案。病人可表现为活动时心率增快，出现体位性低血压， <span class="untestedHL">但 HCT 常无 改变</span>。此时 <span class="untestedHL">可输入适量晶体液、胶体液或少量血浆代用品</span>。
*** 若失血量超过总血容量 20%（1000ml） 时,除有较明显的血容量不足、血压不稳定外，还可出现 HCT 下降。此时，除输人晶体液或胶体液补 充血容量外，还应适当输人浓缩红细胞( concentrated red blood cells, CRBC) 以提高携氧能力。 <span class="tested">原则上， 失血量在30%以下时，不输全血;超过30%时，可输全血与 CRBC 各半，再配合晶体和胶体液及血浆 以补充血容量。</span>由于晶体液维持血容量作用短暂，需求量大，故应增加胶体液或血浆蛋白量比例，以 维持胶体渗透压。
*** 当失血量超过50%且 <span class="untestedHL">大量输人库存血时，还应及时监测某些特殊成分如清蛋白 (白蛋白）、血小板及凝血因子有无缺乏，并给予补充。</span>
** 输血的适应症/贫血或低蛋白血症 #card
:PROPERTIES:
:id: 624c40e8-623f-4754-ab36-67228e415d0a
:END:
*** <span class="tested">贫血或低蛋白血症 常因慢性失血、烧伤、红细胞破坏增加或清蛋白(白蛋白）合成不足所致。 手术前应结合检验结果输注 CRBC 纠正贫血;补充血浆或白蛋白治疗低蛋白血症。</span>
** 输血的适应症/重症感染 #card
:PROPERTIES:
:id: 624c40ef-9d58-422e-b60c-5e15f79f6502
:END:
*** <span class="tested">重症感染 全身性严重感染或脓毒症、恶性肿瘤化疗后致严重骨髓抑制继发难治性感染者， 当其中性粒细胞低下和抗生素治疗效果不佳时，可考虑输人浓缩粒细胞以助控制感染。</span> <span class="untestedHL">但因输粒细 胞有引起巨细胞病毒感染、肺部合并症等副作用，故使用受到限制。</span>
** 输血的适应症/凝血异常 #card
:PROPERTIES:
:id: 624c40f3-01e7-422e-8a4f-a789860eff03
:END:
*** 凝血异常 输人 <span class="untestedHL">新鲜冰冻血浆以预防和治疗因凝血异常所致的出血</span>。根据引起凝血异常的 原因补充相关的血液成分可望获得良效，如甲型血友病者输湿因子或抗血友病因子(anti-hemophilia factor,AHF)；纤维蛋白原缺乏症者补充纤维蛋白原或冷沉淀制剂;血小板减少症或血小板功能障碍 者输血小板等。
** 输血的适应症/2000年卫生部输血指南建议 #card
:PROPERTIES:
:id: 624c442d-c7f9-4424-9f29-72e690869696
:END:
*** <span class="untestedHL">根据 2000 年卫生部输血指南建议：Hb>100g/L不需要输血;Hb<70g/L可输入浓缩红细胞；Hb为 70~100g/L时，应根据病人的具体情况来决定是否输血。对于可输可不输的病人应尽量不输。</span>
** 输血的适应症/血小板输入 #card
:PROPERTIES:
:id: 624c449e-927c-4139-ad44-a6f5cc8c5a78
:END:
*** 血小板输注用于病人血小板数量减少或功能异常伴有出血倾向或表现：血小板计数≥ <span class="untestedHL">100×10⁹/ L,可以不输；血小板计数<50×10⁹/L,应考虑输;血小板计数在(50~100）x10⁹/L之间，应根据是否有 自发性出血或伤口渗血决定;如术中出现不可控滲血，确定血小板功能低下，输血小板不受上述限制。</span>
** 输血的适应症/新鲜冰冻血浆输注 #card
:PROPERTIES:
:id: 624c4506-d532-48d1-be0c-942dbe2d236d
:END:
*** 新鲜冰冻血浆输注 <span class="untestedHL">用于凝血因子缺乏的病人</span>：PT或 APTT>正常值 1.5 倍， <span class="untestedHL">创面弥漫性渗血;</span>
*** 病人  <span class="untestedHL">急性大出血输人大量库存全血或浓缩红细胞后</span>(出血量或输血量相当于病人自身血容量);
*** 病史或临 床过程表现有 <span class="untestedHL">先天性或获得性凝血功能障碍；</span>
*** <span class="untestedHL">紧急对抗华法林的抗凝血作用。</span>
* 输血的注意事项 #card
:PROPERTIES:
:id: 624c40cc-569c-4679-8ae6-fbe78b3aeaec
:END:
** 输血前必须仔细核对病人和供血者姓名、血型和交叉配血单
** 并检查 <span class="untestedHL">血袋是否 滲漏，血液颜色有无异常及保存时间。</span>
** 除生理盐水外， <span class="untestedHL">不向血液内加人任何其他药物和溶液</span>，以免产生溶血或凝血。
** <span class="untestedHL">输血时应严密观察病人</span>,询问有无不适症状，检查体温、脉搏、血压及尿液颜色等，发 现问题及时处理。
** 输血完毕后仍需要观察病情，及早发现延迟型输血反应。 <span class="untestedHL">输血后血袋应保留 1天， 以便必要时化验检查。</span>