#+title: 外科学/普通外科/门静脉高压症/教材

* 定义
** 门静脉高压症（portal hypertension）是指各种原因导致门静脉血流受阻和（或）血流量增加所引起的门静脉系统压力增高，继而引起脾大和脾功能亢进，食管-胃底静脉曲张、呕血或黑便和腹水等。它不是一种单独的疾病，是一个综合征。门静脉正常压力13~24cmH₂0，平均值18cmH₂0，比肝静脉压力高5~9cmH₂0。门静脉压力大于25cmH₂O时即定义为门静脉高压，多数病例的门静脉压力可上升至30~50cmH₂0。
* 【解剖概要】
** 门静脉有别于体静脉的两大特点：
*** 门静脉系统位于两个毛细血管网之间，门静脉系统内没有瓣膜。
*** 门静脉主干是由肠系膜上、下静脉和脾静脉汇合而成，肠系膜上、下静脉和脾静脉由来自胃、肠、脾、胰的毛细血管网逐渐汇合而成。门静脉主干在近肝门处分为左、右两支分别进人左、右半肝后逐级分支，其小分支最终与肝动脉小分支的血流汇合于肝小叶内的肝窦（肝的毛细血管网），然后汇人肝小叶的中央静脉，再汇人小叶下静脉、肝静脉，最后汇人下腔静脉。
** 门静脉和肝动脉的小分支血流除了汇合于肝小叶内的肝窦，还在肝小叶间汇管区借着无数的动静脉间的交通支相互沟通。这种动静脉交通支一般仅在肝内血流量增加时才开放。正常人全肝血流量每分钟约为1500ml，其中门静脉血流量每分钟约为1125ml，占全肝血流量的60%~80%（平均75%）；肝动脉血流量约为375ml，占20%~40%（平均25%）。肝动脉的压力大，血的含氧量高，故门静脉和肝动脉对肝的供氧比例则几乎相等。
** 门静脉系与腔静脉系之间有四个交通支（图39-1），正常情况下都很细小、血流量都很少。
*** 1.胃底、食管下段交通支 门静脉血流经胃冠状静脉、胃短静脉，通过食管胃底静脉丛与奇静脉、半奇静脉的分支吻合，汇人上腔静脉。
*** 2.直肠下端、肛管交通支 门静脉血流经肠系膜下静脉、直肠上静脉与肛管静脉吻合、直肠下静脉吻合，流人下腔静脉。
*** 3.前腹壁交通支 门静脉（左支）的血流经脐旁静脉与腹上深静脉、腹下深静脉，分别汇人上、下腔静脉。
*** 4.腹膜后交通支 许多肠系膜上、下静脉分支与下腔静脉分支在腹膜后相互吻合。
* 病因
** 【病理生理】门静脉压力通过流入血流和流出阻力形成并维持。门静脉血流阻力增加，常是门静脉高压症的始动因素。按阻力增加的部位，可将门静脉高压症分为肝前、肝内和肝后三型。肝内型门静脉高压症又可分为窦前、窦后和窦型。
*** 肝前型门静脉高压症的常见病因有肝外门静脉血栓形成（脐炎、腹腔感染如急性阑尾炎和胰腺炎、创伤等）、先天性畸形（闭锁、狭窄或海绵样变等）和外在压迫（转移癌、胰腺炎等）。肝外门静脉阻塞的病人，肝功能多正常或轻度损害，预后较肝内型好。
*** 在我国，肝炎肝硬化是引起肝窦和窦后阻塞性门静脉高压症的常见病因。由于增生的纤维束和再生的肝细胞结节挤压肝小叶内的肝窦，使其变窄或闭塞，导致门静脉血流受阻，门静脉压力也就随之增高。其次是由于位于肝小叶间汇管区的肝动脉小分支和门静脉小分支之间的许多动静脉交通支，在肝窦受压和阻塞时大量开放，约为门静脉压力8~10倍的肝动脉血直接流入压力较低的门静脉小分支，使门静脉压力更加增高（图39-2）。
**** 肝内窦前阻塞性门静脉高压症的常见病因是血吸虫病。
*** 肝后型门静脉高压症的常见病因包括巴德-吉亚利综合征（Budd-Chiari syndrome）、缩窄性心包炎、严重右心衰竭等。
* 病理生理
** 上述各种情况引起门静脉高压持续存在后，可发生下列病理变化：
** 1.脾大（splenomegaly）、脾功能亢进（hypersplenism）门静脉压力升高后，脾静脉血回流受阻，脾窦扩张，脾髓组织增生，脾脏肿大。脾内血流在脾脏内的驻留时间延长，遭到脾脏吞噬细胞吞噬的机会增大。脾亢脾巨噬细胞吞噬功能增强，吞噬大量血细胞，导致外周血白细胞、血小板和红细胞减少，称为脾功能亢进。
** 2.交通支扩张 由于正常的肝内门静脉通路受阻，上述的四个交通支大量开放，并扩张、扭曲形成静脉曲张。其中最有临床意义的是在食管下段、胃底形成的曲张静脉。它离门静脉主干和腔静脉最近，压力差最大，因而经受门静脉高压的影响也最早、最显著。肝硬化病人常有胃酸反流，腐蚀食管下段黏膜引起反流性食管炎，或因坚硬粗糙食物的机械性损伤，以及咳嗽、呕吐、用力排便、重负等使腹腔内压突然升高，可引起曲张静脉破裂，导致致命性的大出血。其他交通支也可发生扩张，如直肠上、下静脉丛扩张可以引起继发性痔；脐旁静脉与腹上、下深静脉交通支扩张，可以引起前腹壁静脉曲张，典型的可形成“海蛇头”体征；腹膜后交通支的临床意义相对较小，但偶尔也有曲张破裂引起腹膜后血肿的报道。
** 3.腹水 门静脉压力升高，使门静脉系统毛细血管床的滤过压增加，同时肝硬化引起的低蛋白血症，血浆胶体渗透压下降及淋巴液生成增加，促使液体从肝表面、肠浆膜面漏入腹腔而形成腹水。门静脉高压症时门静脉内血流量增加，有效循环血量减少，继发刺激醛固酮分泌过多，加上慢性肝病时醛固酮、抗利尿激素等在肝内的灭活减少，导致钠、水猪留而加剧腹水形成。
** 在门静脉高压症时，胃壁淤血、水肿，胃黏膜下层的动-静脉交通支广泛开放，胃黏膜微循环发生障碍，导致胃黏膜防御屏障的破坏，形成门静脉高压性胃病（portal hypertensive gastropathy），发生率约20%，占门静脉高压症上消化道出血病例的5%~20%。此外，门静脉高压症时由于自身门体血流短路或手术分流，造成大量门静脉血流绕过肝细胞或因肝实质细胞功能严重受损，致使有毒物质（如氨、硫醇和y-基丁酸）进人体循环，从而对脑产生毒性作用并出现精神神经综合征，称为肝性脑病（hepatic eneephalopathy）。常因胃肠道出血、感染、过量摄入蛋白质、镇静药、利尿剂而诱发。
* 【临床表现】主要是脾大和脾功能亢进、呕血或黑便、腹水及非特异性全身表现（主要是肝功能不良的表现如疲乏、嗜睡、厌食、肝病面容、蜘蛛痣、肝掌、男性乳房发育、睾丸萎缩等）。
** 曲张的食管、胃底静脉一旦破裂，立刻发生急性大出血，呕吐鲜红色血液。
** 由于肝功能损害引起凝血功能障碍，又因脾功能亢进引起血小板减少，因此出血不易自止。
** 由于大出血引起肝组织严重缺氧，容易导致肝性脑病。
** 体检时如能触及脾，提示可能有门静脉高压症。如有黄疸、腹水和前腹壁静脉曲张等体征，表示门静脉高压症严重。如肝病属于早期，可以触到质地较硬、边缘较钝而不规整的肝，但临床更多见的是肝硬化致肝缩小而难以触到。
* 辅助检查
** 1.血常规 牌功能充进时，血细胞计数减少，以白细胞计数降至3x10°/L以下和血小板计数减少至（70~80）x10°/L以下最为多见。出血、营养不良、溶血或骨髓抑制都可以引起贫血。
** 2.肝功能检查常见血浆白蛋白降低而球蛋白增高，白、球蛋白比例倒置。由于许多凝血因子在肝合成，加上慢性肝病病人有原发性纤维蛋白溶解亢进，所以凝血酶原时间常有延长。还应作肝炎病原免疫学和甲胎蛋白检查。肝功能分级见表39-1。CT肝脏体积检测和吲噪菁绿排泄试验对肝功尤其是肝储备功能的评价有临床指导意义。
** 3.腹部超声 可以显示腹水、肝密度及质地异常、门静脉扩张、血管开放情况、门静脉与肝动脉血流量，门静脉系统有无血栓等。门静脉高压症时门静脉内径>1.3cm。
** 4.骨髓检查可以排除骨髓纤维化病人髓外造血引起的脾大，避免误切脾脏。还可评价牌切除术后病人三系细胞的恢复情况，
** 5.X线钡餐和内镜检查 食管在钡剂充盈时，曲张的静脉使食管的轮廓呈虫蚀状改变；排空时，曲张的静脉表现为虹蚓样或串珠状负影；钡剂进入胃、十二指肠中还可显示有无胃底静脉曲张、鉴别有无溃疡形成。但这些在内镜检查时更为明显。
** 6.CT，CT血管造影（CTA）或磁共振门静脉血管成像（MRPVG）可以了解肝硬化程度（包括肝体积）、肝动脉和脾动脉直径、门静脉和脾静脉直径、入肝血流，以及了解侧支血管的部位、大小及其范围。有助于指导手术方式的选择。手术切口和穿刺口需规避腹壁曲张静脉，尽可能保留天然分流通道。
* 治疗 主要是针对食管胃底曲张静脉破裂出血，脾大、脾功能亢进，顽固性腹水和原发肝病的治疗。
** 食管静脉曲张非手术治疗
:PROPERTIES:
:collapsed: true
:END:
*** （1）非手术治疗：适用于一般状况不良，肝功能较差，难以耐受手术的病人；手术前准备。
**** 1）补液、输血
***** 发生急性出血时，应尽快建立有效的静脉通道进行补液，监测病人生命体征。
***** 如出血量较大、血红蛋白小于70g/L时应同时输血，扩充有效血容量。维持血流动力学稳定并使血红蛋白水平维持在80g/L左右后，输血补液应缓慢进行，避免过量，防止门静脉压力反跳性增加而引起再出血。
**** 2）药物治疗：
***** ①止血：急性出血时首选血管收缩药。
****** 三甘氨酰赖氨酸加压素（特利加压素terlip-ressin，glypressin）：首剂 2mg静脉输注，然后2mg，每4小时1次。若出血控制可逐渐减量至1mg，每4小时1次。
****** 生长抑素（somatostatin）和它的八肽衍生物奥曲肽（octreotide）：生长抑素首次剂量250μg静注，以后250pg/h静脉持续点滴。奥曲肽首次剂量50pg静注，以后25~50ug/h静滴，推荐使用5天。药物治疗的早期再出血率较高，必须采取进一步的措施防止再出血。
****** β受体阻滞剂如普茶洛尔长期口服可预防出血。
***** ②预防感染：使用头抱类广谱抗生素。
***** ③其他：包括使用质子泵抑制剂抑制胃酸分泌、利尿、预防肝性脑病以及护肝治疗等。
**** 3）内镜治疗：有两种方法：
***** ①内镜下硬化治疗（endoscopic injection sclerotherapy，EIS）：经内镜将硬化剂（如鱼肝油酸钠）直接注射到曲张静脉腔内或曲张静脉旁的黏膜下组织，使曲张静脉闭塞，以治疗食管静脉曲张出血和预防再出血。主要并发症是食管溃疡、狭窄或穿孔，食管穿孔发生率虽然仅1%。但死亡率却高达50%。
***** ②内镜下食管静脉曲张套扎术（endoscopic esophageal varix ligation，EVL）：是经内镜将要结扎的曲张静脉吸人到结扎器中，用橡皮圈套扎在曲张静脉基底部。此方法与硬化治疗比，简单而且安全，公认是控制急性出血的首选方法。与药物治疗联合应用更为有效，成功率可达80%~100%。两种方法均需要反复多次进行，EIS间隔时间一般为7天，EVL间隔时间一般为10~14天。
**** 4）三腔管压迫止血：
***** 三腔管（图39-3）一腔通胃囊，充气后压迫胃底；一腔通食管囊，充气后压迫食管下段；一腔通胃腔，经此腔可行吸引、冲洗和注入止血药。Minnesota管还有第四个腔，用以吸引充气气囊以上口咽部的分泌物。原理是利用充气的气囊分别压迫胃底和食管下段的曲张静脉，以达止血目的。是紧急情况下暂时控制出血的有效方法，三腔管放置充气压迫一般不超过24小时，可使80%食管胃底曲张静脉出血得到控制，但约50%的病人排空气囊后会发生再次出血。并发症有吸入性肺炎、食管破裂及室息等，应注意预防。
**** 5）经颈静脉肝内门体分流术（transjugular intrahepatic port-osystemic shunt，TIPS）：
***** 是采用介人放射方法，经颈静脉途径在肝内肝静脉与门静脉主要分支间建立通道，置人支架以实现门体分流，TIPS的内支撑管的直径为8~12mm。TIPS可明显降低门静脉压力，用于治疗急性出血和预防再出血。
***** 适用于经药物和内镜治疗无效、外科手术后再出血以及等待肝移植的病人。
***** 应注意的是，TIPS后肝衰竭发生率为5%~10%，肝性脑病发生率高达20%~40%。还有，支撑管血栓形成而逐渐狭窄闭塞，影响分流效果，使用覆膜支架可降低栓塞率。
** 食管静脉曲张手术治疗
:PROPERTIES:
:collapsed: true
:END:
*** （2）手术治疗：适用于曾经或现在发生消化道出血，或静脉曲张明显和“红色征”出血风险较大，及一般情况尚可、肝功能较好（Child A级、B级），估计能耐受手术者。肝功能Child C级病人一般不主张手术，尽量采取非手术治疗。
**** 1）手术时机的选择：
***** 手术时机可以分为急诊手术、择期手术、预防手术。
***** 出血来势凶猛，出血量大；经过严格的内科治疗48小时内仍不能控制出血，或止血后24小时内再出血者，应急诊手术。但此时病情往往严重、多合并休克，急诊手术病死率较高。
***** 食管胃底曲张静脉一旦破裂引起出血，很有可能反复出血，而每次出血必将给肝带来损害，所以对于有过出血病史的病人应在充分术前准备下择期手术，不但可以防止再出血，也可减少肝性脑病的发生。
***** 对没有发生过出血者进行的手术，称为预防性手术。食管胃底静脉曲张不明显者，不主张做预防性手术；但如果同时伴有明显脾大、脾功能亢进者，为了消除脾亢同时有助于治疗肝病，可行预防性手术。食管胃底静脉重度曲张，特别是镜下见曲张静脉表面有“红色征”者，发生急性大出血的可能性较大，可考虑做预防性手术。
**** 2）手术方式的选择：门脉高压症手术方式较多，手术方式不外乎分为分流术、断流术及复合手术、肝移植[见后（四）肝脏原发病治疗]四大类。
***** A.分流术（portosystemic shunts）：通过在门静脉系统与腔静脉系统间建立分流通道、降低门静脉压力、达到止血效果的一类手术。优点：降压效果好、再出血率低。缺点：术后肝脏更加缺少门静脉血。供，对肝功不利，不适用于肝功能较差的病人；术后肝性脑病的发生率较高。因此对于有食管胃曲张静脉破裂出血（史）伴随有明显门静脉高压性胃病出血及断流术后再次出血者更为适用。分流术可再分为非选择性分流、选择性分流（包括限制性分流）两类：
****** a.非选择性门体分流术：是将入肝的门静脉血完全转流入体循环，代表术式是门静脉与下腔静脉端侧分流术[图39-4（1）]：将门静脉肝端结扎，防止肝内门静脉血倒流；门静脉与下腔静脉侧侧分流术[图39-4（2）]：离肝门静脉血流一并转流人下腔静脉，减低肝窦压力，有利于控制腹水形成。肠系膜上静脉与下腔静脉“桥式”（H形）分流术[图39-4（3）]和近端脾-肾静脉分流术：切除脾，将脾静脉近端与左肾静脉端侧吻合[图39-4（4）]。非选择性门体分流术治疗食管胃底曲张静脉破裂出血效果好，但肝性脑病发生率高达30%~50%，易引起肝衰竭。如破坏了第一肝门的结构，为日后肝移植造成了困难。
****** b.选择性门体分流术：旨在保存门静脉的人肝血流，同时降低食管胃底曲张静脉的压力。代表术式是远端脾-肾静脉分流术[图39-4（5）]，即将脾静脉远端与左肾静脉进行端侧吻合，同时离断门奇静脉侧支，包括胃冠状静脉和胃网膜静脉。该术式的优点是肝性脑病发生率低。但有大量腹水及脾静脉口径较小的病人，一般不选择这一术式。
限制性门体分流的目的是充分降低门静脉压力，制止食管胃底曲张静脉出血，同时保证部分人肝血流。代表术式是限制性门-腔静脉分流（侧侧吻合口控制在10mm）和门-腔静脉“桥式”（H形）分流（桥式人造血管口径为8~10mm）[图39-4（6）]。前者随着时间的延长，吻合口径可扩大，如同非选择性门体分流术；后者，近期可能形成血栓，需要取栓或溶栓治疗。
***** B.断流手术：断流术是指通过阻断门奇静脉间的反常血流，达到止血目的。
****** 缺点：术后门静脉高压仍较明显、再出血率高。
****** 优点：手术操作相对简单、创伤小，对肝脏门静脉血供影响较少，适应证宽，甚至肝功能Child C级的病人也能耐受，手术死亡率及并发症发生率低，术后生存质量高，易于在基层医院推广，在国内的临床应用最为广泛（85%）。
****** 断流手术的具体方式也很多，应用较多的有贲门周围血管离断术、胃周围血管缝扎术、食管下端横断术、胃底横断术以及食管下端胃底切除术等。
******* 在这些断流手术中，以牌切除加贲门周围血管离断术（splenectomy with paraesophagogastric devascularization）最为常用，不仅离断了食管胃底的静脉侧支，还保存了门静脉入肝血流。
******** 此术式适合于门静脉循环中没有可供与体静脉吻合的通畅静脉，既往分流手术和其他非手术疗法失败而又不适合分流手术、及需要行预防性手术的病人。
******** 在施行此手术时，了解责门周围血管的局部解剖十分重要[图39-5（1）]。责门周围血管可分成四组：
********* ①冠状静脉：包括胃支、食管支及高位食管支。胃支较细，沿着胃小弯走行，伴行着胃右动脉。食管支较粗，伴行着胃左动脉，在腹膜后注入脾静脉；其另一端在责门下方和胃支汇合而进入胃底和食管下段。高位食管支源自冠状静脉食管支的凸起部，距责门右侧3~4cm处，沿食管下段右后侧向上行走，于责门上方3~4cm或更高位处进入食管肌层。特别需要提，出的是，有时还出现“异位高位食管支”[图39-5（1）]，它与高位食管支同时存在，起源于冠状静脉主干，也可直接起源于门静脉左干，距贵门右侧更远，在责门以上5cm或更高位才进人食管肌层。
********* ②胃短静脉：一般为3~4支，伴行着胃短动脉，分布于胃底的前后壁，注入脾静脉。
********* ③胃后静脉：起始于胃底后壁，伴着同名动脉下行，注入脾静脉。
********* ④左膈下静脉：可单支或分支进人胃底或食管下段左侧肌层。门静脉高压症时，上述静脉都显著扩张，高位食管支的直径常达0.6~1.0cm，彻底切断上述静脉，包括高位食管支或同时存在的异位高位食管支，同时结扎、切断与静脉伴行的同名动脉，才能彻底阻断门奇静脉间的反常血流，这种断流术称为“责门周围血管离断术”[图39-5（2）]。腹腔镜下门奇静脉断流术除具有传统开腹的治疗效果外，尚可进一步减少出血和创伤。临床应用逐渐增多。
***** C.复合手术：复合手术结合选择性分流和断流手术特点，既保持一定的门静脉压力及门静脉向肝血流，又疏通门静脉系统的高血流状态，起到“断、疏、灌”的作用，初衷是达到相互取长补短的效果。但复合手术创伤和技术难度较大，且对病人肝功能要求高。
** 2.脾大、脾功能亢进
*** 门静脉高压症时脾功能处于素乱状态，会促进肝病的进展。脾切除是治疗脾功能亢进最有效的方法，而且能够降低门静脉压力，延缓肝病进展。几乎全部断流术及部分分流术均包含有脾切除术。脾射频消融术、脾动脉栓塞术治疗脾亢效果不确切，并发症多，主要适用于不愿手术或不能耐受手术的病人。
** 3.顽固性腹水
*** 是指腹水量较大、持续时间较长，经过正规的利尿、补充白蛋白等消腹水治疗无效的腹水。可采用腹腔穿刺外引流、TIPS、腹腔-上腔静脉转流术或腹水皮下转流术等治疗。如存在原发性腹膜炎加用抗生素则会起到更好效果。
** 4.原发肝病
*** 我国绝大多数门静脉高压症是病毒性肝炎肝硬化所致，肝功能损害多较严重，所以抗病毒及护肝治疗应贯彻于整个治疗过程。如果肝硬化严重，肝功能差而药物治疗不能改善者，应做肝移植，既替换了病肝，又使门静脉系统血流动力学恢复到正常，目前认为是最根本的治疗方法。
缺点是供肝短缺、终生服用免疫抑制剂、费用昂贵。
由上可见，门静脉高压症病人病因多样、病变复杂、治疗方法繁多、各有优缺点。为了提高治疗效果、改善病人预后，应根据具体情况选择科学合理的个体化治疗方案。
* 附：巴德-吉亚利综合征
* 巴德-吉亚利综合征也名布-加综合征。它指的是由肝静脉或其开口以上的下腔静脉阻塞引起的以门静脉高压或门静脉和下腔静脉高压为特征的一组疾病。
** 【病因】中国、日本、印度和南非大多由肝静脉以上的下腔静脉隔膜（大多属先天性）引起，少数由肝静脉隔膜引起。欧美则多由肝静脉血栓形成所致，与高凝状态，如真性红细胞增多症、抗凝血酶I缺乏、高磷脂综合征等有关。
** 【分型】按病变部位的不同分为三型：A型为局限性下腔静脉阻塞；B型为下腔静脉长段狭窄或阻塞；C型为肝静脉阻塞（图39-6）。
** 【诊断】病人早期有劳累后右上腹胀痛、肝脾大，发展期有腹水、双下肢水肿、胸腹
壁乃至腰背部静脉曲张及食管静脉曲张以至破裂出血。晚期病人腹大如鼓、骨瘦如柴，如“蜘蛛人”。凡双下肢水肿、腹胀或肝脾大者要高度怀疑此征。超声检查可发现肝静脉或其开口以上的下腔静脉阻塞。下腔和（或）B肝静脉造影可帮助确诊。此外，尚需明确该病的原发病因，如某种高凝状态。
** 【治疗】由急性肝、腔静脉血栓引起者，可用纤溶疗法，将诊断时所插人下腔静脉或肝静脉导管保留，经其进行纤溶疗法疗效显著。对A型病变首选球囊扩张和支架疗法（图39-7）；失败时可取经右心房和经股静脉病变穿破C和球囊扩张或行根治性矫正术。对B型病变可酌情选用下腔静脉-右心房、肠系膜上静脉-右心房、脾静脉-右心房和肠系膜上-颈内静脉转流术（图39-8）。C型病变可采用多种门体分流术。肝移植术只用于晚期病例。图39-6 巴德-吉亚利综合征分类