#+title: 外科学/普通外科/阑尾疾病/教材/急性阑尾炎

* 病因
** 【病因】阑尾易发生炎症是由其自身解剖特点决定的，其解剖结构为一细长盲管，腔内富含微生，物，肠壁内有丰富的淋巴组织，容易发生感染。一般认为阑尾炎有以下因素综合造成。
** 1.阑尾管腔阻塞 是急性阑尾炎最常见的病因。阑尾管腔阻塞的最常见原因是淋巴滤泡的明显增生，约占60%，多见于年轻人。肠石也是阻塞的原因之一，约占35%。异物、炎性狭窄、食物残渣、蛔虫、肿瘤等则是较少见的病因。阑尾管腔细，开口狭小，系膜短使阑尾蜷曲，这些都是造成阑尾管腔易于阻塞的因素。阑尾管腔阻塞后阑尾黏膜仍继续分泌黏液，腔内压力上升，血运发生障碍，使阑尾炎症加剧。
** 2.细菌入侵 由于阑尾管腔阻塞，细菌繁殖，分泌内毒素和外毒素，损伤黏膜上皮并使黏膜形成溃疡，细菌穿过溃疡的黏膜进人阑尾肌层。阑尾壁间压力升高，妨碍动脉血流，造成阑尾缺血，最终造成梗死和坏疽。致病菌多为肠道内的各种革兰阴性杆菌和厌氧菌。
** 3.其他阑尾先天畸形，如阑尾过长、过度扭曲、管腔细小、血运不佳等都是急性炎症的病因，胃肠道功能障碍引起内脏神经反射，导致肠管肌肉和血管疫李，黏膜受损，细菌人侵而致急性炎症。
**
* 急性阑尾炎/临床病理分型
** 【临床病理分型】根据急性阑尾炎的临床过程和病理解剖学变化，可分为四种病理类型。
1.急性单纯性阑尾炎 属轻型阑尾炎或病变早期。病变多只限于黏膜和黏膜下层。阑尾外观轻度肿胀，浆膜充血并失去正常光泽，表面有少量纤维素性渗出物。镜下，阑尾各层均有水肿和中性粒细胞浸润，黏膜表面有小溃疡和出血点。临床症状和体征均较轻。
** 2. 急性化脓性阑尾炎 亦称急性蜂窝织炎性阑尾炎，常由单纯性阑尾炎发展而来。阑尾肿胀明显，浆膜高度充血，表面覆以纤维素性（脓性）渗出物。镜下，阑尾黏膜的溃疡面加大并深达肌层和浆膜层，管壁各层有小脓肿形成，腔内亦有积脓。阑尾周围的腹腔内有稀薄脓液，形成局限性腹膜炎。临床症状和体征较重。
** 3. 坏疽性及穿孔性阑尾炎 是一种重型的阑尾炎。阑尾管壁坏死或部分坏死，呈暗紫色或黑色。阑尾腔内积脓，压力升高，阑尾壁血液循环障碍。穿孔部位多在阑尾根部和尖端。穿孔如未被包裹，感染继续扩散则可引起急性弥漫性腹膜炎。
** 4. 阑尾周围脓肿 急性阑尾炎化脓坏疽或穿孔，如果此过程进展较慢，大网膜可移至右下腹部，将阑尾包裹并形成粘连，形成炎性肿块或阑尾周围脓肿（periappendicular abscess）。急性阑尾炎的转归有以下几种：
*** ①炎症消退：一部分单纯性阑尾炎经及时药物治疗后炎症消退。大部分将转为慢性阑尾炎，易复发；
*** ②炎症局限化：化脓、坏疽或穿孔性阑尾炎被大网膜包裹粘连，炎症局限，形成阑尾周围脓肿。需用大量抗生素、中药，或两者联合治疗，治愈缓慢；
*** ③炎症扩散：阑尾炎症重，发展快，未予及时手术切除，又未能被大网包裹局限，炎症扩散，发展为弥漫性腹膜炎、化脓性门静脉炎、感染性休克等
* 急性阑尾炎/诊断/
** 症状
*** （1）腹痛：典型的腹痛发作始于上腹，逐渐移向脐部，数小时（6~8小时）后转移并局限在右下腹。此过程的时间长短取决于病变发展的程度和阑尾位置。约70%~80%的病人具有这种典型的转移性腹痛的特点。
**** 部分病例发病开始即出现右下腹痛。不同类型的阑尾炎其腹痛也有差异，如单纯性阑尾炎表现为轻度隐痛；化脏性阑尾炎呈阵发性胀痛和剧痛；坏疽性阑尾炎呈持续性剧烈腹痛；穿孔性阑尾炎因阑尾腔压力骤减，腹痛可暂时减轻，但出现腹膜炎后，腹痛又会持续加剧。
**** 不同位置的阑尾炎，其腹痛部位也有区别，如盲肠后位阑尾炎疼痛在右侧腰部，盆位阑尾炎腹痛在耻骨上区，肝下区阑尾炎可引起右上腹痛，极少数左下腹部阑尾炎呈左下腹痛。
*** （2）胃肠道症状：发病早期可能有厌食，恶心、呕吐也可发生，但程度较轻。有的病例可能发生腹泻。盆腔位阑尾炎，炎症刺激直肠和膀胱，引起排便、里急后重症状。弥漫性腹膜炎时可致麻痹性肠梗阻，腹胀、排气排便减少。
*** （3）全身症状：早期乏力。炎症重时出现中毒症状，心率增快，发热，达38℃左右。阑尾穿孔时体温会更高，达39℃或40℃。如发生门静脉炎时可出现寒战、高热和轻度黄疸。当阑尾化脓坏疽穿孔并腹腔广泛感染时，并发弥漫性腹膜炎，可同时出现血容量不足及败血症表理，甚至合并其他脏器功能障碍。
** 体征
*** 2.体征
（1）右下腹压痛： <span class="tested">是急性阑尾炎最常见的重要体征。压痛点通常位于麦氏点（图36-3），可随阑尾位置的变异而改变，但压痛点始终在一个固定的位置上。发病早期腹痛尚未转移至右下腹时，右下腹便可出现固定压痛。</span>压痛的程度与病变的程度相关。老年人对压痛的反应较轻。当炎症加重，压痛的范围也随之扩大。当阑尾穿孔时，疼痛和压痛的范围可波及全腹。但此时，仍以阑尾所在位置的压痛最明显。可用叩诊来检查，更为准确。也可嘱病人左侧卧位，体检效果会更好。
*** （2） <span class="tested">腹膜刺激征象：反跳痛（Blumberg征），腹肌紧张，肠鸣音减弱或消失等。这是壁腹膜受炎症刺激出现的防卫性反应。提示阑尾炎症加重，出现化脓、坏疽或穿孔等病理改变。</span>腹膜炎范围扩大，说明局部腹腔内有渗出或阑尾穿孔。但是，在小儿、老人、孕妇、肥胖、虚弱者或盲肠后位阑尾炎时，腹膜刺激征象可不明显。
*** （3）右下腹肿块：如体检发现右下腹饱满，扪及一压痛性，肿块，边界不清，固定，应考虑阑尾周围脓肿的诊断。
*** （4）可作为辅助诊断的其他体征
**** <span class="tested">1）结肠充气试验（Rovsing征）：病人仰卧位，用右手压迫图36-3 阑尾炎压痛点左下腹，再用左手挤压近侧结肠，结肠内气体可传至盲肠和阑尾，引起右下腹终痛者为阳性。</span>
**** <span class="tested">2）腰大肌试验（Psoas征）：病人左侧卧，使右大腿后伸，引起右下腹疼痛者为阳性。说明阑尾位十腰大肌前方，自肠后位或腹膜后位。</span>
**** <span class="tested">3）闭孔内肌试验（Obturator征）：病人仰卧位，使右畿和右大腿屈曲，然后被动向内旋转，引起右下腹疼痛者为阳性。提示阑尾靠近闭孔内肌。</span>
**** 4）经肛门直肠指检：引起炎症阑尾所在位置压痛。 <span class="untestedHL">压痛常在直肠右前方。当阑尾穿孔时直肠前壁压痛广泛。当形成阑尾周围脓肿时，有时可触及痛性肿块。</span>
** 实验室检查
** 影像学检查
** 腹腔镜检查
* 诊断注意事项
** <span class="untestedHL">①诊断急性阑尾炎最有意义的临床症状是转移性右下腹疼痛，最有意义的体征是右下腹固定性压痛。其阳性意义大于腰大肌试验、闭孔内肌试验、结肠充气试验阳性。</span>
** <span class="untestedHL">②病程较长的急性阑尾炎，可发展为阑尾周围脓肿，解题时应注意此知识点。</span>
** <span class="untestedHL">③阑尾炎炎症可经阑尾静脉→回结肠静脉→门静脉→肝脏，故急性阑尾炎可引起门静脉炎、肝脓肿。</span>
* <span class="tested">急性阑尾炎的并发症</span>
** （1） <span class="tested">腹腔脓肿</span> .<span class="untestedHL">是阑尾炎未经及时治疗的后果。在阑尾周围形成的阑尾周围脓肿最常见</span>，也可在腹腔其他部位形成脓肿，常见部位有盆腔、隔下或肠间隙等处。临床表现有 <span class="untestedHL">麻痹性肠梗阻的腹胀症状、压痛性肿块和全身感染中毒症状等</span>。超声和CT扫描可协助定位。 <span class="untestedHL">一经诊断即应在超声引导下穿刺抽旅冲洗或置管引流，或必要时手术切开引流</span>。由于炎症粘连较重，切开引流时应小心防止副损伤，尤其注意肠管损伤。中药治疗阑尾周围脓肿有较好效果，可选择应用。 <span class="untestedHL">阑尾脓肿非手术疗法治愈后其复发率很高。因此应在治愈后3个月左右择期手术切除阑尾，相比急诊手术效果好。</span>
** （2） <span class="tested">内、外痿形成</span> <span class="untestedHL">阑尾周围脓肿如未及时引流，少数病例脓肿可向小肠或大肠内穿破，亦可向膀胱、阴道或腹壁穿破，形成各种内痿或外痿</span>，此时脓液可经接管排出。 <span class="untestedHL">X线钡剂检查或者经外痿置管造影可协助了解瘘管走行，有助于选择相应的治疗方法。</span>
** （3） <span class="tested">化脓性门静脉炎</span>（pylephlebitis）急性阑尾炎时阑尾静脉中的感染性血栓， <span class="untestedHL">可沿肠系膜上静脉至门静脉，导致化脓性门静脉炎症</span>。临床表现为寒战、高热、肝大、剑突下压痛、轻度黄疸等。虽属少见， <span class="untestedHL">如病情加重会产生感染性休克和脓毒症，治疗延误可发展为细菌性肝脓肿</span>。行阑尾切除并大剂量，抗生素治疗有效。
* 治疗与手术并发症
** <span class="untestedHL">（1）非手术治疗 适用于单纯性阑尾炎、急性阑尾炎的早期、其他严重器质性疾病禁忌手术者。</span>
** <span class="untestedHL">（2）手术治疗 适用于大多数阑尾炎的治疗。</span>
** <span class="untestedHL">（3）阑尾切除术并发症 腹腔内出血（最严重）、切口感染（最常见）、粘连性肠梗阻、阑尾残株炎、粪痿。</span>
*