#+title: 外科学/普通外科/阑尾疾病/教材/特殊类型阑尾炎

* 一般成年人急性阑尾炎诊断多无困难，早期治疗的效果非常好。如遇到婴幼儿、老年人及妊娠妇女患急性阑尾炎时，诊断和治疗均较困难，值得格外重视，
:PROPERTIES:
:id: 625547eb-9553-4982-a4e3-afe975c8390d
:END:
* 1.新生儿急性阑尾炎 新生儿阑尾呈漏斗状，不易发生由淋巴滤泡增生或者肠石所致阑尾管腔阻塞。因此，新生儿急性阑尾炎很少见。又由于新生儿不能提供病史，其早期临床表现又无特殊性，仅有厌食、恶心、呕吐、腹泻和脱水等，发热和白细胞升高均不明显，因此术前难以早期确诊，穿孔率可，高达80%，死亡率也很高。诊断时应仔细检查右下腹部压痛和腹胀等体征，并应早期手术治疗。
:PROPERTIES:
:id: 6255483f-35ee-4e41-ba80-59de4c994653
:END:
* <span class="tested">2.小儿急性阑尾炎 小儿大网膜发育不全，不能起到足够的保护作用。病儿也不能清楚地提供病史。其临床特点：</span>
:PROPERTIES:
:id: 6255483d-430c-4646-8474-c5837cbccfe2
:END:
** <span class="tested">①病情发展较快且较重，早期即出现高热、呕吐等症状；</span>
:PROPERTIES:
:id: 6255486f-a680-427c-a4f2-b5fd4a8911b5
:END:
** <span class="tested">②右下腹体征不明显、不典型，但有局部压痛和肌紧张，是小儿阑尾炎的重要体征；</span>
:PROPERTIES:
:id: 62554871-93c4-46d8-8742-c5b67d57d450
:END:
** <span class="tested">③穿孔率较高，并发症和死亡率也较高。诊断小儿急性阑尾炎须仔细耐心，取得病儿的信赖和配合，再经轻柔的检查，左、右下腹对比检查，仔细，观察病儿对检查的反应，作出判断。治疗原则是早期手术，并配合输液、纠正脱水，应用广谱抗生素等。</span>
:PROPERTIES:
:id: 62554875-e1f0-4f1d-8cd4-cc6ba11ebefc
:END:
* 3.妊娠期急性阑尾炎 较常见。尤其妊娠中期子宫的增大较快，盲肠和阑尾被增大的子宫推挤向右上腹移位，压痛部位也随之上移。腹壁被抬高，炎症阑尾刺激不到壁腹膜，所以使压痛、肌紧张和反跳痛均不明显；大网膜难以包裹炎症阑尾，腹膜炎不易被局限而易在腹腔内扩散。这些因素致使妊娠中期急性阑尾炎难以诊断，炎症发展易致流产或早产，威胁母子生命安全。
:PROPERTIES:
:id: 6255482e-2dba-4a27-ae30-066fdd77a317
:END:
** <span class="tested">治疗以早期阑尾切除术为主。妊娠后期的腹腔感染难以控制，更应早期手术。围术期应加用黄体酮。手术切口需偏高，操作要轻柔，以减少对子宫的刺激。尽量不用腹腔引流。术后使用广谱抗生素。加强术后护理。临产期的急性阑尾炎如并发阑尾穿孔或全身感染症状严重时，可考虑经腹剖宫产术，同时切除病变阑尾。</span>
:PROPERTIES:
:id: 6255488a-5ab7-430a-99a7-e862c77de35b
:END:
* 4.老年人急性阑尾炎 随着社会老龄人口增多，老年人急性阑尾炎的发病率也相应升高。因老年人对疼痛感觉迟钝，腹肌薄弱，防御功能减退，所以主诉不强烈，体征不典型，临床表现轻而病理改变却很重，体温和白细胞升高均不明显，容易延误诊断和治疗。又由于老年人动脉硬化，阑尾动脉也会发生改变，易导致阑尾缺血坏死。加之老年人常伴发心血管病、糖尿病、肾功能不全等，使病情更趋复杂严重。
:PROPERTIES:
:id: 62554831-d8c2-42c8-a294-de0994701ae1
:END:
* 5.AIDS/HIV感染病人的阑尾炎 其临床症状及体征与免疫功能正常者相似，但不典型，此类病人WBC不高，常被延误诊断和治疗。超声或CT检查有助于诊断。阑尾切除术是主要的治疗方法，强调早期诊断并手术治疗，可获较好的短期生存，否则穿孔率较高（占40%）。因此，不应将AIDS和HIV感染者视为阑尾切除的手术禁忌证。
:PROPERTIES:
:id: 62554832-975d-4d5f-8166-24e1ddeddba1
:END: