#+title: 外科学/普通外科/结直肠与肛管疾病/教材/直肠癌

* 直肠癌/定义
** <span class="tested">直肠癌（carcinoma of the rectum）以腹膜返折为界分为上段直肠癌和下段直肠癌，也可分为低位直肠癌（距肛缘5cm以内）、中位直肠癌（距肛缘5~10cm）和高位直肠癌（距肛缘10cm以上），以肿瘤下，缘确定位置。</span>
** 中国人直肠癌与西方人比较，有两个流行病学特点：
** <span class="tested">①直肠癌比结肠癌发生率高，大约占60%；最近的资料显示结肠癌和直肠癌发生率逐渐靠近，有些地区已接近1：1，主要是结肠癌发生率增高所致；</span>
** <span class="tested">②低位直肠癌所占的比例高，约占直肠癌的60%~70%，绝大多数癌肿可在直肠指诊时，触及。</span>
** 上段直肠癌的细胞生物学行为与结肠癌相似，根治性切除术后5年总生存率与结肠癌也相近，中低位直肠癌在50%左右。
* 直肠癌/扩散与转移
** 1.直接浸润 癌肿首先直接向肠壁深层浸润性生长，向肠壁纵轴浸润发生较晚。 <span class="untestedHL">癌肿浸润肠壁-圈约需1.5~2年。</span>直接浸润可穿透浆膜层侵入邻近脏器如子宫、膀胱等，下段直肠癌由于缺乏浆膜层的屏障作用，易向四周浸润，侵入附近脏器如前列腺、精囊腺、阴道、输尿管等。
** <span class="tested">2.淋巴转移是主要的扩散途径</span>
*** <span class="untestedHL">上段直肠癌向上沿直肠上动脉、肠系膜下动脉及腹主动脉周围淋巴结转移。发生逆行性转移的现象非常少见。如淋巴液正常流向的淋巴结发生转移且流出受阻时，可逆行向下转移。</span>
*** <span class="untestedHL">下段直肠癌（以腹膜返折为界）向上方和侧方转移为主。大宗病例报道（1500例）发现肿瘤下缘平面以下的淋巴结阳性者98例（6.5%）；平面以下2cm仍有淋巴结阳性者仅30例（2%）。齿状线周围的癌肿可向上、侧、下方转移。向下方转移可表现为腹股沟淋巴结肿大。</span>
** <span class="untestedHL">3.血行转移 癌肿侵人静脉后沿门静脉转移至肝；也可由髂静脉转移至肺、骨和脑等。直肠癌手术时约有10%~15%的病例已发生肝转移；直肠癌致肠梗阻和手术时的挤压，易造成血行转移，</span>
** <span class="untestedHL">4.种植转移 直肠癌种植转移的机会较小，上段直肠癌可发生种植转移</span>
** 直肠癌/症状
*** 1.直肠刺激症状 <span class="untestedHL"> 便意频繁，排便习惯改变；便前肛门有下坠感、里急后重、排便不尽感，晚期有下腹痛。</span>
*** 2.癌肿破溃出血症状   <span class="untestedHL">大便表面带血及黏液，甚至有脓血便。</span>
*** 3.肠腔狭窄症状   <span class="untestedHL">癌肿侵犯致肠管狭窄，初时大便进行性变细，当造成肠管部分梗阻后，有腹痛、腹胀、肠鸣音亢进等不全性肠梗阻表现。</span>
*** 4.癌肿侵犯周围组织或转移远处器官引起相应症状  <span class="untestedHL">侵犯前列腺、膀胱，可出现尿频、尿痛、血尿。侵犯阴道，可出现阴道异常分泌物。侵犯骶前神经可出现骶尾部剧烈持续性疼痛</span>
*** 局部症状出现的频率依次为： <span class="untestedHL">便血80%~90%、便频60%~70%、便细40%、黏液便35%、肛门痛20%、里急后重20%、便秘10%</span>
** 直肠癌/体征
*** <span class="tested">1.直肠指诊触及肿物 60%~70%能在直肠指诊时触及；因此，直肠指诊是诊断低位直肠癌最重要的体格检查，凡遇直肠刺激症状、便血、大便变细等均应采用</span>
指诊应记录肿物的方位、大小、硬度、形状与肛缘的距离以及指套染血情况。有经验的外科医师能从肿物的固定程度判断其深度：容易和黏膜一起被推动的提示未浸润至肌层； <span class="untestedHL">尚能与肠壁一起被推动的提示已浸润肌层、但未穿透肠壁；固定于盆腔的提示已累及肠壁外周围结构。如果肿瘤位于前壁，男性病人应注意肿物与前列腺的关系，女性病人应注意与阴道的关系，必要时经阴道指诊明确。</span>
*** 2.腹股沟淋巴结肿大  <span class="untestedHL">由于齿状线上下淋巴引流的不同特点，直肠癌罕见转移到腹股沟淋巴结。腹股沟淋巴结肿大多见于累及齿状线以下的直肠癌，提示肿瘤可能含有鳞癌成分。</span>
*** <span class="untestedHL">3.并发症或晚期体征 肠梗阻可表现为腹部膨隆、肠鸣音亢进；肝转移可表现为肝大、黄疸、移动性浊音；晚期可表现为营养不良或恶病质。</span>
** 直肠癌/辅助检查
*** 1.实验室检查 与结肠癌类似，直肠癌 <span class="untestedHL">没有敏感而且特异的实验室检查。</span>
大便潜血：由于其经济性可作为 <span class="untestedHL">结、直肠癌的初筛手段</span>，阳性者再作进一步检查。
肿瘤标记物：癌胚抗原（carcinoembryonic antigen，CEA）缺乏对早期结、直肠癌的诊断价值，仅45%的结、直肠癌病人初诊时升高。大量研究表明结、直肠癌病人的血清CEA水平与肿瘤分期呈正相关Ⅰ,Ⅱ、Ⅲ、IV期的血清CEA阳性率分别约为25%、45%、75%和85%，因此CEA <span class="untestedHL">主要用于评估肿瘤负荷和监测术后复发。CA19-9的临床意义与CEA相似</span>。
*** 2.内镜检查 根据检查范围不同分为肛门镜、乙状结肠镜和结肠镜。门诊常规检查时可用肛门镜检查，操作方便、不需肠道准备，乙状结肠镜在中国使用较少。结肠镜在肠道准备充分的情况下可以观察自肛门至回盲部的全部大肠，并可早期处理癌前病变（如腺瘤）和定期筛查结直肠癌，大约使肠癌的发病率降低56%，死亡率降低66%，这种保护作用至少持续17~22年。由于多数肠癌在50岁以后发生，推荐50岁接受第一次结肠镜，有肠癌家族史的提前到40岁。结肠镜通过活检取得病理学诊断，是制订治疗方案的依据。已诊断的直肠癌在手术治疗前也必须行结肠镜检查，因为结、直肠癌有5%~10%为多发癌。术前梗阻无法行结肠镜的，术后6个月内应检查梗阻近端以排除多源癌。
*** 3.影像学检查 直肠癌获得病理诊断以后需要进一步评估临床分期，用于评估预后和制订治疗方案。
（1）直肠腔内超声：通过将超声探头置入直肠，可以清晰分辨五层回声信号。对5000多例直肠癌的荟萃分析显示， <span class="untestedHL">腔内超声对T分期的敏感性为81%~96%，特异性为91%~98%</span>。
（2）盆腔增强MRI：不但能评估肿瘤浸润肠壁深度、淋巴结是否转移，更 <span class="untestedHL">重要的是能准确分辨直，肠系膜筋膜是否受累。</span>
（3）胸腹盆增强CT：主要用于评估多发于肝、肺的远处转移。肝、肺多数大于1cm的病变可以通过CT准确判定是否转移。盆腔CT对软组织的分辨能力不如MRI。
（4）全身PET-CT：主要被推荐用于2种情况： <span class="untestedHL">①已有淋巴结转移的结直肠癌；②术后检查怀疑复发转移。</span>