#+title: 外科学/外科学总论/代谢及营养治疗/教材/外科病人的代谢变化
#+deck: 外科学::外科学总论::代谢及营养治疗::教材::外科病人的代谢变化

* 正常情况下的物质代谢/梗概 
:PROPERTIES:
:id: 624e7b5f-e81e-447e-a244-0164938b4897
:END:
** 正常生命活动中需要不断摄取各种营养物质，通过转化和利用以维持机体新陈代谢。食物中碳水化合物、脂肪、蛋白质、水、电解质、微量元素和维生素等营养底物进入人体后，参与体内一系列代谢过程，通过合成代谢使人体结构得以生长、发育、修复及再生，并为机体生命活动提供必不可少的能源。
** 碳水化合物
** 蛋白质
** 脂肪
* 正常情况下的物质代谢/梗概
:PROPERTIES:
:collapsed: true
:END:
** 正常情况下的物质代谢/碳水化合物  
:PROPERTIES:
:id: 33242d90-9da5-4e19-b009-23005148bf62
:END:
#+BEGIN_QUOTE
碳水化合物供能约多少,哪些组织或器官完全靠葡萄糖供能
#+END_QUOTE
*** 1.碳水化合物  <span class="untestedHL">主要生理功能是供能,同时也是细胞结构的重要成分</span>。正常情况下, <span class="untestedHL">碳水化合物提供约55%~65%维持成人机体正常功能所需的能量</span>, <span class="untestedHL">机体一些组织器官如大脑神经细胞、肾上腺及血细胞等则完全依赖葡萄糖氧化供能</span>。食物中碳水化合物经消化道消化、吸收后以葡萄糖、糖原及含糖复合物形式存在。碳水化合物在体内代谢过程主要体现为葡萄糖的代谢,正常情况下,进入和移出血液中的葡萄糖处于相对平衡状态,使血糖维持在4.5~5.5mmol/L水平。血糖来源于食物中糖的消化和吸收、肝糖原分解或肝脏糖异生作用;血糖去路则为周围组织及肝脏摄取利用、糖原合成、转化为非糖物质或其他含糖物质。血糖水平保持恒定是糖、脂肪、氨基酸代谢协调的结果,也是肝脏、肌肉、脂肪组织等器官组织代谢协调的结果。
** 正常情况下的物质代谢/蛋白质  
:PROPERTIES:
:id: a16ce910-71f4-4bc3-b7e9-64df41aa2e7d
:END:
#+BEGIN_QUOTE
主要作用是什么
#+END_QUOTE
*** 2.蛋白质  <span class="untestedHL">是构成生物体的重要组成成分,在生命活动中起着极其重要作用。蛋白质主要生理功能是参与构成各种细胞组织,维持细胞组织生长、更新和修复,参与多种重要生理功能及氧化供能。</span>食物中蛋白质是人体蛋白质的主要来源,在蛋白酶及肽酶的作用下水解成为寡肽及氨基酸而被吸收。正常情况下机体内各种蛋白质始终处于动态更新之中,蛋白质的更新包括蛋白质分解和合成代谢,其合成和降解的相互协调对维持机体组织、细胞功能、调节生长及控制体内各种酶的生物活性起着十分重要作用。
** 正常情况下的物质代谢/脂肪  
:PROPERTIES:
:id: fca246b9-393d-48f4-86ca-3402d1845ab7
:END:
#+BEGIN_QUOTE
主要生理功能是什么,短链和中链脂肪酸构成的甘油三酯怎么吸收,长链呢,
#+END_QUOTE
*** <span class="untestedHL">主要生理功能是提供能量、构成身体组织、供给必需脂肪酸并携带脂溶性维生素等</span>。膳食中脂类是人体脂肪的主要来源,脂类不溶于水,在消化道中经胆汁酸盐、胰脂酶、磷脂酶A2、胆固醇脂酶等作用下消化形成甘油一酯、脂肪酸、胆固醇、溶血磷脂等,乳化成更小的微团后被消化酶消化。 <span class="untestedHL">短链和中链脂肪酸构成的甘油三酯,经胆汁酸盐乳化后即可被吸收。</span>在肠黏膜细胞内脂肪酶的作用下，水解成脂肪酸及甘油，通过门静脉进入血液循环。 <span class="untestedHL">长链脂肪酸构成的甘油三酣与磷脂、胆固醇及载脂蛋白结合形成乳廉微粒，通过淋巴进入血液循环</span>。
*** 甘油三酯是机体储存能量的形式。
* 能量代谢/机体能量组成,测定及其计算 
:PROPERTIES:
:id: 624e7f18-62e7-4d32-8fc7-032c7a7dc121
:END:
** 基础能量消耗
*** 机体每日的能量消耗 <span class="untestedHL">包括基础能量消耗（或静息能量消耗）、食物的生热效应、兼性生热作用、活动的生热效应几个部分</span>，其中 <span class="untestedHL">基础能量消耗在每日总能量消耗所占比例最大（60%～70%）</span>，是机体维持正常生理功能和内环境稳定等活动所消耗的能量。由于测定基础代谢率的要求十分严格，因此，临床实践中通常测定机体静息能量消耗而非基础能量消耗
*** #+BEGIN_QUOTE
可按 Haris-Benedict 公式计算。
男性 BEE（kcal/d）=66+13.7W+5.0H-6.8A;女性 BEE（kcal/d）=655+9.6W+1.85H-4.7A
其中，W为体重（kg），H为身高（cm），A为年龄（年）。
#+END_QUOTE
** 静息能量消耗
*** ((624e810e-b43d-4763-94cf-27e9d8aba66a))
** 两者之差
*** <span class="untestedHL">Harris-Benedict公式是健康机体基础能量消耗估算公式,临床上各种疾病状态下病人的实际静息能量消耗值与Harris-Benedict公式估算值之间存在一定的差异,如择期手术约增加10%左右,严重创伤、多发性骨折、感染时可增加20%~30%,大面积烧伤时能量消耗增加最明显,最大可增高100%左右。</span>
* 能量代谢/机体能量需要量的测定  
:PROPERTIES:
:id: 624e811e-d67d-4ba4-9059-963053c4ac06
:END:
#+BEGIN_QUOTE
日常能量需求是多少
#+END_QUOTE
** 准确的能量供给与营养疗效和临床结局直接相关,能量摄人不足可造成机体蛋白质消耗,影响器官结构和功能,从而影响病人预后。尽管间接测热法测定机体静息能量消耗值是判断病人能量需要量理想的方法,但临床上大多数病人尚无法实时测量机体的能量消耗值,较多的仍然是应用预测公式或凭经验估计来确定病人的能量需求。
** <span class="tested">目前认为,对于非肥胖病人25~30kcal/(kg. d)能满足大多数住院病人的能量需求,而BMI>30kg/m的肥胖病人,推荐的能量摄人量为正常目标量的70%~80%。</span>
* 饥饿时机体代谢改变 
:PROPERTIES:
:id: 624e8151-15bf-4fc8-8fe6-4611ff672610
:END:
** 源性能量底物和营养物质缺乏是整个饥饿反应的基础，饥饿时机体正常代谢途径可能部分或全部停止，一些途径则被激活或出现新代谢途径。饥饿时机体生存有赖于利用自身储存的脂肪、糖原及细胞内的功能蛋白，
** 饥饿早期， <span class="untestedHL">机体首先利用肝脏及肌肉中的糖原储备消耗以供能直至糖原耗尽然后再依赖糖异生作用</span>。此时，机体能量消耗下降，肝脏及肌肉蛋白分解以提供糖异生前体物质，蛋白质合成下降。
** 随后， <span class="untestedHL">脂肪动员增加成为主要能源物质，体内酮体形成及糖异生作用增强，大脑及其他组织越来越多利用酮体作为能源</span>，从而减少了骨髓肌蛋白分解程度，其 <span class="untestedHL">目的是尽可能地保存机体的蛋白质，使生命得以延</span>续。
* 创伤应激状态下机体代谢变化  
:PROPERTIES:
:id: 624e82fd-775f-4799-a6a3-09fd6d2c21c4
:END:
#+BEGIN_QUOTE
糖,蛋白质,脂肪如何变化
#+END_QUOTE
** <span class="tested"> 外科感染、手术创伤等应激情况下,机体发生一系列代谢改变,其特征为静息能量消耗增高、高血糖及蛋白质分解增强。</span>
** 应激状态时碳水化合物代谢改变主要表现为
*** <span class="tested">内源性葡萄糖异生作用明显增加</span>
*** <span class="tested">组织、器官葡萄糖的氧化利用下降以及外周组织对胰岛素抵抗,从而造成高血糖。</span>
** 创伤后蛋白质代谢变化是
*** <span class="tested">蛋白质分解增加、负氮平衡,其程度和持续时间与创伤应激程度、创伤前营养状况、病人年龄及应激后营养摄入有关,并在很大程度上受体内激素反应水平的制约。</span>
** 脂肪是应激病人的重要能源, <span class="tested">创伤应激时机体脂肪分解增强,其分解产物作为糖异生作用的前体物质,从而减少蛋白质分解,保存机体蛋白质。</span>