#+deck: 外科学::普通外科::腹部损伤::教材::概论

*
* 腹部损伤/【分类】 #card
:PROPERTIES:
:id: 62538403-36e0-4b60-bc4a-55e49da6d840
:END:
** 根据损伤是否穿透腹壁以及腹腔是否与外界相通,腹部损伤可分为开放性和闭合性两大类。
*** <span class="tested">开放性损伤有腹膜破损者为穿透伤(多伴内脏损伤),无腹膜破损者为非穿透伤(可伴内脏损伤)</span>;其中投射物有入口、出口者为贯通伤,有入口无出口者为盲管伤。
*** <span class="untestedHL">闭合性损伤可能仅局限于腹壁,也可同时兼有内脏损伤。</span>
** 此外,穿刺、内镜、灌肠、刮宫、腹部手术等各种诊疗措施导致的腹部损伤称医源性损伤。开放性损伤即使涉及内脏,其诊断常较明确; <span class="untestedHL">但闭合性损伤体表无伤口,要确定有无内脏损伤,有时很困难,故其临床意义更为重要。</span>
* 腹部损伤/病因 #card
:PROPERTIES:
:id: 62538481-ad85-490d-9beb-0ad42dbb6d85
:END:
** 【病因】开放性损伤常由刀刃、枪弹、弹片等利器所引起,闭合性损伤常系坠落、碰撞、冲击、挤压、拳打脚踢、棍棒等钝性暴力所致。无论开放或闭合伤,都可导致腹部内脏损伤。 <span class="untestedHL">开放性损伤中常见的受损内脏依次是肝脏、小肠、胃、结肠、大血管等</span>;
** 闭合性 <span class="untestedHL">损伤中依次是脾脏、肾脏、小肠、肝脏、肠系膜等</span>。胰腺、十二指肠、隔、直肠等由于解剖位置较深,损伤发生率较低。
** 腹部损伤的严重程度,是否有内脏伤,以及涉及什么内脏等情况,在很大程度上取决于暴力的强度、速度、着力部位和作用方向等因素,还受解剖特点和内脏原有病理情况和功能状态等内在因素的影响。例如,肝和牌组织结构脆弱,血供丰富,位置比较固定,受到暴力打击容易导致破裂;上腹受挤压时,胃窦、十二指肠第三部或胰腺可因被压在脊柱上而导致断裂;肠道的固定部分(上段空肠、末段回肠、粘连的肠管等)比活动部分更易受损;充盈的空腔脏器(饱餐后的胃、未排空的膀胱等)比空虚时更易破裂。
* 腹部损伤/临床表现   #card
:PROPERTIES:
:id: 62538491-f723-4805-ab87-c8c06fc3966a
:END:
#+BEGIN_QUOTE
差异很大,实质性脏器损伤,空腔脏器损伤?
#+END_QUOTE
** 【临床表现】由于致伤原因及伤情的不同, <span class="untestedHL">腹部损伤后的临床表现差异极大</span>,从无明显症状和体征到出现重度休克甚至濒死状态。一般单纯腹壁损伤的症状和体征较轻,可表现为受伤部位疼痛,局限性腹壁肿胀和压痛,有时可见皮下瘀斑。如为内脏挫伤,可有腹痛或无明显症状,严重者主要的病理变化是腹腔内出血或腹膜炎。
** <span class="tested">实质性脏器如肝、脾、胰、肾等或大血管损伤 主要临床表现为腹腔内或腹膜后出血,严重者可发生休克。腹痛呈持续性,一般并不很剧烈,腹膜刺激征也不明显。如果肝破裂伴有较大肝内胆管断裂时,因有胆汁沾染腹膜或胰腺损伤若伴有胰管断裂,胰液溢人腹腔,可出现明显的腹痛和腹膜刺激征,</span>体征最明显处一般是损伤所在部。肩部放射痛提示隔肌受刺激,多为肝或脾的损伤。肝、脾包膜下破裂或肠系膜、网膜内出血可表现为腹部肿块。移动性浊音虽然是腹腔内出血的有力证据,但出血量较大时才会出现,对早期诊断帮助不大。肾脏损伤时可出现血尿。
** <span class="tested">空腔性脏器如 胃肠道、胆道、膀胱等破裂的主要临床表现是局限性或弥漫性腹膜炎。除胃肠道症状(恶心、呕吐、便血、呕血等)及稍后出现的全身性感染的表现外, 最为突出的是腹膜刺激征,其程度因空腔器官内容物不同而异。通常, 胃液、胆汁、胰液的刺激最强,肠液次之,血液最轻。</span>伤者可因 肠麻痹而出现腹胀,严重时可发生感染性休克。腹膜后十二指肠破裂的病人有时可出现翠丸疼痛,阴囊血肿和阴茎异常勃起等症状和体征。 空腔脏器破裂处也可有程度不同的出血,但出血量一般不大,除非有合并邻近大血管损伤。
* 腹部损伤/诊断/梗段 #card
:PROPERTIES:
:id: 6253864a-bd64-4267-b803-13c39bb0e88f
:END:
** 【诊断】详细询问外伤史和细致的体格检查,是诊断腹部损伤的主要依据;但有时因伤情紧急,了解病史和体检常需和一些必要的急救措施(如止血、输液、抗休克、维护呼吸道通畅等)同时进行。腹部损伤不论是开放伤或闭合伤,应在排除身体其他部位的合并伤(如颅脑损伤、胸部损伤、肋骨骨折、脊柱骨折、四肢骨折等)后,首先确定有无内脏损伤,再分析脏器损伤的性质、部位和严重程度,确定有无剖腹探查的指征。
开放性损伤的诊断要慎重考虑是否为穿透伤。有腹膜刺激征或腹内组织、内脏自腹壁伤口显露者显然腹膜已穿透,且绝大多数都有内脏损伤。穿透伤诊断还应注意:
*** ①穿透伤的入口或出口可能不在腹部,而可能在胸、肩、腰、臂或会阴等处;
*** ②有些腹壁切线伤虽未穿透腹膜,但并不能排除内脏损伤的可能;
*** <span class="tested">③穿透伤的人、出口与伤道不一定呈直线,因受伤时的姿势与检查时可能不同,低速或已减速投射物可能遇到阻力大的组织而转向;</span>
*** <span class="tested">④伤口大小与伤情的严重程度不一定成正比。</span>
闭合性损伤诊断中需要仔细判断是否有内脏损伤,如不能及时确诊,可能贻误手术时机而导致严重后果。腹部闭合性损伤的诊断思路如下。
** 有无内脏损伤
** 何种脏器受到损伤
** 是否存在多发性损伤
** 诊断有困难怎么办
**
* 腹部损伤/诊断/梗段
** 腹部损伤/诊断/有无内脏损伤 #card
:PROPERTIES:
:id: dda2cbd2-5561-48af-b3e8-3148d1a8e5f3
:END:
*** 1.有无内脏损伤 多数伤者根据临床表现即可确定内脏是否受损,但仍有不少伤者早期腹内脏器损伤体征并不明显,或虽然为单纯腹壁损伤,由于局部疼痛明显,这些都会影响正确判断。因此,需进行严密观察,直至明确诊断。值得注意的是,有些伤者常有较严重的合并损伤,可能掩盖腹部内脏损伤的表现。例如,在合并颅脑损伤时,伤者可因意识障碍而无法反映腹部损伤的症状;合并胸部损伤时有严重的胸痛和呼吸困难,合并长骨骨折时骨折部的剧痛和运动障碍,这些都会影响腹部损伤的症状和体征而导致漏诊。为此,必须做到:
**** (1) <span class="untestedHL">详细了解受伤史:</span>包括受伤时间、受伤地点、致伤条件、伤情、伤情变化和就诊前的急救处理。伤者有意识障碍或因其他情况不能回答问话时,应询问现场目击者和护送人。
**** (2) <span class="untestedHL">重视观察生命体征</span>:包括血压、脉率、呼吸和体温的测定,注意有无休克征象。
**** (3) <span class="untestedHL">全面而有重点的体格检查</span>:包括腹部压痛、肌紧张和反跳痛的程度和范围,是否有肝浊音界改变或移动性浊音,肠蠕动是否受抑制,直肠指检是否有阳性发现等。还应注意腹部以外部位有无损伤,尤其是有些火器伤或利器伤的人口虽不在腹部,但伤道却通向腹腔而导致腹部内脏损伤。
(4) <span class="untestedHL">必要的实验室检查</span>:红细胞、血红蛋白与血细胞比容下降明显,表明有大量失血。白细胞总数及中性粒细胞升高不但见于腹内脏器损伤时,同时也是机体对创伤的一种应激反应,诊断意义并不大。血、尿淀粉酶升高提示胰腺损伤或胃肠道穿孔,但胰腺或胃肠道损伤未必均伴有淀粉酶升高。血尿是泌尿系损伤的重要标志,但其程度与伤情可能不成正比。
**** <span class="tested">通过检查如发现下列情况之一者,应考虑有腹内脏器损伤:</span>
***** <span class="tested">①早期出现休克,尤其是出血性休克征象;</span>
***** <span class="tested">②有持续性甚至进行性加重的腹部疼痛,伴恶心、呕吐等消化道症状;</span>
***** <span class="tested">③明显腹膜刺激征;</span>
***** <span class="tested">④气腹表现;</span>
***** <span class="tested">5腹部出现移动性浊音;</span>
***** <span class="tested">6便血、呕血或尿血;</span>
***** <span class="tested">直肠指诊发现前壁有压痛或波动感,或指套染血。腹部损伤病人如发生顽固性休克,首先考虑腹部内脏伤所致,其次考虑是否有其他部位的合并伤。</span>
** 腹部损伤/诊断/何种脏器受到损伤 #card
:PROPERTIES:
:id: 5943c8cd-3dbb-4143-be57-21a2514496e9
:END:
*** <span class="untestedHL">2.何种脏器受到损伤 首先确定是哪一类脏器受损,然后考虑具体脏器和损伤程度。</span>单纯实质性器官损伤时,腹痛一般不重,压痛和肌紧张也不明显,出血量多时可有腹胀和移动性浊音。但肝、脾破裂后,因局部积血凝固,可出现固定性浊音。单纯空腔脏器破裂以腹膜炎为主要临床表现,上消化道器官破裂穿孔腹膜刺激尤为严重。但空腔器官破裂早期,有时没有腹膜炎表现,而在48小时或72小时后才出现,尤其是下消化道器官破裂。原因可能是肠壁的破裂很小,可因黏膜外翻或肠内容残渣堵塞暂时封闭了破口。结肠破裂造成的腹膜炎虽出现晚,但由于细菌较多,感染性休克往往较重,应特别注意。
*** 以下各项对于判断何种脏器损伤有一定价值:
**** <span class="tested">①有恶心、呕吐、便血、气腹者多为胃肠道损伤,再结合暴力打击部位,腹膜刺激征最明显的部位和程度,可确定损伤在胃、上段小肠、下段小肠或结肠;</span>
**** <span class="tested">②有排尿困难、血尿、外阴或会阴部牵涉痛者,提示泌尿系脏器损伤;</span>
**** <span class="tested">③有肩部牵涉痛者,多提示上腹部脏器损伤,其中以肝和脾破裂为多见;</span>
**** ④有下位肋骨骨折者,注意肝或脾破裂的可能;
**** ⑤有骨盆骨折者,提示直肠、膀胱、尿道损伤的可能。
** 腹部损伤/诊断/是否存在多发性损伤 #card
:PROPERTIES:
:id: 1157f011-d383-403e-a509-be7102e86a79
:END:
*** 3.是否存在多发性损伤 多发性损伤可能有以下几种情况:
**** ①腹内某一脏器有多处损伤;
**** ②腹内有一个以上脏器受到损伤;
**** ③除腹部损伤外,尚有腹部以外的合并损伤;
**** ④腹部以外损伤累及腹内脏器。不论哪种情况,在诊断和治疗中都应提高警惕,避免漏诊而产生严重后果。追问病史、详细体检、严密观察和诊治中的全局观点是避免误诊漏诊的关键。例如,对血压偏低或不稳的颅脑损伤者,经颅脑伤处理后未能及时纠正休克,应考虑到腹腔内出血的可能,而且在没有脑干受压或呼吸抑制的情况下,应该优先处理腹腔内出血。
** 腹部损伤/诊断/诊断有困难怎么办/梗概 #card
:PROPERTIES:
:id: 9ef2a974-2e7c-4a75-8756-baad8c65cbe5
:END:
*** 辅助检查
*** 进行严密观察
*** 剖腹探查
***
***
* 腹部损伤/诊断/诊断有困难怎么办/
** 腹部损伤/诊断/诊断有困难怎么办/辅助检查/
*** 腹部损伤/诊断/诊断有困难怎么办/辅助检查/梗概 #card
:PROPERTIES:
:id: 62538e58-73fa-427b-b7f6-f4ab91dd8f9e
:END:
**** 诊断性腹腔穿刺术和腹腔灌洗术
**** X线检查
**** 超声检查
**** CT检查
**** 诊断性腹腔镜检查
**** 其他检查
*** 腹部损伤/诊断/诊断有困难怎么办/辅助检查/
**** 腹部损伤/诊断/诊断有困难怎么办/辅助检查/诊断性腹腔穿刺术和腹腔灌洗术
**** 腹部损伤/诊断/诊断有困难怎么办/辅助检查/X线检查
**** 腹部损伤/诊断/诊断有困难怎么办/辅助检查/超声检查
**** 腹部损伤/诊断/诊断有困难怎么办/辅助检查/CT检查
**** 腹部损伤/诊断/诊断有困难怎么办/辅助检查/诊断性腹腔镜检查
**** 腹部损伤/诊断/诊断有困难怎么办/辅助检查/其他检查
** 腹部损伤/诊断/诊断有困难怎么办/进行严密观察
** 腹部损伤/诊断/诊断有困难怎么办/剖腹探查
**
** 腹部损伤/处理
***