#+title: 外科学/胸部外科/胸部损伤/教材/血胸
:#+deck: 外科学::胸部外科::胸部损伤::教材::血胸

* 血胸/定义 #card
:PROPERTIES:
:id: 62523624-3cb9-4f1e-b529-080a054f75b0
:END:
** <span class="untestedHL">胸膜腔积血称为血胸(hemothorax),与气胸同时存在称为血气胸(hemopneumothorax)。</span>胸腔积血主要来源于心脏、胸内大血管及其分支、胸壁、肺组织、隔肌和心包血管出血。血胸发生后不但因血容量丢失影响循环功能,还可压迫肺,减少呼吸面积。血胸推移纵隔,使健侧肺受压,并影响腔静脉回流。 <span class="untestedHL">当胸腔内迅速积聚大量血液,超过肺、心包和隔肌运动所起的去纤维蛋白作用时,</span>胸腔内积血发生凝固,形成 <span class="untestedHL">凝固性血胸</span>(coagulating hemothorax)。凝血块机化后形成纤维板,限制肺与胸廓活动,损害呼吸功能。经伤口或肺破裂口侵入的细菌,会在积血中迅速繁殖,引起 <span class="untestedHL">感染性血胸(</span>infective hemo-thorax) ,最终导致血胸( pyohemothorax)。 <span class="untestedHL">持续大量出血所致胸膜腔积血称为进行性血胸</span>(progressive hemothorax)。少数伤员因 <span class="untestedHL">助骨断端活动刺破助间血管或血管破裂处血凝块脱落,发生延 迟出现的胸腔内积血,称为迟发性血胸(</span>delayed hemothorax)。
* 血胸/临床表现/
** 临床表现/血胸分类 #card
:PROPERTIES:
:id: 62523820-d4fa-4013-a804-293c39a581f0
:END:
*** 血胸的临床表现与出血量、速度和个人体质有关。在成人伤员, <span class="untestedHL">血胸量<500ml为少量血胸,500~1000ml为中量,>1000ml为大量血胸。</span>
** 血胸/临床表现/失血表现 #card
:PROPERTIES:
:id: 6252382f-7e82-413e-8dcc-0fc26feaadda
:END:
*** 伤员会出现不同程度的 <span class="untestedHL">面色苍白、脉搏细速、血压下降和末梢血管充盈不良等低血容量休克表现</span>;
** 血胸/临床表现/胸腔积血表现 #card
:PROPERTIES:
:id: 6252384c-67e9-4c28-a3e9-df385d54f8d9
:END:
*** 并有呼吸急促、肋间隙饱满、气管向健侧移位、伤侧叩诊浊音和呼吸音减低等胸腔积液的临床表现 <span class="untestedHL">,胸部X线检查表现为胸腔积液征象。胸膜腔穿刺抽出血液可明确诊断。</span>
** 血胸/临床表现/进行性血胸判定标准 #card
:PROPERTIES:
:id: 62523857-22b1-45ba-93e3-1feac80b0a5f
:END:
*** 具备以下征象则提示存在进行性血胸:
*** ①持续脉搏加快、血压降低,或虽经补充血容量血压仍不稳定;
*** ②闭式胸腔引流量每小时超过200ml,持续3小时;
*** ③血红蛋白量、红细胞计数和血细胞比容进行性降低,引流胸腔积血的血红蛋白量和红细胞计数与周围血相接近,且迅速凝固。
** 血胸/临床表现/血胸病人出现以下情况时,应考虑感染性血胸: #card
:PROPERTIES:
:id: 625238a7-4c5c-433e-a3d9-85d9b3111f00
:END:
*** ①有畏寒、高热等感染的全身表现;
*** ②抽出胸腔积血1ml,加人5ml蒸馏水,无感染呈淡红透明状,出现混浊或絮状物提示感染;
*** ③胸腔积血无感染时,红细胞白细胞计数比例应与周围血相似,即500:1。感染时白细胞计数明显增加,比例达100:1可确定为感染性血胸;
*** ④积血涂片和细菌培养发现致病菌有助于诊断,并可依此选择有效的抗生素。
* 治疗 #card
:PROPERTIES:
:id: 62523601-30af-4f7f-a1b3-d185297f9081
:END:
** 病人为非进行性血胸,胸腔积血量少,可采用胸腔穿刺及时排出积血。
** 中等量以上血胸、血胸持续存在会增加发生凝固性或感染性血胸的可能者,应该积极安置闭式胸腔引流,促使肺膨胀,改善呼吸功能,并使用抗生素预防感染。
** 进行性血胸应及时开胸探查手术。
** 凝固性血胸应待伤员情况稳定后尽早手术,清除血块,并剥除胸膜表面血凝块和机化形成的纤维包膜;开胸手术可提早到伤后2~3天,更为积极地开胸引流则无益,但明显推迟手术时间可能使清除肺表面纤维蛋白膜变得困难,从而使手术复杂化。
** 感染性血胸应及时改善胸腔引流,排尽感染性积血积胀;若效果不佳或肺复张不良,应尽早手术清除感染性积血,剥离脑性纤维膜。电视胸腔镜用于凝固性血胸、感染性血胸的处理,具有创伤小、疗效好、住院时间短、费用低等优点。
*