#+title: 外科学/普通外科/腹外疝/教材/股疝
#+deck: 外科学::普通外科::腹外疝::教材::股疝

* 股疝/股管结构 
:PROPERTIES:
:id: 6252ac86-956e-4a4f-9fb8-e39e455d4c72
:END:
** 【股管解剖概要】股管是一个狭长的漏斗形间隙,长约1~1.5cm,内含脂肪、疏松结缔组织和淋巴结。
** 股管有 <span class="untestedHL">上下两口。上口称股环,直径约1.5cm,有股环隔膜覆盖;</span>
** <span class="untestedHL">其前缘为腹股沟韧带,</span>
** <span class="untestedHL">后缘为耻骨梳韧带,</span>
** <span class="untestedHL">内缘为腔隙韧带,</span>
** <span class="untestedHL">外缘为股静脉。</span>
** <span class="untestedHL">股管下口为卵圆窝。卵圆窝是股部深筋膜(阔筋膜)上的一个薄弱部分,覆有一层薄膜,称筛状板。</span>它位于腹股沟韧带内侧端的下方, <span class="untestedHL">下肢大隐静脉在此处穿过筛状板进入股静脉。</span>
* 股疝/好发情况 
:PROPERTIES:
:id: 6252ac80-e98e-4671-b96c-56c75b4a6f62
:END:
** 疝囊通过股环、经股管向卵圆窝突出的疝,称为股疝(femoral hemia)。股疝的发病率约占腹外疝的3%~5%,多见于 <span class="untestedHL">40岁以上妇女</span>。</span>
* 股疝/病因  
:PROPERTIES:
:id: 6252ae89-6f41-4c03-bb58-594796c071ca
:END:
#+BEGIN_QUOTE
解剖因素,内压因素?
#+END_QUOTE
** 女性 <span class="untestedHL">骨盆较宽大、联合肌腱和腔隙韧带较薄弱,以致股管上口宽大松弛而易发病。
** 妊娠是腹内压增高的主要原因。
* 股疝/病理解剖
** 在腹内压增高的情况下,对着股管上口的腹膜,被下坠的腹内脏器推向下方,经股环向股管突出而形成股疝。疝块进一步发展,即由股管下口顶出筛状板而至皮下层。 <span class="untestedHL">疝内容物常为大网膜或小肠。</span>由于 <span class="untestedHL">股管几乎是垂直的,疝块在卵圆窝处向前转折时形成一锐角,且股环本身较小,周围又多坚韧的韧带,因此股疝容易嵌顿</span>。 <span class="tested">在腹外疝中,股疝嵌顿者最多,高达60%。股疝一旦嵌顿,可迅速发展为绞窄性疝,应特别注意。</span>
* 股疝/临床表现 
:PROPERTIES:
:id: 6252aeb5-a888-47aa-b364-957a28c8f1b8
:END:
** 【临床表现】 <span class="tested">疝块往往不大,常在腹股沟韧带下方卵圆窝处表现为一半球形的突起。</span> <span class="tested">平卧回纳内容物后,疝块有时不能完全消失,这是因为疝囊外有很多脂肪堆积的缘故。由于疝囊颈较小,咳嗽冲击感也不明显。</span>易复性股疝的症状较轻,常不为病人所注意,尤其在肥胖者更易疏忽。一部分病人可在久站或咳嗽时感到患处胀痛,并有可复性肿块。
** 股疝如发生嵌顿,除引起局部明显疼痛外, <span class="untestedHL">也常伴有较明显的急性机械性肠梗阻</span>,严重者甚至可以掩盖股疝的局部症状。
* 股疝/治疗 
:PROPERTIES:
:id: 6252b009-8e9b-458b-8a56-e03253c76483
:END:
** 【治疗】 <span class="tested">股疝容易嵌顿,一旦嵌顿又可迅速发展为绞窄性疝。因此,股疝诊断确定后,应及时手术治疗。</span> <span class="untestedHL">对于嵌顿性或绞窄性股疝,更应紧急手术。</span>
** <span class="tested">最常用的手术是McVay修补法。此法不仅能加强腹股沟管后壁而用于修补腹股沟疝,同时还能堵住股环而用于修补股疝</span>。 <span class="tested">另一方法是在处理疝囊后,在腹股沟韧带下方把腹股沟韧带、腔隙韧带和耻骨肌筋膜缝合在一起,借以关闭股环。</span>也可采用无张力疝修补法或经腹腔镜疝修补术。
嵌顿性或绞窄性股疝手术时,因疝环狭小,回纳疝内容物常有一定困难。遇此情况时, <span class="untestedHL">可切断腹股沟韧带以扩大股环。但在疝内容物回纳后,应仔细修复被切断的韧带。</span>
*
**