#+title: 外科学/外科学总论/外科休克/教材/概论
#+deck: 外科学::外科学总论::外科休克::教材::概论

* 外科休克/外科休克的基本概念 #card
:PROPERTIES:
:id: 624d08de-5e82-4038-a9a4-675eca38bda0
:collapsed: true
:END:
** <span style="color:red;">休克(shock）是机体有效循环血容量减少、组织灌注不足,细胞代谢紊乱和功能受损的病理生理过程，由多种病因引起。</span>组织灌注不足导致组织氧的传递、转运和利用障碍，从而发生代谢障碍，引起 细胞能量物质的缺乏及细胞代谢产物的堆积。
** <span style="color:red;">组织细胞氧供给不足和需求增加是休克的本质</span>， <span style="color:yellow;">产生 炎症介质是休克的特征</span>，因此恢复对其供氧、促进其有效的利用，重新建立氧的供需平衡和维护正常 的细胞功能是治疗休克的关键环节。
**
* 外科休克/分类 #card
:PROPERTIES:
:id: 624d0978-5ea0-4a01-9c99-5cf091711cf8
:collapsed: true
:END:
** <span style="color:yellow;">通常将休克分为低血容量性(包括失血性及创伤性）、感染性、心源性、神经源性和过敏 性休克五类。低血容量性和感染性休克在外科最常见。</span>
* 外科休克/病理生理
:PROPERTIES:
:collapsed: true
:END:
** 外科休克/病理生理/梗概 #card
:PROPERTIES:
:id: 624d09ef-3c4d-468a-a763-24fd76252a22
:END:
*** 微循环的改变
**** <span style="color:red;">在有效循环量不足引起休克的过程中，占总循环量20%的微循环也发生相应 地变化。</span>
*** 代谢改变
*** 炎症介质释放和缺血再灌注损伤
*** 内脏器官的继发性休克
** 外科休克/病理生理/微循环的改变
*** 外科休克/病理生理/微循环的改变/微循环收缩期 #card
:PROPERTIES:
:id: 624d0c47-e80a-4c46-9521-c4087df26f9e
:END:
**** （1）微循环收缩期：休克早期，由于有效循环血容量显著减少，引起循环容量降低、动脉血压下 降。此时机体启动一系列代偿机制而发生以下病理生理变化，包括：通过主动脉弓和颈动脉实压力感受器引起血管舒缩中枢加压反射， <span style="color:red;">交感-肾上腺轴兴奋导致大量儿茶酚胺释放以及肾素-血管紧张素 </span>分泌增加等环节，引起 <span style="color:red;">心跳加快、心排血量增加以维持循环相对稳定;</span> <span style="color:red;">又通过选择性收缩外周(皮肤、 骨骼肌）和内脏(如肝、脾、胃肠）的小血管使循环血量重新分布，保证;心、脑等重要器官的有效灌注</span>。 由于内胜小动、静脉血管平滑肌及毛细血管前括约肌受儿茶酚胺等激素的影响发生强烈收缩,动静脉间短路开放，结果使外周血管阻力和回心血量均有所增加;毛细血管前括约肌收缩和后括约肌相对开 放有助于组织液回吸收和血容量得到部分补偿。 <span style="color:yellow;">微循环内因前括约肌收缩而致“只出不进</span>〞，血量减 少,组织仍处于低灌注、缺氧状态。若能在此时去除病因积极复苏，休克常较容易得到纠正。
*** 外科休克/病理生理/微循环的改变/微循环扩张期 #card
:PROPERTIES:
:id: 624d0c58-9b43-4610-a2f2-56368a8906d8
:END:
**** （2）微循环扩张期：若休克继续进展，微循环将进一步因 <span style="color:yellow;">动静脉短路和直捷通道大量开放</span>，使原 有的组织灌注不足更为加重，细胞因严重缺氧处于无氧代谢状况，出现能量不足、乳酸类产物蓄积和 舒血管的介质如 <span style="color:yellow;">组胺、缓激肽等释放。这些物质可直接引起毛细血管前括约肌舒张，而后括约肌则因 对其敏感性低仍处于收缩状态，导致微循环内“只进不出”</span>。结果是， <span style="color:yellow;">血液滞留在毛细血管网内</span>，使其 静水压升高,加上毛细血管壁通透性增强， <span style="color:yellow;">使血浆外滲、血液浓缩和血液黏稠度增加，回心血量又进一 步降低</span>,心排血量继续下降，心、脑器官灌注不足，休克加重而进入微循环扩张期。
*** 外科休克/病理生理/微循环的改变/微循环衰竭期 #card
:PROPERTIES:
:id: 624d0c62-ffee-487e-86f8-a832b77ec92e
:END:
**** （3） 微循环衰竭期：若病情继续发展，便进人不可逆性休克。 <span style="color:yellow;">淤滞在微循环内的黏稠血液在酸性 环境中处于高凝状态</span>,红细胞和血小板 <span style="color:yellow;">容易发生聚集并在血管内形成微血栓，甚至引起弥散性血管内 凝血</span>。此时，由于组织缺少血液灌注， <span style="color:yellow;">细胞处于严重缺氧和缺乏能量的状态,细胞内的溶酶体膜破裂， 溶酶体内多种酸性水解酶溢出，引起细胞自溶并损害周围其他的细胞</span>。最终引起大片组织、整个器官 乃至多个器官功能受损。
** 外科休克/病理生理/代谢改变 #card
:PROPERTIES:
:id: 624d0a3e-011e-4ac7-ba16-c3ceca789878
:END:
*** (1） <span style="color:yellow;">无氧代谢引起代谢性酸中毒</span>：当氧释放不能满足细胞对氧的需要时，将发生无氧糖酵 解。缺氧时丙酮酸在胞质内转变成乳酸，因此，随着细胞氧供减少，乳 <span style="color:yellow;">酸生成增多，丙酮酸浓度 降低，即血乳酸浓度升高和乳酸/丙酮酸(L/P）比率增高</span>。在没有其他原因造成高乳酸血症的 情况下，,乳酸盐的含量和L/P比值，可以反映病人细胞缺氧的情况。当发展至重度酸中毒pH＜ 7.2 时, <span style="color:yellow;">心血管对儿茶酚胺的反应性降低，表现为心跳缓慢、血管扩张和心排血量下降</span>，还可使 氧合血红蛋白离解曲线右移。
*** (2）能量代谢障碍： <span style="color:yellow;">创伤和感染使机体处于应激状态，交感神经-肾上腺髓质系统和下丘脑-垂体- 肾上腺皮质轴兴奋，使机体儿茶酚胺和肾上腺皮质激素明显升高</span>
**** <span style="color:yellow;">从而抑制蛋白合成、促进蛋白分解， 以便为机体提供能量和合成急性期蛋白( acute phase protein, APP) 的原料。</span>
**** <span style="color:yellow;">上述激素水平的变化还可 促进糖异生、抑制糖降解，导致血糖水平升高。</span>
**** 在 <span style="color:yellow;">应激状态下，蛋白质作为底物被消耗</span>,当具有特殊功能的酶类蛋白质被消耗后，则不能完成复 杂的生理过程，进而导致多器官功能障碍综合征。 <span style="color:yellow;">应激时脂肪分解代谢明显增强，成为危重病人机体 获取能量的主要来源。</span>
** 外科休克/病理生理/炎症介质释放和缺血再灌注损伤 #card
:PROPERTIES:
:id: 624d0a3f-8d0f-4d7d-bca6-5c32e4933eb6
:END:
*** 炎症介质释放和缺血再灌注损伤 <span style="color:yellow;"> 严重创伤、感染、出血等可刺激机体释放过量炎症介质，形 成“瀑布样”连锁放大反应</span>。炎症介质包括 <span style="color:yellow;">白介素、肿瘤坏死因子、集落刺激因子、干扰素和血管扩张 剂一氧化氮(NO)等</span>。活性氧代谢产物可引起脂质过氧化和细胞膜破裂。 在炎症反应中，血管内皮细胞可通过调节血流、白细胞的黏附及聚集影响炎症应答的进程。在炎 症应答中首先被激活的是中性粒细胞。炎症介质及胞外配体激活中性粒细胞后，可促进中性粒细胞 在组织中的游走。一方面分化形成的多形核中性粒细胞( polymorphonuclear neutrophil, PMN)可清除 感染源；另一方面激活 PMIN 介导的细胞毒作用，产生活性氧、蛋白水解酶、血管活性分子等物质，可加 重细胞、组织的损伤,甚至可能与休克相关的多器官功能不全综合征(MODS）的发展有关。 代谢性酸中毒和能量不足还影响细胞各种膜的屏障功能。细胞膜受损后除通透性增加外，还出 现细胞膜上离子泵的功能障碍如 Na*-K*泵、钙泵。表现为细胞内外离子及体液分布异常，如钠、钙离 子进入细胞内不能排出，钾离子则在细胞外无法进人细胞内，导致血钠降低、血钾升高，细胞外液随钠 离子进入细胞内，引|起细胞外液减少和细胞肿胀、死亡，而大量钙离子进人细胞内后除激活溶酶体外， 还导致线粒体内钙离子升高，并从多方面破坏线粒体。溶酶体膜破裂后除前面提到释放出许多引起 细胞自溶和组织损伤的水解酶外，还可产生心肌抑制因子(MDF）、缓激肽等毒性因子。线粒体膜发 生损伤后，引起膜脂降解产生血栓素、白三烯等毒性产物，呈现线粒体肿胀、线粒体嵴消失,细胞氧化磷酸化障碍影响能量生成 
#+BEGIN_QUOTE
这 些炎症介质在机体缺血状况得到纠正后，会大量进入血液循环，导致"再损伤"。
#+END_QUOTE
** 外科休克/病理生理/内脏器官的继发性休克
*** 外科休克/病理生理/内脏器官的继发性休克/梗概 #card
:PROPERTIES:
:id: 624d122b-e541-401b-b021-9ab3d97e05d5
:END:
**** 肺
**** 肾
**** 脑
**** 心
**** 胃肠
**** 肝
*** 外科休克/病理生理/内脏器官的继发性休克/肺 #card
:PROPERTIES:
:id: 624d0e89-1324-4616-b90d-74555162967b
:END:
**** 休克时 <span style="color:yellow;">缺氧</span>可使肺毛细血管 <span style="color:yellow;">内皮细胞和肺泡上皮受损，表面活性物质减少</span>;
**** 复苏过程中， 如大量使用库存血， <span style="color:yellow;">其所含的微聚物可造成肺微循环栓塞</span>。结果导致部分肺泡菱陷和不张,肺水肿以 及部分肺血管嵌闭或灌注不足，引起肺分流和无效腔通气增加， <span style="color:yellow;">严重时导致急性呼吸窘迫综合征 (ARDS)</span>。ARDS 常发生于休克期内，也可在稳定后 48~72 小时内发生。
*** 外科休克/病理生理/内脏器官的继发性休克/肾 #card
:PROPERTIES:
:id: 624d0e8b-fc8d-4616-8f1b-f6026e6b8422
:END:
**** <span style="color:red;">因血压下降、儿茶酚胺分泌增加使肾的人球血管痉挛和有效循环容量减少，肾滤过率明 显下降而发生少尿。</span>
**** <span style="color:red;">休克时，肾内血流重分布、并转向髓质，从而导致皮质区的肾小管缺血坏死，发生 急性肾衰竭。</span>
*** 外科休克/病理生理/内脏器官的继发性休克/脑 #card
:PROPERTIES:
:id: 624d0e8c-dc24-4c58-8cc3-b72cf9d943d8
:END:
**** 因脑灌注压和血流量下降将导致脑 <span style="color:yellow;">缺氧。缺血、CO,潴留和酸中毒</span>会引起 <span style="color:yellow;">脑细胞肿胀、血 管通透性增高而导致脑水肿</span>和颅内压增高，严重者可发生 <span style="color:yellow;">脑疝。</span>
*** 外科休克/病理生理/内脏器官的继发性休克/心 #card
:PROPERTIES:
:id: 624d0e8d-2ed0-4196-bfdf-b4dadb22cb20
:END:
**** 冠状动脉血流减少，导致 <span style="color:yellow;">心肌缺血</span>;
**** 心肌 <span style="color:yellow;">微循环内血栓形成，可引起心肌的局灶性坏死</span>。
**** 心肌含有丰富的黄嘌呤氧化酶， <span style="color:yellow;">易遭受缺血-再灌注损伤</span>; <span style="color:yellow;">电解质异常</span>也将导致心律失常和心肌的收 缩功能下降。
*** 外科休克/病理生理/内脏器官的继发性休克/胃肠道 #card
:PROPERTIES:
:id: 624d0e8e-f8d6-4438-95c1-1c158eeec20a
:END:
**** 胃肠道：肠系膜血管的 <span style="color:yellow;">血管紧张素Ⅱ受体的密度高</span>，对血管加压物质特别敏感，故休克时 肠系膜上动脉 <span style="color:yellow;">血流量可减少 70%</span>。肠黏膜因灌注不足而遭受 <span style="color:yellow;">缺氧性损伤</span>。
**** 肠黏膜上皮的 <span style="color:yellow;">机械和 免疫屏障功能受损</span>，导致肠道内的细菌或其毒素经淋巴或门静脉途径侵害机体，称为细菌移位和 内毒素移位，形成肠源性感染，导致休克继续发展和多器官功能不全，这 <span style="color:yellow;">是导致休克后期死亡的重 要原因。</span>
*** 外科休克/病理生理/内脏器官的继发性休克/肝 #card
:PROPERTIES:
:id: 624d0e93-87b3-4fc7-9b7e-eceeb061cb07
:END:
**** 休克可引起肝缺血、缺氧性损伤，可 <span style="color:yellow;">破坏肝的合成与代谢功能。</span>
**** 另外，来自胃肠道的 <span style="color:yellow;">有害物质可激活肝Kupffer细胞，从而释放炎症介质</span>。组织学方面可见肝小叶中央出血、肝细胞坏死等。生化检测血转氨酶、胆红素升高等代谢异常。
**** 受损肝的 <span style="color:yellow;">解毒和代谢能力均下降，可引起内毒素血症</span>，并加重已有的代谢紊乱和酸中毒。
* 外科休克/临床表现 #card
:PROPERTIES:
:id: 624d1281-d4f7-4684-9c72-566151ef48e3
:collapsed: true
:END:
** 休克代偿期休克失代偿期(中度,重度)
** ((624d1382-ac27-49f2-a47c-0e58e1b2b19d))
* 外科休克/诊断 #card
:PROPERTIES:
:id: 624d13d8-9855-46bf-8663-68bc338218b0
:collapsed: true
:END:
** 【诊断】关键是早期发现并准确分期：
** ①凡遇到严重损伤、大量出血、重度感染以及过敏病人和 有心脏病史者,应想到并发休克的可能;
** ②临床观察中,对于有 <span style="color:yellow;">出汗、兴奋、心率加快、脉压小或尿少</span>等 症状者，应疑有休克;
** ③若病人出现 <span style="color:yellow;">神志淡漠、反应迟钝</span>、 <span style="color:yellow;">皮肤苍白、呼吸浅快</span>、 <span style="color:yellow;">收缩压降至 90mmHg</span> 以 下及尿少或无尿者， <span style="color:yellow;">则标志病人已进入休克失代偿期。</span>
** #+BEGIN_QUOTE
休克的诊断方法为一看二摸三测四量，即一看(是否神志淡漠、反应迟钝、面色苍白)，二摸(是否脉搏快而弱)，三测(血压是否降低)，四量(是否尿量<30ml/h)。

#+END_QUOTE
* 休克的监测
:PROPERTIES:
:collapsed: true
:END:
** 休克的监测/梗概/一般监测 #card
:PROPERTIES:
:id: 624d1509-ba58-4da8-9614-49d47f6bc478
:END:
*** 精神状态
*** 皮肤温度色泽
*** 血压
*** 脉率
*** 尿量
** 休克的监测/梗概/特殊监测 #card
:PROPERTIES:
:id: 624d1525-4970-487a-9382-5847f2a91550
:END:
*** 中心静脉压
*** 动脉血气分析
*** 动脉血乳酸盐测定
*** DIC检测
*** Swan-Ganz 漂浮导管技术
** 休克的监测/一般监测/精神状态 #card
:PROPERTIES:
:id: 624d15af-1c6a-435c-aa08-8fdc6f62a15e
:END:
*** (1）精神状态： <span style="color:red;">是脑组织血液灌流和全身循环状况的反映</span>。如病人神 <span style="color:red;">志清楚，对外界的刺激能正 常反应，说明病人循环血量已基本足够</span>;相反，若病人表情淡漠、不安、谵妄或嗜睡、昏迷，反映脑因血 液循环不良而发生障碍。
** 休克的监测/一般监测/皮肤温度色泽 #card
:PROPERTIES:
:id: 624d15de-3736-4b06-b6e5-c0b228cda6ff
:END:
*** (2）皮肤温度、 <span style="color:red;">色泽：是体表灌流情况的标志</span>。如病人的四肢温暖，皮肤干燥， <span style="color:red;">轻压指甲或口唇时，局部暂时缺血呈苍白，松压后色泽迅速转为正常，表明末梢循环已恢复、休克好转</span>;反之则说明休克情况仍存在。
** 休克的监测/一般监测/血压 #card
:PROPERTIES:
:id: 624d15df-fe24-42a3-9b0e-d5c8da7f3d4d
:END:
*** (3）血压： <span style="color:red;">通常认为收缩压<90mmHlg、脉压<20mmHg 是休克存在的表现</span>;血压回升、脉压增大则 是休克好转的征象。维持稳定的组织灌注压在休克治疗中十分重要。 <span style="color:red;">但是，血压并不是反映休克程 度的唯一指标，还应兼顾其他的参数进行综合分析。</span>
** 休克的监测/一般监测/脉率 #card
:PROPERTIES:
:id: 624d15df-1565-47fd-aaa7-99b76123b589
:END:
*** (4）脉率：脉率是休克监测中的又一重要生理指标。
*** <span style="color:red;">①休克早期，脉率的变化多出现在血压变化 之前，表现为脉率加快，血压正常;</span>
*** <span style="color:red;">②休克失代偿期，脉率加快，血压下降;</span>
*** <span style="color:red;">③休克好转时，脉率往往已 恢复，但此时血压可以表现为正常或低于正常;</span>
*** <span style="color:red;">④应注意的是,在血管活性药物应用或者病人伴有心 脏基础性疾病的情况下，会影响脉率和血压对休克程度判定的原有临床价值。</span> 
#+BEGIN_QUOTE
休克指数=脉率/收缩压=0.5 无休克，>1.0~1.5 有休克，>2.0 为严重休克
#+END_QUOTE
** 休克的监测/一般监测/尿量 #card
:PROPERTIES:
:id: 624d15e0-462c-4309-82bf-83c2403990cf
:END:
*** （5）尿量：是反映肾血液灌注情况的重要指标。
*** <span style="color:red;">尿少通常是休克早期和休克未完全纠正的表现。 尿量<25ml/h、比重增加者表明仍存在肾血管收缩和供血量不足;</span>
*** <span style="color:red;">血压正常但尿量仍少且比重偏低者， 提示有急性肾衰竭可能。当尿量维持在30ml/h 以上时，则休克已好转。</span>
*** 此外，创伤危重病人复苏时 使用高渗溶液者可能产生明显的利尿作用;涉及神经垂体的颅脑损伤可出现尿崩现象;尿路损伤可导 致少尿与无尿，判断病情时应子注意鉴别。
** 休克的监测/特殊监测/中心静脉压 #card
:PROPERTIES:
:id: 624d15ea-021b-4b37-aa8a-163273063961
:END:
*** <span style="color:red;">(1）中心静脉压(CVP)：中心静脉压代表了右心房或者胸腔段腔静脉内压力的变化，可反映全身 血容量与右心功能之间的关系。</span>
*** <span style="color:red;">CVP 的正常值为5～10cmH₂O。当 CVP<5㎝H₂O 时，表示血容量不 足;</span>
*** <span style="color:red;">高于15cmHl,0 时，提示心功能不全、静脉血管床过度收缩或肺循环阻力增高;若 CVP 超过20cmll,0 时,则表示存在充血性心力衰竭。</span>
*** 通常要求连续测定，动态观察其变化趋势以准确反映右心前负荷的 情况。
** 休克的监测/特殊监测/动脉血气分析 #card
:PROPERTIES:
:id: 624d15ff-3cd0-408a-bd4e-b7f04e401261
:END:
*** （2）动脉血气分析：动脉血氧分压(Pa0₂）正常值为 80~100mmHlg;动脉血二氧化碳分压(PacO,） 正常值为36~44mmHg。休克时因肺换气不足，体内二氧化碳聚积致 PaCO,明显升高;相反，如病人原 來并无肺部痪病，因过度换气可致 PaCO,较低;若 PaCO,超过45~50mmHg，常提示肺泡通气功能障 碍;PaO,低于 60mmHlg，吸人纯氧仍无改善者则可能是 ARDS 的先兆。
*** 动脉血 PH 正常为7.35~7.45。
*** 通过监测 pH、碱剩余(BE）、缓冲碱(BB） 和标准重碳酸盐（SB） 的动态变化有助于了解休克时 <span style="color:yellow;">酸碱平 衡的情况</span>。
*** 通过监测动脉血气的动态变化有助于了解休克时酸碱平衡的情况。 <span style="color:yellow;">碱缺失(BD)可反映 全身组织的酸中毒情况，反映休克的严重程度和复苏状况。</span>
** 休克的监测/特殊监测/动脉血乳酸盐测定 #card
:PROPERTIES:
:id: 624d15ff-0527-4803-8026-173231372c24
:END:
*** (3)动脉血乳酸盐测定:组织灌注不足可引起无氧代谢和高乳酸血症,监测乳酸盐水平有助于 <span style="color:yellow;">估计休克及复苏的变化趋势</span>。 <span style="color:yellow;">正常值为1~1.5mmol/L,危重病人有时会达到4mmol/L。乳酸的水平与病人的预后密切相关,持续的高乳酸血症往往表明病人死亡率增加</span>。
** 休克的监测/特殊监测/DIC的检测 #card
:PROPERTIES:
:id: 624d1600-07fc-468d-8aaf-1b49cab74869
:END:
*** (4) DIC的检测:对疑有DIC的病人,应测定其血小板的数量和质量、凝血因子的消耗程度及反映纤溶活性的多项指标,包括:
*** <span style="color:yellow;">①血小板计数低于80x10⁹/L;</span>
*** <span style="color:yellow;">②凝血酶原时间比对照组延长3秒以上;</span>
*** <span style="color:yellow;">③血浆纤维蛋白原低于1.5g/L或呈进行性降低;</span>
*** <span style="color:yellow;">④3P(血浆鱼精蛋白副凝)试验阳性;</span>
*** <span style="color:yellow;">⑤血涂片中破碎红细胞超过2%等。</span>该 <span style="color:yellow;">5项检查中出现3项</span>以上异常,结合临床上有休克及 <span style="color:yellow;">微血管栓塞症状和出血倾向</span>时,便可诊断DIC。
** 休克的监测/特殊监测/Swan-Ganz漂浮导管技术 #card
:PROPERTIES:
:id: 624d1604-b36a-46d9-950d-0b660bf4b590
:END:
*** (5)应用Swan-Ganz漂浮导管可测得 <span style="color:yellow;">心排血量(CO),并计算心脏指数(CI),反映心排血量及外周血管阻力</span>
*** 同时也可测得 <span style="color:yellow;">肺动脉压(PAP)和肺毛细血管楔压(PCWP),可反映肺静脉、左心房和左心室的功能状态。</span>但肺动脉导管技术是一项有创性检查,有发生严重并发症的可能(发生率约3%~5%),故应当严格掌握适应证。
* 休克的治疗
** 休克的治疗/梗概 #card
:PROPERTIES:
:id: 624d2348-1eb4-4245-8a0b-f361ebdd24f4
:END:
*** 应当针对引起休克的原因和休克不同发展阶段的重要生理紊乱采取下列相应的治疗， <span style="color:red;">其中重点是恢复灌注和对组织提供足够的氧，</span> <span style="color:yellow;">目的是防止多器官功能不全综合征发生</span>
** 休克的治疗/紧急治疗 #card
:PROPERTIES:
:id: 624d2350-4b1a-41a8-8112-4f749083567d
:END:
*** 1.紧急治疗 包括 <span style="color:yellow;">积极处理引起休克的原发伤病</span>,如创伤制动、大出血止血、保证呼吸道通畅等。
*** <span style="color:yellow;">采取头和躯干抬高20°~30°、下肢抬高15°~20°体位,以增加回心血量</span>( <span style="color:yellow;">记忆为两头翘体位</span>)。
*** <span style="color:yellow;">及早建立静脉通路,并用药维持血压</span>。
*** <span style="color:yellow;">早期予以鼻管或面罩吸氧</span>。
*** <span style="color:yellow;">注意保温。
</span>
*** 在对重症或创伤病人的处理中,应掌握以下原则:① <span style="color:yellow;">保证呼吸道通畅;②及时控制活动性出血;③手术控制出血的同时予血制品及一定量的晶体液扩容。</span>
** 休克的治疗/补充血容量 #card
:PROPERTIES:
:id: 624d2394-9741-4a9b-870f-36871a3969dc
:END:
*** <span style="color:red;">2.补充血容量 是纠正休克引起的组织低灌注和缺氧的关键。</span>应在连续监测动脉血压、尿量和CVP的基础上,结合病人皮肤温度、末梢循环、脉搏及毛细血管充盈时间等微循环情况,判断补充血容量的效果。 <span style="color:yellow;">目前,晶体液仍然是容量复苏时的第一线选择</span>,大量液体复苏时 <span style="color:yellow;">可联合应用人工胶体液</span>,必要时进行成分输血。对休克病人,争取在诊断的最初6小时这一黄金时段内,进行积极的输液复苏,以尽快恢复最佳心搏量、稳定循环功能和组织氧供。这一治疗休克的策略被称为早期达标治疗 ( early goal directed therapy, EGDT)。 
#+BEGIN_QUOTE
 <span style="color:yellow;">补充血容量是休克治疗首先 、最重要最关键的治疗措施，针对的是休克的本质</span>
#+END_QUOTE
** 休克的治疗/积极处理原发病 #card
:PROPERTIES:
:id: 624d2394-cad6-4e5c-b29f-4a8e4f7a82a5
:END:
*** 积极处理原发病 外科疾病引起的休克,多存在需手术处理的原发病变,如内脏大出血、肠袢坏死、消化道穿孔和脓肿等。 <span style="color:yellow;">应在尽快恢复有效循环血量后,及时施行手术处理原发病变,才能有效地治疗休克</span>。 <span style="color:yellow;">有的情况下,应在积极抗休克的同时进行手术</span>,以免延误抢救时机。
** 休克的治疗/纠正酸碱平衡失调 #card
:PROPERTIES:
:id: 624d239e-8ad2-478f-b9fe-57d752e07705
:END:
*** 4.纠正酸碱平衡失调 酸性内环境对心肌、血管平滑肌和肾功能均有抑制作用。在休克早期,又可能因过度换气引起低碳酸血症、呼吸性碱中毒。按照血红蛋白氧合解离曲线的规律,碱中毒使血红蛋白氧离曲线左移,氧不易从血红蛋白释出,可使组织缺氧加重;
*** <span style="color:yellow;">故不主张早期使用碱性药物</span>。而酸性环境有利于氧与血红蛋白解离,从而增加组织供氧。目 <span style="color:yellow;">前对酸碱平衡的处理多主张宁酸毋碱</span>。根本措施是改善组织灌注,并适时和适量地给予碱性药物。 <span style="color:yellow;">另外,使用碱性药物须首先保证呼吸功能完整,否则会导致CO2渚留和继发呼吸性酸中毒。</span>
** 休克的治疗/血管活性药物的应用
:PROPERTIES:
:collapsed: true
:END:
*** 休克的治疗/血管活性药物的应用/梗概 #card
:PROPERTIES:
:id: 624d2aa3-f5fb-44e5-8f61-32c2b42d28ff
:END:
**** 在容量复苏的同时应用血管活性药物可以迅速升高血压和改善循环,尤其是在感染性休克的病人。 <span style="color:red;">理想的血管活性药物应能迅速提高血压，改善心脏和脑血流灌注，又能改善肾和肠道等内脏器官血流灌注</span>。
**** 血管收缩剂
**** 血管扩张剂
**** 强心药
*** 休克的治疗/血管活性药物的应用/血管收缩剂 #card
:PROPERTIES:
:id: 624d2bf1-ecc4-47f4-a240-005fad84ba25
:END:
**** 有多巴胶、去甲肾上腺素和间羟胺等。
**** 多巴胺是最常用的血管活性药,兼具兴奋a、β₁和多巴胺受体作用,其药理作用与剂量有关。
***** <span style="color:red;">小剂量[<10μg/(min· kg)]时,主要是β₁和多巴胺受体作用,可增强心肌收缩力和增加心排血量,并扩张肾和胃肠道等内脏器官血管;</span>
***** <span style="color:red;">大剂量[>15pg/(min·kg) ]时则为a受体作用,增加外周血管阻力。</span>
***** <span style="color:red;">抗休克时主要取其强心和扩张内脏血管的作用,宜采取小剂量。为提升血压,可将小剂量多巴胺与其他缩血管药物合用,而不增加多巴胺的剂量。</span>多巴酚丁胺对心肌的正性肌力作用较多巴胺强,能增加心排血量,降低PCWP,改善心泵功能。
**** <span style="color:red;">去甲肾上腺素与多巴酚丁胺联合应用是治疗感染性休克最理想的血管活性药物。去甲肾上腺素是以兴奋a受体为主、轻度兴奋β受体的血管收缩剂,能兴奋心肌,收缩血管,升高血压及增加冠状动脉血流量,作用时间短</span>。
**** 间羟胺(阿拉明)间接兴奋a、β受体,对心脏和血管的作用 <span style="color:yellow;">同去甲肾上腺素,但作用弱,维持时间约30分钟</span>。
**** <span style="color:red;">异丙基肾上腺素是能增强心肌收缩和提高心率的β受体兴奋剂,因对心肌有强大收缩作用和容易发生心律不齐,不能用于心源性休克。</span>
**** 休克的治疗/血管活性药物的应用/血管扩张剂 #card
:PROPERTIES:
:id: 624d2be9-0caf-4f23-b707-b59816024350
:END:
***** (2)血管扩张剂: <span style="color:yellow;">分a受体阻滞剂和抗胆碱能药两类</span>。前者包括酚妥拉明、酚苄明等,能解除去甲肾上腺素所引起的小血管收缩和微循环淤滞并增强左室收缩力;后者包括阿托品、山莨菪碱和东莨菪碱。 <span style="color:yellow;">临床上较常用的是山莨菪碱</span>(人工合成品为654-2),可使血管舒张,从而改善微循环。还可通过抑制花生四烯酸代谢,降低白三烯、前列腺素的释放而保护细胞,是良好的细胞膜稳定剂。多用于感染性休克的治疗。
**** 休克的治疗/血管活性药物的应用/强心药 #card
:PROPERTIES:
:id: 624d2ddb-60d0-4f84-856d-b41b8bbfd7ec
:END:
***** (3)强心药: <span style="color:yellow;">包括兴奋α和β肾上腺素能受体兼有强心功能的药物,如多巴胺和多巴酚丁胺等</span>,其他还有强心昔如毛花昔丙(西地兰),可增强心肌收缩力,减慢心率。通常在输液量已充分但动脉压仍低,而CVP检测提示前负荷已经够的情况下使用。
***
** 休克的治疗/治疗DIC改善微循环 #card
:PROPERTIES:
:id: 624d23a8-72b6-41a0-8a1e-b3fe68ede0f2
:END:
*** 6.治疗DIC 改善微循环  <span style="color:yellow;">对诊断明确的DIC,可用肝素抗凝</span>。一般1.Omg/kg,6小时一次, <span style="color:yellow;">成人首次可用10 000U</span>(1mg相当于125U左右)。有时还使用抗纤溶药如氨甲苯酸、氨基己酸,抗血小板黏附和聚集的阿司匹林、双密达莫和小分子右旋糖酥。
** 休克的治疗/皮质类固醇和其他药物的应用 #card
:PROPERTIES:
:id: 624d23b2-3fa7-46d6-a2ca-7e2d4b60ab84
:END:
*** 7.皮质类固醇和其他药物的应用 皮质类固醇可用于感染性休克和其他较严重的休克。其作用主要有:① <span style="color:yellow;">阻断a受体兴奋作用,使血管扩张</span>,降低外周血管阻力,改善微循环;② <span style="color:yellow;">保护细胞内溶酶体</span>,防止溶酶体破裂;③增强心肌收缩力,增加心排血量;④增进线粒体功能和防止白细胞凝集;⑤ <span style="color:yellow;">促进糖异生,使乳酸转化为葡萄糖,减轻酸中毒</span>。 <span style="color:yellow;">一般主张应用大剂量,静脉滴注,一次滴完。为了防止多用皮质类固醇后可能产生的副作用,一般只用1~2次。</span>
休克纠正后可以考虑加强营养代谢支持和免疫调节治疗,适当的肠内和肠外营养可减少组织的分解代谢。联合应用生长激素和谷氨酰胺具有协同作用。谷氨酰胺是肠黏膜细胞的主要能源物质及核酸的合成物质。
其他类药物包括:①钙通道阻断剂如维拉帕米、硝苯地平和地尔硫革等,具有防止钙离子内流、保护细胞结构与功能的作用;②吗啡类拮抗剂纳洛酮,可改善组织血液灌流和防止细胞功能失常;③氧自由基清除剂如超氧化物歧化酶(SOD),能减轻缺血再灌注损伤中氧自由基对组织的破坏作用;④调节体内前列腺素(PGS),如输注前列环素(PGL)以改善微循环;⑤应用三磷腺昔-氯化镁(ATP-MgCI,)疗法,具有增加细胞内能量、恢复细胞膜钠-钾泵的作用及防治细胞肿胀和恢复细胞功能的效果。需要指出的是,这些药物只发挥辅助作用,临床效果尚不肯定,不是休克治疗中的首选药物。
休克复苏过程中需要动态评估其变化。除观察生命体征指标外,近年来越来越重视其他指标的动态监测,包括:乳酸、碱剩余、心排量、氧转运及氧耗、组织的pH、氧含量、二氧化碳含量、细胞膜电势等。这些指标与组织细胞的灌注和代谢相关。一般认为乳酸和碱剩余是评估缺氧状态、组织酸中毒、无氧代谢程度较好的间接指标,对评估预后也有重要作用。