#+title: 外科学/外科学总论/创伤/教材/创伤概论
#+deck: 外科学::外科学总论::创伤::教材::创伤概论

* 创伤
** 创伤/概念 #card
:PROPERTIES:
:id: 624f9c65-858d-4bf9-b6cc-73094d7ec89e
:END:
*** 狭义的创伤是指机械性致伤因素作用于人体所造成的 <span style="color:yellow;">组织结构完整性的破坏或功能障碍</span>;而广义上讲,物理、化学、心理等因素对人体造成的伤害也可称为创伤。
** 创伤/分类 #card
:PROPERTIES:
:id: 624f9c6e-ba1f-4b6c-bb80-568b12898ccc
:END:
*** 1.按致伤机制分类 可分为挫伤、擦伤、刺伤、切割伤、挤压伤、撞击伤、火器伤等。
*** 2.按受伤部位分类一般分为头部伤、领面部伤、颈部伤、胸(背)部伤、腹(腰)部伤、骨盆伤、脊柱脊髓伤、四肢伤和多发伤等。诊治时需进一步明确受伤的组织和器官,如软组织损伤、骨折、脱位或内脏损伤等。
*** 3.按伤后皮肤或黏膜完整性分类 皮肤或黏膜完整无伤口者称闭合伤(closed injury),如挫伤 (contusion)、挤压伤(crush injury)、扭伤(sprain)、震荡伤(concussion)、关节脱位和半脱位、闭合性骨折和闭合性内脏伤等。有皮肤或黏膜破损者称开放伤(opened injury),如擦伤(abrasion)、撕裂伤(lac-eration)、切割伤、砍伤和刺伤等。在开放伤中,又可根据伤道类型再分为贯通伤(既有入口又有出口者)和盲管伤(只有人口没有出口者)等。一般而言,开放伤易发伤口感染,但某些闭合性伤如肠破裂等可造成严重的感染。
*** 4.按伤情轻重分类 一般分为轻度、中度和重度伤。
**** 组织器官结构轻 <span style="color:yellow;">度损害或部分功能障碍,无生命危险,预后良好者</span>为轻度伤;
**** 组织器官结构 <span style="color:yellow;">损害较重或有较严重的功能障碍,有一定生命危险,预后对健康有一定伤害者</span>为中度伤;
**** 组织器官结构 <span style="color:yellow;">严重损伤和功能障碍,通常危险生命,预后对健康有较大伤害者为重度伤</span>。
**** 创伤评分是一种相对量化的分类方法,是以计分的形式估计创伤的严重程度。一般用量化和权重处理的方法,选择生命体征、解剖部位的损伤严重度和其他指标(如年龄、既往疾病、生化指标等)作为参数,经数学计算而得,并以分值大小反映伤员伤情的轻重。创伤评分的方法较多,可分为院前评分和院内评分两类,分别用于自受伤到医院确定性诊断前和医院内伤员伤情严重程度的判断。常 用的主要有院前指数(prehospital index, PHI)、创伤指数(trauma index, TI)、简明损伤定级(abbreviated injury scale, AIS)和损伤严重度评分(injury severity score, ISS)等
** 创伤/病理/梗概 #card
:PROPERTIES:
:id: 624f9c75-9a1d-4f2b-af42-3127193605b6
:END:
*** 局部反应
*** 全身反应
*** 组织修复和创伤愈合
*** 创伤愈合类型
*** 影响创伤愈合的因素
* 创伤/病理/
** 创伤/病理/局部反应 #card
:PROPERTIES:
:id: 39e42b1b-4d93-4ed9-9b68-5d6752bc650d
:END:
*** 1.局部反应 是由于组织结构破坏,或细胞变性坏死、微循环障碍,或病原微生物入侵及异物存留等所致。 <span style="color:yellow;">主要表现为局部炎症反应,其基本病理过程与一般炎症相同。</span>局部反应的轻重与致伤因素的种类、作用时间、组织损害程度和性质,以及污染轻重和是否有异物存留等有关。严重创伤时,由于局部组织细胞损伤较重,多存在组织结构破坏及邻近组织细胞严重变性坏死,加之伤口常有污染、异物存留、局部微循环障碍及各种化学物质生成而造成的继发性损伤,从而使局部炎症反应更为严重,血管通透性及渗出更加明显,局部炎症细胞浸润更为显著,炎症持续时间可能更长,对全身的影响将更大。创伤性炎症反应是非特异性的防御反应,有利于清除坏死组织、杀灭细菌及组织修复。
** 创伤/病理/全身反应 #card
:PROPERTIES:
:id: 0fb73c10-ff73-4984-a3a5-a8a6b0c687d6
:END:
*** 2.全身反应 是致伤因素作用于人体后引起的一系列神经内分泌活动增强并由此而引发的各种功能和代谢改变的过程 <span style="color:yellow;">,是一种非特异性应激反应</span>。表现为综合性的复杂过程,不仅包括神经内分泌系统和物质能量代谢,还涉及凝血系统、免疫系统、重要的生命器官和一些炎症介质及细胞因子等。 <span style="color:red;">神经内分泌系统通过下丘脑-垂体-肾上腺皮质轴和交感神经-肾上腺髓质轴产生大量的儿茶酚胺、肾上腺皮质激素、抗利尿激素、生长激素和胰高血糖素;</span> <span style="color:yellow;">同时,肾素-血管紧张素-醛固酮系统也被激活。</span>上述三个系统相互协调,共同调节全身各器官功能和代谢,动员机体的代偿能力,以对抗致伤因素的损害作用。 <span style="color:yellow;">由于神经内分泌系统的作用,伤后机体总体上处于一种分解代谢的状态,表现为基础代谢率增高,能量消耗增加,糖、蛋白质、脂肪分解加速,糖异生增加。</span>因此伤后常出现高血糖、高乳酸血症,血中游离脂肪酸和酮体增加,尿素氮排出增加,从而出现负氮平衡状态。水、电解质代谢素乱可导致水、钠猪留,钾排出增多及钙、磷代谢异常等。
** 创伤/病理/组织修复和创伤愈合/
*** 创伤/病理/组织修复和创伤愈合/梗概 #card
:PROPERTIES:
:id: 624f9f64-50a3-40c2-95fc-d58663db38ce
:END:
**** <span style="color:red;">组织修复的基本方式是由伤后增生的细胞和细胞间质再生增殖、充填、连接或替代损伤后的缺损组织。</span>
**** 理想的修复是组织缺损 <span style="color:yellow;">完全由原来性质的细胞来修复,恢复原有的结构和功能,称为完全修复</span>。但由于人体各种组织细胞固有的再生增殖能力不同,使各种组织创伤后修复情况差别较大。
**** <span style="color:yellow;">因此,创伤后多见的组织修复方式是不完全修复</span>,即组织损伤不能由原来性质的细胞修复,而是由其他性质细胞(常是成纤维细胞)增生替代来完成。
*****
** 创伤/病理/组织修复和创伤愈合/组织修复的基本过程: #card
:PROPERTIES:
:id: 624f9fbf-d528-4b88-87d9-713be6fa0013
:END:
*** 大致可分为 <span style="color:yellow;">三个既相互区分又相互联系的阶段:</span>
**** ①局部炎症反应阶段:在创伤后立即发生,常可持续3~5天。 <span style="color:yellow;">主要是血管和细胞反应、免疫应答、血液凝固和纤维蛋白的溶解</span>,目的在于清除损伤或坏死的组织,为组织再生和修复莫定基础。
**** ②细胞增殖分化和肉芽组织生成阶段: <span style="color:yellow;">局部炎症开始不久,即可有新生细胞出现。成纤维细胞、内皮细胞等增殖、分化、迁移,分别合成、分泌组织基质(主要为胶原)和形成新生毛细血管,并共同构成肉芽组织。</span>浅表的损伤一般通过上皮细胞的增殖、迁移,可覆盖创面而修复。 <span style="color:yellow;">但大多数软组织损伤则需要通过肉芽组织生成的形式来完成。</span>
**** ③组织塑形阶段: <span style="color:yellow;">经过细胞增殖和基质沉积,伤处组织可达到初步修复</span>,但新生组织如纤维组织,在数量和质量方面并不一定能达到结构和功能的要求,故需进一步改构和重建。主要包括胶原纤维交联增加、强度增加;多余的胶原纤维被胶原蛋白酶降解;过度丰富的毛细血管网消退和伤口的黏蛋白及水分减少等。
** 创伤/病理/组织修复和创伤愈合/创伤愈合的类型: #card
:PROPERTIES:
:id: 624f9f76-9924-4818-9031-a5273b0bf4c6
:END:
*** 可分为两种:
*** ①一期愈合: <span style="color:yellow;">组织修复以原来的细胞为主,仅含少量纤维组织,局部无感染、血肿或坏死组织,再生修复过程迅速,结构和功能修复良好。</span>多见于损伤程度轻、范围小、无感染的伤口或创面。
*** ②二期愈合: <span style="color:yellow;">以纤维组织修复为主,不同程度地影响结构和功能恢复,多见于损伤程度重、范围大、坏死组织多,且常伴有感染而未经合理的早期外科处理的伤口。</span>因此,在创伤治疗时,应采取合理的措施,创造条件,争取达到一期愈合。
** 创伤/病理/组织修复和创伤愈合/影响创伤愈合的因素: #card
:PROPERTIES:
:id: 624f9f7e-ea40-4e12-ac96-eb32a70c111c
:END:
*** 主要有局部和全身两个方面。
**** 局部因素中伤口感染是最常见的原因。 <span style="color:red;">细菌感染可损害细胞和基质,导致局部炎症持久不易消退,甚至形成化脓性病灶等,均不利于组织修复及创伤愈合。</span>
**** 损伤范围大、坏死组织多,或有异物存留的伤口,伤缘往往不能直接对合,且被新生细胞和基质连接阻隔,必然影响修复。
**** <span style="color:red;">局部血液循环障碍使组织缺血缺氧,或由于采取的措施不当(如局部制动不足,包扎或缝合过紧等)造成组织继发性损伤也不利于愈合。</span>
*** 全身因素 <span style="color:red;">主要有营养不良</span>(蛋白质、维生素、铁、铜、锌等微量元素缺乏或代谢异常)、 <span style="color:red;">大量使用细胞增生抑制剂</span>(如皮质激素等)、 <span style="color:red;">免疫功能低下及全身性严重并发症</span>(如多器官功能不全)等。因此,在创伤处理时,应重视影响创伤愈合的因素,并积极采取相应的措施予以纠正。
* 创伤/病理/创伤并发症/ #card
:PROPERTIES:
:id: 624fa412-c249-4651-b2e1-24c42fb53ab8
:END:
** 严重创伤后,由于组织或器官损伤,局部及全身器官功能和代谢素乱,易发生较多的并发症,可影响伤员的伤情及病程的发展和预后。故对创伤并发症应有足够的警惕性,要密切观察,早期诊断,积极采取措施预防和处理。常见的并发症有以下几种:
** (1 <span style="color:yellow;">)感染</span>:开放性创伤一般都有污染,如果污染严重,处理不及时或不当,加之免疫功能降低,很容易发生感染。闭合性创伤如累及消化道或呼吸道,也容易发生感染。初期可为局部感染,重者可迅速扩散成全身感染。特别是广泛软组织损伤,伤道较深,并有大量坏死组织存在,且污染较重者,还应注意发生厌氧菌(破伤风或气性坏疽)感染的可能。
** (2) <span style="color:yellow;">休克:</span>早期常为失血性休克,晚期由于感染发生可导致脓毒症,甚至脓毒性休克。
** (3) <span style="color:yellow;">脂肪栓塞综合征</span>:常见于多发性骨折,主要病变部位是肺,可造成肺通气功能障碍甚至呼吸功能不全。
** (4) <span style="color:yellow;">应激性溃疡</span>:发生率较高,多见于胃、十二指肠,小肠和食管也可发生。溃疡可为多发性,有的面积较大,且可深至浆膜层,可发生大出血或穿孔。
** (5) <span style="color:yellow;">凝血功能障碍:</span>主要是由于凝血物质消耗、缺乏,抗凝系统活跃,低体温和酸中毒等,常表现为出血倾向。凝血功能障碍、低体温和酸中毒被称为“死亡三联征”,是重症创伤死亡的重要原因一。
** (6) <span style="color:yellow;">器官功能障碍</span>:创伤多伴有组织的严重损伤,存在大量的坏死组织,可造成机体严重而持久的炎症反应,加之休克、应激、免疫功能素乱及全身因素的作用,容易并发急性肾衰竭、急性呼吸窘迫综合征等严重内脏并发症。此外,由于缺血缺氧、毒性产物、炎症介质和细胞因子的作用,还可发生心脏和肝脏功能损害。
** (7) <span style="color:yellow;">创伤后应激障碍</span>:经历创伤事件后,延迟出现和(或)长期持续的精神障碍。目前关于其产生,机制主要包括以下方面:脑内的记忆系统素乱,神经内分泌功能素乱,易感性和神经解剖改变等。临床表现主要为反复重现创伤性体验,持续性回避,持续性焦虑和警觉水平增高,常在创伤后数天,甚至数月后才出现(很少超过6个月),病程可长达多年。治疗方式主要为心理治疗和药物治疗及家庭治疗。