#+title: 外科学/普通外科/乳房疾病/教材/急性乳腺炎
#+deck: 外科学::普通外科::乳房疾病::教材::急性乳腺炎

* 急性乳腺炎的定义 
:PROPERTIES:
:id: 625178b1-e4ee-4168-8bd5-0658c7fd085b
:END:
** <span class="tested">急性乳腺炎(acute mastitis)是乳腺的急性化脓性感染,多为产后哺乳的妇女,尤以初产妇更为多见,往往发生在产后3~4周</span>。因乳房血管丰富,早期就可出现寒战、高热及脉搏快速等脓毒血症表现。
*
* 急性乳腺炎/病因 
:PROPERTIES:
:id: 625178f0-98ea-448f-9d7e-5e691c7e8e4e
:END:
** 1.乳汁淤积  <span class="untestedHL">乳汁是理想的培养基,乳汁淤积将有利于入侵细菌的生长繁殖</span>。
** 2.细菌入侵  <span class="untestedHL">乳头破损或被裂,使细菌沿淋巴管入侵是感染的主要途径</span>。细菌也可直接侵人乳管,上行至腺小叶而致感染。多数发生于初产妇。也可发生于断奶时,因6个月以后的婴儿已长牙,易致乳头损伤。 <span class="untestedHL">致病菌主要为金黄色葡萄球菌。</span>
* 急性乳腺炎/临床表现 
:PROPERTIES:
:id: 62517974-bf0d-42cf-b485-1e4170b412ff
:END:
** <span class="untestedHL">局部症状 病人感觉乳房疼痛、局部红肿、发热。</span>
** <span class="untestedHL">全身症状: 随着炎症发展，可有寒战、高热、脉搏加快,常有病侧淋巴结肿大、压痛,白细胞计数明显增高。</span>
** 肿肿形成或破溃: 局部表现可有个体差异(图23-4)。 <span class="untestedHL">一般起初呈蜂窝织炎样表现,数天后可形成脓肿,脓肿可以是单房或多房性。脓肿可向外溃破，深部脓肿还可穿至乳房与胸肌间的疏松组织中</span>， <span class="untestedHL">形成乳房后服肿</span>（retromammary abscess）。感染严重者，可并发脓毒症。 <span class="tested">当局部有波动感或超声证明有脓肿形成时，应在压痛最明显的炎症区或超声定位下进行穿刺，抽到脓液表示脓肿已形成，脓液应作细菌培养及药物敏感试验。</span>
* 急性乳腺炎/治疗 
:PROPERTIES:
:id: 62517a84-388f-4b95-a15a-644353f2bcc0
:END:
** <span class="untestedHL">【治疗】原则是消除感染、排空乳汁。
</span>
** 脓肿未形成时,给予抗生素治疗
*** 早期呈蜂窝织炎表现而未形成脓肿之前,应用抗生素可获得良好的效果。 <span class="untestedHL">因主要病原菌为金黄色葡萄球菌,可不必等待细菌培养的结果,应用青霉素治疗,或用耐青霉素酶的苯唑西林钠(新青霉素I),或头孢一代抗生素如头孢拉啶。</span>
*** <span class="untestedHL">对青霉素过敏者,则应用红霉素。</span>
*** <span class="untestedHL">抗生素通过乳汁而影响婴儿的健康,因此如四环素、氨基糖苷类、喹诺酮类,磺胺药和甲硝唑等药物应避免使用。</span>
** 脓肿形成后作切开引流
*** <span class="tested">脓肿形成后,主要治疗措施是及时作脓肿切开引流。手术时要有良好的麻醉,为避免损伤乳管而形成乳痿,应作放射状切开,乳晕下脓肿应沿乳晕边缘作弧形切口(图23-5)</span>
*** <span class="tested">深部脓肿或乳房后胀肿可沿乳房下缘作弧形切口,经乳房后间隙引流。切开后以手指轻轻分离脓肿的分隔,以利引流。脓腔较大时,可在脓腔的最低部位另加切口作对口引流(图23-6)。</span>
*** <span class="untestedHL">一般不停止哺乳,因停止哺乳不仅影响婴儿喂养,且提供了乳汁淤积的机会。</span> <span class="untestedHL">但病侧乳房应停止哺乳,并以吸乳器吸尽乳汁,促使乳汁通畅排出。</span> <span class="untestedHL">若感染严重或脓肿引流后并发乳痿,应停止哺乳。可口服澳隐亭1.25mg,每日2次,服用7~14天,或己烯雌酸1~2mg,每日3次,共2~3日,或肌内注射苯甲酸雌二醇,每次2mg,每日1次,至乳汁停止分泌为止。</span>
* 急性乳腺炎/预防
** 【预防】 <span class="untestedHL">关键在于避免乳汁淤积,防止乳头损伤,并保持其清洁。</span>应加强孕期卫生宣教,指导产妇经常用温水、肥皂洗净两侧乳头。如有乳头内陷,可经常挤捏、提拉矫正之。要养成定时哺乳、婴儿不含乳头而睡等良好习惯。每次哺乳应将乳汁吸空,如有淤积,可按摩或用吸乳器排尽乳汁。哺乳后应清洗乳头。乳头有破损或皲裂要及时治疗。注意婴儿口腔卫生。
*