:PROPERTIES:
:id: 6274ee90-177f-4be5-a03a-62a20d09f9ae
:END:
1. 2016N179X 髌骨骨折的治疗原则是
A.解剖复位，保持关节面平滑
B.尽可能保留髌骨
C.稳定固定的情况下早期活动
D.屈曲位膝关节固定
答案：ABC 
#+BEGIN_QUOTE
A 废话,要不要解剖复位?关节内骨折如果不解剖复位容易引起创伤性关节炎
B 
C 废话 并不是一来就直接活动
D 应该是功能位固定 比如手外伤是握球位.
 #+END_QUOTE 
#+BEGIN_QUOTE
（P665）&“【治疗】 无移位的髌骨骨折采用非手术方法治疗。保持膝关节伸直位，用石膏托或下肢支具固定4～6周（D错），即可开始股四头肌等长收缩训练（C对）”。（P666）&“髌骨的粉碎骨折如果关节软骨面不平整，均应行手术治疗，恢复关节面的平滑（A对），复位后用钢丝环绕捆扎固定”。（P666）&“对严重粉碎骨折，无法恢复髌骨软骨面完整性时，可摘除髌骨，修补韧带，术后3-4周开始进行功能锻炼”。
#+END_QUOTE 
#+BEGIN_QUOTE
七版黄家驷外科学P2859页认为，髌骨骨折的治疗原则是：①尽可能保留髌骨；②充分恢复其后关节面的平整；③修复股四头肌扩张部分的裂伤；④早期锻炼股四头肌；⑤在尽可能条件下，早期练习膝关节的伸屈活动，以期通过模造，使髌股关节恢复吻合（C对）。解剖复位，保持关节面平滑（A对），否则容易引起髌股关节的骨关节病。尽可能保留髌骨（B对），切除髌骨易导致股四头肌的伸膝功能及控制膝关节的能力受损。髌骨骨折应保持膝关节伸直位固定（D错）。
#+END_QUOTE

* 1. 2017N65A 男，80岁，摔倒后致右髋部疼痛2天，平素体健。X线检查见右股骨颈头下型骨折，有移位。最合适的治疗方法是
A.皮牵引
B.人工股骨头置换术
C.切开复位内固定
D.卧床休息，穿防旋转鞋
答案：B 
#+BEGIN_QUOTE
该患者至少为Garden ⅢⅣ型; Ⅰ型不移位,Ⅱ型嵌插移位.
若老年人暗示体差需要过渡.此题平素体健
考虑此老年人年龄大.半换就足够了
#+END_QUOTE 
#+BEGIN_QUOTE
老年患者，右股骨颈头下型骨折，有移位，该患者一般情况较好，最合适的治疗方法是人工股骨头置换术（B对）。股骨颈头下型骨折易造成股骨头缺血坏死，高龄病人若发生该型骨折，难以自我恢复，应使用股骨头置换术或全髋关节置换术。皮牵引（A错）和卧床休息，穿防旋转鞋（D错）用于年龄过大，全身情况差等不可耐受手术者。切开复位内固定（C错）用于手法复位失败，或固定不可靠，或青壮年的陈旧骨折不愈合等情况。
#+END_QUOTE
* 1. 2018N164X 关于肱骨外科颈骨折，下列说法正确的有
A.多见于中老年人
B.可合并血管神经损伤
C.可合并肱骨头碎裂骨折
D.有侧方和成角移位者须手术治疗
答案：ABC 
#+BEGIN_QUOTE
与股骨颈与股骨转子间的骨折类比 都好发于中老年人
首先想到Neol分型
若Ⅰ或轻度Ⅱ 则采取三角巾固定
重度Neol Ⅱ以上采用手术内固定
老年人Neoll IV: 换关节
并不是说有移位有成角就需要手术,且移位达到一定程度才能有标准
#+END_QUOTE 
#+BEGIN_QUOTE
（P632）&“在解剖颈下较近部位，有臂丛神经、腋血管通过，有发生骨折合并血管神经损伤的可能”（B对）。（P632）&“肱骨近端骨折可发生于任何年龄，但以中、老年人为多”（A对）。（四版实用外科学P2120）&“老年人可出现嵌插型骨折，如外力强大，骨质亦较疏松脆弱，即可发生不同程度的粉碎骨折”（C对）。
#+END_QUOTE 
#+BEGIN_QUOTE
肱骨外科颈骨折主要是因间接外力所致，可发生于任何年龄，多见于中老年人（A对）。在解剖颈下2～3cm，有臂丛神经、腋血管通过，可合并血管神经损伤（B对）。如撞击外力强大，骨质亦较疏松脆弱，可合并肱骨头碎裂骨折（C对），肱骨外科颈骨折切开复位适应证包括：三型骨折、开放性二型骨折或二型骨折闭合复位失败，伴血管神经损伤，肩关节脱位者或治疗较晚不能手法复位者，有侧方和成角移位者需根据位移的情况和患者本身的实际状况来决定是否手术（D错）。
#+END_QUOTE
* 10. 2020N103A 男性，50岁。因车轮碾压致左前臂外伤5小时。查体：神志清楚，左前臂明显肿胀疼痛，皮肤瘀斑，出血，成角畸形(若不是两根一起断另一根可起到固定作用())。应首先考虑的诊断是
A.桡骨头脱位
B.尺骨骨折
C.桡骨骨折
D.尺、桡骨骨折
答案：D 
#+BEGIN_QUOTE
从骨间膜的角度与成角畸形角度都提示为双骨折
#+END_QUOTE 
#+BEGIN_QUOTE
50岁男性患者，前臂碾压外伤史（尺桡骨骨折常见原因），查体患者基本情况良好，左前臂明显肿胀疼痛，皮肤瘀斑、出血，成角畸形（尺桡骨骨折临床表现），根据该患者受伤史、临床表现和体征，应诊断为尺、桡骨骨折（前臂双骨折）（D对）。尺骨骨折（B错）在西方被称之为“警棍骨折”，其多由于防护性动作致伤，多为直接碰撞、打击所引起，如摔倒时前臂内侧（尺侧）先着地，因尺骨位于皮下，配合前臂正侧位X光检查，易于诊断。桡骨骨折（C错）发生率少于尺骨骨折，多发生于青壮年或儿童，多有旋转移位，患者前臂旋后运动完全丧失，患侧手向桡侧屈曲或旋转前臂，旋转范围可不受限，但因其局部疼痛加剧，配合前臂正侧位X光检查，易于诊断。桡骨头脱位（A错）俗称牵拉肘，是小儿多见的日常损伤，多见于5岁以内儿童，为肘关节处于伸直位时，前臂旋前时突然受到牵拉致伤，查体前臂多呈旋前位半屈，患者多有哭闹，不肯使用患肢特别是举起前臂，桡骨头处可有压痛，但无肿胀及畸形，肘关节活动明显受限。
#+END_QUOTE
* 11. 2020N104A 男性，50岁。因车轮碾压致左前臂外伤6小时。查体：神志清楚，左前臂明显肿胀疼痛，皮肤瘀斑，出血，成角畸形。该患者治疗方案选择手法复位外固定的依据是
A.受伤时间较短的开放性骨折
B.稳定性骨折
C.神经血管损伤
D.合并肌腱损伤
答案：B 
#+BEGIN_QUOTE
重点是:一根为稳定性骨折,另一根是不稳定的先复位哪一个?
先复位稳定的,因为先固定好后通过骨间膜能够更容易复位下一个
若两个都为不稳定的则复位大的,桡骨在下段大,尺骨在上段大.中段则前弄浅的,尺骨更浅.

注意8-10周的问题 是前臂的旋转训练.一般2-4周就可以训练了.
#+END_QUOTE 
#+BEGIN_QUOTE
（P640）&“2.切开复位内固定（1）手术指征：①手法复位失败；②受伤时间较短、伤口污染不重的开放性骨折（A错）；③合并神经、血管、肌腱损伤（CD错）；④同侧肢体有多发性损伤；⑤陈旧骨折畸形愈合”。
#+END_QUOTE 
#+BEGIN_QUOTE
50岁男性患者，前臂碾压外伤史（尺桡骨骨折常见原因），查体患者基本情况良好，左前臂明显肿胀疼痛，皮肤瘀斑、出血，成角畸形（尺桡骨骨折临床表现），根据该患者受伤史、临床表现和体征，应诊断为尺、桡骨骨折（前臂双骨折），对于一些位移不显著，较为稳定的骨折，在臂神经丛阻滞下进行手法复位外固定，可以得到满意的闭合复位（B对），前臂双骨折可接受的整复标准是：桡骨旋转畸形不能大于30°，尺骨旋转畸形不能大于10°，尺桡骨的成角畸形不得大于10°（不符合以上标准的，应直接进行手术切开复位内固定，以便获得良好的功能结果）（七版黄家驷外科学P2799）。损伤时间较短的开放性骨折（A错）、合并血管神经损伤（C错）、伴有肌腱损伤（D错）属于切开复位内固定的手术指征。
#+END_QUOTE
* 12. 2020N105A 男性，50岁。因车轮碾压致左前臂外伤6小时。查体：神志清楚，左前臂明显肿胀疼痛，皮肤瘀斑，出血，成角畸形。患者经手法复位，小夹板固定4小时后，感觉患肢剧痛，手指麻木，肿胀，活动时疼痛加重，可能的原因是
A.神经损伤
B.骨筋膜室综合征
C.急性骨髓炎
D.缺血性骨坏死
答案：B 
#+BEGIN_QUOTE
5 P 综合征 痛 麻 白 无 常 (痛骂白无常)
无痛、苍白、感觉异常、麻痹、无脉
#+END_QUOTE 
#+BEGIN_QUOTE
（P616）&“5.骨筋膜室综合征…常见于前臂掌侧和小腿，多由创伤骨折后水肿和组织水肿引起骨筋膜室内内容物体积增加，或外包扎过紧，局部压迫使骨筋膜室容积减小而导致骨筋膜室内压力增高所致…可根据以下四个体征确定诊断：①病肢感觉异常；②被动牵拉受累肌肉出现疼痛（肌肉被动牵拉试验阳性）；③肌肉在主动屈曲时出现疼痛；④筋膜室即肌处有压痛”（三版八年制外科学P869）&“严重尺、桡骨干骨折可合并神经血管损伤，或因严重肿胀发生骨筋膜室高压，应仔细观察临床症状及检查手的血液循环及神经功能”（B对）。
#+END_QUOTE
* 6岁男孩，摔倒时左手撑地，即出现左肘部疼痛肿胀，桡动脉搏动减弱。局部检查明显压痛，有骨摩擦音，肘前方可扪及骨折断端。最可能的诊断是
A.桡骨头半脱位
B.桡骨头骨折
C.肱骨髁上骨折
D.肱骨干骨折
E.尺骨鹰嘴骨折
答案：C 
#+BEGIN_QUOTE
肱骨髁上骨折好发于10岁以下儿童
桡骨远端Colles好发于中老年
#+END_QUOTE
* 男性，35岁，因车祸右小腿受伤，经拍X线片，诊断为右胫骨中下1/3交界处斜型骨折，其易发生
A.骨筋膜室综合征
B.脂肪栓塞
C.延迟愈合或不愈合
D.血管损伤
E.神经损伤
答案：C 
#+BEGIN_QUOTE
（P694）&“【解剖概要】…胫骨的营养血管从胫骨干上、中1/3交界处进入骨内，在中、下1/3的骨折使营养动脉损伤，供应下1/3段胫骨的血液循环显著减少；同时下1/3段胫骨几乎无肌附着，由胫骨远端获得的血液循环很少，因此下1/3段骨折愈合较慢，容易发生延迟愈合或不愈合”（C对）。
#+END_QUOTE 
#+BEGIN_QUOTE
胫骨不同部位的骨折并发症总结：胫骨上1/3骨折易损伤胫后动脉而致下肢缺血坏死（D错），胫骨中1/3骨折易发生骨筋膜室综合征（A错），胫骨中下1/3骨折易并发骨折延迟愈合或不愈合（C对）。腓骨颈骨折易并发腓总神经损伤（E错）。脂肪栓塞（B错）为骨折早期并发症，多见于股骨干骨折。
#+END_QUOTE
* 3. 2020N165X 关于粘连性肩关节囊炎，正确的描述有
A.最主要的激发因素是肩部急性挫伤
B.肩盂肱关节囊粘连、僵硬，致肩关节痛和活动受限
C.颈椎病可诱发本病
D.本病有自限性
答案：BCD 
#+BEGIN_QUOTE
（P720）&“本病是因多种原因致肩盂肱关节囊炎性粘连，僵硬，以肩关节周围疼痛、各方向活动受限为特点，尤其是外展外旋和内旋后伸活动”（B对）。（P720）&“【病因】1.肩部因素…②长期过度活动，姿势不良等所产生的慢性损伤是主要的激发因素（A错）…2.肩外因素 颈椎病（C对）、心、肺、胆道疾病发生的肩部牵涉痛，因原发病长期不愈是肩部肌持续性痉挛、缺血而形成炎性病灶，转变为真正的粘连性肩关节囊炎”。（P720）&“【临床特点】1.本病有自限性（D对），一般在6～24个月可自愈，但部分不能恢复到正常功能水平”。
#+END_QUOTE 
#+BEGIN_QUOTE
粘连性肩关节囊炎又称肩周炎，俗称冻结肩，是肩周、肌腱、肌肉、滑囊及关节囊的慢性损伤性炎症，以活动时疼痛、功能受限为其临床特点，其最主要的致病激发因素是慢性致伤力，如长期过度活动，姿势不良等（A错），肩外因素如颈椎病也可诱发本病（C对）。本病病变主要发生在盂肱关节周围，肩盂肱关节囊炎性粘连，僵硬，从而产生疼痛和活动受限（B对）。肩周炎有其自然病程，有自限性（D对），早期给予理疗、针灸、适度的推拿按摩，可改善症状，但若不配合治疗和功能锻炼，将遗留不同程度的功能障碍，肩外因素所致肩周炎除局部治疗外，还需对原发病进行治疗。
#+END_QUOTE
* 6. 2021N106A 女性，50岁，右手中指晨起僵硬伴疼痛半年，近两周出现中指关节轻度肿胀及活动受限，活动患指可出现弹响伴明显疼痛，最可能诊断
A.类风湿关节炎
B.关节内游离体
C.骨关节炎
D.狭窄性腱鞘炎
答案：D 
#+BEGIN_QUOTE
（P717-P718）&“1.弹响指和弹响拇　起病缓慢。初时，晨起患指发僵、疼痛，缓慢活动后即消失。随病程延长逐渐出现弹响伴明显疼痛，严重者患指屈曲，不敢活动。各手指发病的频率依次为中、环指最多，示、拇指次之，小指最少”（三版八年制外科学P948）&“又称扳机指或弹响指。拇指为拇长屈肌腱鞘炎，又称弹响指。本病可发生于不同年龄，多见于妇女及手工劳动者”（D对）。
#+END_QUOTE 
#+BEGIN_QUOTE
中年女性患者（狭窄性腱鞘炎好发人群），右手中指晨起僵硬伴疼痛半年，近两周出现中指关节轻度肿胀及活动受限（符合狭窄性腱鞘炎病程发展表现），活动患指可出现弹响伴明显疼痛（狭窄性腱鞘炎典型体征），综合患者的病史、临床表现，该病人考虑诊断为狭窄性腱鞘炎（D对），为手指屈肌腿腿鞘炎（弹响指）。类风湿关节炎（A错）多发生于20～45岁女性，常有乏力、肌肉痛，低热和手足麻木、刺痛等全身症状，以及反复发作的、对称性、多发性小关节炎（P767）。关节内游离体（B错）为股骨头坏死没有及时修复引起的，也可见于骨关节炎，是关节软骨失去弹性后，不断磨损，软骨破裂、剥脱形成的（P723）。骨关节炎（C错）主要表现为静息痛，特点为静止或晨起时疼痛，稍微活动后减轻，但过量活动时疼痛加剧，休息后可好转，其疼痛可与天气变化、潮湿受凉等因素有关（P761）。
#+END_QUOTE
* 7. 2021N107A 女性，50岁，右手中指晨起僵硬伴疼痛半年，近两周出现中指关节轻度肿胀及活动受限，活动患指可出现弹响伴明显疼痛，目前最正确的治疗是
A.腱鞘切开减压
B.限制中指运动
C.口服糖皮质激素
D.反复按摩患处
答案：B 
#+BEGIN_QUOTE
（P718）&“1.通常在初始治疗中使用保守疗法，包括调整手部活动、夹板固定或（和）短期使用NSAID 。对于保守治疗后症状未能改善的病人，可行局部糖皮质激素注射…2.非手术治疗无效时可考虑行狭窄的腱鞘切开减压术”（B对）。
#+END_QUOTE 
#+BEGIN_QUOTE
中年女性患者（狭窄性腱鞘炎好发人群），右手中指晨起僵硬伴疼痛半年，近两周出现中指关节轻度肿胀及活动受限（符合狭窄性腱鞘炎病程发展表现），活动患指可出现弹响伴明显疼痛（狭窄性腱鞘炎典型体征），综合患者的病史、临床表现，该病人考虑诊断为狭窄性腱鞘炎，目前该患者最正确的治疗应采取保守疗法，减少手部活动、尤其是中指屈伸活动（B对），也可根据情况进行蜡疗或鞘管内注射皮质激素类药物（C错）。理疗、按摩等（D错）可根据患者实际情况作为辅助治疗措施。手术治疗即腱鞘切开减压（A错）用于注射治疗无效或症状反复者。
#+END_QUOTE
* 11. 2022N104A 男童，8岁，1天前突发“感冒”，伴寒战，体温39.5℃，同时右大腿下端疼痛、红肿、皮温增高、压痛，行走困难，怀疑急性化脓性骨髓炎。目前，对该患者最具有早期诊断价值的辅助检查是
A.X线片检查
B.MRI检查
C.CT检查
D.局部脓肿分层穿刺
答案：B 
#+BEGIN_QUOTE
（P740）&“8.MRI检查　根据MRI影像的异常信号，可以早期发现局限于骨内的炎性病灶”（P740）&“凡有下列表现均应想到有急性骨髓炎的可能：①全身中毒症状，高热寒战，局部持续性剧痛，长骨干骺端疼痛剧烈而不愿活动肢体，局部深压痛；②白细胞总数增高，中性粒细胞增高， 血培养阳性；③分层穿刺见脓液和炎性分泌物；④X线平片征象，两周左右方有变化；⑤MRI 检查具有早期诊断价值”。
#+END_QUOTE 
#+BEGIN_QUOTE
对急性化脓性骨髓炎具有早期诊断价值的检查是MRI和局部分层穿刺。MRI检查对对病灶敏感性高、特异性强，可以更早期发现长在长骨干骺端的病灶，于骨干内有炎性异常信号，还可以显示出骨膜下脓肿。局部分层穿刺对早期诊断也有重要价值，若骨膜下脓肿形成可以抽到血性脓液，但任何性质穿刺液都应作细菌培养与药物敏感试验，故对该患者最具有早期诊断价值的辅助检查是MRI（B对D错）。早期（起病后14天内）骨髓炎患儿X线平片一般正常，但于鉴别诊断有益（A错）。CT有助于评价骨膜下脓肿、软组织脓肿以及骨破坏的定位，较X线平片可以提前发现骨膜下脓肿，但对小的骨脓肿仍难以显示（C错）。
#+END_QUOTE
* 15. 2020N67A 男性，20岁。胫骨中上段慢性骨髓炎，一般情况好，体温正常，局部有流脓窦道，X线片有3cm×1cm死骨，周围包壳完整。下列选项中不考虑的治疗方式是
A.手术摘除死骨，肌瓣填塞消灭死腔
B.手术摘除死骨，庆大霉素-骨水泥珠链填塞和二期植骨
C.病灶清除术，伤口一期缝合，负压吸引
D.患肢管型石膏固定，开窗换药，全身大量应用抗生素
答案：D 
#+BEGIN_QUOTE
（P743）&“【治疗】以手术治疗为主，原则是清除死骨、炎性肉芽组织和消灭无效腔”（P743）&“1.手术指征  有死骨形成，有死腔及窦道流脓者均应手术治疗。2.手术禁忌证（1）慢性骨髓炎急性发作时不宜作病灶清除术，应以抗生素治疗为主，积脓时宜切开引流…3.手术方法 手术有下列几种方式…（2）肌瓣填塞…（6）伤口的闭合：伤口应该一期缝合，并留置负压吸引管。外固定管型石膏，开窗换药”。
#+END_QUOTE 
#+BEGIN_QUOTE
青年男性患者，胫骨中上段慢性骨髓炎，局部有流脓窦道，X片显示有3cm×1cm死骨（有死骨形成），周围包壳完整，一般情况良好，无发热，该患者的基本情况符合慢性骨髓炎手术治疗指征，手术需要解决以下三个问题：清除病灶、消灭死腔、伤口的闭合。清除病灶要摘除死骨，吸尽脓液，切除坏死组织和肉芽组织，边缘带血管组织通常也要切除。消灭死腔的方式有：碟形手术（Orr开放手术法）适用于死腔较小患者；肌瓣填塞适用于死腔较大者（A对）；抗生素骨水泥珠链如庆大霉素-骨水泥珠链填塞和二期植骨（B对）；闭式灌洗适用于小儿患者。伤口的闭合应为一期缝合，并留置负压吸引管（C对），当周围软组织缺少不能缝合时，应敞开伤口，骨腔内填充凡士林纱布或碘纺纱条，包管形石膏，开窗换药；本例患者采取手术治疗，术前需进行细菌培养和药敏试验，在术前两日开始使用抗生素为最佳，保证手术部位组织有足够的抗生素浓度，同时术后应选择针对多数致病菌有效的广谱抗生素进行全身治疗，本例患者一般情况良好，体温正常，不需大剂量使用抗生素（D错，为本题正确答案）。
#+END_QUOTE
* 9. 2021N165X 类风湿性关节炎的诊断标准
A.3个关节肿大（大于6周）
B.对称关节肿大（大于6周）
C.晨僵大于一个小时（＞6周）
D.关节畸形（＞6周）
答案：ABC 
#+BEGIN_QUOTE
（P768）&“目前国际上通用的仍是1987年美国风湿病协会修订的诊断标准：①晨起关节僵硬至少1小时（≥6周）（C对）；②3个或3个以上关节肿胀(≥6周）（A对）；③腕、掌指关节或近侧指间关节肿胀（≥6周）；④对称性关节肿胀（≥6周）（B对）；⑤皮下结节；⑥手、腕关节X线平片有明确的骨质疏松或骨侵蚀；⑦类风湿因子阳性（滴度＞1:32)。确认本病需具备4条或4条以上标准”。（P767）&“6.关节活动受限或畸形　病变持续发展，关节活动受限；晚期关节出现不同程度畸形，如手指的鹅颈畸形，掌指关节尺偏畸形，膝关节内、外翻畸形等”（D错）。
#+END_QUOTE
* 41. 2020N107A 男性，15岁。无意中发现右膝内下一圆形肿物，质硬，固定，局部无红肿热痛，X线片显示右胫骨上端有一骨性突起，皮质和松质骨以宽广的蒂与正常骨相连。目前应该采取的处理是
A.根治性瘤段切除、假体植入
B.放化疗加免疫治疗
C.肿瘤切除术
D.不需治疗，观察 
#+BEGIN_QUOTE
（P775）&“【治疗】一般不需治疗。若肿瘤生长过快，有疼痛或影响关节活动功能；影响邻骨或发生关节畸形；压迫神经、血管以及肿瘤自身发生骨折；肿瘤表面滑囊反复感染；或病变活跃有恶变可能者应行切除术”。
#+END_QUOTE 
#+BEGIN_QUOTE
青少年男性患者，无意中发现右膝内下一圆形肿物（骨软骨瘤常见发现方式），质硬，固定（骨软骨瘤可有临床表现），局部无红肿热痛（无感染表现），X线显示右胫骨上端有一骨性突起，皮质和松质骨以宽大的蒂与正常骨相连（骨软骨瘤典型影像学表现），根据患者的临床表现和影像学检查结果，最可能的诊断是骨软骨瘤，又称外生性骨疣，单发常见于儿童或青少年，好发于长骨干骺端，特别是股骨下端、胫骨上端、肱骨上端，该患者目前无明显症状，也无感染、恶变倾向，可暂不做手术，密切观察（D对ABC错），本病外科手术指征为：成年后持续生长；出现疼痛；影响关节活动；肿瘤较大影响外观；有邻近骨骼血管神经压迫；位于中轴部位，如骨盆、肩脾骨、脊柱等；怀疑有恶变倾向。
#+END_QUOTE