#+deck: 外科学::普通外科::乳房疾病::教材::乳腺囊性增生病

* 乳腺囊性增生病/定义 
:PROPERTIES:
:id: 62517d5f-459e-475a-8081-6c23158adbe0
:END:
** <span class="untestedHL">乳腺囊性增生病(breast cystic hyperplasia)亦称乳腺病</span>,是妇女的多发病,常见于中年妇女。由于对本病的不同认识,有多种命名,如乳腺小叶增生症、乳腺结构不良症、纤维囊性病等。 <span class="untestedHL">其病理形态呈多样性表现,增生可发生于腺管周围并伴有大小不等的囊肿形成,囊内含淡黄色或棕褐色液体;或腺管内表现为不同程度的乳头状增生,伴乳管囊性扩张,也有发生于小叶实质者,主要为乳管及腺泡上皮增生。</span>由于本病的临床表现有时与乳腺癌混滑,因此正确认识本病十分重要。
* 乳腺囊性增生病/临床表现 
:PROPERTIES:
:id: 62517daf-2c5a-440e-805b-9351a6b0e7a5
:END:
** 【临床表现】 <span class="tested">一侧或双侧乳房胀痛和肿块是本病的主要表现,部分病人具有周期性</span>。 <span class="tested">乳房胀痛一般于月经前明显,月经后减轻,严重者整个月经周期都有疼痛。</span> <span class="tested">体检发现一侧或双侧乳房内可有大小不一,质韧的单个或为多个的结节,可有触痛,与周围分界不清,亦可表现为弥漫性增厚。少数病人可有乳头溢液,多为浆液性或浆液血性液体。本病病程较长,发展缓慢。</span>
* 乳腺囊性增生病/诊断 
:PROPERTIES:
:id: 62517ef1-1888-4f58-a266-446d9c941429
:END:
** 【诊断】 <span class="tested">根据以上临床表现,本病的诊断并不困难。但要特别注意乳腺癌与本病有同时存在的可能,应嘱病人每隔3~6个月复查</span>。当局限性乳腺增生肿块明显时,要与乳腺癌相区别。后者肿块更明确,质地偏硬,与周围乳腺有较明显区别,有时伴腋窝淋巴结肿大,铜靶和超声检查有助于两者的鉴别。
* 乳腺囊性增生病/治疗 
:PROPERTIES:
:id: 62517f29-867d-4cf1-97b6-0f1c506cdca6
:END:
** 【治疗】 <span class="tested">本病的治疗主要是对症治疗,</span>可用中药如口服中药道遥散3~9g,每日3次。
** 药物治疗:   <span class="tested">对症状较重者,可用他莫昔芬治疗,于月经干净后5天开始口服,每天两次,每次10mg,连用15天后停药</span>。该药治疗效果较好,但因对子宫内膜及卵巢有影响而不宜长期服用。
** 对 <span class="untestedHL">局限性乳腺囊性增生病,应在月经干净后5天内复查,若肿块变软、缩小或消退,则可予以观察并继续中药治疗。</span>
** 手术治疗
*** <span class="untestedHL">若肿块无明显消退者,或在观察过程中,对局部病灶有恶性病变可疑时,应予切除并作快速病理检查</span>。如有不典型上皮增生,同时有对侧乳腺癌或有乳腺癌家族史等高危因素者,以及年龄大,肿块周围乳腺组织增生也较明显者,可作单纯乳房切除术。