#+title: 外科学/胸部外科/胸部损伤/教材/肋骨骨折
:#+deck: 外科学:胸部外科::胸部损伤::教材::肋骨骨折

*
* 外科学/胸部外科/胸部损伤/教材/肋骨骨折/好发部位 
:PROPERTIES:
:id: 62522bef-1d85-4fbd-8b30-b6e8609c4bc4
:END:
** 暴力直接作用于助骨,可使受力处肋骨向内弯曲折断,前后挤压暴力使助骨体段向外弯曲折断,发生肋骨骨折(rib fracture)。
** 第1~3肋骨粗短,且有锁骨、肩胛骨保护,不易发生骨折。但致伤暴力巨大时,也可能发生骨折,常常同时合并锁骨、肩胛骨骨折和颈部、腋部血管神经损伤。
** 第4~7肋骨较长而纤薄,易发生骨折。
** <span class="tested">第8~10肋前端肋软骨形成肋弓与胸骨相连</span>
** <span class="tested">第11~12肋前端游离,弹性都较大,不易骨折;若发生骨折,应警惕合并腹内脏器和隔肌损伤。</span>肋骨骨折处胸壁皮肤软组织完整,不与外界相通称为闭合性肋骨骨折;肋骨断端与外界相通称为开放性肋骨骨折。老年人肋骨骨质疏松,脆性较大,容易发生骨折。已有恶性肿瘤转移灶的肋骨,也容易发生病理性骨折。
** <span class="tested">多根多处肋骨骨折是指在两根以上相邻肋骨各自发生2处或以上骨折,使局部胸壁失去完整肋骨支撑而软化,在自主呼吸时出现反常运动,即吸气时软化区胸壁内陷,呼气时相对外突,导致伤员出现低通气状态,甚至诱发呼吸衰竭,称为连枷胸(flail chest)(图24-1)。</span>
* 外科学/胸部外科/胸部损伤/教材/肋骨骨折/临床表现 
:PROPERTIES:
:id: 62522c9d-41dd-4436-9f11-8d1e65f1924a
:END:
** 【临床表现】肋骨骨折断端可刺激肋间神经产生局部疼痛,在深呼吸、咳嗽或转动体位时加剧。胸痛使呼吸变浅、咳嗽无力,呼吸道分泌物增多、涨留,易致肺不张和肺部感染。胸壁可见畸形,局部明显压痛;间接挤压骨折处疼痛加重,甚至产生骨摩擦音,即可与软组织挫伤鉴别。骨折断端向内移位可刺破胸膜、肋间血管和肺组织,产生血胸、气胸、皮下气肿或略血。伤后晚期骨折断端移位发生的损伤可能造成迟发性血胸或血气胸。连枷胸的反常呼吸运动可使伤侧肺受到塌陷胸壁的压迫, <span class="untestedHL">呼吸时两侧胸腔压力的不均衡造成纵隔扑动</span>,影响肺通气,导致缺氧和二氧化碳滞留,严重时可发生呼吸和循环衰竭。连枷胸病人常伴有广泛肺挫伤、挫伤区域的肺间质或肺泡水肿导致氧弥散障碍,出现低氧血症。 <span class="untestedHL">胸部X线照片可显示肋骨骨折断裂线和断端错位,但不能显示前胸肋软骨骨折。</span>
* 外科学/胸部外科/胸部损伤/教材/肋骨骨折/治疗 
:PROPERTIES:
:id: 62522d1a-129e-4f1d-a59d-00870611535c
:END:
** <span class="tested">【治疗】肋骨骨折处理原则为有效控制疼痛、肺部物理治疗和早期活动。</span>有效镇痛能增加钝性胸伤连枷胸病人的肺活量、潮气量、功能残气量、肺顺应性和血氧分压,降低气道阻力和浮动胸壁的反常运动,有效改善肺功能。理想的镇痛治疗能够降低肺部并发症,减少机械通气,避免助骨固定手术,缩短ICU停留和住院时间,促进病人早日下床活动并降低相关治疗费用。一般肋骨骨折可采用口服或肌内注射镇痛剂,多根多处助骨骨折则需要持久有效的镇痛治疗。方法包括硬膜外镇痛、静脉镇痛、肋间神经阻滞和胸膜腔内镇痛。硬膜外镇痛可将局麻药和镇痛药持续分次地注入相应脊神经分布所在平面的硬脊膜外腔,具有区域神经阻滞的优点,镇痛效果更为完善,并可借助装置实现病人自控镇痛,也明显减少全身性静脉镇痛导致伤员嗜睡,咳嗽和自主呼吸受抑制的副作用。肋间神经阻滞镇痛时限较短,胸膜腔内镇痛效果不稳定、可能导致隔神经功能抑制。
** 1.闭合性单处肋骨骨折  <span class="tested">骨折两断端因有相邻完整的肋骨和肋间肌支撑,较少有助骨断端错位、活动和重叠。采用多头胸带或弹性胸带固定胸廓,能减少助骨断端活动、减轻疼痛。这种方法也适用于胸背部、胸侧壁多根多处肋骨骨折、胸壁软化范围小而反常呼吸运动不严重的病人。</span>
** 2.闭合性多根多处肋骨骨折  <span class="untestedHL">有效镇痛和呼吸管理是主要治疗原则。</span>咳嗽无力、呼吸道分泌物滞留的伤员,应施行纤支镜吸痰和肺部物理治疗,出现呼吸功能不全的伤员,需要气管插管呼吸机正压通气,正压通气对浮动胸壁可起到“内固定”作用。长期胸壁浮动且不能脱离呼吸机者,可施行常规手术或电视胸腔镜下固定肋骨,术中采用Judet夹板,克氏针或不锈钢丝等固定肋骨断端。因其他指征需要开胸手术时,也可同时施行助骨固定手术。
** 3.开放性肋骨骨折  <span class="untestedHL">胸壁伤口需彻底清创,选用上述方法固定肋骨断端。</span>