* 常见检查体位
** 【常见检查体位】病人的体位对直肠、肛管疾病的检查很重要，体位不当可能引起疼痛或遗漏疾病，应根据病人的身体情况和检查目的，选择不同的体位。
*** ①左侧卧位： <span class="untestedHL">病人左侧卧位[图37-6（1）]，直肠指检常采用该体位。</span>
*** ②膝胸位： <span class="untestedHL">是检查直肠肛管的常用体位[图37-6（2）]，亦是前列腺按摩的常规体位。</span>由于此体位不能持久，因此对于年老体弱及重病员，应酌情采用。
*** ③截石位： <span class="untestedHL">双合诊检查常选择该体位[图37-6（3）].</span>
*** ④蹲位： <span class="untestedHL">适用于检查直肠脱垂、三期内痔和下段息肉[图37-6（4）]。蹲位时直肠肛管承受压力最大，可使直肠下降1~2cm，可见到内痔或脱肛最严重的情况。</span>
* 直肠指诊
** 【直肠指诊】是简单而重要的临床检查方法，对及早发现肛管、直肠癌意义重大。据统计70%左右的直肠癌可在直肠指诊时被发现。
*** 直肠指诊时应注意几个步骤：
**** ①右手戴手套涂以润滑液，首先进行肛门周围指诊，肛管有无肿块、压痛，皮肤有无疣状物，有无外痔等。
**** ②测试肛管括约肌的松紧度，正常时直肠仅能伸人一指并感到肛门环缩。在肛管后方可触到肛管直肠环，
**** ③检查肛管直肠壁有无触痛，波动感、肿块及狭窄，触及肿块时要确定大小、形状、位置、硬度及能否推动。
**** ④直肠前壁距肛缘4~5cm，男性可扪及直肠壁外的前列腺，女性可扪及子宫颈，不要误诊为病理性肿块。
**** ⑤根据检查的具体要求，必要时作双合诊检查。
**** @抽出手指后，观察指套有无血迹或黏液，若有血迹而未触及病变，应行乙状结肠镜检查。
** 经肛直肠指诊可发现以下一些常见的病变。
*** <span class="tested">1.痔 内痔多较柔软不易扪及，如有血栓形成，可扪及硬结，有时有触痛、出血。</span>
*** <span class="tested">2.肛痿 沿痿外口向肛门方向延伸，双指合诊常可扪及条索状物或痿内口处小硬结。</span>
*** <span class="tested">3.直肠息肉 可扪及质软可推动的圆形肿块，多发息肉则可扪及大小不等的质软肿块，移动度大的息肉多可扪及蒂部。</span>
*** <span class="tested">4.肛管、直肠癌在肛管或示指可及的直肠内可扪及高低不平的硬结、溃疡、菜花状肿物，肠腔可有狭窄，指套上常有脓血和黏液。</span>
*** <span class="tested">5.直肠脱垂 触诊直肠腔内是否空虚，初步判定有无直肠黏膜脱垂。直肠指诊还可发现直肠肛管外的一些常见疾病，如：前列腺炎、盆腔脓肿、急性附件炎、骶前肿瘤等；如在直肠膀胱陷凹或直肠子宫陷凹触及硬结，应考虑腹腔内肿瘤的种植转移。</span>