#+title: 外科学/普通外科/肝疾病/教材/肝脓肿

* 细菌性肝脓肿
** 病因病理
*** 【病因病理】全身细菌性感染，特别是腹腔内感染时，细菌可侵入肝，如病人抵抗力弱，可发生肝脓肿。有基础性疾病，特别是糖尿病病人，是高发人群。细菌可经下列途径侵入肝：
**** ①胆道：良性或恶性病变导致胆道梗阻并发生化脓性胆管炎时，细菌沿着胆管上行，是引起细菌性肝脓肿的主要原因；
**** ②门静脉：如坏疽性阑尾炎、胃肠道想室炎等，细菌可突破肠道屏障经门静脉人肝；
**** ③肝动脉：体内任何部位的化胀性病变，如细菌性心内膜炎、化脓性骨髓炎等，当并发菌血症时，细菌可经肝动脉侵人肝；
**** ④肝毗邻器官或组织存在感染病灶，细菌可循淋巴系统侵入或直接扩散感染至肝；
**** ⑤开放性肝损伤时细菌可直接经伤口侵人肝引起感染，形成脓肿。此外，肝其他疾病的有创性治疗方法，如经肝动脉化疗栓塞、消融等肿瘤治疗措施，也可能导致肝脓肿。还有一些肝脓肿的病因难以确定，称为隐源性感染。
*** 细菌性肝脓肿（bacterial liver abscess）的致病菌多为[[肺炎克雷伯菌]]、[[大肠埃希菌]]、厌氧链球菌、葡萄球菌等。单发的肝脓肿容积有时可以很大，多发肝脓肿的直径则可在数毫米至数厘米之间，数个脓肿也可融合成一个大脓肿。
** 临床表现与辅助检查
*** 【临床表现】典型症状是寒战、高热、肝区疼痛和肝大。体温常可高达39~40℃
*** 伴恶心、呕吐、食欲缺乏和周身乏力。
*** 肝区钝痛或胀痛多属持续性，有的可伴右肩牵涉痛，右下胸及肝区叩击痛，肿大的肝有压痛；如脓肿在肝前下缘比较表浅部位时，可伴有右上腹肌紧张和局部明显触痛；巨大的肝脓肿可使右季肋呈现饱满状态，有时甚至可见局限性隆起，局部皮肤可出现红肿。严重时或并发胆道梗阻者，可出现黄疸。
*** 肝右叶脓肿可穿破肝包膜形成膈下脓肿，也可突破人右侧胸腔，左叶脓肿则偶可穿人心包。脓肿如向腹腔穿破，则发生急性腹膜炎。少数情况下，肝脓肿可穿破血管和胆管壁，引起大量出血并从胆道排出，临床表现为上消化道出血。
*** 实验室检查可见白细胞计数和中性粒性细胞百分比增高，转氨酶和碱性磷酸酶增高，CRP增高，ESR延长，慢性病程病人可有贫血和低蛋白血症。超声可明确其部位和大小，阳性诊断率可达96%以上，为首选的检查方法；CT更易显示多发小胀肿；MRI对存在可疑胆道疾病时帮助较大；X线胸腹部检查：右叶脓肿可使右膈肌升高，肝阴影增大或有局限性隆起，有时出现右侧反应性胸膜炎或胸腔积液。
** 治疗
*** 1.全身支持治疗 给予充分营养支持，必要时多次小量输血和血浆、纠正低蛋白血症，增强机体，抵抗能力，并纠正水和电解质平衡失调等。〔方案選單〕
*** 2.抗生素治疗 未确定病原菌以前，应经验性选用广谱抗生素，通常为三代头抱联合应用甲硝唑，或者氨苄西林、氨基糖昔类联合应用甲硝唑，待脓腔脓液或血液细菌培养和药敏结果回报后选用，敏感抗生素。抗生素应用应大剂量、足疗程。
*** 3.经皮肝穿刺脓肿置管引流术 对于直径在3~5cm的单个脓肿，如在超声或CT下可见到液化区域，可在其引导下行穿刺抽尽脓液并冲洗，也可置管引流。置管引流术后第二或数日起，即可用等渗盐水缓慢冲洗脓腔和注人抗菌药物。待引流管无脓液引出，病人一般情况好转，冲洗液变清亮，脓腔明显缩小，即可拔管。多数肝脓肿可经抗生素联合穿刺抽液或置管引流治愈
*** 4.手术治疗 适用于脓肿较大、分隔较多；已穿破胸腔或腹腔；胆源性肝脓肿；慢性肝脓肿。手术方式为切开引流，适用于多数病人。经腹腔镜切开引流在很多医院已成为常规手术，开腹肝脓肿切开引流已很少应用。手术中应注意用纱布妥善隔离保护腹腔和周围脏器，避免脓液污染，脓腔内安置多孔橡胶管引流。手术治疗中必须注意：①脓肿已向胸腔穿破者，应同时引流胸腔；②胆道感染引起的肝脓肿，应同时引流胆道；③血源性肝脓肿，应积极治疗原发感染灶。慢性肝脓肿，往往需施行肝切除治疗。
* 阿米巴性肝脓肿
** 阿米巴性肝脓肿（amebie liver abseess）是肠道阿米巴感染的并发症，绝大多数单发，治疗上首先考虑非手术治疗，以抗阿米巴药物（甲硝唑、氯喹、依米丁），以及必要时反复穿刺吸脓和支持疗法为主。人多数病人可获得良好疗效。
** 【治疗】
*** 1.经皮肝穿刺置管引流术 适用于病情较重，脓肿较大，有穿破危险者，或经抗阿米巴治疗及多次穿刺吸脓，而脓腔未见缩小者。
*** 2.手术切开引流适用于：①经抗阿米巴治疗及穿刺引流后仍高热不退者；②脓肿伴继发细菌感染，经穿刺引流及药物治疗不能控制者；③脓肿已穿破人胸腹腔并发脓胸和腹膜炎。切开后采用持续胸腔闭式引流，