#+title: 外科学/外科学总论/外科感染/教材/外科应用抗菌药物原则
#+deck:外科学::外科学总论::外科感染::教材::外科应用抗菌药物原则

* 抗菌药物的合理应用原则 
:PROPERTIES:
:id: 624ee476-2495-4cde-b280-35600a947b05
:END:
** 1.尽早确认致病菌  <span class="tested">对明确或怀疑外科感染者,应尽早查明致病菌并进行药敏试验,有针对性地选用抗菌药物。危重病人在未获知致病菌及药敏结果前,应在临床诊断的基础上预测最有可能的致病菌种,并结合当地细菌耐药情况,选择适当的药物进行治疗;</span>获知致病菌与药敏试验结果后,应结合之前的治疗效果对用药方案做出调整。
** 2.选择最佳的抗菌药物 各种抗菌药物均有特定的抗菌谱与适应证,不同的致病菌对药物的敏感性也不同,要根据临床诊断、细菌学检查、药物的效应及药代动力学特点(吸收、分布、代谢和排泄过程), <span class="untestedHL">选择疗效高、毒性小、应用方便、价廉易得的药物。</span>
** 3.制定合理的用药方案 制定用药方案时应考虑以下因素。
*** (1)给药途径:感染局限或较轻、可接受口服给药者,应选用口服吸收完全的抗菌药物。重症感染者,应给予静脉给药,以确保药效。
*** (2) <span class="tested">给药剂量:按各种抗菌药物的治疗剂量范围给药。</span>氨基糖昔类、喹诺酮类等剂量依赖型抗菌药,其杀菌效应与药物浓度相关,给药剂量宜偏向高限。β-内酰胺类、大环内酯类等时间依赖型抗菌药,只要血药浓度超过最低抑菌浓度(MIC)即可发挥杀菌效应,因此给药剂量宜偏向低限,维持血药浓度大于MIC水平即可。
*** (3)给药次数:根据药代动力学和药效学的原则确定给药次数。半衰期短者,如青霉素、头孢菌素类、克林霉素等,应一日给药多次;喹诺酮类、氨基糖苷类等可一日给药一次。
*** (4)疗程: <span class="untestedHL">多数外科感染经有效抗生素治疗5~7天即可控制。脓毒症抗生素的治疗疗程一般维持7~10天。抗菌药物一般在病人体温正常、白细胞计数正常、病情好转、局部病灶控制后停药。骨髓炎、感染性心内膜炎、植入物感染等常需6~12周的疗程,过早停药可使感染不易控制。</span>
*** (5)联合用药: <span class="untestedHL">联合用药的指征有:①病因未明的严重感染,包括免疫缺陷者的严重感染;②单一抗菌药物不能控制的混合感染或严重感染,如腹膜炎、盆腔炎、感染性心内膜炎、脓毒症等;③需长时间用药,病原菌易产生耐药性的感染,如结核病、尿路感染等;④减少个别药物剂量,降低毒性反应,如两性霉素B与氯胞密啶联用治疗深部真菌病。</span>
* (二)围术期预防用药的原则  
:PROPERTIES:
:id: 624ee61b-bd31-4755-af2d-006862f0d4fc
:END:
** 目的在于 <span class="untestedHL">预防和减少手术相关的外科感染</span>,包括术后切口感染、手术深部或腔隙的感染,和可能发生的全身感染。 <span class="untestedHL">预防使用抗生素的指征主要是清洁-污染手术和污染手术</span>,在一些特殊情况下,清洁手术也需要预防使用抗生素,具体介绍如下。
** 1.清洁手术  <span class="untestedHL">手术野无污染,通常不需预防用抗菌药物</span>,仅在下列情况中考虑预防用药:
*** <span class="untestedHL">①手术范围大、时间长、污染机会增加;</span>
*** <span class="untestedHL">②手术涉及重要脏器,一旦发生污染将造成严重后果者,如头颅手术、心脏手术、眼内手术等;</span>
*** <span class="untestedHL">③异物植入手术;</span>
*** <span class="untestedHL">④病人为高龄或免疫缺陷者等高危人群。</span>
** 2.清洁-污染手术 指呼吸道、消化道、泌尿道和女性生殖道手术,或经以上器官的手术, <span class="untestedHL">由于手术部位存在大量人体寄生菌群,手术时可能污染手术野造成感染,因此需预防应用抗生素</span>。
** 3.污染手术  <span class="untestedHL">指由于胃肠道、尿路、胆道体液大量溢出或开放性创伤等已造成手术野严重污染的手术,需预防应用抗生素。</span>
* 抗菌药物在特殊人群中的应用 
:PROPERTIES:
:id: 624ee747-5d1d-4e00-a518-f13420bbd60a
:END:
** (三)抗菌药物在特殊人群中的应用 病人的病理、生理及免疫状况可影响药物的作用,即使是同一种抗菌药物,在不同的病人体内吸收、分布、代谢与排泄过程也会有差异,用药时应予重视。特别是对特殊人群,用药需遵循个体化原则。
** 1.肾功能减退者 根据感染的严重程度、病原菌种类及药敏试验结果等, <span class="untestedHL">选用低肾毒性或无肾毒性的抗菌药物;必须使用肾毒性抗菌药物时,应调整给药剂量和方法。</span>
** 2.肝功能减退者 ① <span class="untestedHL">主要经肝脏清除的药物:肝功能减退可导致药物清除明显减少,若无明显毒性反应,仍可正常使用</span>,但治疗过程中需严密监测肝功能,必要时减量,若发生毒性反应,应避免使用此类药物;②经 <span class="untestedHL">肝、肾两途径清除的药物:严重肝病时应减量应用</span>;③ <span class="untestedHL">主要经肾脏清除的药物:无需调整用药剂量。</span>
** 3.老年病人 老年病人肾功能呈生理性减退,因此给药时应按轻度肾功能减退情况减量, <span class="untestedHL">即使用正常治疗量的1/2~2/3</span>;宜选用毒性低、杀菌作用强的药物, <span class="untestedHL">若必须使用高毒性药物,应同时行血药浓度监测,并及时调整剂量。</span>
** 4.新生儿病人  <span class="untestedHL">新生儿感染应避免使用毒性大的抗菌药物</span>,若确有应用指征,必须同时行血药浓度监测,并及时调整剂量;避免使用可能发生严重不良反应的抗菌药物;主要经肾脏代谢的药物需减量应用;给药方案应按新生儿日龄进行调整。
** 5.小儿病人 <span class="untestedHL">尽量避免使用有耳、肾毒性的抗生素</span>,如氨基糖昔类和万古霉素,若确有应用指征,需在使用过程中严密观察不良反应; <span class="untestedHL">四环素类抗生素可致牙齿黄染及牙釉质发育不良,</span>不可用于8岁以下小儿;喹诺酮类抗生素对骨酷发育可能产生不良影响,应避免用于18岁以下未成年人。
** 6.妊娠期病人  <span class="untestedHL">对胎儿有致畸或明显毒性作用的药物,如四环素类、喹诺酮类,应避免使用</span>。 <span class="untestedHL">对母体和胎儿均有毒性的药物,如氨基糖昔类和万古霉素,应避免使用</span>;确有应用指征时,需行血药浓度监测。对母体和胎儿均无明显影响,且无致畸作用的药物,如p-内酰胺类,适宜在妊娠期使用。
** 7.哺乳期病人 哺乳期病人使用抗菌药物,药物均可自乳汁分泌, <span class="untestedHL">不论乳汁中药物浓度如何,均可对乳儿产生潜在影响,因此,哺乳期使用任何抗菌药物均应暂停哺乳</span>。总之,合理地选择抗菌药物,既要依据致病菌的种类和药敏结果,同时还要考虑病人生理病理的
具体状况