#+title: 外科学/外科学总论/输血/教材/血液成分制品
#+deck:外科学::外科学总论::输血::教材::血液成分制品

* 血细胞成分/红细胞制品
:PROPERTIES:
:id: 624cf53e-8f6e-45d2-b18e-0a5cd38acd0b
:END:
** 血细胞成分/红细胞制品/梗概 
:PROPERTIES:
:id: 624cf6f3-6975-4ae5-a329-8a605b19b256
:END:
*** 浓缩红细胞
*** 洗涤红细胞
*** 冰冻红细胞
*** 去白细胞的红细胞
** 血细胞成分/红细胞制品/浓缩红细胞 
:PROPERTIES:
:id: 624cf6f3-31d7-4e1f-84dc-1918df609832
:END:
*** 特点
**** 每袋含 <span class="untestedHL">200ml</span>全血中的全部红细胞， <span class="untestedHL">总量 110~120ml, HCT 70% ~ 80%</span>
*** 适应证
**** <span class="tested">各种急性失血，慢性贫血及心功能不全者输血</span>
** 血细胞成分/红细胞制品/洗涤红细胞 
:PROPERTIES:
:id: 624cf6f3-bf83-4b61-976d-d75e29ee7dfe
:END:
*** 特点
**** 200ml中含红细胞170～190时，内 <span class="untestedHL">含少量血浆、无功能白细胞及血小板，去除了肝炎病毒和抗A、B抗体</span>
*** 适应证
**** 对 <span class="untestedHL">自细胞凝集素有发热反应者</span>及 <span class="untestedHL">肾功能不全</span>不能耐受库存血中之 <span class="untestedHL">高钾者</span>
** 血细胞成分/红细胞制品/冰冻红细胞 
:PROPERTIES:
:id: 624cf6f3-a29e-4a03-9486-467133e05599
:END:
*** 特点
**** 200ml 中含红细胞170~190ml， <span class="untestedHL">不含血浆</span>，在含甘油媒介中 <span class="untestedHL">-80°C或更低温度可保存3年</span>，或更长 时间，有利于稀有血型的保存
*** 适应证
**** ①同洗涤红细胞；
**** <span class="untestedHL">②自身红细胞的储存</span>
** 血细胞成分/红细胞制品/去白细胞的红细胞 
:PROPERTIES:
:id: 624cf6f3-fabf-4b27-9d4a-ceaf76e0cc1a
:END:
*** 特点
**** 200ml 全血中含（1~1.5）x10”的白细胞，去除 90％白细胞后,残留的白细胞数为 2×10⁶左右，可 减少 HLA 抗原的同种免疫反应
*** 适应证
**** ① <span class="untestedHL">多次输血</span>后产生白细胞抗体者;
**** ②预期需要长期或反复输血者
* 血细胞成分/白细胞制剂 
:PROPERTIES:
:id: 624cf6f3-1257-46bd-9455-7c85b7a61df5
:END:
** 主要有浓缩白细胞(leukocyte concentate)。 <span class="untestedHL">但由于输注后并发症多，现已较少 应用。</span>
* 血细胞成分/血小板制剂 
:PROPERTIES:
:id: 624cf6f3-c058-4672-9fbb-47f71a0eee4a
:END:
** 血小板的制备有机器单采法与手工法，前者可自由控制，且容易达到所规定的 治疗剂量,产品中红细胞和白细胞污染量低，可减少或延迟同种免疫反应，同时可最大限度地减少肝 炎等疾病的传播。
** 血小板制剂可用于 <span class="untestedHL">再生障碍性贫血和各种血小板低下的病人及大量输库存血</span>或体 外循环手术后血小板锐减的病人。
** <span class="untestedHL">成人输注1 治疗量机采血小板可使血小板数量增加约(20~30）x 10⁹/L。</span>
* 血浆成分
** 血浆成分/FPP和FP 
:PROPERTIES:
:id: 624cf91c-32af-4042-93ed-320263e7fdfc
:collapsed: true
:END:
*** 血浆成分 有新鲜冰冻血浆、冰冻血浆和冷沉淀。新鲜冰冻血浆( fresh frozen plasma., FFP) 是全血采集后 <span class="untestedHL"> 6小时内分离并立即置于-20～-30°C条件下保存的血浆</span>。冰冻血浆(frozen plasma， FP)：新鲜冰冻血浆保存 <span class="untestedHL">1年以上,5年以内</span>为普通冰冻血浆。也可以是在全血有效期内分离并置于 -30°C条件下保存的血浆。
*** FFP 和 FP 两种血浆的主要区别是 <span class="untestedHL">FP 中Ⅷ因子(FⅧ）和V因子(FV)及部分纤维蛋白原 的含量较 FFP </span>低,其他全部凝血因子和各种血浆蛋白成分含量则与 FFP 相同，
*** 二者皆适用于多种 <span class="untestedHL">凝血 因子缺乏症、肝胆疾病引起的凝血障碍和大量输库存血后的出血倾向</span>。对血友病或因  <span class="untestedHL">FⅧ和FV缺乏，引起的出血病人均可应用FFP。</span>
** 血浆成分/冷沉淀 
:PROPERTIES:
:id: 624cfa03-4a64-4640-a266-a614167da531
:collapsed: true
:END:
*** 2. 冷沉淀（ cryoprecipitate，Cryo）是 FFP 在  <span class="untestedHL">4⁰C融解时不融的沉淀物，</span>因故得名。每袋 20~30ml  <span class="untestedHL">内含纤维蛋白原(至少150mg)和 FⅧ(80 ~1201 以上）及血管性假血友病因子(wWF因子)</span>。 主要用于 <span class="untestedHL">血友病甲、先天或获得性纤维蛋白原缺乏症等。</span>
* 血浆蛋白成分 
:PROPERTIES:
:id: 624cf981-9daa-44a7-aa23-b6b41617273c
:END:
** 1. 白蛋白制剂有 <span class="untestedHL">5%、20%和25%三种浓度</span>。常用者为 20%的浓缩白蛋白液，可在室温下保 存，体积小，便于携带与运输。当稀释成 5%溶液应用时不但能提高血浆蛋白水平，且可用来补充血 容量,效果与血浆相当;如直接应用时尚有脱水作用， <span class="untestedHL">适用于治疗营养不良性水肿，肝硬化或其他原因 所致的低蛋白血症</span>。
** 2. 免疫球蛋白 包括 <span class="untestedHL">正常人免疫球蛋白(肌内注射用）、静脉注射免疫球蛋白和针对各种疾病的 免疫球蛋白(抗乙肝、抗破伤风及抗牛痘等）</span>。 <span class="untestedHL">肌注免疫球蛋白多用于预防病毒性肝炎等传染病</span>， <span class="untestedHL">静脉注射丙种球蛋白用于低球蛋白血症引起的重症感染。</span>
** 3. 浓缩凝血因子 包括 <span class="untestedHL">抗血友病因子(AHF）、凝血酶原复合物（飞因子复合物）</span>、浓缩班、X因子 及X亚因子复合物、抗凝血酶I(anti-trombin M，AT-I）和纤维蛋白原制剂等。用于 <span class="untestedHL">治疗血友病及 各种凝血因子缺乏症</span>。其中X亚因子复合物有利于促进伤口愈合。
* 血浆代用品
** 血浆代用品/右旋糖酐 
:PROPERTIES:
:id: 624cfb78-f4d9-4239-8fe2-a298b7e55ba0
:END:
*** 右旋糖酐 <span class="untestedHL"> 6％右旋糖酐等渗盐溶液</span>是常用的多糖类血浆代用品。
*** <span class="untestedHL">中分子量(平均75 000）</span>右 旋糖酐的滲透压较高，能在体内 <span class="untestedHL">维持作用6～12 小时</span>，常用于低血容量性休克、输血准备阶段以代替 血浆。
*** <span class="untestedHL">低分子(平均40 000）</span>右旋糖酐输人后在血中存留时间短， <span class="untestedHL">增加血容量的作用仅维持 1.5 小时</span>， 且具有渗透性利尿作用。
*** 由于 <span class="untestedHL">右旋糖酐有覆盖血小板和血管壁而引起出血倾向，本身又不含凝血因 子，故 24 小时用量不应超过1500ml。</span>
** 血浆代用品/羟乙基淀粉 
:PROPERTIES:
:id: 624cfb9f-6d2c-4903-a9c9-bbc87c017eab
:END:
*** 2. 羟乙基淀粉(hydroxyethyl starch，HES)代血浆 是由玉米淀粉制成的血浆代用品。 <span class="untestedHL">该 制品在体内维持作用的时间较长(24 小时尚有60％</span>）， <span class="untestedHL">目前已作为低血容量性休克的容量治疗及手术 中扩容的常用制剂</span>。临床上常用的有6%羟乙基淀粉代血浆，其中电解质的组成与血浆相近似，并含 碳酸氢根，因此除能维持胶体渗透压外，还能补充细胞外液的电解质和提供碱储备。HES 主要用于 性失血导致的低血容量纠正，一般使用时间不超过24 小时。鉴于 HES 可加重脓毒血症病人的肾损害 并增加其死亡风险，并不推荐将其应用于脓毒性休克的液体复苏。此外，HES对凝血功能亦有影响， 病人合并严重凝血功能障碍时也不宜使用。
** 血浆代用品/明胶类代血浆 
:PROPERTIES:
:id: 624cfb9f-4835-462e-a010-b41001a8ebf1
:END:
*** 3. 明胶类代血浆 是由各种明胶与电解质组合的血浆代用品。含4％ 琥珀酰明胶的血浆代用 品，其胶体渗透压可达 46.5mmHg， <span class="untestedHL">能有效地增加血浆容量、防止组织水肿</span>，因此有利于静脉回流， <span class="untestedHL">并 改善心排血量和外周组织灌注</span>。又因其相对黏稠度与血浆相似，故有血液稀释、改善微循环并加快血 液流速的效果。