* 结肠
** 1.结肠 结肠包括升结肠、横结肠、降结肠和乙状结肠，下接直肠。 <span class="untestedHL">成人结肠全长平均约150cm</span>
(120~200cm）。结肠各部直径不一，自盲肠端的7.5cm逐渐缩小为乙状结肠末端的2.5cm，这是降结肠、乙状结肠肿瘤导致结肠梗阻症状早于盲肠肿瘤的原因之一。
** <span class="untestedHL">结肠有三个解剖标志，即结肠袋、肠脂垂和结肠带，</span>对于术中寻找结肠及沿着结肠带寻找阑尾有重要的临床意义。盲肠以回盲瓣为界与回肠相连接。回盲瓣具有单向括约功能，能控制小肠内容物流入大肠的速度，以便食物在小肠内充分消化吸收，并可防止盲肠内容物逆流回小肠。在回盲瓣远侧约2cm处，有阑尾的开口。 <span class="untestedHL">由于回盲瓣的存在，结肠梗阻易发展为闭祥性肠梗阻。</span>另一方面，保留回盲瓣的短肠综合征较已切除回盲瓣的相同长度的短肠综合征的预后好。 <span class="untestedHL">盲肠为腹膜内位器官</span>，有一定的活动度，其长度在成人约为6~8cm。升结肠与横结肠延续段称为结肠肝曲，横结肠与降结肠延续段称为结肠脾曲，肝曲和脾曲是结肠相对，固定的部位。 <span class="untestedHL">升结肠和降结肠为腹膜间位器官</span>，前面及两侧有腹膜覆盖，后面以Toldt筋膜与腹后壁相贴，是由胚胎期肠系膜与后腹膜融合形成， <span class="untestedHL">故其后壁穿孔时可引起严重的腹膜后感染</span>。侧面的腹膜返折表现为白色Toldt线，可作为游离升结肠、降结肠、乙状结肠的标志。 <span class="untestedHL">横结肠和乙状结肠为腹膜内位器官</span>，完全为腹膜包裹，是结肠活动度较大的部分，乙状结肠若系膜过长易发生扭转或排便困难。
** 结肠的肠壁分为 <span class="untestedHL">浆膜层、肌层、黏膜下层和黏膜层</span>
* 直肠
** 2.直肠 直肠位于盆腔的后部，平第三骶椎处上接乙状结肠，沿骶骨、尾骨前面下行，至尾骨平面穿过盆膈移行于肛管。上部直肠与乙状结肠粗细相同，下部扩大成直肠壶腹， <span class="untestedHL">是暂存粪便的部位</span>。 <span class="untestedHL">直肠长度约12~15cm，以腹膜返折为界分为上段直肠和下段直肠。上段直肠的前面和两侧有腹膜覆盖，前面的腹膜返折形成直肠膀胱陷凹或直肠子宫陷凹。</span>如该陷凹有炎性液体或腹腔肿瘤在此种植转移时，直肠指诊可以帮助诊断；部分盆腔脓肿可在此凹陷处穿刺或切开直肠前壁进行引流。 <span class="untestedHL">下段直肠全部位于腹膜外。</span>男性直肠下段的前方借直肠膀胱隔与膀胱底、输尿管盆段、输精管壶腹、精囊腺及前列腺相邻。女性直肠下段借直肠阴道隔与阴道后壁相邻。 <span class="untestedHL">直肠后方是骶骨、尾骨和梨状肌。</span> <span class="untestedHL">外科临床工作中，亦有将直肠分为上、中、下段直肠：齿状线上5cm，10cm，15cm，分别称为下段直肠、中段直肠、上段直肠。上段直肠癌与中下段直肠癌，治疗方案上有所不同</span>。
** 直肠的肌层与结肠相同。 <span class="untestedHL">直肠环肌在直肠下端增厚而成为肛管内括约肌，属不随意肌，受自主神经支配，可协助排便，其主要功能为维持直肠静息压及保持肛管呈闭锁状态，无括约肛门的功能。</span>直肠纵肌下端与肛提肌和内、外括约肌相连。直肠黏膜紧贴肠壁，黏膜在直肠壶腹部有上、中、下三条半月形的直肠横璧，内含环肌纤维，称为直肠瓣。直肠下端由于与口径较小且呈闭缩状态的肛管相接，其黏膜呈现8~10个隆起的纵形皱璧，称为肛柱。肛柱基底之间有半月形皱璧，称为肛瓣。肛瓣与肛柱下端共同围成的小隐窝，称肛窦。窦口向上，肛门腺开口于此。窦内容易积存粪屑，易于感染而发生肛窦炎，严重者可形成肛痿或坐骨直肠窝脓肿等。肛管与肛柱连接的部位，有三角形的乳头状隆起，称为肛乳头。 <span class="untestedHL">肛瓣边缘和肛柱下端共同在直肠和肛管交界处形成一锯齿状的环形线，称齿状线</span>
（图37-1）。
** 直肠系膜：直肠系膜指的是在中下段直肠的后方和两侧包裹着直肠的半圈1.5~2.Ocm厚的结缔组织，内含动脉、静脉、淋巴组织及大量脂肪组织，上自第3骶椎前方，下达盆隔。
** 肛垫： <span class="untestedHL">位于直肠、肛管结合处，亦称直肠肛管移行区（痔区）。该区为一环状、约1.5cm宽的海绵状组织带，富含血管、结缔组织及与平滑肌纤维相混合的纤维肌性组织（Treitz肌）。Treitz肌呈网络状结构缠绕直肠静脉丛，构成一个支持性框架，将肛垫固定于内括约肌上。肛垫似一胶垫协助括约肌封闭肛门。现在认为肛垫松弛下移是痔形成的基础。</span>
* 肛管
** 3.肛管  <span class="untestedHL">肛管上自齿状线，下至肛门缘</span>，长约1.5~2cm。肛管内上部为移行上皮，下部为角化的复层扁平上皮。 <span class="untestedHL">肛管为肛管内、外括约肌所环绕</span>，平时呈环状收缩封闭肛门。肛管可分为解剖学肛管和外科学肛管。肛门部疾病主要发生在齿状线上下1.5~2cm范围内，长约3~4cm，故称外科学肛管。
** 齿状线是直肠与肛管的交界线。 <span class="untestedHL">胚胎时期，齿状线是内、外胚层的交界处。故齿状线上、下的血管、神经及淋巴来源都不同，是重要的解剖学标志，并在临床上有其重要性</span>。
括约肌间沟位于齿状线与肛缘之间，是内括约肌下缘与外括约肌皮下部的交界处，外观不甚明显，直肠指诊时可触到一浅沟，亦称白线。
* 结直肠肛管的生理功能
** 【结、直肠肛管的生理功能】 <span class="untestedHL">结肠的主要功能是吸收水分，储存和转运类便，也能吸收葡萄糖、电解质和部分胆汁酸。吸收功能主要发生于右侧结肠。此外，结肠能分泌碱性黏液以润滑黏膜，也分泌数种胃肠激素。</span>
** <span class="untestedHL">直肠有排便、吸收和分泌功能。可吸收少量的水、盐、葡萄糖和一部分药物；也能分泌黏液以利排便。</span>
** 肛管的主要功能是排泄粪便。排便过程有着非常复杂的神经反射。 <span class="tested">直肠下端是排便反射的主要发生部位，是排便功能中的重要环节，在直肠手术时应予以足够的重视。</span>
*