#+title: 生理学/消化系统/真题

* 28. 2021N136X 因体内缺乏维生素B₁₂而导致巨幼细胞性贫血的病因是
A.胃酸分泌不足
B.胃大部切除术后
C.末端回肠切除术后
D.体内产生抗内因子抗体
** 答案：ABCD
** #+BEGIN_QUOTE
- 存在于食物中的大多数维生素B₁₂是与蛋白质结合的，胃蛋白酶消化蛋白质的作用和胃内的低pH环境，能够使维生素B₁₂能从结合的形式释放出来，胃酸分泌不足时（A对），使维生素B₁₂不能由食物中的蛋白结合形式释放出来而发生维生素B₁₂缺乏，导致巨幼细胞性贫血。
- 食物中的维生素B₁₂经人体摄入后，与胃黏膜壁细胞合成的内因子结合形成复合物，内因子可保护维生素B₁₂不受胃肠道分泌液的破坏，达到回肠末端经肠上皮细胞吸收。
- 胃大部切除术后（B对）和体内产生内因子抗体（D对）时，内因子缺乏，维生素B₁₂易被胃肠道分泌液破坏，导致巨幼细胞性贫血。
- 回肠末端切除后（C对），维生素B₁₂吸收减少，导致巨幼细胞性贫血。
#+END_QUOTE
* 32. 2005N10A 下列关于胃液分泌调节的叙述，正确的是
A.头期调节属于纯神经反射
B.胃期调节包括神经长、短反射和体液调节
C.迷走神经引起的胃泌素释放可被阿托品阻断
D.肠期调节约占进食分泌总量的30％以上
E.三个时期的分泌是顺序发生，互不重叠的
答案：B
#+BEGIN_QUOTE
- （P187）&“食物直接扩张胃，刺激胃底、胃体的感受器，冲动沿迷走神经中的传入纤维传至中枢，再通过迷走神经中的传出纤维引起胃液分泌，这一反射称为迷走-迷走反射；食物扩张胃也能引起壁内神经丛短反射，直接或通过促胃液素间接引起胃腺分泌”。
- （七版生理学P176）&“阿托品可阻断迷走神经支配的壁细胞分泌，但不能阻断迷走神经引起的胃泌素分泌”。（P187）&“肠期分泌的胃液量少（约占总分泌量的10%）”。
- （七版生理学P176）&“进食后，胃液的分泌开始增多。其分泌的调节可按刺激部位的不同，将胃液分泌人为地分成头期、胃期和肠期三个时期，实际上这三个时期几乎是同时开始，互相重叠的，它们都受神经和体液因素的双重调节”。
#+END_QUOTE

#+BEGIN_QUOTE
- 头期胃液分泌以神经调节为主，但并非于纯神经调节，如存在神经-体液调节：头期神经调节的传出神经为迷走神经，迷走神经节后纤维释放铃蟾素（蛙皮素），引起促胃液素的释放，进而促进壁细胞分泌胃酸（A错）。
- 胃期调节包括神经长反射（迷走-迷走反射）、神经短反射（壁内神经丛短反射）和体液调节（促胃液素释放）（B对）。
- 支配胃黏膜壁细胞的迷走神经节后纤维释放的是ACh，可被阿托品阻断；支配G细胞引起胃泌素释放的迷走神经节后纤维释放的是铃蟾素（蛙皮素），不能被阿托品阻断（C错）。
- 肠期分泌的胃液量只占总分泌量的10%（头期30%，胃期60%）（D错），肠期分泌的胃液量不仅量少，酸度和酶的含量也不高，这可能与酸、脂肪、高张溶液进入小肠后对胃液分泌的抑制作用有关。
- 头期、胃期和肠期三个时期几乎是同时开始，互相重叠的（E错）。
#+END_QUOTE
* 39. 2006N11A 下列选项中，不属于促胃液素生理作用的是
A.刺激胃酸分泌
B.促进胃运动
C.刺激胰酶分泌
D.促进唾液分泌
E.促进胆汁分泌
答案：D

#+BEGIN_QUOTE
- （P188）&“促胃液素可强烈刺激壁细胞分泌胃酸”（A对）。
- （P191）&“促胃液素能促进胃的运动”（B对）。（七版生理学P170）&“表6-3”（C对）。
- （P196）&“促胃液素可通过血液循环作用于肝细胞引起肝胆汁分泌”（E对）。
- （P182）&“进食时唾液分泌明显增多，完全属于神经调节”（D错，为本题正确答案）。
#+END_QUOTE
* 48. 2002N121C 参与胃容受性舒张的有
A.迷走-迷走反射
B.肠-胃反射
C.二者均有
D.二者均无
答案：A 
#+BEGIN_QUOTE
容受性舒张是指进食时食物刺激口腔、咽、食管等处的感受器反射性引起胃底和胃体舒张的过程，其传入神经和传出神经均走行于迷走神经内，故属于迷走-迷走反射（胃期胃液分泌、胃期胰液分泌及胃排空过程也存在迷走-迷走反射调节）
#+END_QUOTE
* 69. 2003N9A 迷走神经兴奋引起胰液分泌的特点是
A.水分少，碳酸氢盐和酶的含量丰富
B.水分和碳酸氢盐的含量少，酶的含量丰富
C.水分多，碳酸氢盐和酶的含量均少
D.水分、碳酸氢盐和酶的含量均多
E.水分和碳酸氢盐的含量多，酶的含量少
答案：B 
#+BEGIN_QUOTE
（P194）&“迷走神经可通过其末梢释放ACh直接作用于胰腺，也可通过引起促胃液素的释放，间接引起胰腺分泌。迷走神经主要作用于胰腺的腺泡细胞，对小导管细胞的作用较弱，因此，迷走神经兴奋引起胰液分泌的特点是水和碳酸氢盐含量很少，而酶的含量却很丰富”（B对）。
#+END_QUOTE
* 70. 1998N11A 关于促胰液素的作用，下列哪项是错误的
A.促进肝胆汁分泌
B.促进胰液分泌
C.促进胃运动
D.促进胰腺分泌HCO₃⁻
E.促进小肠液分泌
答案：C 
#+BEGIN_QUOTE
（P194）&“促胰液素主要作用于胰腺小导管上皮细胞，使其分泌大量的水和HCO₃⁻”（D对）。（P196）&“促胰液素的主要作用是促进胰液分泌，对肝胆汁分泌也有一定刺激作用”（AB对）。（P197）&“此外，促胃液素、促胰液素、缩胆囊素和血管活性肠肽等都能刺激小肠液的分泌”（E对）。（P191）&“另一方面，食糜中的酸和脂肪还可刺激小肠黏膜释放促胰液素、抑胃肽等，抑制胃运动”（C错，为本题正确答案）。
#+END_QUOTE 
#+BEGIN_QUOTE
促胰液素由小肠上段黏膜的S细胞分泌，其生理功能极为广泛及多样化，且大部分功能与缩胆囊素（1990N147X）一致，生理学教材提及的功能包括：舒血管作用（七版P170）、促进胰酶分泌（七版P170 表6-3）、促进胆囊平滑肌收缩（七版P170 表6-3）、抑制食管-胃括约肌收缩（七版P170 表6-3）、收缩幽门括约肌（P181）、促进胰腺外分泌部生长（P181）、舒张食管下括约肌（P183）、促进胃蛋白酶原分泌、抑制促胃液素和胃酸的分泌（P181）、抑制胃的运动（P181）（C错，为本题正确答案）、抑制胃排空（P181）、促进胰腺小导管上皮细胞分泌水和HCO₃⁻分泌（P194）（B对）、促进肝胆汁分泌（P196）（A对）、促进小肠液分泌（P197）（D对）、抑制小肠运动（P197）、促进降钙素分泌（P386）、促进胰岛素分泌（P390）、抑制胰高血糖素分泌（P391）等。
#+END_QUOTE
* 92. 2021N8A 胆石症患者切除胆囊后最可能发生的情况是
A.不再发生胆道结石
B.胆汁排出量明显减少
C.增加消化性溃疡风险
D.影响脂肪性食物消化
答案：D 
#+BEGIN_QUOTE
（九版外科学P439）&“胆石可发生在胆管系统的任何部位，胆囊内的结石为胆囊结石，左右肝管汇合部以下的肝总管和胆总管内为肝外胆管结石，汇合部以上的为肝内胆管结石”（A错）。（P195）&“肝细胞能持续分泌胆汁。在非消化期，肝脏分泌的胆汁主要储存于胆囊内。进食后，食物及消化液可刺激胆囊收缩，将储存于胆囊内的胆汁排入十二指肠。直接从肝细胞分泌的胆汁称为肝胆汁，储存在胆囊内并由胆囊排出的胆汁称为胆囊胆汁”（B错）。(P195）&“胆汁的主要作用是促进脂肪的消化和吸收”（D对）。
#+END_QUOTE