#+title: 病理学/传染病及寄生虫/教材/细菌性痢疾
#+deck:病理学::传染病及寄生虫::教材::细菌性痢疾

* ((6248e1b8-3071-4a0f-98c1-b2804078a0bb))
* 细菌性痢疾/病因与传播途径和发病机制 
:PROPERTIES:
:id: 624913ad-8963-4cfe-962f-390374df6187
:collapsed: true
:END:
** ^^痢疾杆菌是革兰阴性短杆菌^^。按抗原结构和生化反应可分四群，即福氏、宋内、鲍氏和志贺菌。四群均能产生内毒素，^^志贺菌尚可产生强烈外毒素。^^
** 患者和带菌者是本病的传染源。痢疾杆菌从^^粪便中排出后^^可直接或间接（苍蝇为媒介）经^^口传染给健康人^^。食物和饮水的污染有时可引起菌痢的暴发流行。菌痢全年均可发病，但以夏秋季多见。好发于儿童，其次是青壮年。
** 经口入胃的痢疾杆菌大部分被胃酸杀死,仅少部分进入肠道。^^细菌在结肠内繁殖^^,从上皮细胞直接侵入肠黏膜，并在^^黏膜固有层内增殖,^^随之^^释放具有破坏细胞作用的内毒素^^,使肠黏膜产生溃疡。菌体内毒素吸收入血，引起全身毒血症。志^^贺杆菌释放的外毒素，是导致水样腹泻的主要因素。^^
* 细菌性痢疾/病理变化与临床病理联系 
:PROPERTIES:
:id: 624913da-3b91-4440-b6a3-db69311f21e1
:collapsed: true
:END:
** ^^菌痢的病理变化主要发生于大肠,尤以乙状结肠和直肠为重。^^病变严重者可波及整个结肠甚至回肠下段。根据肠道病变特征、全身变化及临床经过的不同，菌痢分为以下三种
** 急性细菌性痢疾
** 慢性细菌性痢疾
** 中毒性细菌性疾
* 细菌性痢疾/病理变化与临床病理联系/急性细菌性痢疾 
:PROPERTIES:
:id: 624913dd-45bd-4a7f-82bf-7b57232a32c8
:collapsed: true
:END:
** 其典型病变过程为^^初期的急性卡他性炎^^，^^随后的特征性假膜性炎^^和^^溃疡形成^^，^^最后愈合^^。
** 早期^^黏液分泌亢进，黏膜充血^^、水肿、^^中性粒细胞和巨噬细胞浸润^^，可见点状出血。
** 病变进一步发展黏膜浅表坏死，^^在渗出物中有大量纤维素，后者与坏死组织、炎症细胞和红细胞及细菌一起形成特征性的假膜。^^假膜首先出现于^^黏膜皱襞的顶部^^，呈糠皮状，随着病变的扩大可融合成片。假膜一般呈^^灰白色，如出血明显则呈暗红^^色，如受^^胆色素浸染则呈灰绿色^^。
** 大约^^1周假膜^^开始脱落，形成大小不等，形状不一的^^“地图状”溃疡^^（图17-12）,^^溃疡多较表浅^^。经适当治疗或病变趋向愈合时，肠黏膜渗出物和坏死组织逐渐被吸收、排出，经周围健康组织再生，缺损得以修复。临床上由于病变肠管蠕动亢进并有痉挛，引起阵发性腹痛、腹泻等症状。由于^^炎症刺激直肠壁内的神经末梢及肛门括约肌，导致里急后重和排便次数增多^^。与肠道的病变相对应，最初为^^稀便混有黏液，待肠内容物排尽后转为黏液脓血便,偶尔排出片状假膜^^。急性菌痢的病程一般1~2周，经适当治疗大多痊愈。^^并发症如肠出血、肠穿孔少见，少数病例可转为慢性。^^
*** ((624917bd-6acb-4f7b-b1a8-d6f6fbefa853))
** #+BEGIN_QUOTE
Cmts: 卡他→假膜→脱落形成溃疡
#+END_QUOTE
* 细菌性痢疾/病理变化与临床病理联系/慢性细菌性痢疾 
:PROPERTIES:
:id: 624915ae-8d5e-487a-8611-3cdc4ee47481
:collapsed: true
:END:
** 菌痢病程^^超过2个月^^以上者称为慢性菌痢。多由急性菌痢转变而来,以^^福氏菌感染者^^居多，有的病程可长达数月或数年。
** 肠道病变常此起彼伏，^^原有溃疡尚未愈合，新的溃疡又形成，因此新旧病灶同时存在^^。慢性溃疡^^边缘常不规则，黏膜常过度增生而形成息肉^^。肠壁各层有慢性炎症细胞浸润和纤维组织增生，乃至瘢痕形成，使肠壁不规则增厚、变硬，严重者可致肠腔狭窄。
** 细菌性痢疾临床表现可有^^腹痛、腹胀、腹泻^^等肠道症状。由于炎症的加剧，出现急性菌痢的症状称^^慢性菌痢急性发作^^。少数慢性菌痢患者可无明显状溃疡的症状和体征，但大便培养持续阳性,成为慢性带菌者及传染源。
* 细菌性痢疾/病理变化与临床病理联系/中毒性细菌性痢疾
:PROPERTIES:
:collapsed: true
:END:
** 该型的特征是^^起病急骤、严重的全身中毒症状^^，但^^肠道病变和症状轻微^^。
** ^^肠道病变一般为卡他性炎^^，有时肠壁集合和^^孤立淋巴小结滤泡增生肿大^^，而呈^^滤泡性肠炎改变^^。多见于2~7岁儿童，发病后数小时即可出现中毒性休克或呼吸衰竭而死亡。病原菌常为毒力较低的福氏或宋内痢疾杆菌。
*