#+title: 病理学/传染病及寄生虫/教材/艾滋病
#+deck:病理学::传染病及寄生虫::艾滋病

* ((6248e1b8-3071-4a0f-98c1-b2804078a0bb))
* 艾滋病/概念 
:PROPERTIES:
:id: 624936d1-7db7-4083-aedd-473b01482816
:END:
** 获得性免疫缺陷综合征由^^人类免疫缺陷病毒^^（humanimmunodeficiencyvirus,HIV）感染引起，其特征为^^严重免疫抑制^^，导致机会性感染、继发性肿瘤及神经系统症状。临床表现为^^发热、乏力、体重下降^^、全身淋巴结肿大及神经系统症状。
* 艾滋病/病因 
:PROPERTIES:
:id: 624936d9-dd68-48e8-a5ad-eaa87948b50f
:END:
** 本病由^^HIV感染^^所引起。HIV属反转录病毒科，为^^单链RNA病毒^^。已知HIV分为HIV-1和HIV-2两个亚型.HIV-1病毒结构已清楚，为圆形或椭圆形，病毒核心由^^两条RNA链^^（病毒基因组）、反转录酶和核心蛋白P17及p24构成，并由来自^^宿主细胞的脂质膜^^包被，^^膜上^^嵌有由病毒编码的糖蛋白即外^^膜蛋白gpl20和跨膜蛋白gp41^^（图5-3），在感染宿主细胞过程中发挥重要作用。HIV-1基因组包括9个基因，其中部分基因在编码核心蛋白、反转录酶和嵌于膜上的糖蛋白以及调控病毒复制功能方面发挥作用，但尚有部分基因功能不清楚。现发现一些人通过血液途径感染了缺乏调控病毒复制基因^^（如nef基因）的HIV,并未发展为AIDS^^,提示可将病毒调控蛋白（如nef基因编码的蛋白）作为抗AIDS药物的靶点,或采用缺乏关键调控蛋白的HIV突变体作为疫苗
* 艾滋病/传播途径 
:PROPERTIES:
:id: 6249369e-4dc7-4feb-b897-758aefd72a4d
:END:
** 患者和无症状病毒携带者是本病的传染源。HIV主要存在于宿主^^血液、精液、子宫、阴道分泌物和乳汁中^^。其他体液如唾液、尿液或眼泪中偶尔可分离出病毒，但迄今为止尚无证据表明能够传播本病。
** AIDS的传播途径包括:
*** ①性接触传播:异性性接触、同性性接触和双性性接触是AIDS传播的最常见方式,全球的HIV感染大约75%是通过性接触传播的。^^同性恋或双性恋男性曾是高危人群^^，占报道病例的60%以上。但目前经异性性传播已成为世界HIV流行的普遍规律。
*** ②血道传播:包括使用被病毒污染的针头作静脉注射、含有病毒血液和血制品的应用。
*** ③母-婴传播:母体病毒经胎盘感染胎儿或通过哺乳、黏膜接触等方式感染婴儿。
*** ④医务人员职业性传播,少见。
* 艾滋病/发病机制 
:PROPERTIES:
:id: 62493869-581d-437e-9869-d87293f82e8d
:END:
** HIV感染^^CD4+T细胞:^^^^CD4分子^^是HIV的主要受体。当HIV进入人体后，嵌于病毒包膜上的^^gP120与CD4+T细胞膜上CD4受体^^结合,同时,HIV又以趋化因子受体CXCR4和CCR5作为共受体进行识别，即^^HIV必须同时与CD4受体和共受体结合后才能进入细胞内^^。CXCR4为HIV附着淋巴细胞所必需，而CCR5则促进HIV进入巨噬细胞。进入细胞后，病毒RNA链经反转录酶的作用合成反义链DNA,被运送至细胞核，经多聚酶作用复制为双股DNA,在整合酶作用下，与宿主基因组整合。整合后的环状病毒DNA称前病毒（provirus），此时病毒处于潜伏状态。经数月至数年的临床潜伏期，前病毒可被某些因子所激活（如TNFJL-6等）开始不断复制，在细胞内装配成新病毒并以芽生方式释放入血,释出后的病毒再侵犯其他靶细胞。病毒复制的同时可直接导致受感染^^CD4+T细胞破坏、溶解^^。因CD4+T细胞在免疫应答中起核心作用，故CD4+T细胞的消减可导致:①淋巴因子产生减少；②CD8+T细胞的细胞毒活性下降;③巨噬细胞溶解肿瘤细胞、杀灭胞内寄生菌、原虫的功能减弱；④NK细胞功能降低;⑤B细胞在特异性抗原刺激下不产生正常的抗体反应，而原因不明的激活和分化引起高丙种球蛋白血症;⑥作用于骨髓中造血干细胞，影响造血细胞的分化。总之,CD4+T细胞在HIV直接和间接作用下，大量破坏、功能受损,导致细胞免疫缺陷。由于其他免疫细胞均不同程度受损，因而促进并发各种严重的机会性感染和肿瘤
** HIV感染组织中^^单核巨噬细胞^^:存在于脑、淋巴结和肺等器官组织中的单核巨噬细胞可有10%~50%被感染，其感染过程与CD4+T细胞存在不同之处,具体表现在:①因^^巨噬细胞表达低水平CD4,故HIV一方面通过gpl20与CD4结合的方式感染巨噬细胞^^;另一方面通过细胞的^^吞噬作用进入细胞，或经Fc受体介导的胞饮作用，使由抗体包被的HIV^^进入细胞。②病毒可在巨噬细胞内大量复制,但通常储存于胞质内，不像CD4+T细胞在胞膜上大量出芽。单核巨噬细胞能抵抗HIV的致细胞病变作用，因而不会迅速死亡，^^反成为HIV的储存场所^^,在病毒扩散中起重要作用。其可携带病毒通过血-脑屏障，引起中枢神经系统感染。研究表明，淋巴结生发中心的^^滤泡树突状细胞也可受到HIV的感染^^，并成为HIV的“储备池”。其树突可表达IgG的Fc受体，从而与由^^IgG型抗体包被的HIV结合，使病毒进入细胞内^^(图5-4)。
*
* 艾滋病/病理变化 
:PROPERTIES:
:id: 6249392c-525e-4fe1-a0a4-c31d18d7aecf
:collapsed: true
:END:
** 淋巴组织的变化
*** 早期
**** 淋巴结肿大。
**** 镜下，淋巴滤泡明显增生，髓质内较多浆细胞。
**** 电镜下或通过原位杂交法检测，可见HIV颗粒位于生发中心内，主要^^集中于滤泡树突状细胞,也可出现于巨噬细胞及CD4+T细胞内^^。
*** 随着病变的发展，^^滤泡外层淋巴细胞减少或消失^^，小血管增生，生发中心被分割。^^副皮质区CD4+T细胞进行性减少,代之以浆细胞浸润^^。
*** 晚期的^^淋巴结病变，往往在尸检时才能看到。淋巴结呈现一片荒芜^^，淋巴细胞几乎消失殆尽，仅残留少许^^巨噬细胞和浆细胞^^。有时特殊染色可见大量分枝杆菌、真菌等病原微生物，却很少见到肉芽肿形成等细胞免疫反应性病变. ^^脾、胸腺也表现为淋巴细胞减少。^^
** 继发性感染
*** ^^多发机会性感染^^是本病的另一特点。其感染范围广泛，可累及各器官，以^^中枢神经系统、肺、消化道^^受累最为常见。由于严重的免疫缺陷，感染所致的^^炎症反应往往轻而不典型^^。
**** 如^^肺部结核菌感染，很少形成典型的肉芽肿性病变^^，而病灶中^^的结核杆菌却甚多^^。
**** 70%~80%的患者可经历^^一次或多次肺孢子虫感染^^在艾滋病因机会感染而死亡的病例中，约一半死于肺孢子虫感染，因而对诊断本病有一定参考价值。
**** 约70%的病例有中枢神经系统受累，其中继发性机会感染有弓^^形虫或新型隐球菌感染^^所致的脑炎或脑膜炎；^^巨细胞病毒和乳头状瘤空泡病毒^^感染所致的进行性多灶性白质脑病等。由HIV直接引起的疾病有脑膜炎、亚急性脑病及痴呆等，提示，^^除淋巴细胞、巨噬细胞外，神经系统也是HIV感染的靶组织。^^
** 恶性肿瘤: 约30%的患者可发生Kaposi肉瘤。其他常见的伴发肿瘤为淋巴瘤。
* 艾滋病/临床病理联系 
:PROPERTIES:
:id: 62493ba6-a3f5-4bb6-a52d-8b2a5d0b538f
:END:
** 本病潜伏期较长,一般认为可经^^数月至10年或更长时间才发展为AIDS^^。根据世界卫生组织和美国疾病控制中心修订的HIV感染的临床分类，可将其分为三大类:
*** ①A类,包括^^急性感染^^、无症状感染和持续性全身淋巴结肿大综合征；
*** ②B类,包括免^^疫功能低下时出现的AIDS相关综合^^征、继发细菌感染、病毒感染和发生淋巴瘤等;
*** ③C类，患者^^已有严重免疫缺陷，^^出现各种机会性感染、继发性肿瘤以及神经系统症状等AIDS表现。
** AIDS按病程可分为三个阶段:
** ①早期或称急性期:感染^^HIV3~6周后,可表现出咽痛、发热、肌肉酸痛等非特异性症状^^。病毒在体内复制，但由于^^患者尚有较好的免疫反应能力,2~3周后这些症状可自行缓解。^^
** ②中期或称慢性期:机体的免疫功能与病毒之间处于相互抗衡的阶段，在某些病例此期可长达数年或不再进入末期。^^此期病毒复制持续处于低水平,临床可无明显症状或出现明显的全身淋巴结肿大,常伴发热、乏力、皮疹等。^^
** ③后^^期或称危险期:机体免疫功能全面崩溃,临床表现为持续发热、乏力、消瘦、腹泻，并出现神经系统症状^^，明显的机会性感染及恶性肿瘤,血液检测淋巴细胞明显减少，^^尤以CD4+T细胞减少为著，细胞免疫反应丧失殆尽（^^图5-5）。本病预后差，大力开展预防,对防止AIDS流行至关重要。
*