#+title: 病理学/传染病及寄生虫/教材/结核病
#+deck:病理学::传染病及寄生虫::教材::结核病

* ((6248e1b8-3071-4a0f-98c1-b2804078a0bb))
* 结核病的病因 #card
:PROPERTIES:
:id: 6248e2bf-cd95-48e5-8e58-85e501765c00
:collapsed: true
:END:
** 结核病的病原菌是^^结核分枝杆菌^^(mycobacteriumtuberculosis)，为细长弯曲、^^革兰阳性需氧菌^^，细菌细胞壁中含分枝菌酸，^^抗酸染色呈红色^^。对人致病的结核杆菌主要是^^人型和牛型^^。结核病主要经呼吸道传染，也可经消化道感染(食入带菌的食物,如含菌牛奶)，少数经皮肤伤口感染。^^呼吸道传播是最常见和最重要的途径^^。
* 结核病的发病机制 #card
:PROPERTIES:
:id: 6248e4a7-27db-4e5f-ab18-cfcafb6a5ea2
:collapsed: true
:END:
** 结核杆菌是^^细胞内生长的细菌，不产生内、外毒素^^，其致病性^^与菌体细胞壁的结构成分密切相关^^。结核病的发病机制即由结核杆菌^^引起的细胞免疫和Ⅳ型超敏反应^^（变态反应），一方面吞噬和杀伤细菌，一方面导致组织破坏（图17-2）。
** 到达肺泡的结核杆菌^^首先趋化和吸引巨噬细胞^^，并为巨噬细胞所吞噬。在有效的细胞免疫建立以前，巨噬细胞将其杀灭的能力很有限，^^则结核杆菌在细胞内繁殖^^，一方面可引起局部炎症，另一方面可发生全身性血源性播散,成为以后肺外结核病发生的根源。机体对结核杆菌产生^^特异细胞免疫的时间一般需30-50天^^，这种特异的细胞免疫在临床上表现为皮肤结核菌素试验阳性。
** 结核病的免疫反应和超敏反应（IV型）常同时发生并相伴出现。超敏反应的出现提示机体已获得免疫力，对病原菌有抵抗力，且^^超敏反应同时伴随干酪样坏死，试图破坏和杀灭结核杆菌^^。已致敏的个体动员机体防御反应较未致敏的个体快，但组织坏死也更明显。因此机体对结核杆菌感染所呈现的^^临床表现取决于机体反应性的不同^^。^^如以保护性反应为主，则病灶局限，结核杆菌被杀灭。如主要表现为组织破坏性反应,则机体表现为有结构和功能损害的结核病。^^其基本病变与机体免疫状态的关系见表
** ((6248e516-f26a-424f-8253-bf07f1ceb701))
^^Cmt: 增生说明它弱我强,且免疫力强,渗出与坏死都是它强我免疫弱区别是变态反应的强弱^^
* 结核病的基本病理变化
:PROPERTIES:
:collapsed: true
:END:
** 结核病的基本病理变化 #card
:PROPERTIES:
:id: 6248e5e8-8a18-4c49-bd3f-281f1d6a0d4e
:END:
*** 以渗出为主的病变
*** 以增生为主的病变
*** 以坏死为主的病变
** 结核病的基本病理变化/以渗出为主的病变 #card
:PROPERTIES:
:id: 6248e62d-18fe-4f93-9358-7dcb20714084
:END:
*** ^^现于结核性炎症的早期或机体抵抗力低下,菌量多，毒力强或变态反应较强时^^，主要表现为^^浆液性或浆液纤维素性炎^^。
*** 病变^^早期局部有中性粒细胞浸润，但很快被巨噬细胞所取代^^。在渗出液和巨噬细胞中可查见结核杆菌.
*** 此型变化好发于^^肺、浆膜、滑膜和脑膜^^等处。渗出物可完全吸收不留痕迹，或转变为以增生为主或以坏死为主的病变。
** 结核病的基本病理变化/以增生为主的病变 #card
:PROPERTIES:
:id: 6248e6e6-2e35-4a7c-95ae-05d283542c65
:END:
*** ^^当细菌量少，毒力较低或人体免疫反应较强时，则发生以增生为主的变化，形成具有诊断价值的结核结节（tubercle）^^,又称结核性肉芽肿（tuberculousgranuloma）。结核结节是在细胞免疫的基础上形成的，^^由上皮样细胞（epithelioidcell）、朗汉斯巨细胞（Langhansgiantcell）加上外周局部集聚的淋巴细胞和少量反应性增生的成纤维细胞构成^^。典型者^^结节中央有干酪样坏死^^（图17-3）o吞噬有结核杆菌的巨噬细胞体积增大逐渐转变为上皮样细胞，呈梭形或多角形,胞质丰富,HE染色呈淡伊红色，境界不清。核呈圆形或卵圆形，染色质甚少，甚至可呈空泡状,核内有1~2个核仁。上皮样细胞的活性增加，有利于吞噬和杀灭结核杆菌。^^多数上皮样细胞互相融合或一个细胞核分裂胞质不分裂乃形成朗汉斯巨细胞^^。^^朗汉斯巨细胞为多核巨细胞^^，直径可达300μm,胞质丰富。其胞质突起常和上皮样细胞的胞质突起相连接，核与上皮样细胞核相似。核的数目由十几个到几十个不等，有超过百个者。核排列在胞质周围呈花环状、马蹄形或密集于胞体的一端。
** 结核病的基本病理变化/以坏死为主的病变 #card
:PROPERTIES:
:id: 6248e7ca-0ff0-4329-84b3-9136781e65ce
:END:
*** ^^在结核杆菌数量多、毒力强，机体抵抗力低或变态反应强时，上述以渗出为主或以增生为主的病变均可继发干酪样坏死。^^
*** 结核坏死灶由于含^^脂质较多而呈淡黄色^^、均匀细腻，质地较实，状似奶酪，故称^^干酪样坏死(caseousnecrosis)o^^镜下为红染无结构的颗粒状物。干酪样坏死对结核病病理诊断具有一定的意义。干酪样坏死物中大都会有一定量的结核杆菌，可成为结核病恶化进展的原因。^^渗出、坏死和增生三种变化往往同时存在而以某一种改变为主,而且可以互相转化^^。在同一器官或不同器官中的结核病变往往是复杂多变的。
* 结核病的基本病理变化的转化规律 #card
:PROPERTIES:
:id: 6248e6e0-f305-43df-87b4-03bfa1ddf742
:collapsed: true
:END:
** 结核病的发展和结局取决于^^机体抵抗力和结核杆菌致病力^^之间的矛盾关系。在机体抵抗力增强时，结核杆菌被抑制、杀灭，病变转向愈合;反之,则转向恶化
** 转向愈合
*** 吸收、消散
**** 为^^渗出性病变^^的主要愈合方式，渗出物^^经淋巴道吸收^^而使病灶缩小或消散。X线检查可见边缘模糊、密度不均、^^呈云絮状的渗出性病变的阴影逐渐缩小或被分割成小片^^，以致完全消失，临床上称为吸收好转期。^^较小的干酪样坏死灶及增生性病灶^^，经积极治疗也有吸收消散或缩小的可能。
*** 纤维化、纤维包裹及钙化:
**** ^^增生性病变和小的干酪样坏死灶,可逐渐纤维化，最后形成瘢痕而愈合^^,较大的干酪样坏死灶难以全部纤维化，则由其周边纤维组织增生将坏死物包裹,继而坏死物^^逐渐干燥浓缩，并有钙盐沉着^^。钙化的结核灶内常^^有少量结核杆菌残留^^，此病变临床虽属痊愈,但当^^机体抵抗力降低时仍可复发进展。^^X线检查，可见纤维化病灶呈边缘清楚,密度增高的条索状阴影;钙化灶为密度甚高.、边缘清晰的阴影。临床称为硬结钙化期。
** 转向恶化
*** 浸润进展:
**** 疾病恶化时，病灶周围^^出现渗出性病变，范围不断扩大,并继发干酪样坏死^^。X线检查，原病灶周围出现絮状阴影，边缘模糊，临床上称为浸润进展期。
*** 溶解播散:
**** 病情恶化时，干酪样坏死物可发生液化，形成的半流体物质可经体内的自然管道(如支气管、输尿管等)排出，^^致局部形成空洞^^。空洞内液化的干酪样坏死物中^^含有大量结核杆菌^^，可通过自然管道^^播散到其他部位^^,形成新的结核病灶。X线检查，可见病灶阴影密度深浅不一，出现透亮区及大小不等的新播散病灶阴影。临床称为溶解播散期。此外,结核杆菌^^还可循血道、淋巴道播散至全身各处。^^
* 原发性肺结核
:PROPERTIES:
:collapsed: true
:END:
** 原发性肺结核的病变特点 #card
:PROPERTIES:
:id: 6248ea4e-5137-4ae6-886c-ec02a2944dae
:collapsed: true
:END:
*** 原发性肺结核病是^^第一次感染^^结核杆菌所引起的肺结核病。多发生于^^儿童^^，但也偶见于未感染过结核杆菌的青少年或成人。^^免疫功能严重受抑制^^的成年人由于丧失对结核杆菌的敏感性，因此^^可多次发生^^原发性结核病。
*** 结核杆菌被吸入肺泡后,最初在^^通气较好的肺上叶下部或下叶上部^^近胸膜处形成1~1.5cm大小的原发病灶（Ghon灶），病变为灰白色炎性实变灶,以^^结核性肉芽肿形成为特点^^，病灶中央可见干酪样坏死。原发灶的结核杆菌游离或被巨噬细胞吞噬,很快侵入淋巴管，循淋巴液引流到局部肺门淋巴结，引起^^结核性淋巴管炎和淋巴结炎，表现为淋巴结肿大和干酪样坏死^^。^^肺的原发病灶、淋巴管炎和肺门淋巴结结核称为原发综合征（primarycomplex）^^（图17-4）。X线呈哑铃状阴影。
** 原发性肺结核的发展和结局 #card
:PROPERTIES:
:id: 6248eb2b-eb57-402a-bfc9-034d033f1287
:collapsed: true
:END:
*** 原发综合征形成后，虽然在最初几周内有细菌通过血道或淋巴道播散到全身其他器官，但由于^^细胞免疫的建立,95%左右的病例不再发展^^，病灶进行性^^纤维化和钙化^^。有时肺门淋巴结病变继续发展，^^形成支气管淋巴结结核^^。
*** 少数^^营养不良或同时患有其他传染^^病的患儿，病灶扩大、^^干酪样坏死和空洞形成^^，有的甚至^^肺内播散形^^成粟粒性肺结核病或全身播散形成全身粟粒性结核病。这种改变也可见于继发性肺结核病。
* 继发性肺结核
:PROPERTIES:
:collapsed: true
:END:
** 继发性肺结核的类型 #card
:PROPERTIES:
:id: 6248ec0d-4091-4357-857a-c48981a55914
:collapsed: true
:END:
*** 局灶型肺结核
*** 浸润型肺结核
*** 慢性纤维空洞性肺结核
*** 干酪性肺炎
*** 结核球
*** 结核性胸膜炎
** 继发性肺结核/局灶型肺结核 #card
:PROPERTIES:
:id: 6248ec92-9fb3-4547-95bf-8bb0bd9059b6
:collapsed: true
:END:
*** 继发性肺结核病的^^早期病变。^^
*** X线示肺尖部有单个或多个结节状病灶。解剖学上病灶常^^定位于肺尖^^下2〜4cm处，直径0.5~lcm。^^病灶境界清楚，有纤维包裹^^。镜下病变^^以增生为主，中央为干酪样坏死^^。患者常无自觉症状，多在体检时发现。^^属非活动性结核病。^^
** 继发性肺结核/浸润型肺结核 #card
:PROPERTIES:
:id: 6248ecd4-ced2-44ca-a1f0-6322ed8f1d53
:collapsed: true
:END:
*** 是临床上^^最常见的活动性、继发性肺结核^^。^^多由局灶型肺结核发展而来^^。
*** X线示^^锁骨下边缘模糊的云絮状阴影^^。^^病变以渗出为主，中央有干酪样坏死^^，病灶周围有炎症包绕。患者常有低热、疲乏、盗汗、咳嗽等症状。
*** 如及早发现，合理治疗,^^渗出性病变可吸收;增生、坏死性病变，可通过纤维化、钙化而愈合^^。如病变^^继续发展^^，干酪样坏死扩大（浸润进展），坏死物液化后经支气管排出，局部^^形成急性空洞^^，洞壁坏死层内含大量结核杆菌,经支气管播散，可^^引起干酪性肺炎^^（溶解播散）。^^
*** 急性空洞一般易愈合^^。
**** 经适当治疗后，洞壁^^肉芽组织增生^^，洞腔逐渐缩小，闭合，最后^^形成瘢痕组织而愈合^^;
**** 也可通过^^空洞塌陷，形成条索状瘢痕而愈合。^^如果急性空洞经久不愈，^^则可发展为慢性纤维空洞型肺结核。^^
** 继发性肺结核/慢性纤维空洞型肺结核 #card
:PROPERTIES:
:id: 6248ed24-7af9-4c0c-b35d-1c171f7f7f6b
:collapsed: true
:END:
*** ①肺内有一个或多个^^厚壁空洞^^。多位于^^肺上叶^^，大小不一，不规则。壁厚可1cm以上。
**** 镜下洞壁^^分三层:内层为干酪样坏死物^^，其中有大量结核杆菌;
**** 中层为^^结核性肉芽组织^^
**** 外层为^^纤维结缔组织^^。
*** ②同侧或对侧肺组织，特别是肺小叶可见由^^支气管播散^^引起的很多^^新旧不一、大小不等、病变类型不同的病灶^^,^^愈往下愈新鲜^^。
*** ③后期^^肺组织严重破坏，广泛纤维化，胸膜增厚并与胸壁粘连^^,使肺^^体积缩小、变形，严重影响肺功能，甚至使肺功能丧失^^（图17-5）
*** 病变^^空洞与支气管相通^^，成为结核病的传染源,故此型^^又称开放性肺结核^^。如空洞壁的干酪样坏死^^侵蚀较大血管,可引起大咯血^^，患者可因吸入大量血液而窒息死亡。空洞^^突破胸膜可引起气胸或脓气胸。^^经常排出含菌痰液可引起喉结核。咽下含菌痰液可引起肠结核。后期由于肺动脉高压而致肺源性心脏病。
*** 近年来，由于广泛采用多药联合抗结核治疗及增加抵抗力的措施,较小的^^空洞一般可机化,收缩而闭塞^^。体积较大的空洞，内壁坏死组织脱落,肉芽组织逐渐变成^^纤维瘢痕组织^^，由支气管上皮覆盖,此时^^空洞虽仍然存在，但已无菌,实际上已愈合故称开放性愈合。^^
** 继发性肺结核/干酪性肺炎 #card
:PROPERTIES:
:id: 6248efe7-a272-4b0c-a42d-76a88474afef
:collapsed: true
:END:
*** 干酪性肺炎可由^^浸润型肺结核^^恶化进展而来，也可由^^急、慢性空洞内^^的细菌经^^支气管播散^^所致。
*** 镜下主要为^^大片干酪样坏死^^灶。肺泡腔内有^^大量浆液纤维蛋白性渗出^^物。根据病灶范围的^^大小分小叶性和大叶性干酪性肺炎。此型结核病病情危^^
** 继发性肺结核/结核球 #card
:PROPERTIES:
:id: 6248f17e-d116-4c5f-8f13-464eab7cf520
:collapsed: true
:END:
*** 结核瘤（tuberculoma）。结核球是直径2~5cm,有^^纤维包裹的孤立的境界分明的干酪样坏死灶^^（图17-6）。多为单个，也可多个，常位于肺上叶。X线片上有时很难与周围型肺癌相鉴别。
*** 结核球可来自：
:PROPERTIES:
:collapsed: true
:END:
**** ①^^浸润型肺结核的干酪样坏死灶纤维包裹^^;
**** ②结核^^空洞引流支气管阻塞^^，空洞由^^干酪样坏死物填充;^^
**** ③^^多个结核病灶融合。^^结核球由于其纤维包膜的存在,抗结核药不易发挥作用,且有恶化进展的可能。X线片上有时需与肺癌鉴别，因此临床上多采取手术切除。
** 继发性肺结核/结核性胸膜炎 #card
:PROPERTIES:
:id: 6248f28d-2261-4cd1-ab1e-18a2b50d50da
:collapsed: true
:END:
*** 结核性胸膜炎根据病变性质可分干性和湿性两种，以湿性结核性胸膜炎为常见。
*** 湿性结核性胸膜炎又称^^渗出性结核性胸膜炎^^，多见于年轻人。病变主要为浆液纤维素性炎。一般经适当治疗可吸收，如渗出物中纤维素较多，不易吸收，则可因机化而使胸膜增厚粘连。
*** 干性结核性胸膜炎又称^^增生性结核性胸膜炎^^。是由肺膜下结^^核病灶直接蔓延^^到胸膜所致。常发生于^^肺尖。病变多为局限性,以增生性改变为主。一般通过纤维化而愈合。^^
* 肺结核病血源播散所致疾病
:PROPERTIES:
:collapsed: true
:END:
** 肺结核的发展过程示意图 #card
:PROPERTIES:
:id: 6248f486-03cf-4190-a085-bd9588c9c891
:collapsed: true
:END:
*** ((6248f4d9-1fa7-494a-ba5b-ddff71ab77a6))
** 肺结核病血源播散所致疾病类型
:PROPERTIES:
:collapsed: true
:END:
*** 急性全身粟粒性结核病
*** 慢性全身粟粒性结核病
*** 急性肺粟粒性结核病
*** 慢性肺粟粒性结核病
*** 肺外结核病
** 肺结核病血源播散所致疾病/急性全身粟粒性结核病 #card
:PROPERTIES:
:id: 6248f5ac-c645-421e-a560-32d674f3f2b6
:collapsed: true
:END:
*** 结核杆菌在^^短时间内一次或反复多次大量^^侵入^^肺静脉分支,经左心至大循环^^，播散到全身各器官如^^肺、肝、脾和脑膜^^等处，可引起急性全身粟粒性结核病（acutesystemicmiliarytuberculosis）
*** 肉眼观，^^各器官内均匀密布大小一致,灰白色，圆形，境界清楚的小结节^^（图17-8）
*** 镜下主要为^^增生性病变,偶尔出现渗出、坏死为主的病变^^。临床上病情凶险，有高热衰竭、烦躁不安等中毒症状。^^X线可发现两肺有散在分布、密度均匀,粟粒大小细点状阴影^^，病情危重，若能及时治预后仍属良好。少数病例可因结核性脑膜炎而死亡。
** 肺结核病血源播散所致疾病/慢性全身粟粒性结核病 #card
:PROPERTIES:
:id: 6248f65a-21da-4934-bfe1-fc93ba3f5fc1
:collapsed: true
:END:
*** 如急性期不能及时控制而病程迁延^^3周以^^上，^^或结核杆菌在较长时期内每次以少量反复多次^^不规则进入血液,则形成慢性粟粒性结核病。
*** 此时,^^病变的性质和大小均不一致，同时可见增生、坏死及渗出性病变，病程长，^^成人多见。
** 肺结核病血源播散所致疾病/急性肺粟粒性结核病 #card
:PROPERTIES:
:id: 6248f688-f517-45bf-8f64-db51ccbcbce9
:collapsed: true
:END:
*** 由于^^肺门、纵隔、支气管旁的淋巴结干酪样坏死破入邻近大静脉^^，或因含有结核杆菌的^^淋巴液由胸导管回流,经静脉入右^^心^^，沿肺动脉播散于两肺所致，也可为急性全身粟粒性结核病的一部分^^。肉眼观，肺表面和切面可见灰黄或灰白色粟粒大小结节
** 肺结核病血源播散所致疾病/慢性肺粟粒性结核病 #card
:PROPERTIES:
:id: 6248f71b-e48c-4ad2-a369-787490743f5a
:collapsed: true
:END:
*** 多见于成人。^^患者原发灶已痊愈，由肺外某器官的结核病灶内的结核杆菌间歇入血而致病^^。病^^程较长，病变新旧、大小不一。小的如粟粒,大者直径可达数厘米以上^^。病变以^^增生性改变为主^^
** 肺结核病血源播散所致疾病/肺外结核病 #card
:PROPERTIES:
:id: 6248f7dc-a405-40b1-8f86-047bd6fae486
:collapsed: true
:END:
*** 肺外结核病除^^淋巴结结核由淋巴道播散^^所致，消^^化道结核可由咽下含菌的食物或痰液^^直接感染引起，^^皮肤结核可通过损伤的皮肤感染外^^,^^其他各器官的结核病多为原发性肺结核病血源播散所形成的潜伏病灶进一步发展所致。^^
* 肺外结核病
:PROPERTIES:
:collapsed: true
:END:
** 肺外结核病类型 #card
:PROPERTIES:
:id: 6248f8ac-1698-4352-87fd-60fa68a7a489
:collapsed: true
:END:
*** 肠结核病
*** 结核性腹膜炎
*** 结核性脑膜炎
*** 泌尿生殖系统结核病
*** 骨关节结核病
*** 淋巴结结核
** 肺外结核病/肠结核病
:PROPERTIES:
:collapsed: true
:END:
*** 肺外结核病/肠结核病/临床病理联系 #card
:PROPERTIES:
:id: 6248f883-5b00-41ae-8272-40214d65667c
:collapsed: true
:END:
**** 肠结核病可分原发性和继发性两型。
**** 原发性者很少见，常发生于小儿。一般由^^饮用带有结核杆菌的牛奶或乳制品而感染^^。可形成与^^原发性肺结核时原发综合征相似的肠原发综合征^^（肠的^^原发性结核性溃疡、结核性淋巴管炎和肠系膜淋巴结结核^^）。
**** ^^绝大多数肠结核继发于活动性空洞型肺结核病，因反复咽下含结核杆菌的痰液所引起^^
*** 肺外结核病/肠结核病/病理表现 #card
:PROPERTIES:
:id: 6248f951-4bac-4b4b-afdb-7adf0c234eb5
:collapsed: true
:END:
**** 肠结核病大多（约85%）发生于^^回盲部^^
***** ^^因该段淋巴组织最为丰富^^，病菌易于通过肠壁淋巴组织侵入肠壁
***** ^^并且食物在此停留时间较长^^接触细菌的机会较多之缘故。依其病变特点不同分两型：
**** 1.溃疡型较多见。
***** 结核杆菌侵入肠壁淋巴组织，形成结核结节,以后^^结节逐渐融合并发生干酪样坏死，破溃后形成溃疡^^。肠壁^^淋巴管环肠管走行^^，病变沿淋巴管扩散，因此典型的^^肠结核溃疡多呈环形,其长轴与肠腔长轴垂直^^。溃疡边缘参差不齐，一般较浅,底部有干酪样坏死物,其下为结核性肉芽组织。^^溃疡愈合后由于瘢痕形成和纤维收缩而致肠腔狭窄^^。肠浆膜面每见纤维素渗出和多数结核结节形成，连接成串,这是结核性淋巴管炎所致。后期纤维化可致粘连。
**** 2.增生型较少见。以肠壁大量^^结核性肉芽组织形成和纤维组织增生为其病变特^^征。肠壁^^高度肥厚、肠腔狭窄^^。黏膜面可有浅溃疡或息肉形成。^^临床上表现为慢性不完全低位肠梗阻。右下腹可触及肿块，故需与肠癌相鉴别。^^
** 肺外结核病/结核性腹膜炎 #card
:PROPERTIES:
:id: 6248fb41-b70f-4710-a78a-38d273b621b8
:collapsed: true
:END:
*** 青少年多见。感染途径以^^腹腔内结核灶直接蔓延为主^^。^^溃疡型肠结核病是最常见的原发病灶^^,其次为^^肠系膜淋巴结结核或结核性输卵管炎^^。由腹膜外结核灶经^^血道播散至腹膜者^^少见。
*** 根据病理特征可分{{embed 干性和湿性两型，以混合型多见}}。湿性结核性腹膜炎以^^大量结核性渗出^^为特征。^^干性结核性腹膜炎因大量纤维素性渗出物机化而引起腹腔脏器的粘连^^。
** 肺外结核病/结核性脑膜炎 #card
:PROPERTIES:
:id: 6248fcfb-f178-4b66-83bc-4d676401b410
:collapsed: true
:END:
*** ^^以儿童多见，成人较少。主要是由于结核杆菌经血道播散所致^^。在儿童往往是肺原发综合征血行播散的结果，故^^常为全身粟粒性结核病的^^一部分。
*** 在成人，除^^肺结核病外，骨关节结核和泌尿生殖系统结核^^病常是血源播散的根源。部分病例也可由于^^脑实质内的结核球液化溃破，大量结核杆菌进入蛛网膜下腔所致^^。
*** 病变以^^脑底最明显^^。在脑桥、脚间池、视神经交叉及大脑外侧裂等处的蛛网膜下腔内，有^^多量灰黄色混浊的胶冻样渗出物积聚^^。脑室脉络丛及室管膜有时也可有结核结节形成。病变严重者可累及脑皮质而引起脑膜脑炎。^^病程较长者则可发生闭塞性血管内膜炎^^，从而引起多发性脑软化。未经适当治疗而致病程迁延的病例，由于蛛网膜下腔渗出物的机化而发生蛛网膜粘连,可使第四脑室正中孔和外侧孔堵塞，引起脑积水。
** 肺外结核病/泌尿生殖系统结核病
:PROPERTIES:
:collapsed: true
:END:
*** 肺外结核病/泌尿生殖系统结核病/肾结核病 #card
:PROPERTIES:
:id: 6248fccf-d002-4e97-981a-b71a87c1b462
:collapsed: true
:END:
**** 最常见于20-40岁男性。^^多为单侧性^^。结核杆菌来自^^肺结核病的血道播散。^^
**** 病变大多起始于^^肾皮、髓质交界处或肾锥体乳头^^。最初为^^局灶性结核病变,继而发生干酪样坏死,^^然后破坏肾乳头而破入肾盂成为结核性空洞（图17-9）以后由于^^病变的继续扩大,形成多个空洞，最后可使肾仅剩一空壳,肾功能丧失^^。
**** ^^干酪样坏死物随尿下行，常使输尿管和膀胱感染^^。输尿管黏膜可发生^^溃疡和结核性肉芽肿^^形成，使管壁增厚、管腔狭窄，甚至阻塞，而引起肾盂积水或积脓。膀胱结核,以^^膀胱三角区最先受累形成溃疡^^,以后可累及整个膀胱。肌壁受累后^^膀胱壁纤维化和肌层破坏，致膀胱容积缩小^^。膀胱溃疡和纤维组织增生如影响到对侧的输尿管口，可^^使管口狭窄或失去正常的括约肌功能，造成对侧健肾引流不畅^^，最后可引起肾盂积水而损害肾功能。
*** 肺外结核病/泌尿生殖系统结核病/生殖系统结核病 #card
:PROPERTIES:
:id: 6248fbd8-63a6-4984-bc1f-dc6b06fcff49
:collapsed: true
:END:
**** 性生殖系统结核病与泌尿系统结核病有密切关系，结核杆菌可使^^前列腺和精囊感染^^，并可蔓延至^^输精管、附睾^^等处。^^血源感染偶见。^^
**** 病变器官有结核结节和干酪样坏死形成。^^附睾结核是男性不育的重要原因之一^^。女性生殖系统结核多由血道或淋巴道播散而来，也可由邻近器官的结核病蔓延而来。^^以输卵管结核最多见，为女性不孕的原因之一^^，其次是子宫内膜和卵巢结核。
** 肺外结核病/骨关节结核 #card
:PROPERTIES:
:id: 62490041-c999-4aa6-8bf4-6b870f04cebc
:collapsed: true
:END:
*** 骨关节结核多见于儿童和青少年,^^多由血源播散所致^^。
*** 骨结核
**** 骨结核多侵犯^^脊椎骨、指骨及长骨骨骺(股骨下端和胫骨上端）等处^^。病变常由松质骨内的小结核病灶开始，以后可发展为^^干酪样坏死型或增生型^^。
***** 干酪样坏死型可^^见明显干酪样坏死和死骨形成^^。病变常累及周围软组织,引起^^干酪样坏死和结核性肉芽组织^^形成。^^坏死物液化后在骨旁形成结核性“脓肿”，由于局部并无红、热、痛,故又称“冷脓肿”^^。病变穿破皮肤可形成经久不愈的^^窦道^^。
***** 增生型比较少见，主要形成^^结核性肉芽组织^^，病灶内骨小梁渐被侵蚀、吸收和消失，^^但无明显的干酪样坏死和死骨形成^^。
**** ^^脊椎结核是骨结核中最常见者^^，多见于第10胸椎至第2腰椎。病变起自椎体，常发生干酪样坏死，以后破坏椎间盘和邻近椎体。由于病变^^椎体不能负重而发生塌陷^^，引起^^脊椎后突畸形^^。如病变穿破骨皮质可在脊柱两侧^^形成“冷脓肿^^”，或沿筋膜间隙坏死物下流，在远隔部位形成“冷脓肿”。
*** 2.关节结核^^以髋、膝、踝、肘^^等关节结核多见，多继发于骨结核。病变通常开始于骨骺或干骺端，发生干酪样坏死。当病变发展侵入关节软骨和滑膜时则成为关节结核^^;关节结核痊愈时,关节腔常被大量纤维组织充填,造成关节强直，失去运动功能^^。
** 肺外结核/淋巴结结核病 #card
:PROPERTIES:
:id: 62490238-61a3-4f89-9008-3a34f4880a4b
:collapsed: true
:END:
*** 淋巴结结核病多见于儿童和青年,以颈部、支气管和肠系膜淋巴结多见,尤以^^颈部淋巴结结核（俗称瘰病）最为常见^^。结核杆菌可来自^^肺门淋巴结结核的播散,亦可来自口腔、咽喉部结核感染^^灶。
*** 淋巴结常成群受累，有结核结节形成和干酪样坏死。淋巴结逐渐肿大，^^最初各淋巴结尚能分离^^，当炎^^症累及淋巴结周围组织时，则淋巴结彼此粘连，形成较大的包^^
*
*