#+title: 病理学/传染病及寄生虫/教材/性传播疾病
#+deck:病理学::传染病及寄生虫::教材::性传播疾病

* ((6248e1b8-3071-4a0f-98c1-b2804078a0bb))
* 尖锐湿疣
:PROPERTIES:
:collapsed: true
:END:
** 尖锐湿疣/病因 #card
:PROPERTIES:
:id: 6249249c-e7ff-4433-bd10-ab819e257017
:collapsed: true
:END:
*** 是由人乳头瘤病毒(humanpapillomavirus,HPV)(主要是^^HPV6型和11型^^)引起的STD(性传播疾病)
***
** 尖锐湿疣/传播途径 #card
:PROPERTIES:
:id: 624924c5-210a-47ba-8aee-a0c75f855e40
:collapsed: true
:END:
*** 主要通过性接触传播，但也可以通过非性接触的间接感染而致病。
** 尖锐湿疣/病理变化 #card
:PROPERTIES:
:id: 624924da-03aa-4bb8-b190-2c6279bae90f
:collapsed: true
:END:
*** 好发于^^潮湿温暖的黏膜和皮肤^^交界的部位。男性常见于^^阴茎冠状沟、龟头、系带、尿道口或肛门附近^^。女性多见于^^阴蒂、阴唇、会阴部及肛周^^。亦可发生于身体的其他部位如腋窝等。
*** 初起为^^小而尖的突起^^，逐渐扩大。^^淡红或暗红，质软，表面凹凸不平,呈疣状颗粒。^^有时较大呈^^菜花状生长^^，顶端可有感染^^溃烂，触之易出血。^^
*** 镜下
**** ^^表皮角质层轻度增厚，几乎全为角化不全细胞^^，^^棘层肥^^厚，有乳头状瘤样增生，^^表皮钉突增粗延长^^，偶见核分裂。^^表皮浅层凹空细胞出现有助于诊断^^。凹空细胞较正常细胞大，核增大居中，圆形、椭圆形或不规则形，染色深^^，可见双核或多核^^，^^核周胞质空化或有空晕^^。
**** 真皮层可见^^毛细血管及淋巴管扩张，大量慢性炎症细胞浸润^^（图17-13）
* 梅毒
:PROPERTIES:
:collapsed: true
:END:
** 梅毒/病因与传播途径 #card
:PROPERTIES:
:id: 6249255e-3bf8-4389-8aed-d2940fe36a41
:END:
*** ^^梅毒螺旋体^^是梅毒的病原体，体外活力低，不易生存。对理化因素的抵抗力极弱，对^^四环素、青霉素、汞、砷、铋剂^^敏感。
*** ^^95%以上通过性交传播,少数可因输血、接吻、医务人员不慎受染等直接接触传播（后天性梅毒）^^。梅毒螺旋体还^^可经胎盘感染胎儿（先天性梅毒）。梅毒患者为唯一的传染源。^^
*** 机体在感染梅毒后第6周血清出现^^梅毒螺旋体特异性抗体^^及反应素，有血清诊断价值,但^^可出现假阳性应予注意^^。随着抗体产生，机体对螺旋体的免疫力增强,病变部位的螺旋体数量减少，以至^^早期梅毒病变有不治自愈的倾向。^^然而不治疗或治疗不彻底者，体内的螺旋体^^常难以完全消灭，即为复发梅毒和晚期梅毒发生的原因^^。少数人感染了梅毒螺旋体后，^^在体内可终身隐伏（血清反应阳性而无病变和临床症状），或在二、三期梅毒时局部病变消失而血清反应持续阳性，均称为隐性梅毒^^。
** 梅毒/基本病理变化 #card
:PROPERTIES:
:id: 62492f79-eccf-4250-a18a-42815ec644b8
:collapsed: true
:END:
*** 闭塞性动脉内膜炎和小血管周围炎
**** 闭塞性动脉内膜炎指^^小动脉内皮细胞及纤维细胞增生^^，使^^管壁增厚、血管腔狭窄闭塞^^。
**** 小动脉周围炎指^^围管性单核细胞、淋巴细胞和浆细胞浸润^^。^^浆细胞恒定出现是本病的病变特点之一。此类病变可见于各期梅毒。^^
*** 树胶样肿
**** ^^树胶样肿（gumma）又称梅毒瘤（syphiloma）,是梅毒的特征性病变^^。病灶灰白色，大小不一，小者仅镜下可见，大者可达数厘米。^^因其质韧而有弹性，如树胶,故而得名树胶样肿^^。
**** 镜下结构颇^^似结核结节，中央为凝固性坏死，形态类似干酪样坏死,唯坏死不如干酪样坏死彻底，弹力纤维尚保存。弹力纤维染色可见组织内原有血管壁的轮廓。^^坏死灶^^周围肉芽组织中富含淋巴细胞和浆细胞,而上皮样细胞和朗汉斯巨细胞较少^^，且^^必有闭塞性小动脉内膜炎和动脉周围炎^^。
**** 树胶样肿后期可被吸收、纤维化，最后使器官变形^^,但绝少钙化^^。树胶样肿可发生于任何器官，最常见于皮肤、黏膜、肝、骨和睾丸。^^仅见于第三期梅毒。^^
** 梅毒/临床病理类型 #card
:PROPERTIES:
:id: 62493163-0207-4f58-869c-38904bd477fe
:collapsed: true
:END:
*** 后天性梅毒
**** 分一、二、三期。^^一、二期梅毒称早期梅毒，有传染性^^。三期梅毒又称晚期梅毒，^^传染性小^^,因^^常累及内脏，故又称内脏梅毒^^
**** (1)第一期梅毒:梅毒螺旋体侵入人体^^后3周左右^^，侵入部位发生炎症反应，^^形成下疳(chancre)^^下疳常为单个，直径约1cm,表面可^^发生糜烂或溃疡,溃疡底部及边缘质硬，乃称硬性下疳。^^病变^^多见于阴茎冠状沟、龟头^^、子宫颈、阴唇，亦可发生于口唇、舌、肛周等处。病变部位^^镜下见闭塞性小动脉内膜炎和动脉周围炎^^。下疳出现后1~2周，局部淋巴结肿大，呈^^非化脓性增生性反应^^。下疳经^^1个月左右多自然消退^^，仅留浅表的瘢痕,局部肿大的淋巴结也消退。临床上^^处于静止状态，但体内螺旋体仍继续繁殖。^^
**** (2)第二期梅毒:^^下疳发生后7~8周，体内螺旋体又大量繁殖^^，由于^^免疫复合物的沉积^^引起全身皮肤、黏膜广泛的^^梅毒疹和全身性非特异性淋巴结肿大^^。镜下呈^^典型的血管周围炎改变^^，^^病灶内可找到螺旋体.故此期梅毒传染性大^^。梅毒疹可自行消退。
**** (3)第三期梅毒:常发生于感染后^^4~5年,病变累及内脏，特别是心血管和中枢神经系统，形成特征性的树胶样肿^^。由于树胶样肿^^纤维化、瘢痕收缩^^引起严重的组织破坏、变形和功能障碍。
***** 病变^^侵犯主动脉，可引起梅毒性主动脉炎^^、主动脉瓣关闭不全、主动脉瘤等。梅毒性主动脉瘤破裂常是患者猝死的主要原因。
***** 神经系统病变主要累及^^中枢神经及脑脊髓膜，可导致麻痹性痴呆和脊髓痨^^。
***** 肝脏病变主要形成^^树胶样肿^^，肝呈结节性肿大，继而发生纤维化、瘢痕收缩，以致^^肝呈分叶状^^。
***** 此外，病变常造成^^骨和关节损害^^，鼻骨被破坏形成^^马鞍鼻^^。长骨、肩胛骨与颅骨亦常受累。
*** 先天性梅毒
**** 根据被感染胎儿发病的早晚有早发性和晚发性之分。早发性先天性梅毒系指^^胎儿或婴幼儿期发病的先天性梅毒。^^
**** 晚发性先天性梅毒的^^患儿发育不良，智力低下^^。可引发间质性角膜炎、^^神经性耳聋及楔形门齿^^，并有^^骨膜炎及马鞍鼻^^等体征